### ISSUE TITLE
rustfmt doesn't fix poor indentation

### ISSUE THREAD

**Issue by enterprisey** [rust-lang/rustfmt#5764] opened 2023-05-07 03:42 UTC
The following (admittedly weird-looking) example is not modified by rustfmt (although it does compile):

```rust
struct S1;
impl S1 {
    fn f(self, a: Option<()>, b: impl Fn(S2)) {}
}

struct S2 {
    kind: E,
}

enum E {
    E(S3),
}

struct S3 {
    m1: String,
    m2: S4,
}

struct S4;
impl S4 {
    fn body(self) -> String {
        "".into()
    }
}

fn f() {
    let s = S1;
    s.f(None, move |incoming| {
            match incoming.kind {
                E::E(event) => {
                    let timestamp = 1
                .to_string();
                    let sender = event.m1.as_str();
                            let message_text = event.m2.body().replace("<", "&#60;").replace(">", "&#62;");
        let full_message_text = format!("[{timestamp}] &#60;<span foreground='#1290ea'>{sender}</span>&#62; {message_text}\n");

                }
            }
        });
}
```

However, any number of weird little changes will make it successfully format. For example, deleting `{sender}` or `{message_text}` in the `format!` makes it work. This is how it looks after deleting `{message_text}`:

```rust
// rest of sample unchanged
fn f() {
    let s = S1;
    s.f(None, move |incoming| match incoming.kind {
        E::E(event) => {
            let timestamp = 1.to_string();
            let sender = event.m1.as_str();
            let message_text = event.m2.body().replace("<", "&#60;").replace(">", "&#62;");
            let full_message_text =
                format!("[{timestamp}] &#60;<span foreground='#1290ea'>{sender}</span>&#62; {}\n");
        }
    });
}
```

**Comment by ytmimi** [comment] 2023-05-07 19:33
I believe this is a duplicate of #3863. We fail to format the closure because the `format!` line can't fit within the default `max_width` of `100`. rustfmt is able to find a suitable layout if we increase the max width to `101`.

```rust
fn f() {
    let s = S1;
    s.f(None, move |incoming| match incoming.kind {
        E::E(event) => {
            let timestamp = 1.to_string();
            let sender = event.m1.as_str();
            let message_text = event.m2.body().replace("<", "&#60;").replace(">", "&#62;");
            let full_message_text = format!(
                "[{timestamp}] &#60;<span foreground='#1290ea'>{sender}</span>&#62; {message_text}\n"
            );
        }
    });
}
```

**Closed by ytmimi** 2023-05-07 19:33 UTC
