### ISSUE TITLE
Formatting code that heavily uses closures appears to take an extremely long time.

### ISSUE THREAD

**Issue by pwharned** [rust-lang/rustfmt#6420] opened 2024-12-14 13:19 UTC
It takes 30 seconds to format the file at this url:

https://github.com/pwharned/rust-macros/blob/main/parser/src/lib.rs

Which is only 500 lines of code.

![Image](https://github.com/user-attachments/assets/193459d6-9766-4aaf-ac68-b5aa754b3f5c)

(I reinstalled my entire toolchain multiple times while investtigating this error)

![Image](https://github.com/user-attachments/assets/8df3b995-94e1-4ea6-b592-95aefb157c5a)

It seems to have something to do with the heavy use of closures, I can't tell what else would be causing it.

**Comment by ytmimi** [comment] 2024-12-14 15:14
My guess is that it's this deeply nested code:

```rust
pub fn foreign_key<'a>() -> Parser<'a, ConstraintOrColumn> {
    with_whitespace(match_string("FOREIGN KEY")).and_then(move |_| {
        with_whitespace(match_char('('))
            .and_then(|_| comma_sep(with_whitespace(name())))
            .and_then({
                move |defs| {
                    match_char(')').and_then(move |_| {
                        with_whitespace(match_string("REFERENCES")).and_then({
                            let defs2 = defs.clone();
                            move |_| {
                                with_whitespace(schema_name_table_name()).and_then({
                                    let def3 = defs2.clone();
                                    move |tablename| {
                                        with_whitespace(match_char('(')).and_then({
                                            let def4 = def3.clone();
                                            move |_| {
                                                comma_sep(with_whitespace(name())).and_then({
                                                    let def5 = def4.clone();
                                                    move |columnnames| {
                                                        match_char(')').and_then({
                                                            let columnnames2 = columnnames.clone();
                                                                let def6 = def5.clone();

                                                            move |_| cascade()  .map({
                                                            let def6 = def6.clone();
                                                            let columnnames3 = columnnames2.clone();

                                                                move |_| {
                                                               ConstraintOrColumn::Constraint(Constraint::ForeignKey(ForeignKey {
                                                                    source_columns: def6
                                                                        .to_vec()
                                                                        .into_iter()
                                                                        .map(|s| s.to_string())
                                                                        .collect::<Vec<String>>(),
                                                                    target_table: tablename
                                                                        .to_string(),
                                                                    target_columns: columnnames3
                                                                        .to_vec()
                                                                        .into_iter()
                                                                        .map(|s| s.to_string())
                                                                        .collect::<Vec<String>>(),
                                                                }))
                                                            }
                                                        })})
                                                    }
                                                })
                                            }
                                        })
                                    }
                                })
                            }
                        })
                    })
                }
            })
    })
}
```

That said, this is likely a duplicate of https://github.com/rust-lang/rustfmt/issues/5626

**Closed by ytmimi** 2024-12-14 15:14 UTC
