### ISSUE TITLE
Multiline string is ignored altogether in some cases

### ISSUE THREAD

**Issue by janpaul123** [rust-lang/rustfmt#4904] opened 2021-07-16 17:11 UTC
To reproduce:
* I'm using a rustfmt.toml file with just `edition = "2018"` in it.
* `cargo +nightly fmt --version` shows `rustfmt 1.4.37-nightly (b1f8e27b 2021-07-15)`
* Create the following file:

```rust
fn main() {
    foo.bar("test", r#"
                long line long line long line long line long line long line long line long line long line long line long line long line long line
            "#
    );
}
```

* Running `cargo +nightly fmt` on this file doesn't change the file at all.

Expected behavior: if you replace `foo.bar` by just `bar` it will change the file significantly, to this:
```rust
fn main() {
    bar(
        "test",
        r#"
                long line long line long line long line long line long line long line long line long line long line long line long line long line
            "#,
    );
}
```

I would expect the behavior with the `foo.` added in to be the same.

Note that if you keep the `foo.bar` and remove the super long line, that it will also format the file similarly:
```rust
fn main() {
    foo.bar(
        "test",
        r#"
                not so long line
            "#,
    );
}
```

**Comment by calebcartwright** [comment] 2021-07-18 04:30
Thanks for reaching out but closing as duplicate of #3863

**Closed by calebcartwright** 2021-07-18 04:30 UTC
Labels: duplicate
