### ISSUE TITLE
rust fmt does not format block with a long line in a method call

### ISSUE THREAD

**Issue by rukai** [rust-lang/rustfmt#5118] opened 2021-12-02 12:16 UTC
```rust
pub fn main() {
    let foo = Foo;
    foo.bar({
                    let _a = 0; // this line doesnt get formatted ;-;
        let _b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        0i32
    });
}

struct Foo;

impl Foo {
    fn bar(&self, _a: i32) {}
}
```

This is about as minimal as I could get it.
The following changes allow it to format correctly:
* Removing use of dot notation from `foo.bar({`
* Remove an `a` from `aaaaaaaaaaaaa...`

Tested on both stable and nightly rust.

**Comment by calebcartwright** [comment] 2021-12-05 03:37
Thanks for reaching out, but this is a duplicate of an existing issue (and various others since this seems to generate a lot of duplicates)

Duplicates #3863 see #5105 for one of the more recent other duplicates and a more direct/succinct summary of available options

**Closed by calebcartwright** 2021-12-05 03:37 UTC
Labels: duplicate
