### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by john01dav** [rust-lang/rustfmt#5769] opened 2023-05-15 21:14 UTC
I was working on some code of mine and I came across this error:
```
error[internal]: left behind trailing whitespace
  --> <stdin>:88:88:1
   |
88 |             
   | ^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
  --> <stdin>:93:93:1
   |
93 |             
   | ^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
   --> <stdin>:101:101:1
    |
101 |             
    | ^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:105:105:1
    |
105 |                 
    | ^^^^^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:117:117:1
    |
117 |             
    | ^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:265:265:1
    |
265 |             
    | ^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:270:270:1
    |
270 |             
    | ^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:278:278:1
    |
278 |             
    | ^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:282:282:1
    |
282 |                 
    | ^^^^^^^^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> <stdin>:294:294:1
    |
294 |             
    | ^^^^^^^^^^^^
    |

warning: rustfmt has failed to format. See previous 10 errors.
```

I have attached the file that produces this error. Don't mind the code in it — this happened right when I was in the middle of working on something so the code is not really meaningful aside from breaking rustfmt. I tested with both `rustfmt 1.5.2-stable (84c898d 2023-04-16)` and `rustfmt 1.5.2-nightly (18bfe5d 2023-05-14)`, both of which exhibit this behavior.

[broken.rs.zip](https://github.com/rust-lang/rustfmt/files/11481997/broken.rs.zip)

**Comment by ytmimi** [comment] 2023-05-15 21:25
@john01dav could you please post a code snippet instead of a zip file, thanks!

**Comment by jhg** [comment] 2023-05-17 16:17
@ytmimi I have an example, that is not real case but replicate same error:

```rust
fn hello() -> bool {
    let Some(1) = Some(1) else {
        return true;    
    };
    return false;
}
```

The output is like:

```text
error[internal]: left behind trailing whitespace
 --> \\?\C:\Users\[...].rs:9:9:21
  |
9 |         return true;
  |                     ^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by ytmimi** [comment] 2023-05-17 16:25
@jhg Did you get your example from the zipfile posted? Your example is a duplicate of #5714 and other similar issues. 

rustfmt doesn't currently support `let-else` formatting, and opts to leave the code unchanged.  You'll need to manually remove the whitespace in this case. Work on `let-else` formatting is underway, and this will hopefully not be an issue for much longer 🤞🏼

**Comment by jhg** [comment] 2023-05-17 17:02
No, that example was replicating from other code. Sorry, I didn't see the closed issue, I was looking first in open issues and see it was same error message.

I could take one portion that only give that error:

```rust
impl<'s> DeviceBuilder<'s> {
    pub unsafe fn select_physical_device() {
        let device = devices.into_iter().filter_map(|physical_device| {
            let mut background_queue_index = None;
            
            //don't create a new queue if a backgrond queue is not needed
            if self.background_queue_flags.is_empty(){
                background_queue_index = Some(SecondaryQueueSelection::ReuseMainQueue);
            }
            
            //try to find separate secondary index
            if background_queue_index.is_none(){
                if let Some((found_index, _)) = queue_families.iter().enumerate().find(|(index, device)| *index != main_queue_index && self.is_valid_background_queue(*device)){
                    log::info!("{}: Found queue family {} for background queue", name, found_index);
                    background_queue_index = Some(SecondaryQueueSelection::QueueIndex(found_index));
                }
            }
            
            //if primary queue is compatible with secondary && nothing is found yet
            if background_queue_index.is_none() && self.is_valid_background_queue(&queue_families[main_queue_index]){
                let primary_properties = &queue_families[main_queue_index];
                
                //try to duplicate
                if primary_properties.queue_count > 1{
                    log::info!("{}: Reusing primary queue index as background queue", name);
                    background_queue_index = Some(SecondaryQueueSelection::QueueIndex(main_queue_index));
                }

                if background_queue_index.is_none(){
                    log::warn!("{}: Reusing primary queue as background queue. This may not perform optimally, but a better choice is not possible with this device.", name);
                    background_queue_index = Some(SecondaryQueueSelection::ReuseMainQueue);
                }
            }
            
            if background_queue_index.is_none(){
                log::warn!("{}: Discarding device due to no compatible secondary queue.", name);
                return None;
            }
        });
    }
}
```

With that I got same error:

```text
error[internal]: left behind trailing whitespace
  --> \\?\C:\Users\Jesus\Downloads\broken.rs:16:16:1
   |
16 |
   | ^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
  --> \\?\C:\Users\Jesus\Downloads\broken.rs:21:21:1
   |
21 |
   | ^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
  --> \\?\C:\Users\Jesus\Downloads\broken.rs:29:29:1
   |
29 |
   | ^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
  --> \\?\C:\Users\Jesus\Downloads\broken.rs:33:33:1
   |
33 |
   | ^^^^^^^^^^^^^^^^
   |

error[internal]: left behind trailing whitespace
  --> \\?\C:\Users\Jesus\Downloads\broken.rs:45:45:1
   |
45 |
   | ^^^^^^^^^^^^
   |

warning: rustfmt has failed to format. See previous 5 errors.
```

Also I found that removing the next part fix all error (lines 28-32):

```rust

                if background_queue_index.is_none(){
                    log::warn!("{}: Reusing primary queue as background queue. This may not perform optimally, but a better choice is not possible with this device.", name);
                    background_queue_index = Some(SecondaryQueueSelection::ReuseMainQueue);
                }
```

Could that help to have an mcve? 😄

**Comment by ytmimi** [comment] 2023-05-17 17:17
@jhg thanks for taking the time to look into this! You've correctly identified the section that's causing the issue.

The issue here is that the long string prevents rustfmt from formatting the `log::war!()` macro, and because we're inside of the `filter_map` closure we fail to format the entire chain. See #3863 for more details on the underlying issue. The trailing whitespace error is a result of the input snippet already containing trailing whitespace that rutfmt can't remove given the max_width constraint.

@john01dav You have a few options for how to solve this:
1) manually remove the whitespace
2) increasing the `max_width` to some sufficiently large number to allow rustfmt to format the long string literal in `log::war!()`.
3) If you're on nightly you can try setting `format_strings=true` to allow rustfmt to break long string literals.

**Closed by ytmimi** 2023-05-17 17:17 UTC
Labels: duplicate, e-trailing whitespace
