### ISSUE TITLE
Comments in use-blocks may vanish

### ISSUE THREAD

**Issue by SWW13** [rust-lang/rustfmt#5697] opened 2023-02-21 14:05 UTC
When `cargo fmt` is run with the default configuration, comments in use-blocks may be removed unexpectedly.

`cargo fmt --version`
```
rustfmt 1.5.1-stable (d5a82bb 2023-02-07)
```

`cat src/main.rs`
```rust
use std::{
    /*
    io::{Read, Seek, Write},
    */
    path::{Path, PathBuf},
    // important stuff
};

fn main() {
    println!("Hello, world!");
}
```

`cargo fmt -- --emit stdout`
```
./src/main.rs:

use std::path::{Path, PathBuf};

fn main() {
    println!("Hello, world!");
}
```

**Comment by ytmimi** [comment] 2023-02-21 14:54
Thanks for reaching out. Closing this as a duplicate of #4708

**Closed by ytmimi** 2023-02-21 14:54 UTC
Labels: duplicate, a-comments, a-imports
