### ISSUE TITLE
Inconsistent line breaks in match

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rust-lang/rustfmt#3963] opened 2019-12-12 16:12 UTC
**What I expect:**

```rust
impl fmt::Display for RemoteObject {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match &self.object_type {
            RemoteObjectType::Undefined => write!(f, "undefined"),
            RemoteObjectType::Boolean 
            | RemoteObjectType::String => self.display_value(f),
            RemoteObjectType::Null 
            | RemoteObjectType::Object => self.display_object(f),
            RemoteObjectType::BigInt
            | RemoteObjectType::Number
            | RemoteObjectType::Symbol
            | RemoteObjectType::Function => self.display_description(f),
        }
    }
}
```

**What `rustfmt` produces:**

```rust
impl fmt::Display for RemoteObject {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match &self.object_type {
            RemoteObjectType::Undefined => write!(f, "undefined"),
            RemoteObjectType::Boolean | RemoteObjectType::String => self.display_value(f),
            RemoteObjectType::Null | RemoteObjectType::Object => self.display_object(f),
            RemoteObjectType::BigInt
            | RemoteObjectType::Number
            | RemoteObjectType::Symbol
            | RemoteObjectType::Function => self.display_description(f),
        }
    }
}
```

If this isn't a bug - happy to close! Might just be a personal preference of mine :)

**Comment by topecongiro** [comment] 2019-12-15 04:44
This is not a bug, rustfmt uses multiple lines for a `match` arm only if it exceeds max-width (which is 100 by default). So the first three arms are kept in a single line, whereas the last one gets spanned to multiple lines.

**Comment by topecongiro** [comment] 2020-01-09 05:36
Closing in favor of https://github.com/rust-lang/rustfmt/issues/4005.

**Closed by topecongiro** 2020-01-09 05:36 UTC
Labels: duplicate
