### ISSUE TITLE
Unexpected extra space in multi-line tuple struct with `pub`

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/rustfmt#6349] opened 2024-09-24 19:32 UTC
```rust
pub struct MyService(
    pub  dependency::Multi<
        Arc<dyn dependency::ServiceWithDebugInfo + Send + Sync>,
        Arc<dyn dependency::ServiceWithDebugInfo + Send + Sync>,
    >,
);
```

I realize this is kind of a terrible type to begin with, but the extra space after the `pub` for the field was unexpected. If there's a reason for it, though, please close this!

**Comment by ytmimi** [comment] 2024-09-24 19:43
Duplicate of https://github.com/rust-lang/rustfmt/issues/5703, https://github.com/rust-lang/rustfmt/issues/5525, https://github.com/rust-lang/rustfmt/issues/5997

**Closed by ytmimi** 2024-09-24 19:43 UTC

**Comment by jrose-signal** [comment] 2024-09-24 19:51
🤦 I searched "tuple struct space" and "tuple struct pub". Thanks.
