### ISSUE TITLE
Rustfmt doesn't work in for_each blocks with long strings literals

### ISSUE THREAD

**Issue by tafia** [rust-lang/rustfmt#3416] opened 2019-02-25 10:07 UTC
Rustfmt fails to format for_each blocks when there is a long str literal.

* example before running rustfmt:
```rust
fn main() {
    // this block will be properly formatted
    {
        let a = 1;
    let b=2;
    let c = " very very very very very very very very very very very very very very very very very very long string in a block";
    }

    let v = vec![1, 2];

    // this block won't be formatted
    v.iter().for_each(|_| {
        let a = 1;
    let b=2;
    let c = " very very very very very very very very very very very very very very very very very very long string in a block";
    });

    // this block with shorter str will be properly formatted
    v.iter().for_each(|_| {
        let a = 1;
    let b=2;
    let c = " less very very long string in a block";
    });
}
```

* after running rustfmt
```rust
fn main() {
    // this block will be properly formatted
    {
        let a = 1;
        let b = 2;
        let c = " very very very very very very very very very very very very very very very very very very long string in a block";
    }

    let v = vec![1, 2];

    // this block won't be formatted
    v.iter().for_each(|_| {
        let a = 1;
    let b=2;
    let c = " very very very very very very very very very very very very very very very very very very long string in a block";
    });

    // this block with shorter str will be properly formatted
    v.iter().for_each(|_| {
        let a = 1;
        let b = 2;
        let c = " less very very long string in a block";
    });
}
```

Not sure if this is a known bug or not ...

EDIT: added example with short &str in for_each block.

**Comment by scampi** [comment] 2019-02-26 23:21
There are some other similar issues, e.g., #3206 and #3135 . From what I remember with these other issues, there is a call to `wrap_str` that is cancelling any attempts to format that closure.
If you can use the `format_strings` option, then that block can be formatted.

**Comment by calebcartwright** [comment] 2022-07-22 21:40
closing as duplicate of #3863

**Closed by calebcartwright** 2022-07-22 21:40 UTC
Labels: poor-formatting, a-chains, a-strings
