### ISSUE TITLE
Reordering of use statements misses comment

### ISSUE THREAD

**Issue by rsalmei** [rust-lang/rustfmt#5566] opened 2022-10-19 15:55 UTC
Hi, I've just stumbled on something very weird, this:
```rust
use self::unlogged::*; // unlogged token route handlers (/api/<version>/<path>).
use self::rust_results::*; // special common Rust Events' Results handler.
```

Gets rustfmt'ed to this:
```rust
use self::rust_results::*;
use self::unlogged::*; // unlogged token route handlers (/api/<version>/<path>). // special common Rust Events' Results handler.
```

I don't use any custom configuration, everything is the default.
Actually, I use the integration from JetBrains IDEs, don't know whether that could be related.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/6652853/196742453-22aa14b8-38f3-46ce-a55a-59a48b47b6b0.png">

Thanks.

**Comment by ytmimi** [comment] 2022-10-19 16:43
Thanks for reaching out, but going to close this as a duplicate of #3720

**Closed by ytmimi** 2022-10-19 16:43 UTC
Labels: duplicate, a-imports

**Comment by rsalmei** [comment] 2022-10-19 19:38
Sure, thank you!
I tried to find a similar issue, but couldn't find that one.
