### ISSUE TITLE
`array_width` works incorrectly for hex integers

### ISSUE THREAD

**Issue by cmpute** [rust-lang/rustfmt#5219] opened 2022-02-06 04:31 UTC
I found that
```rust
pub const FORMAT_TEST: [u64; 5] = [
    0x0000000000000000,
    0xaaaaaaaaaaaaaaaa,
    0xbbbbbbbbbbbbbbbb,
    0xcccccccccccccccc,
    0xdddddddddddddddd,
];

pub const FORMAT_TEST2: [u64; 5] = [
    1111111111111,
    2222222222222,
    3333333333333,
    4444444444444,
    5555555555555,
];
```
formats to
```rust
pub const FORMAT_TEST: [u64; 5] = [
    0x0000000000000000,
    0xaaaaaaaaaaaaaaaa,
    0xbbbbbbbbbbbbbbbb,
    0xcccccccccccccccc,
    0xdddddddddddddddd,
];

pub const FORMAT_TEST2: [u64; 5] =
    [1111111111111, 2222222222222, 3333333333333, 4444444444444, 5555555555555];
```

I expect that the first array should also be rearranged. Thanks!

**Comment by ytmimi** [comment] 2022-02-06 18:36
Thanks for submitting the issue.

When you get a chance could you please provide the value you're using for ``array_width`` to produce the inconsistent formatting.

**Comment by cmpute** [comment] 2022-02-06 20:24
I just use the default setting (width = 100, array_width = 60). And I also tested with different width settings, the behavior is the same

**Comment by calebcartwright** [comment] 2022-02-07 02:46
I can't reproduce this. Could you please share the version of rustfmt you are using (`rustfmt --version`), and share your full config file?

**Comment by cmpute** [comment] 2022-02-07 03:17
Version: `rustfmt 1.4.38-stable (db9d1b2 2022-01-20)`
I have a config file at `~/rustfmt.toml` with merely one config: `array_width=100`. But I have this problem even without any config.

The specific file I'm trying to format is this: https://github.com/cmpute/num-prime/blob/master/src/tables.rs

**Comment by calebcartwright** [comment] 2022-02-07 03:25
Thanks for the quick response, although I'm going to close this now.

Please note that your first array is formatted vertically because it would exceed the `max_width` (note, not `array_width`) value if it wasn't. Try setting `max_width` to something like 105 or 110 that's just big enough to fit the first array which is longer than the second. Also, the presence of a config file in your home directory which contains an overridden option applies to everything on your system, so you're never running with true defaults unless you're running in a project that has a local config/passing command line opts that override those global settings.

**Closed by calebcartwright** 2022-02-07 03:25 UTC

**Comment by cmpute** [comment] 2022-02-07 04:17
Thanks for your reply! I'm a little bit confused about the array formatting now, in what situation will the array literals be arranged like this:?

https://github.com/cmpute/num-prime/blob/56bfcffe15c8a4b2019550cae7dad1f7d49a6672/src/tables.rs#L19-L25

In my understanding, the array should be wrapped before it reaches the `max_width` limit, but not directly fall back to vertical format. How can I achieve something like
```rust
pub const FORMAT_TEST: [u64; 5] = [
    0x0000000000000000, 0xaaaaaaaaaaaaaaaa, 0xbbbbbbbbbbbbbbbb,
    0xcccccccccccccccc, 0xdddddddddddddddd,
];
```

**Comment by cmpute** [comment] 2022-02-07 04:48
It seems what I would like to achieve is a `ListTactic::Mixed` style. I browse the code and I believe the reason that prevents this list to be formatted in a "mixed" way is because the constant [`SHORT_ITEM_THRESHOLD`](https://github.com/rust-lang/rustfmt/blob/0b8ffac0297a46d7d2d2f8328cbc49de7e7144f2/src/overflow.rs#L29) is set to 10, while a hex representation of an u64 integer has length 18.

Then I would like to request a feature for setting this threshold in the configuration file, or somehow override it only for integer literals.
