### ISSUE TITLE
rustfmt unexpectedly eats comments in block imports (`use` statements)

### ISSUE THREAD

**Issue by lthoerner** [rust-lang/rustfmt#5877] opened 2023-08-03 17:11 UTC
## Issue
When rustfmt is run on a block of imports that contains commented-out imports or any other comments, it will delete said comments when collapsing the statements, under a particular condition explained below.

## Reproducing
Write a block of imports containing one or more "sub-blocks," such as this:
```rs
use std::{
    io::{Read, Write},
    time::{Duration, Instant},
    fmt::Display,
    sync::Arc,
};
```
Now comment out all but one list item, ensuring that the remaining item is one of the aforementioned sub-blocks, like so:
```rs
use std::{
    io::{Read, Write},
    // time::{Duration, Instant},
    // fmt::Display,
    // sync::Arc,
};
```
When formatting, it will collapse to:
```rs
use std::io::{Read, Write};
```
The same is true of normal comments, such as this:
```rs
use std::{
    io::{Read, Write},
    // time::{Duration, Instant},
    // fmt::Display,
    // sync::Arc,
    // Hello world!
};
```

## Possible Causes
I honestly am not sure what causes this beyond knowing how to reproduce it, as I am not familiar with the internals of rustfmt. Please let me know if you have a good explanation and I will edit this.

**Comment by ytmimi** [comment] 2023-08-03 17:15
Thanks for reaching out. Going to close this as a duplicate of #5852

**Closed by ytmimi** 2023-08-03 17:15 UTC

**Comment by ytmimi** [comment] 2023-08-31 04:00
We just merged https://github.com/rust-lang/rustfmt/issues/5852, so this should be resolved come the next release
