### ISSUE TITLE
Formatting stops working with specific code structure

### ISSUE THREAD

**Issue by l3utterfly** [rust-lang/rustfmt#5348] opened 2022-05-22 17:40 UTC
VS Code
rustlang.rust v0.3.1051

The following code does not format (using the format command has no effect).

Removing the `println` line completely seems to make the code format again.

Is this a bug within rustfmt?

````
use std::thread;

enum Switch1 {
    Option1,
    Option2,
}

enum MassiveSwitch {
    Cmd1,
}

struct Worker {
    id: i32,
}

impl Worker {
    pub fn start(self) {
        let switch: MassiveSwitch = MassiveSwitch::Cmd1;
        let switch1 = Switch1::Option1;

        let _ = thread::Builder::new()
            .name(format!("Worker {}", self.id))
            .spawn(move || {
                if true {
                    match switch1 {
                        Switch1::Option1 => match switch {
                            MassiveSwitch::Cmd1 => {







                                // TODO: the white lines here should be deleted by rustfmt on save (or format command)
                                // TODO: removing this line causes rustfmt to work again. Commenting it out doesn't work, have to delete the line complete to get rust fmt to work
                                println!("Shard worker {}: received shutdown signal, exiting loop...", 5);

                                let test = "test";
                            }
                        },
                        Switch1::Option2 => todo!(),
                    }
                }
            })
            .expect("Can't spawn");
    }
}

fn main() {
    let worker = Worker { id: 3 };

    worker.start();
}
````

**Comment by ytmimi** [comment] 2022-05-22 18:18
Hi @l3utterfly Thanks for reaching out. If you're on nightly you can try setting `version=Two` or `format_strings=True`. I just checked and both options should allow rustmt to format the `println!` call vertically.

The issue is that the nested `println!` call exceeds the default max line width of 100. You can try setting the max width to some sufficiently large value like 110, and rustfmt will then be able to reformat the code.

I'm pretty sure this is a duplicate of #3416, and #3863

**Closed by ytmimi** 2022-05-22 18:18 UTC
Labels: duplicate, a-chains, a-strings

**Comment by l3utterfly** [comment] 2022-05-23 02:39
Thank you, this works now

**Comment by ytmimi** [comment] 2022-05-23 03:01
I'm glad to hear that! Out of curiosity, which approach did you take to resolve your issue?

**Comment by l3utterfly** [comment] 2022-05-23 04:08
I used both. I changed "max_width" to 200 which is about my editor screen length. But I still have some strings which are even longer than that, so had to add the "format_strings" flag as well.

**Comment by l3utterfly** [comment] 2022-05-23 04:12
Incidentally, I need to set `version=Two` AND `format_strings=True` to get it to work

**Comment by ytmimi** [comment] 2022-05-23 13:54
Got it! I'm glad that we were able to find a solution for your issue!
