### ISSUE TITLE
Comments inside struct gets indented

### ISSUE THREAD

**Issue by xRiot** [rust-lang/rustfmt#4952] opened 2021-08-11 13:27 UTC
We have a particular struct that contains a lot of useful values and some are commented out for the time being. Each field has its own comment with a explanation for future reference. However, if a field is commented rustfmt adds indentation to get it inlined with the comment on the previous line. Here's a example:
```rust
// Preferred formatting
pub struct Example {
    pub one: String,     // Test
    pub two: bool,       // Test
    //pub three: String, // Test
    //pub four: bool,    // Test
}

// $ cargo fmt
pub struct Example {
    pub one: String, // Test
    pub two: bool,   // Test
                     //pub three: String, // Test
                     //pub four: String,  // Test
}

```
We're using default rustfmt v1.4.36 config and it doesn't seem like there is a way around this in stable channel? We've tried using `/* */` around fields that are supposed to be commented out but it didn't work.

Is there anything we can do about this?

**Comment by calebcartwright** [comment] 2021-09-06 21:50
Thanks for reaching out but going to close as it's largely a duplicate of #4108. rustfmt is never supposed to do any visual/vertical alignment by default, but does in trailing cases like this on struct fields as well as enum variants and params in function signatures.

**Closed by calebcartwright** 2021-09-06 21:50 UTC
