### ISSUE TITLE
Misformatting an array

### ISSUE THREAD

**Issue by 06393993** [rust-lang/rustfmt#5785] opened 2023-06-17 21:46 UTC
`rustfmt` version: 1.5.2-nightly (2023-06-16 6bba061)

Input code(this is also the output):

```Rust
static VULKAN_COMMANDS: Lazy<Vec<(&'static str, VulkanCommand)>> =
    Lazy::new(|| {
        [
            (
                "vkDestroyDevice",
                VulkanCommand {
                    proc: {
    extern "system" fn destroy_device(_: vk::Device, _: *const vk::AllocationCallbacks) {
        unimplemented!()
    }
},
                },
            ),
            (
                "vkEnumeratePhysicalDeviceGroups",
                VulkanCommand {
                    proc: {
    extern "system" fn enumerate_physical_device_groups(
        _: vk::Instance,
        _: *mut u32,
        _phyiscal_device_group_properties: *mut vk::PhysicalDeviceGroupProperties,
    ) {
        unimplemented!()
    }
                },
                },
            ),
        ]
        .iter()
        .cloned()
        .collect()
    });
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d0e04e18f3cf65d4108cc3dbb0a8d19.

Interestingly, if I reduce the length of the parameters of the inline function definition, e.g. change `vk::Device` to `vk::D`, `rustfmt` works again. I assume it's a buffer length related bug.

**Comment by calebcartwright** [comment] 2023-06-17 22:15
Thanks for reaching out but going to close as this is a duplicate of #3863 (the `.iter()....` calls on the array make this a chain too).

You've got some pretty long signatures nested pretty deeply which makes it impossible for rustfmt to properly format your input within the `max_width` boundary. You can either format this by hand (rustfmt will maintain whatever is there), or crank up the max_width value (suspect something like `max_width=120` would work but haven't actually tried counting the columns)

**Closed by calebcartwright** 2023-06-17 22:15 UTC
