### ISSUE TITLE
rustfmt failure

### ISSUE THREAD

**Issue by eminence** [rust-lang/rustfmt#5245] opened 2022-02-28 20:19 UTC
Hi all,

I have a fairly small bit of code that rustfmt seems to fail on.  I don't really have any useful error messages, so I can't really say why it's failing (hence the generic title for this issue)

```rust
use clap::{
App
    
};

pub fn get_app() {
    App::new("myapp")
        .subcommand(
            App::new(   "prepare"   )     
                .after_help(
                    "Downloads some required tools like procmon.  These will be stored in the path specified by --root",
                )     
        );
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1c7900d609e2ad6703d1bf67c2287af2

Any hints about what might be going wrong here?

Thanks!

**Comment by eminence** [comment] 2022-03-01 02:19
@ytmimi I'll try that, thanks!  However, does the long string on line 11 explain why the lines 1 through 3 can't be formatted?

**Comment by ytmimi** [comment] 2022-03-01 02:45
I'm not sure why it's not working on the playground. Have you tried running this locally? When I run rustfmt locally with your snippet and without specifying any non-default configs the first few lines are formatted correctly. I'm using `rustfmt 1.4.37-stable (c8dfcfe0 2021-09-06)`

What version of rustfmt are you using?

**Comment by calebcartwright** [comment] 2022-03-01 05:32
Thanks for the report and investigating @ytmimi but going to close as this is a duplicate of #3863

**Closed by calebcartwright** 2022-03-01 05:32 UTC
