### ISSUE TITLE
Editorconfig support

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rustfmt#2999] opened 2018-09-06 20:11 UTC
Ideally would be great if something like the [editorconfig](https://editorconfig.org/) integration would happen directly in the `rust-${editor}` integration, in the mean time would be quite neat to have a mean to extract the information from the rustfmt configuration and produce a `.editorconfig`.

**Comment by drrlvn** [comment] 2019-08-30 14:40
Isn't this a duplicate of #2938?

**Comment by cehteh** [comment] 2022-01-25 18:00
> Isn't this a duplicate of #2938?

Its the other way around. I'd like this way more.

**Comment by calebcartwright** [comment] 2022-03-05 20:01
Update(@jieyouxu): I don't think we are considering support for this for the time being, cf. https://github.com/rust-lang/rustfmt/pull/6701#issuecomment-3399282690.

---

While I think this is an interesting idea, I'm going to close as it's not something the rustfmt team will implement and I think it's a feature that's better served via a community crate.

If anyone does decide to implement as a crate feel free to post and we'll be happy to link out to it/reference from our docs. Also, similarly to #2938, anyone sufficiently motivated may certainly still submit a PR for review and consideration; just a bit too far outside our core goals/feature focus areas for us to consider.

**Closed by calebcartwright** 2022-03-05 20:01 UTC
Labels: feature-request
