### ISSUE TITLE
Bizarre length related panic with match statement with attribute in closure, in function call.

### ISSUE THREAD

**Issue by bddap** [rust-lang/rustfmt#3962] opened 2019-12-11 21:17 UTC
Given a these very specific inputs, rustfmt panics. Try as I may, these examples are as minimal as I can make them.

Functions named `panics<n>` contain code blocks that cause the panic, while functions named `succeeds<n>` do not.

```rust
fn panics1() {
    Some(()).map(|_| {
        #[allow(deprecated)]
        match 1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa()
        {
            _ => {}
        }
    });
    // thread 'main' panicked at 'Request to format inverted span: Loc { file:
    // SourceFile(./src/main.rs), line: 4, col: CharPos(28),
    // col_display: 28 } to Loc { file: SourceFile(/Users/a/d/tmp/rustfmt_issue_repro/src/main.rs),
    // line: 3, col: CharPos(8), col_display: 8 }', src/tools/rustfmt/src/missed_spans.rs:86:9
    // note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
}

fn succeeds1() {
    Some(()).map(|_| {
        #[allow(deprecated)]
        match 1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa() {
            _ => {}
        }
    });
}

fn panics2() {
    foooooooooooooooooooooooooooooooooooooooo.map(|f| {
        #[allow(deprecated)]
        match f.a(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
        {
            _ => {}
        }
    });
}

fn panics3() {
    foo.map(|f| {
        #[allow(deprecated)]
        match f.a(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {
            _ => {}
        }
    });
}

fn succeeds3() {
    foo.map(|f| {
        #[allow(deprecated)]
        match f.a(aaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {
            _ => {}
        }
    });
}
```

**Comment by bddap** [comment] 2019-12-11 21:19
```bash
rustfmt --version
# rustfmt 1.4.8-stable (afb1ee1c 2019-09-08)
```

**Comment by calebcartwright** [comment] 2019-12-12 17:19
Related/possible dupe of #3934, already fixed in the latest version of rustfmt on master via #3935

**Comment by topecongiro** [comment] 2019-12-15 04:46
Thank you @bddap for the report and @calebcartwright for the confirmation, closing as this is fixed on the latest master.

**Closed by topecongiro** 2019-12-15 04:46 UTC
