### ISSUE TITLE
top-level `use`s are grouped up onto one line

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rustfmt#3547] opened 2019-05-10 17:00 UTC
I know I've filed issues like this before, but I couldn't find the right one, so I'm opening this one again:

```rust
use {
    fidl::endpoints::RequestStream,
    fuchsia_async as fasync,
    fuchsia_zircon as zx,
    std::marker::PhantomData,
};
```

gets rustfmt'd into

```rust
use {
    fidl::endpoints::RequestStream, fuchsia_async as fasync, fuchsia_zircon as zx,
    std::marker::PhantomData,
};
```

which IMO is pretty clearly less readable.

**Comment by scampi** [comment] 2019-05-10 21:13
have you tried the option `imports_layout` ? The variants `HorizontalVertical` or `Vertical` could be what you want.

**Comment by cramertj** [comment] 2019-05-10 21:22
No, I haven't, as I can't use unstable options, and any non-default formatting changes have to be approved for use in the project I work on. `HorizontalVertical` seems like what I would want, though.

In particular, it seems especially wrong to group multiple top-level crates onto the same line.

**Comment by mdittmer** [comment] 2019-07-02 18:13
FWIW, I would advocate putting every comma-separable entity on its own line (regardless of nesting) because version control systems can be of more assistance identifying and/or resolving conflicts precisely where they reside. The cost of extra lines is generally low, since most editor/viewer interfaces support folding bracketed lines.

I suspect that even enforcing this _at least_ for top-level crates would go a long way.

**Comment by kellytk** [comment] 2019-09-07 07:59
@cramertj 
> In particular, it seems especially wrong to group multiple top-level crates onto the same line.

While I personally prefer `Vertical`, https://github.com/rust-lang/rustfmt/issues/3361#issuecomment-499529271 mentions a possible benefit.

**Comment by ytmimi** [comment] 2022-07-20 02:25
This is a duplicate of #3286

**Closed by ytmimi** 2022-07-20 02:25 UTC
Labels: duplicate, poor-formatting, only-with-option, a-imports
