### ISSUE TITLE
Confusing error when a module is found as a file and a directory

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rustfmt#5167] opened 2022-01-10 19:48 UTC
When a module is found as both a file `modname.rs` and a directory `modname/mod.rs`, the error from `cargo fmt --all` is wrong and misleading.

Reproduction steps:
```console
cargo new foo --lib
cd foo
echo "mod bar;" > src/lib.rs
touch src/bar.rs
mkdir -p src/bar
touch src/bar/mod.rs
cargo fmt --all
```

Output:
```console
Error writing files: failed to resolve mod `bar`: hi/foo/src does not exist
```

**Comment by ytmimi** [comment] 2022-01-10 22:19
Thanks for the report!

Confirming that I can reproduce the issue.

I assumed there was an ambiguity error, and if you run ``cargo check`` that's exactly what you get. Here' the output:

```bash
error[E0761]: file for module `bar` found at both "src\bar.rs" and "src\bar\mod.rs"
 --> src\lib.rs:1:1
  |
1 | mod bar;
  | ^^^^^^^^
  |
  = help: delete or rename one of them to remove the ambiguity
```

Cargo check's is a much more helpful error message, so I'll see if I can hunt down what's happening and hopefully provide something similar.

**Comment by calebcartwright** [comment] 2022-01-10 23:48
> When a module is found as both a file `modname.rs` and a directory `modname/mod.rs`, the error from `cargo fmt --all` is wrong and misleading.
> 
> Reproduction steps:
> 
> ```
> cargo new foo --lib
> cd foo
> echo "mod bar;" > src/lib.rs
> touch src/bar.rs
> mkdir -p src/bar
> touch src/bar/mod.rs
> cargo fmt --all
> ```
> 
> Output:
> 
> ```
> Error writing files: failed to resolve mod `bar`: hi/foo/src does not exist
> ```

This almost certainly goes back to a number of pending PR in need of backport triaging. I'd start with those (they should be labeled accordingly) to avoid accidentally reinventing any wheels

**Comment by ytmimi** [comment] 2022-01-11 02:19
Before I saw your comment I actually identified what was going wrong. The issue here is that we're matching on a ``Err(rustc_expand::module::ModError::MultipleCandidates)`` in ``ModResolver::find_external_module`` when we call ``ParseSess::default_submod_path``. Previously this error case was always turned into a ``Err(ModuleResolutionErrorKind::NotFound)``, which isn't correct.

https://github.com/rust-lang/rustfmt/blob/5056f4cfb311a084420f1828cd58af94d143f5e0/src/modules.rs#L447-L453

I was quickly able to fix the issue before I had a chance to read your comment. I've gone through the PRs and I'm struggling to find one that addresses this specific scenario. It's not a major change, just adding a new variant to ModuleResolutionErrorKind, but I'll hold off on submitting it. If you can identify the backport I'll take a look at that otherwise I've got a fix ready to go!

**Comment by calebcartwright** [comment] 2022-01-11 02:29
Try reproducing on the 2.x branch. If you can reproduce then definitely feel free to submit a new PR with your changes. However, if you can't let's try to track down the original fix, and make a decision from there. My hesitation stems from having at least 3 or 4 fixes on that branch that are all dealing with the same code, and I want to try to avoid complicating our ability to pull in those prior fixes

**Comment by ytmimi** [comment] 2022-01-11 03:35
Just tested this out on the 2.0 branch, and couldn't reproduce, so I'll go back through the backport triage more thoroughly to find the PR that fixes this.

**Comment by calebcartwright** [comment] 2022-01-11 03:37
https://github.com/rust-lang/rustfmt/pulls?page=1&q=is%3Apr+label%3Abackport-triage+is%3Aclosed plus any other relevant search criteria you can think of

**Comment by camsteffen** [comment] 2022-01-11 04:45
#4198 may be relevant.

**Comment by ytmimi** [comment] 2022-01-11 20:53
Hey, So I went back and revisited the code. A lot of investigating between the two branches, but I figured out what's going on here. On further inspection I wasn't 100% correct when I said that the issue doesn't occur on the 2.0 branch. We still run into the same parsing error, but the 2.0 branch silently ignores it. The issue comes down to how ``modules::visit_mod_from_ast`` is implemented.

In the 1.0 branch we always return early if their is an error when calling ``ModResolver::visit_sub_mod`` (using the ``? operator``), but in the 2.0 branch we only return early if the error is encountered while we're recursively resolving modules. See the code linked below:

On the 1.0 branch:
https://github.com/rust-lang/rustfmt/blob/5056f4cfb311a084420f1828cd58af94d143f5e0/src/modules.rs#L209-L223

On the 2.0 branch:
https://github.com/rust-lang/rustfmt/blob/cc5521d9b2fff696a852454dd2aa89e7942464dd/src/formatting/modules.rs#L250-L264

#4284 is the ``backport-triage`` PR that introduced this recursive check for returning errors.

I personally feel like the 1.0 behavior is what we want, and that we should let users know that there was a parsing error (the afformentioned ``rustc_expand::module::ModError::MultipleCandidates`` error). However, as things are currently implemented we're telling users that files don't exist, when we it would be more appropriate to inform them about the ambiguous module path.

**Closed** 2022-03-09 03:51 UTC
Labels: a-mods
