### ISSUE TITLE
How to make chained calls to be on new lines

### ISSUE THREAD

**Issue by xahon** [rust-lang/rustfmt#3693] opened 2019-07-18 04:40 UTC
Is there an option to allow >= 3 (or configurable number) calls in a row on self to be wrapped?
```rust
a.do_something()
 .another_thing()
 .build();
```

**Comment by scampi** [comment] 2019-07-18 08:28
#2263 sounds related

**Comment by kellytk** [comment] 2020-03-09 18:26
I would also like for chained calls to be on new lines as shown in @xahon's example.

**Comment by calebcartwright** [comment] 2021-11-23 23:44
Closing as a duplicate of #2263

**Closed by calebcartwright** 2021-11-23 23:44 UTC
Labels: duplicate, a-chains
