### ISSUE TITLE
rustfmt bug which results in poorly formatted code

### ISSUE THREAD

**Issue by Aboussejra** [rust-lang/rustfmt#5381] opened 2022-06-12 09:41 UTC
You can find the repo to reproduce the bug here: https://github.com/Aboussejra/rustfmt_bug

Here is a minimal example I created after I found at work a case that yields a bug in rustfmt.

The given code here in src/main.rs is badly formatted by rustfmt:

```rust
fn main() {
    pub fn foo(vector_of_vectors: Vec<Vec<usize>>) {
        vector_of_vectors.iter().map(|vector_of_number|
            {
            let bar = vector_of_number.iter().find(|number|
            number == &&1).expect("this is a long message, which makes rustfmt fails if long enough");
            bar});
    }
    foo(vec![vec![1, 2]]);
}
```

After investigation the long message in .expect() makes rustfmt fail.

Try changing from:
(Here rustfmt does not work)
`.expect("this is a long message, which makes rustfmt fails if long enough, adding those words do the trick")`

to:
(Here rustfmt does work)
`.expect("this is a long message, which makes rustfmt fails if long enough")`

When rustfmt does not work, code is badly formatted and we have :

```rust
fn main() {
    pub fn foo(vector_of_vectors: Vec<Vec<usize>>) {
        vector_of_vectors.iter().map(|vector_of_number|
            {
            let bar = vector_of_number.iter().find(|number|
            number == &&1).expect("this is a long message, which makes rustfmt fails if long enough, adding those words do the trick");
            bar});
    }
    foo(vec![vec![1, 2]]);
}
```

When it does work (with the shorter message), we have:
```rust
fn main() {
    pub fn foo(vector_of_vectors: Vec<Vec<usize>>) {
        vector_of_vectors.iter().map(|vector_of_number| {
            let bar = vector_of_number
                .iter()
                .find(|number| number == &&1)
                .expect("this is a long message, which makes rustfmt fails if long enough");
            bar
        });
    }
    foo(vec![vec![1, 2]]);
}
```

**Comment by ytmimi** [comment] 2022-06-13 00:44
Thanks for reaching out!

The issue you're running into is that the string passed to `expect()` prevents rustfmt from formatting the chained method calls to satisfy the default `max_width` of `100` so rustfmt just emits back out what you originally wrote. If you format the snippet by hand you'll see that the `expect()` line is ~125 characters long when you include the indentation.

You could get your desired formatting by increasing the `max_width`. If you're using nightly rustfmt you can try setting `format_strings=true` to allow rustfmt to break long strings. For reference here's what your code snippets look like with those two options:

### `max_width=125`

```rust
fn main() {
    pub fn foo(vector_of_vectors: Vec<Vec<usize>>) {
        vector_of_vectors.iter().map(|vector_of_number| {
            let bar = vector_of_number
                .iter()
                .find(|number| number == &&1)
                .expect("this is a long message, which makes rustfmt fails if long enough, adding those words do the trick");
            bar
        });
    }
    foo(vec![vec![1, 2]]);
}
```

### `format_strings=true`

```rust
fn main() {
    pub fn foo(vector_of_vectors: Vec<Vec<usize>>) {
        vector_of_vectors.iter().map(|vector_of_number| {
            let bar = vector_of_number.iter().find(|number| number == &&1).expect(
                "this is a long message, which makes rustfmt fails if long enough, adding those \
                 words do the trick",
            );
            bar
        });
    }
    foo(vec![vec![1, 2]]);
}
```

This is also a duplicate of https://github.com/rust-lang/rustfmt/issues/3416, and https://github.com/rust-lang/rustfmt/issues/3863 so I'm going to close accordingly

**Closed** 2022-06-13 00:45 UTC
Labels: duplicate, a-chains, a-strings
