### ISSUE TITLE
rustfmt fails to remove trailing whitespace prior to overlong string literals

### ISSUE THREAD

**Issue by lf-** [rust-lang/rustfmt#4717] opened 2021-02-23 10:16 UTC
**Describe the bug**

Rustfmt tries to format an overlong string literal, fails, then forgetting to get rid of whitespace, which it notices after and throws an internal error:

```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:3:3:25
  |
3 |     let req_notify_cmds = 
  |                          ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**To Reproduce**

Here's an example that triggers this bug upon attempting to run rustfmt on it:

```rust
fn main() {
    // there is a trailing space on the line below:
    let req_notify_cmds = 
        "        crimes crimes crimes crimes code crimes crimes crimes crimes crimes crimes (of the code variety) crimes crimes crimes";

    println!("{}", req_notify_cmds);
}
```

On the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c7cb0f40061479ae10580897eaea5e83

**Expected behavior**

rustfmt should delete the trailing whitespace successfully

**Meta**

- rustfmt version: rustfmt 1.4.36-nightly (7de6968 2021-02-07)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: editor / cargo fmt / rust playground can reproduce this

**Comment by calebcartwright** [comment] 2021-02-24 03:47
Thanks for reaching out @lf-! I am going to go ahead and close this though as this is currently the expected behavior.

What's happening here is that you've got a very long string lit that rustfmt cannot possibly fit within the max_width limit (`max_width` default is `100` but your string will at a minimum run out to 137). Due to the AST-driven nature of rustfmt, in cases  when successful formatting for a given node cannot be produced, rustfmt is forced to emit the original snippet associated with the node and it doesn't do any subsequent/partial formatting attempts; if your original snippet had trailing whitespace then the emitted snippet will too. That's the default/expected behavior

The best way to fix this would be to either break up your long string yourself so that it's possible to keep all the lines below the max_width limit, or set `format_strings` to `true` to give rustfmt permission to try to split the string to make it fit.

Additionally, in certain cases where the formatting failure is caused by an avoidable excess width limit, such as this one, some subsequent enhancements were made to rustfmt to use the standard formatting rules anyway and allow users to leverage `error_on_unformatted` so that they'll still see the width issue, e.g.

```bash
error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 154)
 --> stdin:3:3:100
  |
3 |     let req_notify_cmds = "        crimes crimes crimes crimes code crimes crimes crimes crimes crimes crimes (of the code variety) crimes crimes crimes";
  |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
```

However, these excess width related enhancements produce different formatting, which violates rustfmt's stability guarantee. As such, these are gated behind the `version` configuration option, so another option for you (albeit one that still has width excess issues) would be to set `version` to `Two`

**Closed by calebcartwright** 2021-02-24 03:47 UTC
Labels: bug
