### ISSUE TITLE
`error[internal]: left behind trailing whitespace`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#5868] opened 2023-07-31 06:08 UTC
````rust
fn main() {
    let _v: Vec<i32> = [1].iter().map(|x| x.clone()).collect(); // could use `*x` instead
    //~^ ERROR using `.clone()` on a double reference, which returns `&str`
}
````

`rustfmt --check`
````
Diff in /tmp/rust/F/icemaker__/5AC1C74D9F9ECD84744150BA76CE5F6322EEB6FB856C15B133BBB855CBA6C3BC.rs at line 1:
 fn main() {
     let _v: Vec<i32> = [1].iter().map(|x| x.clone()).collect(); // could use `*x` instead
+
     //~^ ERROR using `.clone()` on a double reference, which returns `&str`
 }

error[internal]: left behind trailing whitespace
 --> /tmp/rust/F/icemaker__/5AC1C74D9F9ECD84744150BA76CE5F6322EEB6FB856C15B133BBB855CBA6C3BC.rs:3:3:1
  |
3 |
  | ^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
````

**Comment by matthiaskrgr** [comment] 2023-07-31 06:09
[5AC1C74D9F9ECD84744150BA76CE5F6322EEB6FB856C15B133BBB855CBA6C3BC.rs.zip](https://github.com/rust-lang/rustfmt/files/12211943/5AC1C74D9F9ECD84744150BA76CE5F6322EEB6FB856C15B133BBB855CBA6C3BC.rs.zip)

**Comment by ytmimi** [comment] 2023-08-01 01:30
Thanks for the report, but going to close this as a duplicate of #5391

**Closed by ytmimi** 2023-08-01 01:30 UTC
Labels: duplicate, a-comments
