### ISSUE TITLE
`group_imports = "StdExternalCrate"` moved re-exports into use groups

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rustfmt#4723] opened 2021-02-25 19:46 UTC
**Input**

Example: Re-exporting macros from an "associated" proc-macro crate:

```rust
use serde::{Deserialize, Serialize};

// doctests not part of the macro crate because `my_crate`
// needs to be in scope for the macros to actually work

/// # Example
///
/// ```
/// my_crate::do_stuff! { ... }
/// ```
pub use my_macro_crate::do_stuff;

/// # Example
///
/// [Example for derive(MyTrait)...]
pub use my_macro_crate::MyTrait;
```

**Output**

```rust
// doctests not part of the macro crate because `my_crate`
// needs to be in scope for the macros to actually work
/// # Example
///
/// ```
/// my_crate::do_stuff! { ... }
/// ```
pub use my_macro_crate::do_stuff;
/// # Example
///
/// [Example for derive(MyTrait)...]
pub use my_macro_crate::MyTrait;
use serde::{Deserialize, Serialize};
```

Note how the serde import moved all the way down due to it being moved into a group with the re-exports.

**Expected output**

Ideally the same as the input. Maybe re-exports could have their own grouping setting, but just lumping them in with imports seems wrong. Alternatively, re-exports could be their own group or their own three groups (i.e. standard, external, crate re-exports).

**Meta**

- rustfmt version: rustfmt 1.4.36-nightly (7de6968 2021-02-07)
- From where did you install rustfmt?: rustup

**Comment by Cryptjar** [comment] 2021-11-02 18:54
I also got hit by this. To add another example take for instance the example form `Configurations.md#group_imports` with some pubs added, this is the current output of `rustfmt` (spot the `pub`s):

```rust
use alloc::alloc::Layout;
use core::f32;
use std::sync::Arc;

use broker::database::PooledConnection;
pub use chrono::Utc;
use juniper::{FieldError, FieldResult};
use uuid::Uuid;

use super::schema::{Context, Payload};
pub use super::update::convert_publish_payload;
use crate::models::Event;
```

I personally would prefer something similar to the following:

```rust
use alloc::alloc::Layout;
use core::f32;
use std::sync::Arc;

use broker::database::PooledConnection;
use juniper::{FieldError, FieldResult};
use uuid::Uuid;

use super::schema::{Context, Payload};
use crate::models::Event;

pub use chrono::Utc;
pub use super::update::convert_publish_payload;
```

By accident, I discovered one can achieve that behavior with the current `rustfmt` with a little hack:

```rust
use alloc::alloc::Layout;
use core::f32;
use std::sync::Arc;

use broker::database::PooledConnection;
use juniper::{FieldError, FieldResult};
use uuid::Uuid;

use super::schema::{Context, Payload};
use crate::models::Event;

mod hack {} // separates the two import groupings

pub use chrono::Utc;

pub use super::update::convert_publish_payload;
```

**Comment by ytmimi** [comment] 2022-07-26 16:48
going to close this as a duplicate of #4070

**Closed by ytmimi** 2022-07-26 16:48 UTC
Labels: duplicate, a-imports
