### ISSUE TITLE
Group imports by their visiblities

### ISSUE THREAD

**Issue by kafji** [rust-lang/rustfmt#5696] opened 2023-02-20 06:22 UTC
Hi, this is a feature request.

I'm using `group_imports: One` and I found that it's difficult to distinguish re-exported imports at glance.

Unordered:
```rust
use chrono::Utc;
use super::update::convert_publish_payload;

pub use juniper::{FieldError, FieldResult};
use uuid::Uuid;
use alloc::alloc::Layout;

use std::sync::Arc;

use broker::database::PooledConnection;

use super::schema::{Context, Payload};
use core::f32;
use crate::models::Event;
```

Ordered:
```rust
use super::schema::{Context, Payload};
use super::update::convert_publish_payload;
use crate::models::Event;
use alloc::alloc::Layout;
use broker::database::PooledConnection;
use chrono::Utc;
use core::f32;
pub use juniper::{FieldError, FieldResult};
use std::sync::Arc;
use uuid::Uuid;
```

I'm proposing another variant `Visiblity` that will group them by their visibilities.

Unordered:
```rust
pub(super) use chrono::Utc;
pub use super::update::convert_publish_payload;

pub(crate) use juniper::{FieldError, FieldResult};
pub(in crate::models) use uuid::Uuid;
use alloc::alloc::Layout;

use std::sync::Arc;

pub(self) use broker::database::PooledConnection;

use super::schema::{Context, Payload};
use core::f32;
pub use crate::models::Event;
```

Ordered:
```rust
use super::schema::{Context, Payload};
use alloc::alloc::Layout;
use core::f32;
use std::sync::Arc;

pub(self) use broker::database::PooledConnection;

pub(super) use chrono::Utc;

pub(crate) use juniper::{FieldError, FieldResult};

pub(in crate::models) use uuid::Uuid;

pub use super::update::convert_publish_payload;
pub use crate::models::Event;
```

[I've made a patch here](https://github.com/rust-lang/rustfmt/compare/master...kafji:rustfmt:kfj/group-import-visibility).

What do you think?

**Comment by ytmimi** [comment] 2023-02-20 16:44
@kafji Thanks for reaching out! This feels like a duplicate of #4070 so I'm going to close this issue.

PRs are always welcome, but I want to be up front and say that there are higher priorities on the teams backlog and it might be a while before we're able to give it a review.

**Closed by ytmimi** 2023-02-20 16:44 UTC
