### ISSUE TITLE
internal error 1.5.2 stable

### ISSUE THREAD

**Issue by sftse** [rust-lang/rustfmt#5903] opened 2023-09-07 09:00 UTC
rustfmt 1.5.2-stable (eb26296 2023-08-03)

Reduced snippet
```
impl F {
    fn foo() {
        query
            .fold(&mut x, |_| {
                if true {}
                
                if true {
                    j.push("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
                }
            });
    }
}
```

Error

error[internal]: left behind trailing whitespace
 --> /home/c/rustfmt-err/src/lib.rs:6:6:1
  |
6 |                 
  | ^^^^^^^^^^^^^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.

**Comment by sftse** [comment] 2023-09-07 09:01
Also fails on

rustfmt 1.6.0-nightly (28eb857 2023-08-12)

**Comment by sftse** [comment] 2023-09-07 09:07
```
impl F {
    fn f() {
        q.f({
            
            if y {
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            }
        });
    }
}
```

**Comment by ytmimi** [comment] 2023-09-08 01:50
Thanks for the report! Closing this as a duplicate of #3863

You'll have to manually remove the trailing whitespace or increase the `max_width` until rustfmt is able to format this. Alternatively, if you're string has a viable place to break you could try running rustfmt with `--config=format_strings=true` to give rustfmt a chance to break the string so that it comes in under the `max_width`, allowing rustfmt to rewrite the chain.

**Input**:
```rust
impl F {
    fn f() {
        q.f({
            
            if y {
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            }
        });
    }
}
```

**output**:
```rust
impl F {
    fn f() {
        q.f({
            if y {
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            }
        });
    }
}
```

**Closed by ytmimi** 2023-09-08 01:50 UTC
