### ISSUE TITLE
Underindentation for chained methods

### ISSUE THREAD

**Issue by zgotsch** [rust-lang/rustfmt#4199] opened 2020-05-24 22:14 UTC
I noticed that some of my chained methods are not indented as I would expect. Here is my code after formatting:
```rust
let outdated_executables = async {
    let outdated = homebrew::outdated().await.unwrap();
    let executables = join_all(outdated.iter().map(|p| {
        homebrew::executables(&p.package_name, &p.installed_versions.last().unwrap())
    }))
    .await
    .into_iter()
    .flatten()
    .collect::<HashSet<std::ffi::OsString>>();
    return executables;
};
```
and here is what I expect
```rust
let outdated_executables = async {
    let outdated = homebrew::outdated().await.unwrap();
    let executables = join_all(outdated.iter().map(|p| {
        homebrew::executables(&p.package_name, &p.installed_versions.last().unwrap())
    }))
        .await
        .into_iter()
        .flatten()
        .collect::<HashSet<std::ffi::OsString>>();
    return executables;
};
```

I tried to make a minimal example, which looks like this:
```rust
join_all(foo.map(|p| {
    bar(
        // this comment stands in for long arguments
    )
}))
.into_iter();
```
You can also find it and the original here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=60b1965f30288344ffff9b9df6678347

Many changes to the example result in fixed indentation, so I'm not sure exactly what is causing the underindentation. Let me know if this is expected behavior and my expectations are misplaced for some reason!

**Comment by calebcartwright** [comment] 2020-05-24 22:30
This is the expected behavior currently @zgotsch. However, we may provide some future enhancements to allow users to configure whether or not the child chain items are indented when the chain parent is multi-lined

This is a duplicate of #3157 though so I'm going to close this one (feel free to track the linked issue).

**Closed by calebcartwright** 2020-05-24 22:30 UTC
