### ISSUE TITLE
Misaligned comments when mixing unicode and ascii

### ISSUE THREAD

**Issue by tfeldmann** [rust-lang/rustfmt#5564] opened 2022-10-19 13:28 UTC
I've got this strange formatting:

```rust
const STRAIGHT_WIDE: [&str; 16] = [
    "  ",     //
    "╵ ",   //  U
    "╶─", //    R
    "└─", //  U R
    "╷ ",   //      D
    "│ ",   //  U   D
    "┌─", //    R D
    "├─", //  U R D
    "╴ ",   //        L
    "┘ ",   //  U     L
    "──", //    R
    "┴─", //  U R   L
    "┐ ",   //      D L
    "┤ ",   //  U   D L
    "┬─", //    R D L
    "┼─", //  U R D L
];
```

Expected output:
```rust
const STRAIGHT_WIDE: [&str; 16] = [
    "  ", //
    "╵ ", //  U
    "╶─", //    R
    "└─", //  U R
    "╷ ", //      D
    "│ ", //  U   D
    "┌─", //    R D
    "├─", //  U R D
    "╴ ", //        L
    "┘ ", //  U     L
    "──", //    R
    "┴─", //  U R   L
    "┐ ", //      D L
    "┤ ", //  U   D L
    "┬─", //    R D L
    "┼─", //  U R D L
];
```

```
❯ rustfmt -V
rustfmt 1.5.1-stable (a55dd71d 2022-09-19)
```

**Comment by ytmimi** [comment] 2022-10-19 13:34
Thanks for reaching out!

This is a duplicate of #5504, and the issue has been resolved on master, but hasn't been released yet.

**Closed by ytmimi** 2022-10-19 13:34 UTC
