### ISSUE TITLE
Multiline comment inside struct get unidented 

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rustfmt#4976] opened 2021-09-03 07:55 UTC
Take the following code:

```rust
struct MyStruct {
    /* Some comment.
    /// Some field
    some_field: Option<String>,
    */
}
```

Looks reasonable to me, but rustfmt changes it to the following:

```rust
struct MyStruct {
    /* Some comment.
/// Some field
some_field: Option<String>,
*/}
```

Version:
```
rustfmt 1.4.37-stable (a178d032 2021-07-26)
```

**Comment by calebcartwright** [comment] 2021-09-04 17:37
Closing as duplicate of #4854

**Closed by calebcartwright** 2021-09-04 17:37 UTC
Labels: duplicate
