### ISSUE TITLE
Options website broken on Firefox 125

### ISSUE THREAD

**Issue by djeedai** [rust-lang/rustfmt#6153] opened 2024-04-27 13:59 UTC
Using Firefox 125 the options website at http://rust-lang.github.io/rustfmt doesn't load due to some error reported in console:

```
[Vue warn]: Error in created hook (Promise/async): "TypeError: e.response is undefined"

(found in <Root>) vue.js:634:17
TypeError: e.response is undefined
    handleReqFailure https://rust-lang.github.io/rustfmt/?:218
    created https://rust-lang.github.io/rustfmt/?:195
    VueJS 4
    <anonymous> https://rust-lang.github.io/rustfmt/?:103
vue.js:1897:15
Error evaluating async computed property: handleReqFailure@https://rust-lang.github.io/rustfmt/?:218:23
outputHtml@https://rust-lang.github.io/rustfmt/?:137:28
get@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4472:27
evaluate@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4577:23
computedGetter@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4826:19
parsePath/<@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:518:9
get@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4472:27
Watcher@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4461:14
stateMixin/Vue.prototype.$watch@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4936:21
handleAsyncComputedPropetyChanges@https://unpkg.com/vue-async-computed@3.8.1:214:8
created@https://unpkg.com/vue-async-computed@3.8.1:166:46
invokeWithErrorHandling@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:1863:59
callHook@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4214:32
initMixin/Vue.prototype._init@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:4996:15
Vue@https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js:5072:10
@https://rust-lang.github.io/rustfmt/?:103:13
```

I'm not sure this is the correct repo to report, but https://github.com/rust-lang/rust-lang.github.io doesn't seem to have any code related to this.

**Comment by ytmimi** [comment] 2024-04-28 19:51
I updated to the latest version of firefox (125.0.2) and I'm unable to reproduce the issue.

<img width="1370" alt="Screen Shot 2024-04-28 at 3 50 51 PM" src="https://github.com/rust-lang/rustfmt/assets/29028348/5e414630-62b9-47b2-b461-897063bc0cfd">

**Comment by ytmimi** [comment] 2024-04-28 19:52
@djeedai maybe you just need to update to the latest version of firefox? Going to close this since this isn't really a bug in rustfmt and the issue seems to be resolved.

**Closed by ytmimi** 2024-04-28 19:52 UTC

**Comment by ian-h-chamberlain** [comment] 2024-06-14 14:17
Hi @ytmimi, I'm using the latest Firefox 127.0 and I see the same error. I was also able to reproduce in Safari, so I think this might be a documentation bug unrelated to the browser:

<img width="564" alt="Screenshot 2024-06-14 at 10 14 12" src="https://github.com/rust-lang/rustfmt/assets/11131775/c464e685-f7b6-41f0-94ec-a76b301caf30">

In both cases, the configuration option list just appears empty, no matter what version of Rustfmt I select in the dropdown. Search and the `stable` checkbox both also appear to have no effect except the same error message appears in the console each time.

Is there anything else I can do to help debug? For reference I am running on macOS Sonoma 14.5 in case that's important.

**Comment by ytmimi** [comment] 2024-06-14 14:31
@ian-h-chamberlain  We got a PR in yesterday for the docs site, which I'm hoping will address the issue (https://github.com/rust-lang/rustfmt/pull/6194). If you're able to look into whether or not it resolves the issue that would be awesome!

I've also checked on chrome and I can't see the list of configurations.

**Comment by djeedai** [comment] 2024-06-16 21:30
Tried on Safari and Firefox now, this is still broken @ytmimi, with the exact same error. Did the fix deploy?
