### ISSUE TITLE
How to disable formatting for comments?

### ISSUE THREAD

**Issue by Hirrolot** [rust-lang/rustfmt#4787] opened 2021-04-05 10:38 UTC
I have an MD table like this:

```
| Feature | Description |
|----------|----------|
| blah | some long long long long long long long long line |
```

I also have `wrap_comments = true` in my `rustfmt.toml`. As a result, rustfmt breaks the long line and disfigures the table. The comment itself is located at the top level of a `.rs` file and must be treated as a public documentation.

Can I tell rustfmt to skip this table?

**Comment by Hirrolot** [comment] 2021-04-05 13:53
As a workaround:

```rs
#![cfg_attr(feature = "nightly", feature(extended_key_value_attributes))]

// ...

#![cfg_attr(feature = "nightly", doc = include_str!("features.txt"))]
```

**Comment by jyn514** [comment] 2021-04-06 22:46
> #![cfg_attr(feature = "nightly", doc = include_str!("features.txt"))]

FYI this doesn't work like you expect it to: https://github.com/rust-lang/rust/issues/82768

**Comment by calebcartwright** [comment] 2021-04-07 02:21
Thanks for reaching out but going to close as a duplicate of #4210. Please let me know if you feel like this is different/not a duplicate.

The fix has already been made but just hasn't been released. I will try to pull this into the next release, though no guarantees.

**Closed by calebcartwright** 2021-04-07 02:21 UTC
