### ISSUE TITLE
Formatting removes comments within braces of imports

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rustfmt#5319] opened 2022-04-24 14:09 UTC
Minimal example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=942d0b7867cbdf3c09ff7d639a41719c

```rust
pub use std::collections::{
    // HashMap,
    HashSet,
};
```

Rustfmt will turn this into:

```rust
pub use std::collections::HashSet;
```

And completely discard the commented-out `HashMap`. Similarly, this will also remove all comments within the braces for imports, regardless of whether they include valid imports.

**Comment by ytmimi** [comment] 2022-04-24 15:21
Thanks for the report!

This is actually a duplicate of #4708 and #3984. This issue was fixed in another branch and we're waiting for #5290 to be merged so we can backport that fix. I've gone ahead and tested your code snippet on the #5290 branch and the comments are left in place 😄 

Since this is a duplicate I'm going to go ahead and close the issue. Thanks again for taking the time to bring this to our attention!

**Closed** 2022-04-24 15:21 UTC
Labels: duplicate, a-comments, a-imports

**Comment by clarfonthey** [comment] 2022-04-24 15:33
Looks like I didn't search hard enough. ><

Thank you!
