### ISSUE TITLE
Inline comments don't work after {

### ISSUE THREAD

**Issue by oriongonza** [rust-lang/rustfmt#5886] opened 2023-08-15 15:38 UTC
```rs
None => { // Comment
```
gets changed to 
```rs
None => { 
  // Comment
```

**Comment by ytmimi** [comment] 2023-08-15 15:54
Thanks for reaching out. Closing as a duplicate of https://github.com/rust-lang/rustfmt/issues/3255

**Closed as not planned by ytmimi** 2023-08-15 15:54 UTC
Labels: S-duplicate, A-comments
