### ISSUE TITLE
silent formatting failure in match statements

### ISSUE THREAD

**Issue by boemjay** [rust-lang/rustfmt#5950] opened 2023-10-27 11:35 UTC
### Error

rustfmt fails to format any branches inside a match statement if it cannot format the whole statement.

### Expected Behaviour

All other branches in the match statement should be formatted correctly, even if one branch fails to format.

### Steps to reproduce

Try to format the following `main.rs`:
```rs
fn main() {
    match true {
        false => {println!("nothing inside this match statement is formatted anymore")
        }
        _ => "String causing the failure xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    };
}
```

Output of `rustfmt --check`:
_None_

Now remove one of the `x` placeholder characters in the string and format again.

Output of `rustfmt --check`:

```
 fn main() {
     match true {
-        false => {println!("nothing inside this match statement is formatted anymore")
+        false => {
+            println!("nothing inside this match statement is formatted anymore")
         }
-        _ => "String causing the failure xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
+        _ => {
+            "String causing the failure xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
+        }
     };
 }
```

### Additional Information
Tested on `rustfmt 1.6.0-nightly (fcab248 2023-10-13)`

**Comment by ytmimi** [comment] 2023-10-27 17:17
Thanks for reaching out. This is a duplicate of #4797

**Closed by ytmimi** 2023-10-27 17:17 UTC
