### ISSUE TITLE
Comment after enum member prevents rustfmt from doing its work

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rustfmt#4957] opened 2021-08-16 20:14 UTC
The following is not formatted by rustfmt due to the comment:
```rs
use std::cmp::Ordering;

fn main() {
    match 1.cmp(&1) {
        Ordering::Greater |
        Ordering::Equal //hello


        =>       {





                                          }
        
        _=> {}
    }
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a33f654d34616378214d7db0e8e2cff7
I expect a formatting like this:
```rs
use std::cmp::Ordering;

fn main() {
    match 1.cmp(&1) {
        Ordering::Greater |
        Ordering::Equal //hello
        => {}
        _ => {}
    }
}
```

**Comment by calebcartwright** [comment] 2021-09-08 02:08
Thank you for the report but closing as a duplicate of #4119

**Closed by calebcartwright** 2021-09-08 02:08 UTC
