### ISSUE TITLE
Naked semicolon in an empty body needs to be formatted twice

### ISSUE THREAD

**Issue by toc-the-younger** [rust-lang/rustfmt#4627] opened 2021-01-05 19:48 UTC
```
loop {
    ;
}
```
gets formatted to
```
loop {
}
```
which then gets formatted to
```
loop {}
```
Thus requiring two calls to rustfmt to achieve a stable state.

**Expected behavior**
```
loop {
    ;
}
```
should format in one step to
```
loop {}
```

**Meta**

- rustfmt version: `rustfmt 1.4.29-nightly (70ce1825 2020-12-04)`
- From where did you install rustfmt?: cargo
- How do you run rustfmt: `cargo fmt`

**Comment by calebcartwright** [comment] 2021-01-07 02:20
Thanks for the report. This is really a duplicate of #3868 which I'd fixed in source a while ago, but back then we were unable to release/backport the change. That's because at the time the parser/AST didn't give us a way to differentiate between empty tuple expression in a statement position and a standalone semi as an empty statement.

Subsequent enhancements in the parser and AST updates have addressed that though so will clean this up in source and schedule it for an upcoming release.

**Closed** 2021-01-07 03:17 UTC
Labels: 1x-backport:pending, bug, duplicate
