### ISSUE TITLE
Panic with 'byte index is not a char boundary'  with non-ascii char

### ISSUE THREAD

**Issue by erasin** [rust-lang/rustfmt#5006] opened 2021-09-27 06:46 UTC
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=472492734e55e816b0b853634f1f9653)
```rust
enum 消息 {
    内容1,
    内容2,
}

fn main() {
    let 消息内容 = 消息::内容1;

    let n = match 消息内容 {
        消息::内容1 => 1,
        消息::内容2 => 2,
    };

    println!("--> {}!", n);
}
```

```
[Error - 2:59:22 PM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit status: 101
                           stdout: 
                           stderr: thread 'main' panicked at 'byte index 138 is not a char boundary; it is inside '消' (bytes 137..140) of `enum 消息 {
    内容1,
    内容2,
}

fn main() {
    let 消息内容 = 消息::内容1;

    let n = match 消息内容 {
        消息::内容1 => 1,
        消息::内容2 => 2,
    };

    println!("--> {}!", n);
}
`', src/tools/rustfmt/src/visitor.rs:47:15
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail
   3: rustfmt_nightly::visitor::SnippetProvider::span_to_snippet
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: rustfmt_nightly::matches::rewrite_match
   6: rustfmt_nightly::expr::format_expr
   7: rustfmt_nightly::expr::rewrite_assign_rhs_expr
   8: rustfmt_nightly::expr::rewrite_assign_rhs_with
   9: rustfmt_nightly::items::<impl rustfmt_nightly::rewrite::Rewrite for rustc_ast::ast::Local>::rewrite
  10: rustfmt_nightly::stmt::format_stmt
  11: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  12: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  13: rustfmt_nightly::visitor::FmtVisitor::visit_block
  14: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  15: rustfmt_nightly::visitor::FmtVisitor::visit_item
  16: rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering
  17: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  18: rustfmt_nightly::visitor::FmtVisitor::format_separate_mod
  19: rustfmt_nightly::formatting::format_project
  20: scoped_tls::ScopedKey<T>::with
  21: rustfmt_nightly::Session<T>::format
  22: rustfmt::format_and_emit_report
  23: rustfmt::execute
  24: rustfmt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  Code: -32900 
```

**Comment by calebcartwright** [comment] 2021-09-29 02:29
Thanks for reaching out, but I'm going to close as this has already been resolved (duplicate of #4868). You'll note that the issue cannot be reproduced on the playground, so if you're seeing this locally you may want to try updating your toolchain version/ensure you aren't using an old version of rustfmt.

**Closed by calebcartwright** 2021-09-29 02:29 UTC
