### ISSUE TITLE
`wrap_comments` overflows into codeblock fence

### ISSUE THREAD

**Issue by grant0417** [rust-lang/rustfmt#6416] opened 2024-12-12 05:04 UTC
When using a code block in a doc comment and `wrap_comments` is enabled, the comment will wrap into the next line making the following code block no longer valid a valid code block. 

The [syntax reference](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#syntax-reference) for rustdoc says that exact syntax is the [Fenced Code Blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks) section of the CommonMark specification. The CommonMark spec states: "A fenced code block may interrupt a paragraph, and does not require a blank line either before or after."

## Example

Initial code:

```
/// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris. Maecenas congue ligula ac quam
/// ```
/// let foo = 0;
/// ```
fn bar() {}
```

Result:

```
/// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam
/// lectus. Sed sit amet ipsum mauris. Maecenas congue ligula ac quam ```
/// let foo = 0;
/// ```
```

Expected:

```
/// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam
/// lectus. Sed sit amet ipsum mauris. Maecenas congue ligula ac quam 
/// ```
/// let foo = 0;
/// ```
```

**Comment by ytmimi** [comment] 2024-12-12 14:53
Duplicate of https://github.com/rust-lang/rustfmt/issues/5244

**Closed by ytmimi** 2024-12-12 14:53 UTC
