### ISSUE TITLE
`left behind trailing whitespace` prints location as file:line:line:column

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#5810] opened 2023-07-03 16:42 UTC
![frustfmt](https://github.com/rust-lang/rustfmt/assets/476013/f50f3096-6452-41a0-86d4-0372f3460395)

**Comment by ytmimi** [comment] 2023-07-03 17:10
Thanks for reaching out. This is a duplicate of #5463, and #5506 is already open to resolve the issue

**Closed by ytmimi** 2023-07-03 17:10 UTC
