### ISSUE TITLE
[internal error] on trying to format overlong string literal

### ISSUE THREAD

**Issue by moxian** [rust-lang/rustfmt#4414] opened 2020-09-04 12:27 UTC
**Describe the bug**

Have a file with the following contents:

```rust
fn some() {
    let results = 
    foo.bar(r#"
            a aaaaaaaaaaaaa aaaaa aaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaa aaa aaaaaaaaaaaaaaaaaaaa
    "#
    , );
}
```
(the specific content of the string literal does not seen to matter, but the length does).

Run `rustfmt filename.rs`

Get:
```rust
> rustfmt stuff.rs
error[internal]: left behind trailing whitespace
 --> \\?\D:\path\to\stuff.rs:2:2:17
  |
2 |     let results =
  |                  ^
  |

warning: rustfmt has failed to format. See previous 1 errors.

```

Note that the mere presence of the string literal anywhere in the file breaks formatting for the entire file, not just for the containing block (but that might be WAI)

**Expected behavior**

no [internal error]; other lines get formatted just fine, even if this one cannot

**Meta**

- rustfmt version:rustfmt 1.4.20-beta (48f6c32e 2020-08-09)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: doesn't matter. (both `rustfmt path\to\file.rs` and the vscode integration observe the same result)

**Comment by calebcartwright** [comment] 2020-09-06 15:52
Thank you for reaching out @moxian. This is a duplicate (#3863) of a known/existing issues with formatting chains when one or more of the chain elements would exceed max_width when formatted. In these cases, rustfmt leaves the original formatting in place and defers to the developer to properly format, because any formatting rustfmt would apply would violate a rule (max width in this case)

Your snippet above contains a chain due to the foo.bar(... on line 3, and the string arg exceeds the max_width value of 100. Your original snippet has a trailing space after the `=` on line 2, so when rustfmt bails on formatting the chain and reverts to the original snippet, your original trailing space is maintained which triggers the trailing whitespace warning.

To get rid of the warning, you should remove the trailing whitespace after the `=`. To allow rustfmt to be able to format the chain, you could try moving the raw string lit out of the chain `foo.bar(some_new_var)` or if you don't need a raw string lit, use a regular string and try setting `format_strings = true` in your rustfmt config file to allow rustfmt to split the string to stay within the max_width limit.

> Note that the mere presence of the string literal anywhere in the file breaks formatting for the entire file, not just for the containing block (but that might be WAI)

Hmmm. I'm not able to reproduce this locally (although I do observe this behavior on the Playground). 

When I run rustfmt against this:
```rust
fn some() {
    let results = 
    foo.bar(r#"
            a aaaaaaaaaaaaa aaaaa aaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaa aaa aaaaaaaaaaaaaaaaaaaa
    "#
    , );
}

fn           foo (   ) {  



println!("bar")         ; }
```

I get this output:
 
```bash
Diff in /home/caleb/dev/rustfmt-sandbox/chains-8/src/lib.rs at line 6:
     , );
 }
 
-fn           foo (   ) {  
-
-
-
-println!("bar")         ; }
+fn foo() {
+    println!("bar");
+}
+
error[internal]: left behind trailing whitespace
 --> /home/caleb/dev/rustfmt-sandbox/chains-8/src/lib.rs:2:2:17
  |
2 |     let results = 
  |                  ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by calebcartwright** [comment] 2020-09-17 02:58
Closing as a duplicate

**Closed by calebcartwright** 2020-09-17 02:58 UTC
Labels: bug, duplicate
