### ISSUE TITLE
URL in comment prevents formatting

### ISSUE THREAD

**Issue by krtab** [rust-lang/rustfmt#5634] opened 2022-12-22 11:09 UTC
When using rustfmt to wrap doc comments, having a URL in the comments prevents any wrapping from happening.

Example:

```rust
/// This is indented fine. It is rather long but does not contains any link. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
struct Foo {}


/// This is not indented. The only real difference is the presence of a URL. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Source: https://www.lipsum.com/
struct Bar {}
```

Becomes:

```rust
/// This is indented fine. It is rather long but does not contains any link.
/// Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
/// tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
/// quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
/// consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
/// cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
/// non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
struct Foo {}

/// This is not indented. The only real difference is the presence of a URL. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Source: https://www.lipsum.com/
struct Bar {}
```

The config used for the tests was:

```
unstable_features = true
wrap_comments = true
error_on_unformatted = true
error_on_line_overflow = true
```

**Comment by krtab** [comment] 2022-12-22 11:36
According to the comments (cf below) in rustfmt source, this is intended behavior, but I don't understand why, and couldn't find a discussion of why in the tracking issues. Comments frequently have URL, including in markdown links in them, so I think it would be best not to have this limitation.

https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/comment.rs#L799-L803

**Comment by ytmimi** [comment] 2022-12-22 12:51
Thanks for reaching out. This is indeed intended behavior. We've had several issues in the past where breaking urls has been an issue. In the worst case breaking urls would prevent rustdoc from rendering them properly so we're erring on the side of caution and not breaking those lines at all.

Check out the following issues for reference: #506, #3787, #5095, #5260

It would be great if someone could help update the docs for [`wrap_comments`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#wrap_comments) to better communicate those details 😁

**Comment by krtab** [comment] 2022-12-22 13:29
I see how it could have break in the past but isn't it something that can be fixed? Would you be open to a PR restoring wrapping of comments containing urls? It seems to me that this is merely a case of correctly detecting all possible URL formats with an exhaustive enough regex. Am I Missing something?

**Comment by ytmimi** [comment] 2022-12-22 16:00
> but isn't it something that can be fixed? Would you be open to a PR restoring wrapping of comments containing urls?

I think the current implementation could be made more permissive, but we still wouldn't want to introduce line break within a URL. You'll likely need to change how [`break_string`](https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/string.rs#L224) works. You're welcome to give it a try. The simpler and more straightforward the patch the better!

> It seems to me that this is merely a case of correctly detecting all possible URL formats with an exhaustive enough regex. Am I missing something?

Sorry, would you mind elaborating a little on this. Are you referring to the current implementation or what you'd need to do to solve the issue?

**Comment by ytmimi** [comment] 2022-12-22 17:19
All that being said, I would still like to update the docs to better describe cases when we won't wrap comments

**Comment by krtab** [comment] 2022-12-23 14:54
I've added documentation but still would like to give a go to the underlying issue and get formatting of comments with urls to work (without splitting urls themselves of course).

**Comment by ytmimi** [comment] 2022-12-23 21:16
@krtab I'd like to close this once we update the docs to better describe how the feature is currently intended to work.

That being said, I'd be more than happy to review a follow up PR to expand on the current behavior of `wrap_comments` 😁

**Comment by mladedav** [comment] 2023-03-07 21:15
@ytmimi The documentation seems to have been updated in #5637 if you want to close this (and/or create a separate issue)

**Comment by ytmimi** [comment] 2023-03-07 22:21
@mladedav appreciate you pointing that out 😁

**Closed by ytmimi** 2023-03-07 22:21 UTC
Labels: good first issue, documentation
