### ISSUE TITLE
Suggestion: Rename `--all` to `--workspace`

### ISSUE THREAD

**Issue by behnam** [rust-lang/rustfmt#4441] opened 2020-09-27 21:24 UTC
In https://github.com/rust-lang/cargo/issues/6977, `cargo`'s main subcommands, including `check`, `build`, and `test`, were updated to use `--workspace` instead of `--all`, to prevent the confusion about what the phrase "all" refers to.

Looks like `cargo fmt` still uses `--all` and have not switched to `--workspace`. Suggesting making that transition here, as well.

What do you think?

**Comment by calebcartwright** [comment] 2020-09-27 22:43
Thanks for reaching out @behnam 

The `--all` flag means something different in the cargo fmt context, more info [here](https://github.com/rust-lang/rustfmt/issues/4247#issuecomment-644957261), and this is also a duplicate of #3911 so I'm going to close.

**Closed by calebcartwright** 2020-09-27 22:43 UTC
