### ISSUE TITLE
BUG: Fails to keep a space before range `..` when its LHS is a binary operation whose RHS is a float literal ending with `.`

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang/rustfmt#6175] opened 2024-05-24 15:53 UTC
I wonder how I can make the title short :thinking:

In the following code, the space between `1.` and `..` must be kept, as together they form an illegal token `...`.

```rust
fn main() {
    let a = 0. + 1. ..2.;
}
```

Expected: no changes, found:

```rust
fn main() {
    let a = 0. + 1...2.;
}
```

Related: #3854 , but it only handles the case when LHS of `..` is not a binary expression.  Indeed, this code is not modified by rustfmt as expected:
```rust
fn main() {
    let a = 1. ..2.;
}
```

**Comment by ytmimi** [comment] 2024-05-24 16:06
Duplicate of #6059, and should already be fixed by #6085. Just hasn't been released yet.

**Closed by ytmimi** 2024-05-24 16:06 UTC

**Comment by TonalidadeHidrica** [comment] 2024-05-24 16:44
It still presists on nightly build.  Isn't the nightly build from the master branch d5f1200e, which is later than the merge commit 73c8149?

```
$ pbpaste
fn main() {
    let a = 0. + 1. ..2.;
}
$ pbpaste | rustfmt +nightly
fn main() {
    let a = 0. + 1...2.;
}
$ rustfmt +nightly --version
rustfmt 1.7.0-nightly (8679004 2024-05-23)
```

**Comment by ytmimi** [comment] 2024-05-24 17:13
Nope!

rustfmt [and some other dev tools](https://rustc-dev-guide.rust-lang.org/external-repos.html?#external-dependencies-subtree) are git subtrees of the `rust-lang/rust` repo. rustfmt is developed here in `rust-lang/rustfmt`, but it's released from the [in-tree source in `rust-lang/rust`](https://github.com/rust-lang/rust/tree/master/src/tools/rustfmt).

Part of rustfmt's release process is syncing changes here with `rust-lang/rust`. Until we do our sync the changes won't be released.

**Comment by TonalidadeHidrica** [comment] 2024-05-24 17:24
Ah, that makes sense!  Thank you for kindly telling me about it, and I am sorry for having disturbed you.
