### ISSUE TITLE
`/// ///` confuses rustfmt into a crush

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#5317] opened 2022-04-20 10:20 UTC
The following code crushes `rustfmt` with the format code in documentation comments option: 
```rust
/// /// ```
/// ```
/// 
/// ```
/// ```
fn f() {}
```
```shell
; rustfmt --config format_code_in_doc_comments=true t.rs
thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}
`', src/tools/rustfmt/src/lib.rs:399:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
; rustfmt --version
rustfmt 1.4.38-stable (7737e0b 2022-04-04)
```

**Comment by ytmimi** [comment] 2022-04-20 13:20
Thanks for the report!

I'm going to close this as I believe this is a duplicate of both #5234 and #4793, and the issue is the empty code block.

**Closed by ytmimi** 2022-04-20 13:20 UTC
Labels: duplicate, a-comments
