### ISSUE TITLE
rustfmt errors on valid async code

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rustfmt#4652] opened 2021-01-18 08:25 UTC
Found in the [wild](https://github.com/russelltg/srt-rs/blob/master/srt-transmit/src/main.rs#L71):
``` rust
  fn read_to_stream(read: impl AsyncRead + Unpin) -> impl Stream<Item = Result<Bytes, Error>> {
      stream::unfold(read, |mut source| async move {
          let mut buf = [0; 1316];
          let bytes_read = match source.read(&mut buf[..]).await {
              Ok(0) => return None,
              Ok(bytes_read) => bytes_read,
              Err(e) => return Some((Err(Error::from(e)), source)),
          };

          Some((Ok(Bytes::copy_from_slice(&buf[..bytes_read])), source))
      })
  }
```
`async move` is not considered valid:

```
error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found keyword `move`
  --> /Users/lu_zero/Sources/rust/srt/srt-transmit/src/main.rs:72:45
   |
72 |     stream::unfold(read, |mut source| async move {
   |                                             ^^^^ expected one of 8 possible tokens
```

Tested with `rustfmt 1.4.25-stable (0f29ff6d 2020-11-11)` and `rustfmt 1.4.32-nightly (216a6430 2021-01-16)`

**Comment by vallentin** [comment] 2021-01-18 09:20
I can replicate this error with rustfmt 1.4.25-stable (0f29ff6d 2020-11-11).

However, I cannot replicate the error with master (d11fde864d2369623de35a951b8a2026b7652b20), so this might have been fixed.

**Comment by calebcartwright** [comment] 2021-01-18 16:58
This seems like a case of rustfmt being invoked with the default edition of 2015. I cannot reproduce this when the necessary 2018 edition is set

**Comment by calebcartwright** [comment] 2021-01-18 17:39
Thanks for reporting but going to close this given the above. Please feel free to reopen if you can reproduce with the edition set to 2018 (`rustfmt --edition 2018 ...`, `edition = 2018` in rustfmt.toml, or running `cargo fmt` with the 2018 edition set in Cargo.toml)

**Closed by calebcartwright** 2021-01-18 17:39 UTC
