### ISSUE TITLE
Unexpected formatting of macro with block when hard_tabs = true.

### ISSUE THREAD

**Issue by nitsky** [rust-lang/rustfmt#4542] opened 2020-11-22 19:14 UTC
**Describe the bug**

I am observing unexpected formatting of macro bodies when the macro emits a block wrapped in curly braces and `hard_tabs = true`.

**To Reproduce**

Run the following macro definition through rustfmt with `hard_tabs = true`:

Input:

```rust
macro_rules! example {
	() => {{ let x = 5; Ok(x) }};
}
```

Output:

```rust
macro_rules! example {
	() => {{
		let x = 5;
		Ok(x)
		}};
}
```

The output has an extra level indentation at the closing curly braces. This does not happen when `hard_tabs = false` or when the macro does not emit an enclosing block.

**Expected behavior**

```rust
#[macro_export]
macro_rules! example {
	() => {{
		let x = 5;
		Ok(x)
	}};
}
```

**Meta**

- rustfmt version: 1.4.24-stable
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment] 2020-11-23 00:19
This has been fixed in source but not backported to a 1.x release. Let me see if I can squeeze this in the upcoming v.1.4.28 release

**Comment by calebcartwright** [comment] 2020-11-29 00:14
Closing as a duplicate of #4152, fix has been backported and will be in the next release

**Closed by calebcartwright** 2020-11-29 00:14 UTC
Labels: bug, duplicate

**Comment by nitsky** [comment] 2020-11-29 13:44
Thanks! 😀
