### ISSUE TITLE
Running `cargo fmt` on workspace formats crates not part of workspace

### ISSUE THREAD

**Issue by retep998** [rust-lang/rustfmt#3489] opened 2019-04-01 16:47 UTC
`rustfmt 1.0.3-nightly (d6829d62 2019-02-14)` on x86_64-pc-windows-msvc

I have a workspace where some crates in the directory are part of the workspace, and some are vendored dependencies that are path dependencies of crates in the workspace but are not themselves part of the workspace. When I run `cargo fmt` in the root of the workspace *all* the crates are formatted including the vendored dependencies that are not part of the workspace. I'd prefer that only crates which are explicitly part of the workspace be formatted.

**Comment by topecongiro** [comment] 2019-04-01 20:09
Have you ever tried [`ignore`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#ignore) configuration option? Seems like it fixes your issue.

**Comment by retep998** [comment] 2019-04-01 20:14
It is not a fix, but rather a workaround, and it isn't stable yet.

**Comment by scampi** [comment] 2019-04-01 21:06
@retep998 Can you provide a small working example of the problem ? Thanks

**Comment by topecongiro** [comment] 2019-04-02 02:33
@retep998 Sorry, I missed your point. When ran in a workspace, `cargo fmt` should format only members of the workspace. When passed `--all` argument, `cargo fmt` should format all members of the workspace and crates that are referenced by the members.

**Comment by topecongiro** [comment] 2019-05-17 15:56
@retep998 Are your path dependencies added to `exclude` key in Cargo.toml? It turns out that all path dependencies are part of the workspace member (cc https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section). If they are not, could add your vendored dependencies to `exclude` key and try running rustfmt?

**Comment by topecongiro** [comment] 2019-06-03 14:58
Closing this as expected behavior.

**Comment by retep998** [comment] 2019-06-03 14:58
I can confirm that adding the vendored dependencies to `exclude` resolved the issue for me.

**Closed by topecongiro** 2019-06-03 14:58 UTC
Labels: bug
