### ISSUE TITLE
malformed `derive` attribute input deletes derive arguments

### ISSUE THREAD

**Issue by ratmice** [rust-lang/rustfmt#4545] opened 2020-11-23 15:11 UTC
**Describe the bug**
Adding a generic type to a derive macro deletes all derives

**To Reproduce**
```
cat <<EOF | rustfmt
#[derive(Debug, Foo<T>)]
enum Bar{}
EOF 
```

This produces the following output, removing all derive attributes:
```
#[derive()]
enum Bar {}
```
**Expected behavior**
Something less nefarious, like rustc's 
```
error: malformed `derive` attribute input
```

**Meta**
- rustfmt version: rustrustfmt 1.4.24-stable (eb894d5 2020-11-05)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: In an editor with undo hopefully :smiling_imp:

**Comment by camelid** [comment] 2020-11-24 01:15
Just noticed this as well:

```rust
#[derive(Debug, , Default)]
struct Struct(i32);
```

turns into this:

```rust
#[derive()]
struct Struct(i32);
```

which is bizarre when you're deleting one of the derives and you save partway through!

**Comment by calebcartwright** [comment] 2020-11-24 01:17
This has been fixed in source but not backported to a released version. Will try to do so for the upcoming 1.4.28 release

**Comment by calebcartwright** [comment] 2020-11-29 17:15
Closing as a duplicate of #3898, fix has been backported and will be in the next release

**Closed by calebcartwright** 2020-11-29 17:15 UTC
Labels: bug
