### ISSUE TITLE
Rustfmt should not indent multi-line comments's bodies

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#3827] opened 2019-10-03 13:02 UTC
E.g. I often have the following situation when I want to comment out a method:

Before:

![image](https://user-images.githubusercontent.com/535593/66128288-d5e3d980-e5ed-11e9-84a1-476c91f2cf68.png)

Since Sublime Text removes all trailing whitespace, I place the cursor in the empty line before the function, hold Shift, place the cursor in the empty line after the function, so that my text selection includes the whole method, then I do `Ctrl+Shift+/` to toggle-multi-line comment the text selection, which results in this:

![image](https://user-images.githubusercontent.com/535593/66128554-5c002000-e5ee-11e9-99f1-7bf73d4fe410.png)

Then I do `Ctrl+S` to save the file and invoke [RustFmt](https://packagecontrol.io/packages/RustFmt), which results in this:

![image](https://user-images.githubusercontent.com/535593/66128627-8520b080-e5ee-11e9-8fa7-2bf576c77ef3.png)

It indented my outcommented method so that it's not aligned with my non-outcommented methods anymore.
Please don't do this. It'd be ok to just indent the lines containing only `/*` and `*/` but not the comment's body. But I'd prefer if it didn't indent these at all!

Can you show some cases where you think rustfmt **should** indent multi-line comments' bodies?
Then we could distinguish when it should and should not indent. I think at least when the comment starts and ends at zero indentation (column 0) it should leave it as it is.
E.g. cases like this would still be indented:
```rust
    fn foo(&self) {}

/* doesn't end at column 0 */

    fn bar(&self) {}
```

I'm using `rustfmt 1.4.8-nightly (afb1ee1c 2019-09-08)`.

**Comment by ytmimi** [comment] 2022-07-21 01:54
Closing as this is a duplicate of #1264

**Closed by ytmimi** 2022-07-21 01:54 UTC
Labels: poor-formatting, a-comments
