### ISSUE TITLE
`let ... = ... else {}` badly and infinitely indented with repeated formatting

### ISSUE THREAD

**Issue by windowsboy111** [rust-lang/rustfmt#5866] opened 2023-07-29 15:42 UTC
This issue is similar to #4609.

To reproduce:
```rs
macro_rules! a {
    () => {
        let x = y else {
            any
        };
    };
}

fn b() {
    let Some(x) = Some("hai") else {panic!("oops");};
}

d!(
    macro x() {
        let x = y else {
            any
        };
    }
);
```
Run `$ rustfmt test.rs`

And now you get this:
```rs
macro_rules! a {
    () => {
        let x = y else {
                    any
                };
    };
}

fn b() {
    let Some(x) = Some("hai") else {panic!("oops");};
}

d!(
    macro x() {
        let x = y else {
                    any
                };
    }
);
```
Notice the bad indentation in `macro_rules! a` and `d!(...)` and the unchanged bad indentation in `b()`.

for `d!()`, this only happens with:
- macro invocation with `!()`
- the `macro` keyword (weird!)
- and it should look like a function except you replace `fn` with `macro`
- and of course the `let ... = ... else {};` statement; yes you need `;`

And for the case in `b()` it just happens anywhere; seems like there is no support for formatting `let ... = ... else {};` statements in `rustfmt`?

## Some of the affected versions
- rustfmt 1.5.1-stable (d5a82bb 2023-02-07)
- rustfmt 1.5.2-stable (8ede3aa 2023-07-12)

**Comment by calebcartwright** [comment] 2023-07-31 03:32
Thanks but I'm going to close because this is a duplicate of #5503 and you need to have rustfmt v1.6.0 or higher to have a version that has formatting support for let-else statements. That version of rustfmt should be on stable in Rust 1.72, and has been out on the nightly toolchains for a while.

Some docs/links below for reference:
https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#160-2023-07-02
https://github.com/rust-lang/rustfmt/issues/4914
https://blog.rust-lang.org/2023/07/01/rustfmt-supports-let-else-statements.html

**Closed by calebcartwright** 2023-07-31 03:32 UTC
