### ISSUE TITLE
Newlines between commented code in call chains get removed

### ISSUE THREAD

**Issue by AeonSolstice** [rust-lang/rustfmt#6380] opened 2024-10-30 23:25 UTC
```rust
fn main() {
  let el = EventLoop::builder()
    .with_msg_hook(|msg| {
      let msg = msg as *const MSG;

      if unsafe { (*msg).message == WM_NCCALCSIZE && (*msg).wParam.0 == 1 } {
        return true;
      }

      false
    })
    .build()
    .unwrap();
}
```
Using vscode I comment out the following to test something quickly, and save
```rust
fn main() {
  let el = EventLoop::builder()
    // .with_msg_hook(|msg| {
    //   let msg = msg as *const MSG;

    //   if unsafe { (*msg).message == WM_NCCALCSIZE && (*msg).wParam.0 == 1 } {
    //     return true;
    //   }

    //   false
    // })
    .build()
    .unwrap();
}
```
Rustfmt produces the following output
```rust
fn main() {
  let el = EventLoop::builder()
    // .with_msg_hook(|msg| {
    //   let msg = msg as *const MSG;
    //   if unsafe { (*msg).message == WM_NCCALCSIZE && (*msg).wParam.0 == 1 } {
    //     return true;
    //   }
    //   false
    // })
    .build()
    .unwrap();
}
```
I finish testing.
The commented code is still highlighted and I need to <kbd>Ctrl-Z</kbd> 2 times and save again to get my original, clear, code.

I would expect 2+(incl.) newlines to get reduced to 1, but single ones should be kept.
Commented section does not necessarily need to be code.

```shell
$rustfmt --version
rustfmt 1.7.1-stable (f6e511e 2024-10-15)
```

**Comment by ding-young** [comment] 2024-11-06 12:58
This bug is reproducible, and it seems to be caused in the following part. 
https://github.com/rust-lang/rustfmt/blob/777e25a8c91af9923ad356eb4448ac2ed15167a9/src/chains.rs#L450 
rustfmt intentionally trims the try operator and then removes the resulting blank line (the try operator is checked elsewhere and reattached later). However, it appears that it mistakenly removes the blank line even when there isn’t a try operator. —just my guess, though.
https://github.com/rust-lang/rustfmt/blob/777e25a8c91af9923ad356eb4448ac2ed15167a9/src/chains.rs#L1015-L1038

**Comment by ytmimi** [comment] 2024-11-20 05:15
Just now realizing that this is a duplicate of #4012

**Closed by ytmimi** 2024-11-20 05:15 UTC
Labels: a-comments, p-low
