### ISSUE TITLE
How to keep the comments at the same line when reformatting the code with Rust code formatter?

### ISSUE THREAD

**Issue by q2333gh** [rust-lang/rustfmt#5856] opened 2023-07-22 09:27 UTC
I use rust-analyzer in VSCode.  
with all default settings.   
Check out the gif: when press reformat-hot-key:  
my comments move away from the same line of code,  
which is really not good-looking.  
if the comments is at the same line of code ,  
reading the codes will be much more fluent.  
Making the comments become optional read. 

The code  I wish when reformat.
```rust
fn main() {
    let guess: u32 = match guess.trim().parse() {// :u32 : type casting, work with .parse()
        Ok(num) => num,
        Err(_) => { //_  means any error
            println!("Please input numbers!");
            continue;
        }
    };
}
```

The code I don`t like when reformat: 
```rust
fn main() {
    let guess: u32 = match guess.trim().parse() {
        // :u32 : type casting, work with .parse()
        Ok(num) => num,
        Err(_) => {
            //_  means any error
            println!("Please input numbers!");
            continue;
        }
    };
}

```

[![enter image description here](https://i.stack.imgur.com/6m8dE.gif)](https://i.stack.imgur.com/6m8dE.gif)

I want to get some help with it, 
and I assume maybe some people also need this formatting behaviour.

**Comment by calebcartwright** [comment] 2023-07-22 23:57
Thanks but closing as a duplicate of #3255

**Closed by calebcartwright** 2023-07-22 23:57 UTC

**Comment by kuchaguangjie** [comment] 2025-02-16 08:44
I think it's better to keep the comment at the same line, as most language would.
It's more readable.
