### ISSUE TITLE
Rustfmt moves comment from one import to another

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#5485] opened 2022-08-06 17:24 UTC
Here is a case where rustfmt, as part of reordering imports, literally moves a comment from one import to another, entirely destroying its meaning:
```rust
mod realstd {
    struct __FastLocalKeyInner;
}
mod local {
    mod fast {
        struct Key;
    }
}

#[cfg(test)] // comment associated with realstd import
pub use realstd::thread::__FastLocalKeyInner;
#[cfg(test)]
pub use self::local::fast::Key as __FastLocalKeyInnerUnused; // comment associated with fast import

fn main() {}
```
After formatting, the imports look like
```rust
#[cfg(test)]
pub use self::local::fast::Key as __FastLocalKeyInnerUnused;
#[cfg(test)] // comment associated with realstd import
pub use realstd::thread::__FastLocalKeyInner; // comment associated with fast import
```
Not that the comment that explained the `use self::local::fast::Key as`, got moved to the other `use`!

This is with rustfmt 1.5.1-nightly (2022-08-05 affe0d3).

**Comment by ytmimi** [comment] 2022-08-06 23:09
closing as a duplicate of #3720

**Closed by ytmimi** 2022-08-06 23:09 UTC
Labels: duplicate, a-comments, a-imports
