### ISSUE TITLE
Associated types implementation with where clause are not formatted

### ISSUE THREAD

**Issue by ia0** [rust-lang/rustfmt#5751] opened 2023-04-13 13:12 UTC
```rust
trait Foo {
    type Bar;
}

impl Foo for () {
    // The following line doesn't get formatted.
    type Bar = ()    where u8: Copy;
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=448e25cc22bb316f236e5ee6aeb455de)

Removing the `where` clause restores formatting, so this looks specific to where clause in associated types.

**Comment by ytmimi** [comment] 2023-04-13 20:31
@ia0 thanks for the report. Confirming I can reproduce this with `rustfmt 1.5.2-nightly (4aacac8e 2023-04-09)`.

The issue here might be that we haven't defined how to format associated types when the where clause comes after the type.

There doesn't seem to be anything defined in [the Style Guide docs for Associated types](https://github.com/rust-lang/style-team/blob/ba17faa77e4d5a1c53046aea0901e72b6d0ec0f4/guide/items.md#associated-types). @calebcartwright is this something that needs to be brought to `t-style's` attention? Maybe the Style Guide docs should be brought closer in line with the [Rust Reference Associated Types docs](https://doc.rust-lang.org/reference/items/associated-items.html#associated-types)

It looks like we can format the `deprecated form`:

**Input**
```rust
impl Foo for () {
    // The following line doesn't get formatted.
    type Bar = ()    where u8: Copy;

    // The following is formatted.
    type Baz where u8:      Copy   =    ();
}
```

**Output**
```rust
impl Foo for () {
    // The following line doesn't get formatted.
    type Bar = ()    where u8: Copy;
    type Baz
    where
        u8: Copy,
    = ();
}
```

**Comment by ytmimi** [comment] 2023-05-01 17:00
After looking into it I think this is a duplicate of #5580

**Comment by ia0** [comment] 2023-05-01 17:03
> After looking into it I think this is a duplicate of #5580

I confirm. Feel free to close this issue as duplicate. I subscribed to the other one.

**Comment by ytmimi** [comment] 2023-05-07 20:29
Thanks for confirming this is a duplicate

**Closed by ytmimi** 2023-05-07 20:29 UTC
Labels: blocked
