### ISSUE TITLE
--message-format=json panic on broken pipe

### ISSUE THREAD

**Issue by richardscollin** [rust-lang/rustfmt#6183] opened 2024-06-04 17:11 UTC
rustc version: 1.80.0-nightly (7c52d2db6 2024-06-03)
platform: x86_64-unknown-linux-gnu

On a clean project run:
```bash
cargo +nightly fmt --message-format=json | echo ice
```

If the program which is being piped to (echo in this case) doesn't consume the input, the write will cause a panic in rustfmt.

[rustc-ice-2024-06-04T16_38_03-53230.txt](https://github.com/user-attachments/files/15567881/rustc-ice-2024-06-04T16_38_03-53230.txt)

My expected behavior is the command would fail, but it would not generate a rustc-ice-2024-06-04T16_38_03-53230.txt file or suggesting filing an issue.

**Comment by ytmimi** [comment] 2024-06-04 17:29
Thanks for the report. This is likely a duplicate of #6089 and other reported piping issues like #2926

**Closed by ytmimi** 2024-06-04 17:29 UTC
