### ISSUE TITLE
Respect the line break

### ISSUE THREAD

**Issue by lnshi** [rust-lang/rustfmt#5106] opened 2021-11-23 09:55 UTC
I mean the case like:
<img width="1041" alt="Screenshot 2021-11-23 at 17 44 49" src="https://user-images.githubusercontent.com/24580114/143002159-16c30f3f-59ce-4966-923a-e487112d806b.png">
or:
<img width="987" alt="Screenshot 2021-11-23 at 17 45 53" src="https://user-images.githubusercontent.com/24580114/143002203-ea30d0e3-5f97-4109-81d6-159be7486a4f.png">

In either of these cases there are special intentions the developer groups the values or the function calls: **for readability or group by semantics**, current `rustfmt` just totally mess it up with simply calculating the line length....

Personally, I feel the direction that controlling the line length like setting all of these [use_small_heuristics](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_small_heuristics) rules are pretty useless, maybe just do what `gofmt` is doing: respecting the line break, only deal with the blank line and indentions.

**Comment by calebcartwright** [comment] 2021-11-23 23:42
Thanks for sharing your perspective, but I'm going to close this as a duplicate of #5106 (amongst various other issues) which raised the same topic within the last ~week.

**Closed by calebcartwright** 2021-11-23 23:42 UTC
Labels: duplicate
