### ISSUE TITLE
chain not indenting on long lines

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rustfmt#4912] opened 2021-07-20 12:13 UTC
(please ignore that the code doesn't compile)

```
#[test]
fn test_serialize_invalid() {
    assert!(u8::parse::<u8>(
        "  0x000000000000000000000000000000000000000000000000000000000000000"
    )
    .is_data());
}
```
rustfmt does a lovely job formatting it to:
```
#[test]
fn test_serialize_invalid() {
    assert!(
        u8::parse::<u8>("  0x000000000000000000000000000000000000000000000000000000000000000")
            .is_data()
    );
}
```

but if the string is one char longer then it's formatted like the first example above with no indent from the assert for the `.is_data()`.

Is this expected / desired (apologies if it is)? Personally I would have expected it to indent the chain as it does for the less long version.

(Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=48b4bd90bc442e331cb82b53d4b9f0e4 )

**Comment by calebcartwright** [comment] 2021-07-21 03:01
Thanks for the report but closing as a duplicate of #3863

**Closed by calebcartwright** 2021-07-21 03:01 UTC
Labels: duplicate
