### ISSUE TITLE
rustfmt gives up on method chain with closure with very long return type

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/rustfmt#6076] opened 2024-02-16 02:07 UTC
rustfmt refuses to format the following statement (reduced from a real-world example):

```rust
fn test() {
    let output: Vec<_> = input
            .into_iter()
            .map(|serialized| -> Result<long_crate::LongCrateTypeName, long_crate::DeserializationFailure> {
                Ok(serialized)
            })
            .map_err(|_| {
                // A comment
                Failure
            })?;
}
```

The long type names seem to be at fault; shortening either of them results in a successful format. I realize there's not a *great* way to format that type, but giving up on the entire statement was surprising.

[Tested on play.rust-lang.org](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c82fe7b238f8ce84bebfdf9c56484a27) using the 2024-02-04 07dca48 build of rustfmt.

**Comment by ytmimi** [comment] 2024-02-16 16:01
Thanks for the report. This is another duplicate of #3863

**Closed by ytmimi** 2024-02-16 16:01 UTC

**Comment by jrose-signal** [comment] 2024-02-16 18:17
Ah, not specific to types. Thanks!
