### ISSUE TITLE
Last letter in derive statement gets removed by rustfmt nightly

### ISSUE THREAD

**Issue by cdbrkfxrpt** [rust-lang/rustfmt#4610] opened 2020-12-24 11:51 UTC
**Describe the bug**

On the nightly toolchain, rustfmt removes the last letter from any derive statement, i.e.
```rust
#[derive(Debug)]
```
becomes
```rust
#[derive(Debu)]
```

In my rustfmt.toml, I have the following line:
```toml
# "Block" | "Visual"
indent_style = "Visual"
```
If I comment this line (or change it to `"Block"`, which is the default) the issue goes away (but formatting happens completely differently, of course, so this is not a viable fix).

**To Reproduce**

Heads up: I'm only able to reproduce this on my laptop. It does not reproduce on my workstation. However I have no clue what the difference between the systems may be; they're both Debian sid on latest updates, both have Rust installed and updated via rustup, both have the exact same setup in terms of terminal emulator, shell, environment,etc.

To reproduce - if you can - simple throw the following into a file (let's call it test.rs):
```rust
#[derive(Debug)]
struct Foo {
  some:   usize,
  member: String,
}
```
Put the file in a directory together with a rustfmt.toml file containing:
```toml
# "Block" | "Visual"
indent_style = "Visual"
```
Finally, run `rustfmt test.rs`.

**Expected behavior**

I expect rustfmt not to remove letters from my code in this fashion.

**Meta**

- rustfmt version: rustfmt 1.4.29-nightly (70ce182 2020-12-04)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: normally via vim but this issue shows up regardless (i.e. I can reproduce using rustfmt or cargo fmt)

**Comment by calebcartwright** [comment] 2020-12-24 16:08
Closing as duplicate of #4584, already fixed in the latest 1.4.30 version which I believe will be in the next published nightly (otherwise the following one)

**Closed by calebcartwright** 2020-12-24 16:08 UTC
Labels: bug, duplicate

**Comment by cdbrkfxrpt** [comment] 2020-12-24 16:58
i'm sorry, i actually searched "derive" in the issues but #4584 didn't pop up for some reason.

thanks for the info though.

**Comment by calebcartwright** [comment] 2020-12-24 18:04
No worries!
