### ISSUE TITLE
Drifting/unstable formatting when using a macro in an attribute inside a macro definition

### ISSUE THREAD

**Issue by elomatreb** [rust-lang/rustfmt#5707] opened 2023-03-05 19:39 UTC
The following snippet has weird/partially unstable formatting:

```rs
macro_rules! foo {
    () => {
        #[doc =
            concat!("hello world")
        ]
        pub struct Foo;
    };
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5a1f17486169062edcf3f65d6ac9eaea))

Formatting it once makes the contents of the `doc` attribute and its closing bracket drift right:

```rs
macro_rules! foo {
    () => {
        #[doc =
                    concat!("hello world")
                ]
        pub struct Foo;
    };
}
```

This happens again and again with every format until it hits the line length limit (I think):

```rs
macro_rules! foo {
    () => {
        #[doc =
                                                                        concat!("hello world")
                                                                    ]
        pub struct Foo;
    };
}
```

This does not happen outside of a `macro_rules` body or if the `doc` attribute does not contain another macro.

**Comment by ytmimi** [comment] 2023-03-05 19:58
Thanks for reaching out. This is likely a duplicate of #5489, #5062

**Comment by elomatreb** [comment] 2023-03-05 20:05
Right, that looks likely, didn't find those while searching.

Should I close this issue?

**Comment by ytmimi** [comment] 2023-03-06 02:44
Yeah, let's close this.

**Closed by ytmimi** 2023-03-06 02:44 UTC
Labels: bug, duplicate, a-macros
