### ISSUE TITLE
rustfmt does not refuse to format function parameters with doc comments and formats them wrong

### ISSUE THREAD

**Issue by Maxpxt** [rust-lang/rustfmt#5014] opened 2021-10-01 18:56 UTC
#### Description

Doc comments are not allowed in function parameters, so `rustfmt` should either refuse to format code that has them or format them as if they were normal comments. Instead, `rustfmt` incorrectly formats the code by merging the parameter into the doc comment or sometimes removing the doc comment.

#### To Reproduce
For example, `rustfmt` formats

```rust
fn foo(
    /// This is `bar`.
    bar: bool,
) {
}
```

into

```rust
fn foo(/// This is `bar`. bar: bool
) {
}
```

and formats

```rust
fn foo(
    /// This is `bar`.
    bar: bool,
    /// This has a long name.
    veeeeeeeeeeery_long_paramater_name_to_force_multiline_parameter_list: bool,
) {
}
```

into

```rust
fn foo(
    /// This is `bar`. bar: bool,
    veeeeeeeeeeery_long_paramater_name_to_force_multiline_parameter_list: bool,
) {
}
```

#### Meta

* rustfmt version: rustfmt 1.4.37-nightly (aa7aca3b 2021-09-30)
* From where did you install rustfmt?: `rustup`
* How do you run rustfmt?: via rust-analyzer in vscode, but this was tested with `rustfmt` too

**Comment by calebcartwright** [comment] 2021-10-05 01:52
Closing as a duplicate of #4936

In general, while in many cases rustfmt can still format around invalid code, one should not expect rustfmt to be able to handle all cases of invalid syntax, as that way lies madness.

We did opt to go ahead and support this particular use case, but that was primarily because there seemed to be a plan for making this potential valid with macros.

**Closed by calebcartwright** 2021-10-05 01:52 UTC
Labels: duplicate
