### ISSUE TITLE
Nightly `wrap_comments` can break code blocks

### ISSUE THREAD

**Issue by VorpalBlade** [rust-lang/rustfmt#6255] opened 2024-07-28 07:32 UTC
Given:

```rust
    /// To add a key compatible with the above service and user run a command like the following:
    /// ```console
    /// $ secret-tool store --label="Descriptive name" service chezmoi-modify-manager username konversation-login
    /// ```
```

`wrap_comments` reformats this to:

```rust
    /// To add a key compatible with the above service and user run a command
    /// like the following: ```console
    /// $ secret-tool store --label="Descriptive name" service chezmoi-modify-manager username konversation-login
    /// ```
```

It should instead be reformatted to:

```rust
    /// To add a key compatible with the above service and user run a command
    /// like the following:
    /// ```console
    /// $ secret-tool store --label="Descriptive name" service chezmoi-modify-manager username konversation-login
    /// ```
```

This relates to #3347

**Comment by ytmimi** [comment] 2024-08-03 10:23
Closing this as a duplicate of #5244

**Closed by ytmimi** 2024-08-03 10:23 UTC
Labels: duplicate, a-comments, only-with-option, a-markdown
