### ISSUE TITLE
`normalize_comments = true` de-normalizes some comments

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rustfmt#4909] opened 2021-07-19 15:29 UTC
According to https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#normalize_comments should convert `/* yada */` to `// yada`, but the inverse happens.

```sh
# rustfmt +nightly --version
rustfmt 1.4.37-nightly (d2b04f0 2021-07-07)
```

```toml
normalize_comments = true
normalize_doc_attributes = true
```

results in a delta of 

```patch
@@ -150,11 +151,11 @@ pub enum Stage {
        AvailabilityRecovery = 6,
        BitfieldDistribution = 7,
        ApprovalChecking = 8,
-       // Expand as needed, numbers should be ascending according to the stage
-       // through the inclusion pipeline, or according to the descriptions
-       // in [the path of a para chain block]
-       // (https://polkadot.network/the-path-of-a-parachain-block/)
-       // see [issue](https://github.com/paritytech/polkadot/issues/2389)
+       /* Expand as needed, numbers should be ascending according to the stage
+        * through the inclusion pipeline, or according to the descriptions
+        * in [the path of a para chain block]
+        * (https://polkadot.network/the-path-of-a-parachain-block/)
+        * see [issue](https://github.com/paritytech/polkadot/issues/2389) */
 }
 
 /// A wrapper type for a span.
```

**Comment by calebcartwright** [comment] 2021-07-21 02:59
Thanks for the report. This is technically a duplicate of a similar report added in a comment in #3350, but better to have a dedicated issue for it any way

**Comment by jplatte** [comment] 2021-09-27 10:46
I just hit this when commenting out a field in a struct definition, but I haven't even set `normalize_comments = true`.

`rustfmt --version`: 1.4.37-nightly (5ecc8ad 2021-09-19)

**Closed** 2021-11-20 01:18 UTC
Labels: a-comments, only-with-option, help wanted
