### ISSUE TITLE
Rustfmt Macro with `$( tt )*` can introduce breaking comma

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rustfmt#5654] opened 2023-01-08 01:56 UTC
Without running rustfmt, this macro compiles (albeit it does look very strange).
After running rustfmt, it introduces a comma between functions which leads to it no longer compiling.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0d69aa8f44c299d2726f3e39e6c535ff

Inlined:
```
macro_rules! document {
  ($t: ty, $( $code_block: tt )*)=> {
    const DOC: &'static str = stringify!($( $code_block )*);

    $( $code_block )*
  }
}
struct T;

document!(T, fn example() {} fn other() {});
// ^ Comma is introduced here: `fn example() {}, fn other() {}`

fn main() {}
```

**Comment by ytmimi** [comment] 2023-01-08 02:17
Thanks for reaching out. I believe this is a duplicate of #4375 and #4631

**Closed** 2023-01-08 02:17 UTC
Labels: duplicate, a-macros
