### ISSUE TITLE
rustfmt refuses to format a file

### ISSUE THREAD

**Issue by Speak2Erase** [rust-lang/rustfmt#6223] opened 2024-06-30 16:17 UTC
rustfmt refuses to format https://github.com/Astrabit-ST/Luminol/blob/ceea9bf0d99a12c1d1d3479c1ec80320d54fcc32/crates/modals/src/event_graphic_picker.rs. Whenever I make a change that leaves behind a trailing whitespace, it doesn't get formatted away.
Instead, I see this in my terminal: (running `cargo fmt`)
![image](https://github.com/rust-lang/rustfmt/assets/54482069/5d4291fc-06a0-4a85-b65d-593992350f7c)
It drives me crazy whenever this happens, because it'll happen randomly to one of the files in my project, and then suddenly fix itself a few weeks later
I tried `rustfmt 1.7.1-nightly (e9e6e2e 2024-06-28` and this still seems to be an issue.

**Comment by ytmimi** [comment] 2024-07-01 02:36
i think this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863 that results in a whitespace error message. When rustfmt fails to format any AST node it leaves the span of that node unformatted. If the span contains trailing whitespace then rustfmt will leave that unchanged as well, and later issue the error message to alert the user that there's whitespace it can't remove.

**Closed by ytmimi** 2024-07-01 02:36 UTC
