### ISSUE TITLE
Same name files was overwrite

### ISSUE THREAD

**Issue by hemaolong** [rust-lang/rustfmt#3421] opened 2019-02-27 05:04 UTC
The files with same name in different path may be overwrite .

This is the mini project to reproduce the bug.
In thiscase, src/system/pay.rs will be messed.
/////////////// main.rs
// Be careful the sequence of mod definition in the main.rs
mod system {
    pub mod pay;
}
mod hf;

pub fn main() {}
//////////////end if main.rs

//////////////////// project layout
E:.
│   hf.rs
│   main.rs
│
├───hf
│   └───system
│                     pay.rs
│
└───system
                   pay.rs

**Comment by hemaolong** [comment] 2019-02-27 05:10
btw, rustfmt version:    rustfmt 1.0.3-nightly (d6829d62 2019-02-14)

**Comment by topecongiro** [comment] 2019-02-28 15:18
@hemaolong Thanks you for reporting this issue. Unfortunately I could not reproduce this locally with the following layout. I think that the actual content of the files could matter. Is it possible for you to publish the exact minimal project so that I could investigate this issue further?

```tree
.
├── hf
│   └── system.rs
├── hf.rs
├── main.rs
├── pay.rs
└── system
    └── pay.rs
```

**Comment by hemaolong** [comment] 2019-03-03 03:32
@topecongiro
My mistake, the first pay.rs should be under /src/hf/system/pay.rs.
But I failed to attach the minimal project by both IE and Chrome. It seems uploaded ok but has no effect.
------------
.
├── hf
│   └── system.rs
        └── pay.rs
├── hf.rs
├── main.rs
└── system
    └── pay.rs

Sorry to response too late.
I tried again, could you see the attachment?

**Comment by hemaolong** [comment] 2019-03-03 03:37
@topecongiro 
[fmt_bug.zip](https://github.com/rust-lang/rustfmt/files/2922725/fmt_bug.zip)
My mistake, the first pay.rs should be under /src/hf/system/pay.rs.

Sorry to response too late.
I attached the minimal project but it seems has no effect.
I do it again  after update my Chrome ^-^

**Comment by topecongiro** [comment] 2019-03-03 13:13
@hemaolong Thanks! I could reproduce it with your example.

cc #3427.

**Comment by rchaser53** [comment] 2019-03-17 06:57
This issue is resolved by https://github.com/rust-lang/rustfmt/pull/3448

**Comment by topecongiro** [comment] 2019-03-17 12:02
@rchaser53 Thanks!

**Closed by topecongiro** 2019-03-17 12:02 UTC
Labels: bug, p-high
