### ISSUE TITLE
Rustfmt incorrectly aligns comments

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rustfmt#3431] opened 2019-03-04 19:03 UTC
I have a module with hundres of constants that are defined by external documentation. Some of them are (currently) unused and commented out:

```rust
    pub const SQ_CRETAB: u16 = 0x000e; // CREATE TABLE
    pub const SQ_DRPTAB: u16 = 0x000f; // DROP TABLE
    pub const SQ_CREIDX: u16 = 0x0010; // CREATE INDEX
    //const SQ_DRPIDX: u16 = 0x0011;	// DROP INDEX
    //const SQ_GRANT: u16 = 0x0012;	// GRANT
    //const SQ_REVOKE: u16 = 0x0013;	// REVOKE
```
Rustfmt incorrectly assumes that the `//const SQ_DRPIDX ...` should be aligned with `... // CREATE INDEX` and reformats to something like the following

```rust
    pub const SQ_CRETAB: u16 = 0x000e; // CREATE TABLE
    pub const SQ_DRPTAB: u16 = 0x000f; // DROP TABLE
    pub const SQ_CREIDX: u16 = 0x0010; // CREATE INDEX
                                       //const SQ_DRPIDX: u16 = 0x0011;	// DROP INDEX
                                       //const SQ_GRANT: u16 = 0x0012;	// GRANT
                                       //const SQ_REVOKE: u16 = 0x0013;	// REVOKE
```

Which is actually worse.

**Comment by scampi** [comment] 2019-03-12 22:49
As a temporary workaround, you may put the unused constants in a separate block:

```rust
    pub const SQ_CRETAB: u16 = 0x000e; // CREATE TABLE
    pub const SQ_DRPTAB: u16 = 0x000f; // DROP TABLE
    pub const SQ_CREIDX: u16 = 0x0010; // CREATE INDEX

    //const SQ_DRPIDX: u16 = 0x0011;	// DROP INDEX
    //const SQ_GRANT: u16 = 0x0012;	// GRANT
    //const SQ_REVOKE: u16 = 0x0013;	// REVOKE
```

**Comment by sphynx** [comment] 2019-05-02 21:47
Duplicate of #2996 ?

**Comment by scampi** [comment] 2019-05-08 21:50
thanks for spotting this @sphynx

**Closed by scampi** 2019-05-08 21:50 UTC
Labels: a-comments, duplicate, poor-formatting
