### ISSUE TITLE
Support formatting for `decl_macro`s.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rustfmt#5111] opened 2021-11-27 07:37 UTC
This code
```rust
#![feature(decl_macro)]
pub macro xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx($x:expr) {
    $x
}

pub fn yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy(x:()) {
    x
}
```

After rustfmt invocation, the `fn` got wrapped by rustfmt, but the `macro` doesn't.

**Comment by calebcartwright** [comment] 2021-11-27 17:37
Thanks but going to close as a duplicate of #1539

**Closed by calebcartwright** 2021-11-27 17:37 UTC
Labels: duplicate

**Comment by crlf0710** [comment] 2021-11-29 05:05
oops, totally forgot i commented before under that issue...
