### ISSUE TITLE
misformatting of commented out struct fields

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#4988] opened 2021-09-12 06:47 UTC
```rust
struct A {
    // a: u8,
// b: u16
// c: u32
}
````

When I try to make the comment indentation consistent, rustfmt always changes it to what you see here :sweat_smile:

**Comment by calebcartwright** [comment] 2021-09-12 18:33
Thanks for sharing but going to close as a duplicate of #4854

**Closed by calebcartwright** 2021-09-12 18:33 UTC
Labels: duplicate
