### ISSUE TITLE
Rustfmt fails to format code with a long string inside struct

### ISSUE THREAD

**Issue by sterliakov** [rust-lang/rustfmt#5986] opened 2023-12-22 01:46 UTC
This terrible input (reduced from some larger struct with 2 levels of nesting) is left as-is.

```rust
fn test_fetch_existing_receipt() {
    let expected =
    Event {
                            topics: 1,
                            data: Bytes::copy_from_slice(&b"vtho-usd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x84\x17\x19\x1a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0e\x7f\x8eJ"[..])
                        };
}
```

Applies to both current nightly and stable: 
```shell
$ cargo fmt -- -V
rustfmt 1.6.0-stable (a28077b 2023-12-04)
$ cargo +nightly fmt -- -V
rustfmt 1.7.0-nightly (3f28fe1 2023-12-18)
```

I wanted to just split a struct copied from terminal output, but ended up doing it manually:(

**Comment by ytmimi** [comment] 2023-12-22 20:44
Thanks for reaching out.

Originally I thought this was a duplicate of #4992 #4800. Both of those issues are fixed when using `version=Two`.
Unfortunately the call to `Bytes::copy_from_slice` is what makes this a different issues. Because the string literal is way longer than the default of `max_width` rustfmt fails to format `Bytes::copy_from_slice`, which prevents rustfmt from formatting the `Event` struct.

I think your best option here is to refactor your code:
### Option 3:

**input**
```rust
fn test_fetch_existing_receipt() {
    let data = Bytes::copy_from_slice(&b"vtho-usd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x84\x17\x19\x1a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0e\x7f\x8eJ"[..]);
    let expected = 
    Event {
                            topics: 1,
                            data
                        };
}
```

**Output**
```rust
fn test_fetch_existing_receipt() {
    let data = Bytes::copy_from_slice(&b"vtho-usd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x84\x17\x19\x1a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0e\x7f\x8eJ"[..]);
    let expected = Event { topics: 1, data };
}
```

**Closed by ytmimi** 2023-12-22 20:44 UTC
