### ISSUE TITLE
When function call identifier + indentation takes up 98 columns, empty parameters get broken between lines

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [rust-lang/rustfmt#5567] opened 2022-10-20 19:59 UTC
Minor bug.

Seems that _fmt_ likes to have 99 column length but it is not smart about to enough. 

```rust
fn main() {
    a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789();
}
```

changes to

```rust
fn main() {
    a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789(
    );
}
```
---
```rust
println!("{}",    
    "    a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789".len());
```
```console
98
```
<details>
<summary>You can try</summary>

```rust
fn main() {
    a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789();
}

mod a123456789 {
    pub mod b123456789 {
        pub mod c123456789 {
            pub mod d123456789 {
                pub mod e123456789 {
                    pub mod f123456789 {
                        pub mod g123456789 {
                            pub fn h123456789() {}
                        }
                    }
                }
            }
        }
    }
}
```
</details>

**Comment by ytmimi** [comment] 2022-10-20 21:20
Thanks for reaching out.

Made some minor tweaks to the issue description to better reflect that `a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789()` is parsed as a `ast::ExprKind::Call` (function call) instead of a `ast::ExprKind::MethodCall` (method call) from the AST perspective.

The len of  `" 
   a123456789::b123456789::c123456789::d123456789::e123456789::f123456789::g123456789::h123456789();"` above is 101 so rustfmt can't format the entire call on a single line with the default with of `100`. 

Running rustfmt with `max_width=101` would be one way to alleviate the issue.

This is likely a duplicate of, or related to #5356

**Comment by ytmimi** [comment] 2022-10-20 21:22
I believe the issue can be tracked down to somewhere in [`wrap_items`](https://github.com/rust-lang/rustfmt/blob/ef91154250977b3b5d05448dafbca524a1168b47/src/overflow.rs#L633)

**Comment by bravequickcleverfibreyarn** [comment] 2022-10-21 19:06
Seems to be duplicated.

```rust
    println!("{}",
    "                return Err(SomeError::OutOfMemory(OutOfMemory::new(mem::size_of::<SomeType,>())));".len());
```
```console
98
```

Linked one is more complex, nonetheless it seems it covers this problem also.

**Comment by ytmimi** [comment] 2022-11-05 18:04
Thanks for confirming that this is a duplicate. I'm going to close this accordingly, but I think this snippet will serve as a good test case to ensure we've solved this one.

**Closed by ytmimi** 2022-11-05 18:04 UTC
Labels: poor-formatting, p-low
