### ISSUE TITLE
Useless whitespace between two Tuple struct without named fields

### ISSUE THREAD

**Issue by erwanvivien** [rust-lang/rustfmt#5718] opened 2023-03-20 18:28 UTC
Minimal reproduce:

```rust
struct A(u8);
struct B(A);

fn main() {
    let foo = B(A(0));

    dbg!(foo.0 .0);
}
```

Doesn't format to
```rust
dbg!(foo.0.0);
```

**Comment by ytmimi** [comment] 2023-03-21 15:44
Thanks for reaching out. This is a duplicate of #5532

This is fixed when setting `version=Two`. See https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276 for more details.

**Closed by ytmimi** 2023-03-21 15:44 UTC
