### ISSUE TITLE
Doc comment whitespace is incrementally removed

### ISSUE THREAD

**Issue by johnbchron** [rust-lang/rustfmt#6370] opened 2024-10-21 13:41 UTC
When module doc comments have more than 1 extra line of trailing whitespace, it isn't removed fully in 1 run; it takes 2 runs.

```bash
echo '//! Foo\n//!\n//!' | rustfmt           # yields "//! Foo\n//!"
echo '//! Foo\n//!\n//!' | rustfmt | rustfmt # yields "//! Foo"
```

```
$ rustfmt --version
rustfmt 1.7.1-nightly (9c01301c 2024-09-05)
```

Please note that I have taken no steps to determine the extent of this issue, or related affected areas. I'm also not certain that this is not the intended behavior - I'm just guessing.

**Comment by ytmimi** [comment] 2024-10-21 15:25
Thanks for the report. This is a duplicate of https://github.com/rust-lang/rustfmt/issues/6168

**Closed by ytmimi** 2024-10-21 15:25 UTC
