### ISSUE TITLE
Generic associated impl trait type with bounds on self formatted to broken code

### ISSUE THREAD

**Issue by tim3z** [rust-lang/rustfmt#4911] opened 2021-07-20 07:52 UTC
### Describe the bug

When specifying an impl trait type alias for a generic associated type with a lifetime bound on `Self`, rustfmt will remove the bound, causing a compiler error, i.e.:

```rust
impl SomeTrait for SomeType {
    type SomeGAT<'a> where Self: 'a = impl SomeOtherTrait;
}
```
will be changed to
```rust
impl SomeTrait for SomeType {
    type SomeGAT<'a> = impl SomeOtherTrait;
}
```

### To Reproduce
The following code compiles, but when running rustfmt on it it will remove the `Self` bound `where Self" 'a` in the implementation  for Foo leading to a compiler error:

```rust
#![allow(incomplete_features)]
#![feature(generic_associated_types)]
#![feature(min_type_alias_impl_trait)]

struct Foo<'b>(&'b ());

trait Iterable {
    type Iter<'a>
    where
        Self: 'a;
    fn iter(&self) -> Self::Iter<'_>;
}

impl<'b> Iterable for Foo<'b> {
    type Iter<'a> where Self: 'a = impl Iterator + 'a;

    fn iter(&self) -> Self::Iter<'_> {
        std::iter::once(self.0)
    }
}
```

### Expected behavior
The above code compiles and should not be formatted so it doesn't compile.

### Meta
- rustfmt 1.4.37-nightly (014026d 2021-07-19)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: rustfmt, sublime RustFmt package

**Comment by calebcartwright** [comment] 2021-07-21 03:00
Thanks for the report but I'm going to close this as a duplicate of various prior issues. It's been fixed in source but not pulled into a nightly release yet.

**Comment by tim3z** [comment] 2021-07-21 06:55
Thanks for the response. I looked into other related closed issues (#4257 #4315 #4322) but they are from July 2020 and the examples from these issues are all formatted correctly with the current rustfmt version. So while this seems very similar, I don't think, that this is a duplicate. The combination with the impl trait type alias seems to cause another problem.

**Comment by calebcartwright** [comment] 2021-07-22 03:36
Ah I see now. The way the snippets were structured in the issue description was a bit of a misdirection. Would be helpful to update extend that initial snippet to a minimal repro itself (within the impl) since it's not reproducible as is.

**Comment by tim3z** [comment] 2021-07-22 07:51
Updated initial example

**Closed** 2021-08-07 03:03 UTC
Labels: bug
