### ISSUE TITLE
format_code_in_doc_comments=true converts long // comments to /* 

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rustfmt#5674] opened 2023-01-26 07:50 UTC
```
struct Scope {
    free: u32, // abracadabra long long very long very very long comment comment comment hello world
}
```

Using master revision, 1d8491b120223272b13451fc81265aa64f7f4d5b (Jan 24 2023).

```
cat a.rs | cargo run --bin rustfmt -- --config format_code_in_doc_comments=true
```

Converts `//` comments to `/*` comments.

```
struct Scope {
    free: u32, /* abracadabra long long very long very very long comment comment comment hello world */
}
```

However, short comments are preserved as `//` comments.

**Comment by ytmimi** [comment] 2023-01-26 16:42
Thanks, but this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5533, and we've got PR https://github.com/rust-lang/rustfmt/pull/5536 ready to merge soon in order to fix it.

**Closed by ytmimi** 2023-01-26 16:42 UTC
Labels: duplicate
