### ISSUE TITLE
Misalignment with `or` pattern arguments.

### ISSUE THREAD

**Issue by fbernier** [rust-lang/rustfmt#4885] opened 2021-06-29 21:34 UTC
The following code:

```rust
fn is_meta_character(c: char) -> bool {
    matches!(
        c,
        '\\' | '.' | '+' | '(' | ')' | '|' | '[' | ']' | '{' | '}' | '^' |
        '$'  | '#' | '&' | '-' | '~' | '*' | '?'
    )
}
```

gets formatted into
```rust
fn is_meta_character(c: char) -> bool {
    matches!(
        c,
        '\\' | '.'
            | '+'
            | '('
            | ')'
            | '|'
            | '['
            | ']'
            | '{'
            | '}'
            | '^'
            | '$'
            | '#'
            | '&'
            | '-'
            | '~'
            | '*'
            | '?'
    )
}
```

I see two issues with this. First, horizontal bars are misaligned, and second it's a big waste of vertical space. I did not have time to gather more info as of now but will update this issue if I get back to it.

Thanks!

**Comment by calebcartwright** [comment] 2021-07-06 02:23
Thank you for reaching out, but I'm going to close as a duplicate of #4462

Few things to be aware of in this context:

* rustfmt has fairly limited support for formatting macros (refs #8)
* When rustfmt encounters macro calls with certain delimiters it will check to see if the inputs can be parsed as valid rust code, and if so then the code is formatted according to the corresponding prescription from the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs/tree/master/guide)
* `matches!` calls are currently treated like any other macro call, and since the second arg gets parsed as a binop expression it is formatted accordingly
* In rare, well known cases, we can add some special case handling for certain macro calls, and ultimately plan to do the same for `matches` one day too

**Closed by calebcartwright** 2021-07-06 02:23 UTC
