### ISSUE TITLE
rustfmt doesn't format this code

### ISSUE THREAD

**Issue by TeXitoi** [rust-lang/rustfmt#4072] opened 2020-03-05 10:04 UTC
Here a case where rustfmt doesn't do anything. I tried to simplify to the maximum the use case. If you remove (almost) any character, rustfmt does its job.

```rust
fn main() {
    n()
            .ser(a
            .app(
                default().limieeeeeeeeeeeeeeeeet().error_handler(|err, req| {
                    error!("Invalid model    req                      ", "error" => err.to_string());
                }
            )
        )
    )
}
```

Tested with the latest nightly: rustfmt 1.4.12-nightly (9f53665 2020-02-10)

**Comment by calebcartwright** [comment] 2020-03-05 17:45
I believe this is due to a known existing issue with chains wherein if the formatted result for any individual chain element exceeds the `max_width` value then rustmft leaves the entire original chain snippet as is. 

Refs (and likely duplicate of) #3863

**Comment by topecongiro** [comment] 2020-03-31 15:09
@TeXitoi @calebcartwright Thanks, this is indeed a duplicate of #3863.

**Closed by topecongiro** 2020-03-31 15:09 UTC
Labels: duplicate
