### ISSUE TITLE
feature(const_trait_impl): rustfmt earts const keyword 

### ISSUE THREAD

**Issue by andre-richter** [rust-lang/rustfmt#4650] opened 2021-01-17 17:43 UTC
**Describe the bug**

`rustfmt` eats the const in an `impl const`

**To Reproduce**

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ae26c3383019895433746dc93dfceb5c

**Expected behavior**

the `const` should persist if the feature is active.

**Meta**

- rustfmt version: nightly

**Comment by calebcartwright** [comment] 2021-01-17 17:46
Thanks for the report but closing as a duplicate of #4084 which is still pending backporting

**Closed by calebcartwright** 2021-01-17 17:46 UTC
Labels: bug, duplicate

**Comment by andre-richter** [comment] 2021-01-17 17:52
I should have used the search function for closed bugs as well. Sorry!

**Comment by calebcartwright** [comment] 2021-01-17 17:54
No worries! We've got some weird branching stuff going on that's resulted in things that have been long fixed in source and associated issues long since closed, but which haven't been released and that makes things tough to find.
