### ISSUE TITLE
Chained imports not canonicalized into single-import form

### ISSUE THREAD

**Issue by JakeWharton** [rust-lang/rustfmt#4764] opened 2021-03-19 02:59 UTC
**Input**

With `.rustfmt.toml` of:
```
imports_granularity = "Item"
```

```rust
use fs::File;
use io::stdin;
use std::fs;
use std::io;
```

This is produced by IntelliJ Rust which itself could be argued as its bug. However, I would like rustfmt to take care of this regardless.

**Output**

```rust
use fs::File;
use io::stdin;
use std::fs;
use std::io;
```

**Expected output**

```rust
use std::fs::File;
use std::io::stdin;
```

**Meta**

rustfmt version:

```
$ rustfmt +nightly --version
rustfmt 1.4.36-nightly (7de6968e 2021-02-07)
```

From where did you install rustfmt?:

cargo (via nightly)

**Comment by calebcartwright** [comment] 2021-03-19 03:13
Thank you for reaching out but going to close this because your requested/expected output would not be a safe transformation and has the potential to emit code that no longer compiles.

Yes, it works fine for the case of that particular minimal snippet because there's nothing using the imports, but in real code there very easily could be (e.g. elsewhere in the code an `fs::FileType`).

**Closed by calebcartwright** 2021-03-19 03:13 UTC

**Comment by JakeWharton** [comment] 2021-03-19 03:24
Yeah that makes sense. But I guess I assumed rustfmt looked at that and included it as part of its decision. (I'm relatively junior in Rust coming from Java/Kotlin where an import formatter will walk the whole AST)

But it sounds like the import canonicalization is a bit more naive than I had assumed, which further emphasizes that this is an IntelliJ Rust bug since it produces this pattern very regularly when it need not.

**Comment by calebcartwright** [comment] 2021-03-19 03:39
> I'm relatively junior in Rust coming from Java/Kotlin where an import formatter will walk the whole AST to do things like removed unused imports

No worries! There's a ton of config options related to imports, but none of them, including `imports_granularity` really deals with unused imports. The problem is that we may or may not be dealing with the same AST depending on whether the use is formatting a single file in isolation or running in `--recursive` mode which allows rustfmt to trigger the parsing of submodules defined in separate files (the former most often occurring with format-on-save scenarios in editors, the latter a full project formatting with `cargo fmt`).

One scenario where this gets problematic:

```rust
// something like a main.rs or lib.rs
use std::fs;
mod foo;
```

```rust
// foo.rs
use super::*;

fn bar() {
    let db = fs::DirBuilder::new();
}
```

So in order to be able to do this safely, both for single-file and full project formatting, we'd have to always parse every reachable file and then walk the _entire_ tree to vet out usage, which runs counter to some other goals.

> which further emphasizes that this is an IntelliJ Rust bug since it produces this pattern very regularly when it need not.

AIUI IntelliJ has their own formatter that's different than rustfmt (though believe IntelliJ can be configured to use either). If you're getting the 2-line collapsed version of the imports, then that's definitely not coming from rustfmt.

**Comment by JakeWharton** [comment] 2021-03-19 13:56
Yeah "naive" was the wrong word here. I think I meant like "conservative". Thanks for the illustrative example!
