### ISSUE TITLE
rustfmt panics on this simple code

### ISSUE THREAD

**Issue by alexxbb** [rust-lang/rustfmt#4509] opened 2020-11-04 05:18 UTC
**Describe the bug**

Running `rustfmt-nightly` panics when encounter **a space character** between a type field and a method. See the example.

**To Reproduce** 

[Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b5b3ffdc76cec5562fa50a655ab660a7)

You can see a whitespace character between `0.` and `abs()` which freaks out rustfmt

Try to apply **rustfmt** in the playground and you'll an error.

**Meta**

- rustfmt version: **1.4.21**
- From where did you install rustfmt?: 
`env CFG_RELEASE_CHANNEL=nightly CFG_RELEASE=1.47.0-nightly cargo +nightly install --force rustfmt-nightly`
- How do you run rustfmt: **rustfmt and via Intellij Rust plugin**

**Comment by calebcartwright** [comment] 2020-11-04 15:32
Duplicate of #4355, resolved in the upcoming 1.4.23 release

**Closed by calebcartwright** 2020-11-04 15:32 UTC
Labels: bug, duplicate
