### ISSUE TITLE
`single_line_let_else_max_width` emits a warning if a macro definition exists

### ISSUE THREAD

**Issue by mamekoro** [rust-lang/rustfmt#6386] opened 2024-11-06 09:25 UTC
`single_line_let_else_max_width` prints an incorrect warning if there's a macro definition in the source code.

```console
$ rustfmt --version
rustfmt 1.7.1-stable (f6e511e 2024-10-15)
$ cat rustfmt.toml
single_line_let_else_max_width = 100
$ cat src/main.rs
fn main() {}

macro_rules! a {
    () => {};
}
$ rustfmt src/main.rs
`single_line_let_else_max_width` cannot have a value that exceeds `max_width`. `single_line_let_else_max_width` will be set to the same value as `max_width`
$ rustfmt -v src/main.rs
Using rustfmt config file /home/rust/hello/rustfmt.toml for /home/rust/hello/src/main.rs
Formatting /home/rust/hello/src/main.rs
`single_line_let_else_max_width` cannot have a value that exceeds `max_width`. `single_line_let_else_max_width` will be set to the same value as `max_width`
Spent 0.000 secs in the parsing phase, and 0.000 secs in the formatting phase
```

The default value of `max_width` is 100, so there should be nothing wrong with `single_line_let_else_max_width = 100`.

---

If the macro definition in `src/main.rs` is deleted, this warning will not occur.

```console
$ echo "fn main() {}" >src/main.rs
$ rustfmt src/main.rs
```

**Comment by ytmimi** [comment] 2024-11-06 16:15
Thanks for the report. This is a duplicate of https://github.com/rust-lang/rustfmt/issues/5404

**Closed by ytmimi** 2024-11-06 16:15 UTC
