### ISSUE TITLE
rustfmt should value internal consistency in trait method signatures

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rustfmt#4555] opened 2020-11-25 19:36 UTC
**Input**

```rust
trait Sample {
    fn bytelen(width: u32, height: u32, samples: u32)
        -> ImageResult<usize>;

    fn from_bytes(bytes: &mut [u8], width: u32, height: u32, samples: u32)
        -> ImageResult<Vec<u8>>;

    fn from_ascii(reader: &mut dyn Read, width: u32, height: u32, samples: u32)
        -> ImageResult<Vec<u8>>;
}
```

**Output**

```rust
trait Sample {
    fn bytelen(width: u32, height: u32, samples: u32) -> ImageResult<usize>;

    fn from_bytes(mbytes: &mut [u8], width: u32, height: u32, samples: u32)
        -> ImageResult<Vec<u8>>;

    fn from_ascii(
        reader: &mut dyn Read,
        width: u32,
        height: u32,
        samples: u32,
    ) -> ImageResult<Vec<u8>>;
}
```

**Expected output**

None of the lines in the Input violate the line length requirements. Thus, I would expect that code is most legible if it has a consistent style and function parameters and return types are placed similarly. Instead, it changes the output to have all three different styles. Another acceptable output would be to change all or at least the second and third method to the fully expanded style.

```rust
trait Sample {
    fn bytelen(width: u32, height: u32, samples: u32)
        -> ImageResult<usize>;

    fn from_bytes(bytes: &mut [u8], width: u32, height: u32, samples: u32)
        -> ImageResult<Vec<u8>>;

    fn from_ascii(reader: &mut dyn Read, width: u32, height: u32, samples: u32)
        -> ImageResult<Vec<u8>>;
}
```

**Meta**

- rustfmt version: `1.4.27-nightly (2020-11-16 580d826)`
- From where did you install rustfmt?: play.rust-lang.org
- Similar to #3995, #3176 for which I would both have more samples but they have enough already.

**Comment by calebcartwright** [comment] 2020-11-29 21:56
Thank you for reaching out @HeroicKatora, however, this is working as designed. The formatting emitted by rustfmt is governed by the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs) which prescribes specific formatting guidelines for all code constructs. All of the formatting rules are applied consistently to each node in the AST, and by design those rules are not conditionally applied/broken based on original formatting nor the formatted result of other/"related" elements.

The request here runs counter to the formatting approach of the style guide and thus rustfmt, so going to close this.

**Closed by calebcartwright** 2020-11-29 21:56 UTC
Labels: wont-fix
