### ISSUE TITLE
Comments on lines with curlies are moved to the next line.

### ISSUE THREAD

**Issue by DanielSchuette** [rust-lang/rustfmt#3527] opened 2019-04-25 09:42 UTC
I don't know if this was already reported, but I observe the following behavior:

If I have comments on the same line as opening or closing curly braces (nothing one usually does, I know), the code gets reformatted as follows.

```rust
// ...
} else { /* some comment, either this style or '//' */
// ...
```
becomes:
```rust
// ...
} else {
/* the comment ends up on the next line! */
// ...
```

My use-case is running code through a post-processor that *needs*  comments to be on a line with the braces, so I would really, *really* appreciate an option to turn this behavior off. Thanks for considering this request!

**Comment by nokola** [comment] 2019-12-17 04:53
Another use case: in our team we usually "explain if-s" with the intention of the `if` statement like so:
```
        if self.root == None { // if empty tree
```
As is, rustfmt will convert the above code to: 
```
        if self.root == None {
            // if empty tree
```

Which is undesired. Would love to have an option to keep comments on the same line.

**Comment by calebcartwright** [comment] 2019-12-17 05:07
@nokola what version of rustfmt are you using? with the latest version of rustfmt on master the comments are now left on the same line in both your snippet and the snippet from @DanielSchuette in the OP. 

I forget exactly which version of rustfmt would contain the fix as there have been quite a few comment-related PRs over the last several weeks

**Comment by topecongiro** [comment] 2020-01-14 22:39
Closing in favor of #3255.

**Closed by topecongiro** 2020-01-14 22:39 UTC
Labels: a-comments, duplicate, poor-formatting

**Comment by nokola** [comment] 2020-01-15 07:16
Yes, the scenario I reported is duplicate of #3255.
