### ISSUE TITLE
Support --workspace flag as an alias for --all

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rustfmt#5635] opened 2022-12-22 12:17 UTC
`cargo fmt` supports a `--all` flag for operating on all members in a workspace. `cargo check` also supports `--all` for the same purpose, but this is deprecated in favor of `--workspace`, which is an alias with no semantic difference. Other tools based on `cargo check`, like `cargo clippy`, inherit the ability to use `--workspace`. The inability to use `--workspace` in an official tool thus feels inconsistent.

For reference, here's the PR where `cargo clippy` switched to using `cargo check`'s manifest handling, which had the effect of removing their own bespoke `--all` flag: https://github.com/rust-lang/rust-clippy/pull/2585 .

It would be nice for all of the officially-provided tools to present consistent interfaces.

**Comment by ytmimi** [comment] 2022-12-22 12:34
Thanks for reaching out, but this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5010

**Closed by ytmimi** 2022-12-22 12:34 UTC
Labels: duplicate
