### ISSUE TITLE
Comments on items in `extern` block are deleted

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustfmt#4533] opened 2020-11-17 18:22 UTC
**Describe the bug**

When a normal comment (non-doc-comment) is applied to an item in an `extern` block, `rustfmt` will delete it.

**To Reproduce**

The following code:

```
extern "C" {
    // A comment
    fn bar();
}
```

is formatted as:

```
extern "C" {
    fn bar();
}
```

**Expected behavior**

`rustfmt` should leave the comment intact

**Meta**

- rustfmt version: rustfmt 1.4.26-nightly (293d7d0 2020-11-14)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment] 2020-11-17 18:25
Duplicate of #4528, fixed in the next nightly (https://github.com/rust-lang/rust/pull/79120)

**Closed by calebcartwright** 2020-11-17 18:25 UTC
Labels: bug, duplicate
