### ISSUE TITLE
Formatting stops when encountering `-` `>` tokens in a macro call that is longer than the line length limit

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rustfmt#5231] opened 2022-02-18 18:59 UTC
The code
```rust
macro_rules! foo_bar_baz {
    (() - > FillTheLineSomehow_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) => {
        Some(5)
    };
}

fn main() {
    foo_bar_baz!(() - > FillTheLineSomehow_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
    .map(|_|
        "hello"     .to_string() // note this bad formatting here
    );
}
```
gets formatted to exactly the same output, using default options.

Statements after this one get formatted correctly.

The code compiles successfully using `rustc`.

Rustfmt version: `rustfmt 1.4.38-nightly (30b3f35 2022-02-17)` (latest version right now)

Some things I tried thatmade `rustfmt` format the code correctly:
* Removing the `-` or `>` from the macro
* Making the line shorter

#1128 seems to be related to this.

The issue was discovered by @Super-Pizza, I found this minimal example.

**Comment by calebcartwright** [comment] 2022-02-19 22:27
Thanks for reaching out, but going to close as this is a duplicate of #3863

**Closed by calebcartwright** 2022-02-19 22:27 UTC
Labels: duplicate
