### ISSUE TITLE
Bug: rustfmt complains that fn_call_width is bigger than max_width when it isn't

### ISSUE THREAD

**Issue by bergkvist** [rust-lang/rustfmt#6074] opened 2024-02-15 22:24 UTC
When running `cargo fmt`, I get the following warning message printed out to my terminal:
```
`fn_call_width` cannot have a value that exceeds `max_width`. `fn_call_width` will be set to the same value as `max_width`
```
*rust version 1.78.0-nightly (ee9c7c940 2024-02-14)*

The following macro somehow triggers the warning:
```rs
mod a {
    macro_rules! b {
        () => {};
    }
}
```

When you have a `.rustfmt.toml` config set up file like this:
```toml
max_width = 100
fn_call_width = 90
```

Increasing max_width to 102, or changing the macro to the following will make the warning go away:
```rs
mod a {
    macro_rules! b {
        () => {{}};
    }
}
```

See this repo for how to reproduce:
https://github.com/bergkvist/rustfmt-bug

**Comment by bergkvist** [comment] 2024-02-15 23:15
Seems like this might be caused by the following:
```rs
// max_width here is 100
// fn_call_width here is 90
mod a {
    // max_width here is 96
    // fn_call_width here is 90
    macro_rules! b {
        () => {
            // max_width here is 88
            // fn_call_width here is 90
        };
    }
}
```

**Comment by bergkvist** [comment] 2024-02-16 00:46
This seems like it is caused by the same problem as https://github.com/rust-lang/rustfmt/issues/5404.

**Comment by ytmimi** [comment] 2024-02-16 16:54
Thanks for the report! Right, this is likely a duplicate of https://github.com/rust-lang/rustfmt/issues/5404 so I'm going to close this one.

**Closed by ytmimi** 2024-02-16 16:54 UTC
