### ISSUE TITLE
Move mod statements before use statements

### ISSUE THREAD

**Issue by sazzer** [rust-lang/rustfmt#5631] opened 2022-12-10 11:46 UTC
As a preference, I like to have all my `mod` statements at the top of the file, and `use` statements after them. As I understand, this has no impact on the code but it makes it read better when a `use` statement refers to a `mod` statement.

For example:

Preferred
```rust
mod a;
mod b;

use a::MyA;
pub use b::MyB;
```

It would be great if there was some way for rustfmt to help ensure this. For example, when using the builtin tools in rust-analyzer it often puts the `use` statements right at the top of the file:

```rust
use a::MyA;
pub use b::MyB;

mod a;
mod b;
```

Which works but just doesn't read as well in my opinion.

Is this already possible? Or, if not, could it be considered as a feature request? :)

Cheers

**Comment by ytmimi** [comment] 2022-12-10 16:07
Thanks for reaching out. Currently there isn't an option to enforce this, but I'm going to close this as it's a duplicate of #3959

**Closed by ytmimi** 2022-12-10 16:07 UTC
Labels: duplicate
