### ISSUE TITLE
Rustfmt leaves improperly-formatted code as-is

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rustfmt#5001] opened 2021-09-23 21:06 UTC
Rustfmt fails to format the following code, even though it is not properly formatted. In particular, note the trailing `)` and `}`, and also the very long first line of the function.

```rust
fn receive_icmpv6_error<
    B: BufferMut,
    C: InnerBufferIcmpv6Context<B>,
    BB: ByteSlice,
    M: IcmpMessage<Ipv6, BB, Body = OriginalPacket<BB>>,
>(
    ctx: &mut C,
    packet: &IcmpPacket<Ipv6, BB, M>,
    err: Icmpv6ErrorCode,
) {
    packet.with_original_packet(|res| match res.ok().and_then(|original_packet| original_packet.proto().map(|proto| (original_packet, proto))) {
            Some((original_packet, proto)) => {
                let dst_ip = try_unit!(SpecifiedAddr::new(original_packet.dst_ip()).ok_or_else(|| {
                    trace!("receive_icmpv6_error: Got ICMP error message whose original IPv6 packet contains an unspecified destination address; discarding");
                }));
                let body = match original_packet.body() {
                    Ok(body) => body.into_inner(),
                    Err(UndefinedBodyBoundsError) => {
                        trace!("receive_icmpv6_error: We could not parse the original packet's extension headers, and so we don't know where the original packet's body begins; discarding");
                        // There's nothing we can do in this case, so we just
                        // return.
                        return;
                    }
                };
                InnerIcmpContext::receive_icmp_error(
                    ctx,
                    SpecifiedAddr::new(original_packet.src_ip()),
                    dst_ip,
                    proto,
                    body,
                    err,
                );
            }
            None => debug!(
                "receive_icmpv6_error: Got ICMPv6 error message with unparsable original IPv6 packet"
            ),
        }
)
}
```

Version:

```
$ rustfmt --version
rustfmt 1.4.37-nightly (1f94abcda68 2021-08-06)
```

**Comment by calebcartwright** [comment] 2021-09-24 02:46
Thanks for reaching out, but closing as a duplicate of #3863

**Closed by calebcartwright** 2021-09-24 02:46 UTC
