### ISSUE TITLE
[unstable option] report_todo

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3393] opened 2019-02-13 22:57 UTC
Tracking issue for report_todo

**Comment by tangmi** [comment] 2019-11-08 01:56
I'm unsure if this is the right place for these comments, but I love `report_todo` and am wondering what work needs to be done to stabilize it?

**Comment by topecongiro** [comment] 2019-12-09 11:14
@tangmi Sorry for the late reply, but actually, this option is something that I would like to remove from rustfmt. This option is not related to formatting and can be replaced with other tools like `rg TODO`.

**Comment by tangmi** [comment] 2019-12-11 02:26
@topecongiro Makes sense, based on rustfmt's scope, but sad to see it go. Being able to use `report_todo` without having to install anything additional in CI scenarios was really handy!

**Comment by mathstuf** [comment] 2020-04-11 07:41
Note that it has some [eager behaviors](https://github.com/mathstuf/devtodo/runs/578683910) today and catches structures and variables named `todo` today.

**Comment by tangmi** [comment] 2020-04-12 21:53
I wonder if something changed (I haven't followed the history pre-crate split)?

Here is where rustfmt matches on the "todo" string:

https://github.com/rust-lang/rustfmt/blob/1e9af9fa2eb6ba4e0ad1e2e275003ada7e5a27e2/rustfmt-core/rustfmt-lib/src/issues.rs#L123-L137

... and where it calls into that code:

https://github.com/rust-lang/rustfmt/blob/1e9af9fa2eb6ba4e0ad1e2e275003ada7e5a27e2/rustfmt-core/rustfmt-lib/src/formatting.rs#L523

It seems like in `formatting.rs`/`issue.rs` needs to keep track of whether or not the TODO exists in a comment (or if doing something like `unimplemented!("TODO(#1234): ...")` or `todo!("TODO(#1234): ...")` is intended behavior...

**Comment by calebcartwright** [comment] 2021-10-30 15:21
> Reopening, 2.0 is not happening and current docs are still pointing to this issue.
> 
> This has been implemented by clippy in the meantime: https://rust-lang.github.io/rust-clippy/master/#todo

Thanks @karyon. Couple minor additions/tweaks, I don't want to convey that 2.0 will _never_ happen, it's just increasingly unlikely that it will happen outside an entire Rust ecosystem 2.0, and certainly going to happen any time _soon_.

Additionally, this option and the associated behavior is a bit different from the clippy lint, as rustfmt actually looks for textual `TODO`s in comments, whereas clippy is just looking for the macro usage.

I think there's still a strong argument for us to drop this from rustfmt (it's quite orthogonal to formatting of code) and we may still do so

**Comment by calebcartwright** [comment] 2021-11-22 19:17
Going to close this because stabilization doesn't make sense given our intent to deprecate and remove the option, refs #5101

**Closed by calebcartwright** 2021-11-22 19:17 UTC
Labels: unstable option
