### ISSUE TITLE
Additional calls to `cargo fmt` keep indenting lines in a macro forever

### ISSUE THREAD

**Issue by Chris--B** [rust-lang/rustfmt#5622] opened 2022-12-01 15:56 UTC
I have a simplified bit of some code:
```rust
macro_rules! foo {
    (x: $input:expr) => {};
}

mod bar {
    foo! {
    x: r"
    x
".trim()
        }
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a2068704725c5c3e4abdf3c5900c4293)

When I run `cargo fmt`, it indents like so:
```rust
macro_rules! foo {
    (x: $input:expr) => {};
}

mod bar {
    foo! {
        x: r"
    x
".trim()
            }
}
```
but continues to indent on each run of `cargo fmt`:
```rust
macro_rules! foo {
    (x: $input:expr) => {};
}

mod bar {
    foo! {
            x: r"
    x
".trim()
                }
}
```

Each iteration, the `x: r"` and `}` are indented further. Some things I noticed as I simplified my repro:

- If `".trim()` has any whitespace on the line before it, this doesn't happen
- If the raw string doesn't have non-whitespace (the `x` above), this doesn't happen
- If the macro call is not inside of a module (`mod bar`), this doesn't happen

I do not see it ever stabilize. I generally rely on formatting in a loop per save to eventually stabilize, while writing code.

**Comment by ytmimi** [comment] 2022-12-01 16:22
Thanks for reaching out!

Going to close this as I believe this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5283

**Closed by ytmimi** 2022-12-01 16:22 UTC
Labels: bug, duplicate, a-macros
