### ISSUE TITLE
Very long use line fails to format

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/rustfmt#5371] opened 2022-06-07 10:45 UTC
[Reproduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=92e05c8ec98f161ead2ebb20acf9b42d):
```rust
use a::very::very::very::very::very::very::very::{

    very::very::very::very::very::very::very::very::very::long::Path
};
```

This tries to format into

```rust
use a::very::very::very::very::very::very::very::very::very::very::very::very::very::very::very::very::long::Path
```

Which I think triggers some misbehaviour and causes the block of imports to fail to format silently.

If given another item in the long module chain, it can format fine:

```rust
use a::very::very::very::very::very::very::very::{

    very::very::very::very::very::very::very::very::very::long::Path,
    another::path,
};
// turns into
use a::very::very::very::very::very::very::very::{
    another::path, very::very::very::very::very::very::very::very::very::long::Path,
};
```

Amount of modules doesn't change anything, only the number of characters.

**Comment by Globidev** [comment] 2022-06-07 11:06
After experimenting a bit, there might be other parameters at play, like byte length and module nesting possibly ?
```rs
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::{

    ඞ::ඞ
};
// one more ඞ
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::{

    ඞ::ඞ
};
// less nesting but longer
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::{

    ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ
};
```
only formats the second one incorrectly:
```rs
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::ඞ::ඞ;
// one more ඞ
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::{

    ඞ::ඞ
};
// less nesting but longer
use ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ::ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ;
```
[playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=3018f3f16abba8c6dd43fe47f42307de)

**Comment by calebcartwright** [comment] 2022-06-11 00:05
Thanks for sharing but closing as a duplicate of #4746

**Closed by calebcartwright** 2022-06-11 00:05 UTC
Labels: duplicate
