### ISSUE TITLE
Nested match statements break formatting

### ISSUE THREAD

**Issue by DzenanJupic** [rust-lang/rustfmt#5645] opened 2022-12-29 13:47 UTC
When trying to format the following code [[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e8815b49c0144ae48dc06ea2688239c0)] (I know it would not compile, but should be valid syntax):

```rust
fn temp() {
    match _ {
        _ => iter
            .map(|_| {
                iter.into_iter()
                    .filter_map( |_|
                    {
                        let _ = {};

                        match range
                        {
                            Some(range ) if range.start >= file_name_range.start && range.end <= file_name_range.end => {
                            },
                            Some( range) =>
                            {
                                panic!("File '{path:?}' contains a range differing from it's name: {range:?}");
                            }
                        }
                    }
                      )
                    .collect::<Vec<_ >>()
            }),
    }
}
```

`rustfmt` just does noting, and does not fix any of the obvious formatting errors.
Also, when a single empty line is added somewhere, like [in this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=18ba1a697bd37fa84db0fba5f90c81fd), `rustfmt` fails with

```
error[internal]: left behind trailing whitespace
  --> /playground/src/main.rs:23:23:1
   |
23 |             
   | ^^^^^^^^^^^^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by ytmimi** [comment] 2022-12-29 16:41
Thanks for reaching out. This is actually a duplicate of #3863. The line with the call to `panic!` exceeds the default max width of 100, and prevents us from formatting the `iter.into_iter().filter_map()` chain.

Your options to resolve this are to set `format_strings=true` (if you're using a nightly rustfmt) or to increase the `max_width` to a sufficiently large value. Through testing I found that `102` is the minimum width you need for rustfmt to format your input.

#### With `format_string=true`:
```rust
fn temp() {
    match _ {
        _ => iter.map(|_| {
            iter.into_iter()
                .filter_map(|_| {
                    let _ = {};

                    match range {
                        Some(range)
                            if range.start >= file_name_range.start
                                && range.end <= file_name_range.end => {}
                        Some(range) => {
                            panic!(
                                "File '{path:?}' contains a range differing from it's name: \
                                 {range:?}"
                            );
                        }
                    }
                })
                .collect::<Vec<_>>()
        }),
    }
}
```

#### With `max_width=102`
```rust
fn temp() {
    match _ {
        _ => iter.map(|_| {
            iter.into_iter()
                .filter_map(|_| {
                    let _ = {};

                    match range {
                        Some(range)
                            if range.start >= file_name_range.start
                                && range.end <= file_name_range.end => {}
                        Some(range) => {
                            panic!(
                                "File '{path:?}' contains a range differing from it's name: {range:?}"
                            );
                        }
                    }
                })
                .collect::<Vec<_>>()
        }),
    }
}
```

#### with `max_width=110`
```rust
fn temp() {
    match _ {
        _ => iter.map(|_| {
            iter.into_iter()
                .filter_map(|_| {
                    let _ = {};

                    match range {
                        Some(range)
                            if range.start >= file_name_range.start && range.end <= file_name_range.end => {}
                        Some(range) => {
                            panic!("File '{path:?}' contains a range differing from it's name: {range:?}");
                        }
                    }
                })
                .collect::<Vec<_>>()
        }),
    }
}
```

I hope that helps!

**Closed by ytmimi** 2022-12-29 16:41 UTC
Labels: duplicate, a-chains, a-strings
