### ISSUE TITLE
Macro within macro not idempotent

### ISSUE THREAD

**Issue by Ten0** [rust-lang/rustfmt#5045] opened 2021-10-27 22:23 UTC
Not sure if "macro within macro" is the actual issue, but here's the example:

```rust
macro_rules! make_macro {
    ($d: tt $x: ident) => {
        macro_rules! make_x {
            ($d b: ident) => {
                pub struct $x{
                    pub $d b : (),
                }
            };
        }
    };
}

make_macro!($ Foo);

mod bar {
    make_x! {x}
}

fn main() {
    let _ = bar::Foo { x: () };
}
```

Rustfmt adds 2 indents on lines [4, 9] every time it's run.

**Comment by calebcartwright** [comment] 2021-10-30 14:47
Believe this is a duplicate of #4609?

**Closed** 2021-10-30 16:47 UTC
