### ISSUE TITLE
Code block with ".await"-ed closure and long line inside the closure is not formatted

### ISSUE THREAD

**Issue by ppershing** [rust-lang/rustfmt#4832] opened 2021-05-06 14:45 UTC
Smallest repro:
```
fn error(s: &str) {}

pub async fn do_something1() {
    (|| async {
        error("This line works because it is shorter");
    })()
    .await;
}

pub async fn do_something2() {
    (|| async {
                      error("This sentence is veeery veeery long, what the heck is happening here with rust formatter????");
    })().await;
}

fn main() {}
```

Note that
1) this seem to be related to the line length
2) `async` keyword is not needed, I tried with directly returning futures (`tokio::time::sleep`) from closure and the same problem persisted
3) removing `.await` helps with formatting

```
>cargo fmt --version
rustfmt 1.4.36-stable (7de6968 2021-02-07)
```

**Comment by calebcartwright** [comment] 2021-05-16 19:18
Thanks for reaching out with the report! I'm going to go ahead and close this though as a duplicate of #3863.

The TL;DR is that in cases when any part of a chain cannot be formatted (as is the case here because it's impossible to format within the max_width constraints due to the string lit) then rustfmt is unable to format the chain entirely.

There's a few ways you can address this:

* define a local for the string lit and then use that local for the arg
* manually break up the string into multiple lines so that it can fit within the width constraints
* enable the `format_strings` configuration option to give rustfmt permission to attempt to wrap long strings on your behalf

**Closed by calebcartwright** 2021-05-16 19:18 UTC
