### ISSUE TITLE
`rustfmt 1.7.0-nightly` inconsistent output across targets

### ISSUE THREAD

**Issue by kyle-mccarthy** [rust-lang/rustfmt#5964] opened 2023-11-20 23:40 UTC
Our CI started failing at the formatting check step after updating to `1.7.0-nightly (9a66e4471 2023-11-19)`; however, when run locally `cargo +nightly fmt --check` passes. I verified that they both are using the same version of rustfmt, the only differences being the platform/target.

CI: `nightly-x86_64-unknown-linux-gnu installed - rustc 1.76.0-nightly (9a66e4471 2023-11-19)`
Local: `nightly-aarch64-apple-darwin - Up to date : 1.76.0-nightly (9a66e4471 2023-11-19)`

Note that `rustfmt 1.7.0-nightly (28317017 2023-11-17)` produces the same output regardless of platform, so I think that the issue only exists in the most recent nightly (`rustfmt 1.7.0-nightly (9a66e447 2023-11-19)`) on the `nightly-aarch64-apple-darwin` target.

# Example

**CI Output (`nightly-x86_64-unknown-linux-gnu`)**

```rust
use serde_json::json;

fn main() {
    let map = json!({ "key": "value" });

    let _value: String = map
        .get("key")
        .map(|v| v.as_str())
        .flatten()
        .unwrap_or_default()
        .to_string();
}
```

**Local Output (`nightly-aarch64-apple-darwin`)**

```rust
use serde_json::json;

fn main() {
    let map = json!({ "key": "value" });

    let _value: String =
        map.get("key")
            .map(|v| v.as_str())
            .flatten()
            .unwrap_or_default()
            .to_string();
}
```

**Output Diff**

```
diff --git a/src/main.rs b/src/main.rs
index 789b018..771d6ca 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -3,10 +3,10 @@ use serde_json::json;
 fn main() {
     let map = json!({ "key": "value" });

-    let _value: String =
-        map.get("key")
-            .map(|v| v.as_str())
-            .flatten()
-            .unwrap_or_default()
-            .to_string();
+    let _value: String = map
+        .get("key")
+        .map(|v| v.as_str())
+        .flatten()
+        .unwrap_or_default()
+        .to_string();
 }
```

**Comment by lukesneeringer** [comment] 2023-11-21 22:09
As a note, the output on Darwin is alarmingly weird. The formatting differences are annoying enough, but it also eats comments after a single blank line, e.g.

```rs
// This is a comment.
//
// This is more information.
```

^-- The second and third line of the above get removed.

**Comment by ytmimi** [comment] 2023-11-21 22:18
@kyle-mccarthy thanks for reaching out. I'm not quite sure what would have changed recently to cause the formatting diff. Our last subtree sync with the rustlang-rust repo was about a month ago https://github.com/rust-lang/rust/pull/117066 so we haven't released anything for a while.


> Note that rustfmt 1.7.0-nightly (28317017 2023-11-17) produces the same output regardless of platform, so I think that the issue only exists in the most recent nightly (rustfmt 1.7.0-nightly (9a66e447 2023-11-19)).

Thanks for taking the time to do a little investigating on this.


I checked `rustfmt 1.7.0-nightly (4cb3beec 2023-11-18)` and `rustfmt 1.7.0-nightly (9a66e447 2023-11-19)` and here are the results:

`rustfmt 1.7.0-nightly (4cb3beec 2023-11-18)` does not produce a diff, and I can confirm that `rustfmt 1.7.0-nightly (9a66e447 2023-11-19)` does.

```
ytmimi ~ $: rustfmt +nightly-2023-11-19 --version
rustfmt 1.7.0-nightly (4cb3beec 2023-11-18)
ytmimi ~ $: rustfmt +nightly-2023-11-19 --check  
use serde_json::json;

fn main() {
    let map = json!({ "key": "value" });

    let _value: String = map
        .get("key")
        .map(|v| v.as_str())
        .flatten()
        .unwrap_or_default()
        .to_string();
}
ytmimi ~ $: rustfmt +nightly-2023-11-20 --version
rustfmt 1.7.0-nightly (9a66e447 2023-11-19)
ytmimi ~ $: rustfmt +nightly-2023-11-20 --check  
use serde_json::json;

fn main() {
    let map = json!({ "key": "value" });

    let _value: String = map
        .get("key")
        .map(|v| v.as_str())
        .flatten()
        .unwrap_or_default()
        .to_string();
}
Diff in <stdin> at line 3:
 fn main() {
     let map = json!({ "key": "value" });
 
-    let _value: String = map
-        .get("key")
-        .map(|v| v.as_str())
-        .flatten()
-        .unwrap_or_default()
-        .to_string();
+    let _value: String =
+        map.get("key")
+            .map(|v| v.as_str())
+            .flatten()
+            .unwrap_or_default()
+            .to_string();
 }
```

@calebcartwright do you think something weird could have happened with changes made to rustfmt directly from `rust-lang/rust`?

**Comment by ytmimi** [comment] 2023-11-21 22:22
@lukesneeringer Are you sure that your issue is related? I just double check and I can't reproduce. It would probably be best for you to open up a separate issue fully explaining the issue that you're having as well as any configuration options that you're using.

```
ytmimi ~ $: rustfmt +nightly-2023-11-19 --check  
// This is a comment.
//
// This is more information.
ytmimi ~ $: rustfmt +nightly-2023-11-20 --check
// This is a comment.
//
// This is more information.
```

**Comment by lukesneeringer** [comment] 2023-11-21 22:25
I can do that. Although I'm fairly certain it's related, and [this comment](https://github.com/hashintel/hash/pull/3548#pullrequestreview-1742397269) seems to suggest the same.

I'll open a separate issue in a little bit when I get a moment. :-)

**Comment by ytmimi** [comment] 2023-11-21 23:59
@calebcartwright it Also doesn't look like there were any changes made to rustfmt in the `rust-lang/rust` repo within the last two weeks: https://github.com/rust-lang/rust/commits/master/src/tools/rustfmt

**Comment by ytmimi** [comment] 2023-11-22 00:31
For what it's worth this doesn't seem to be an issue on the [Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cacdae762fdc948d2f9165e62627a0be) which as of today is using `1.7.0-nightly (2023-11-20 3a85a5c)`

<img width="1727" alt="Screen Shot 2023-11-21 at 7 24 55 PM" src="https://github.com/rust-lang/rustfmt/assets/29028348/1d077ecd-4279-42fe-b205-970c8fa3e275">


Though when I ran with `rustfmt 1.7.0-nightly (3a85a5cf 2023-11-20)` locally with the `nightly-2023-11-21-aarch64-apple-darwin` toolchain I got a diff:

```diff
Diff in <stdin> at line 3:
 fn main() {
     let map = json!({ "key": "value" });
 
-    let _value: String = map
-        .get("key")
-        .map(|v| v.as_str())
-        .flatten()
-        .unwrap_or_default()
-        .to_string();
+    let _value: String =
+        map.get("key")
+            .map(|v| v.as_str())
+            .flatten()
+            .unwrap_or_default()
+            .to_string();
 }
```

**Comment by kyle-mccarthy** [comment] 2023-11-22 01:07
> For what it's worth this doesn't seem to be an issue on the [Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cacdae762fdc948d2f9165e62627a0be) which as of today is using `1.7.0-nightly (2023-11-20 3a85a5c)`

The rust playground is actually how produced the `nightly-x86_64-unknown-linux-gnu` output in my original bug report (it has the same output as our CI). Note that the playground is currently running linux and the architecture is x86_64.

The output that it is producing right now (`2023-11-20 3a85a5c`), is the same output that it was producing yesterday (`9a66e4471 2023-11-19`). I think that this is the correct/intended output.

The incorrect formatting seems to happen on `nightly-aarch64-apple-darwin` starting with `9a66e4471 2023-11-19`.

I don't have access to test on other targets so I am not sure if the wrong output is limited to `nightly-aarch64-apple-darwin` or if it extends to others.

**Comment by xxchan** [comment] 2023-11-22 03:05
Similar issue here.  Also `aarch64-apple-darwin`.

<img width="682" alt="image" src="https://github.com/rust-lang/rustfmt/assets/37948597/c5df4723-e95d-4060-af4b-d302530a127f">

**Comment by xxchan** [comment] 2023-11-22 03:10
Is it possible that this is caused by sth like rustup or rust nightly release pipeline?

**Comment by lukesneeringer** [comment] 2023-11-22 03:25
@ytmimi I've come up with a fairly simple repro case. I'm posting it here rather than making it a new ticket because I've proven that it _only_ occurs on aarch64-apple-darwin (not Linux). I'm happy to open a new issue if appropriate.

Here's my `src/lib.rs` file (this is documentation from one of my actual crates, but you can repro with literally just this):

```rs
//! Market calendar aware utilities
//!
//! This crate primarily provides the [`MarketCalendar`] trait, which adds methods for traversing
//! trading days, determining whether the markets are open on a given date, and so on. Currently
//! the trait is only applied to [`chrono::NaiveDate`], and when brought into scope, allows you to
//! ask about the market calendar for a given date, or traverse by trading day count.
//!
//! ```
//! use chrono::NaiveDate;
//! use market_cal::MarketCalendar;
//!
//! let dt = NaiveDate::from_ymd_opt(2020, 12, 24).unwrap();
//! assert_eq!(dt.next_trading_day(), NaiveDate::from_ymd_opt(2020, 12, 28).unwrap());
//! ```
```

Also the following `rustfmt.toml` file:

```toml
format_code_in_doc_comments = true
wrap_comments = true
```

## Expected Behavior (Linux)

On Linux, using `nightly-2023-11-21` I get this diff (the diffs are expected as I use other rustfmt options, which I removed to make the repro case simple):

```diff
 //! Market calendar aware utilities
 //!
-//! This crate primarily provides the [`MarketCalendar`] trait, which adds methods for traversing
-//! trading days, determining whether the markets are open on a given date, and so on. Currently
-//! the trait is only applied to [`chrono::NaiveDate`], and when brought into scope, allows you to
-//! ask about the market calendar for a given date, or traverse by trading day count.
+//! This crate primarily provides the [`MarketCalendar`] trait, which adds
+//! methods for traversing trading days, determining whether the markets are
+//! open on a given date, and so on. Currently the trait is only applied to
+//! [`chrono::NaiveDate`], and when brought into scope, allows you to
+//! ask about the market calendar for a given date, or traverse by trading day
+//! count.
 //!
 //! ```
 //! use chrono::NaiveDate;
Diff in /home/luke/Code/testme/src/lib.rs at line 10:
 //! use market_cal::MarketCalendar;
 //!
 //! let dt = NaiveDate::from_ymd_opt(2020, 12, 24).unwrap();
-//! assert_eq!(dt.next_trading_day(), NaiveDate::from_ymd_opt(2020, 12, 28).unwrap());
+//! assert_eq!(
+//!     dt.next_trading_day(),
+//!     NaiveDate::from_ymd_opt(2020, 12, 28).unwrap()
+//! );
 //!
```

## Unexpected Behavior (Darwin)

On Mac/Darwin _only_, on `nightly-2023-10-21`, I get this diff:

```diff
 //! Market calendar aware utilities
-//!
-//! This crate primarily provides the [`MarketCalendar`] trait, which adds methods for traversing
-//! trading days, determining whether the markets are open on a given date, and so on. Currently
-//! the trait is only applied to [`chrono::NaiveDate`], and when brought into scope, allows you to
-//! ask about the market calendar for a given date, or traverse by trading day count.
-//!
-//! ```
-//! use chrono::NaiveDate;
-//! use market_cal::MarketCalendar;
-//!
-//! let dt = NaiveDate::from_ymd_opt(2020, 12, 24).unwrap();
-//! assert_eq!(dt.next_trading_day(), NaiveDate::from_ymd_opt(2020, 12, 28).unwrap());
-//! ```
```

I'm happy to post another issue if you still believe it's unrelated, although since it popped up at the same time _and_ appears to be isolated to Macs, I really do think it's a symptom of the same issue.

**Comment by ytmimi** [comment] 2023-11-22 03:49
@lukesneeringer thanks for providing a small reproducible test case. I think a new issue would be overkill at this point. I couldn't tell you why these issues are related, but something definitely seems off on `aarch64-apple-darwin` and the issues start with the `nightly-2023-11-20-aarch64-apple-darwin` toolchain.

<details>
<summary>Confirmation Screenshot</summary>
<img width="767" alt="Screen Shot 2023-11-21 at 10 40 54 PM" src="https://github.com/rust-lang/rustfmt/assets/29028348/241d5e11-6d92-4756-9f7c-f6f9138a3de6">
</details>


@xxchan thank you for also providing some confirmation on this.

> Is it possible that this is caused by sth like rustup or rust nightly release pipeline?

At this point I'm not too sure what the underlying issue is, but I'll be sure to report back if I figure anything out.

**Comment by ytmimi** [comment] 2023-11-22 04:09
Also want to highlight that neither issue is reproducible when build rustfmt from source:

rustfmt 1.7.0-nightly (37489e43 2023-11-01)

<details>
<summary>Screenshot</summary>
<img width="760" alt="Screen Shot 2023-11-21 at 11 06 38 PM" src="https://github.com/rust-lang/rustfmt/assets/29028348/7543c876-57b8-406c-abcf-75501d3ed9eb">

</details>

**Comment by calebcartwright** [comment] 2023-11-22 04:21
> @calebcartwright do you think something weird could have happened with changes made to rustfmt directly from rust-lang/rust?

@ytmimi no, though I think this has already been borne out in subsequent discussion, both because of the seeming platform dependency and the git history.

<hr />

We aren't involved with the packaging and distribution aspects of rustfmt, as is the typical pattern for the dev tools that ship with the toolchains. There shouldn't be any saliant (see: behavioral, commit, etc.) differences between the rustfmt binaries per platform, so I'd guess we're looking at an upstream packaging issue, or somehow execution is occurring with a different config.

I'd like to start with the most absolute minimal repro possible, and then do a platform-specific bisect, essentially walking back through each nightly version on nightly-aarch64-apple-darwin, making sure the version of `cargo-fmt` & `rustfmt` is as expected for each toolchain, and then running in verbose mode for each tool chain so that the relevant config info is displayed.

If nothing jumps out from that, then next I think we'd want to take a look at the actual binary that rustup is grabbing from the upstream buckets so that we have more info when we talk to them and/or infra

**Comment by ehuss** [comment] 2023-11-22 04:21
FWIW, bisecting showed the change appeared with https://github.com/rust-lang/rust/pull/117500.

**Comment by ehuss** [comment] 2023-11-22 04:36
CC @RalfJung, perhaps you have a theory why https://github.com/rust-lang/rust/pull/117500 might have changed rustfmt to behave differently on aarch64?  I tested aarch64-apple-darwin, aarch64-unknown-linux-gnu, and aarch64-pc-windows-msvc, and they all behave differently from x86_64 builds (the aarch64 hosts now have different formatting behavior).

**Comment by calebcartwright** [comment] 2023-11-22 04:38
I'll add that the diffs seem to be related to rustfmt now thinking the width/length isn't the same across the platforms

**Comment by RalfJung** [comment] 2023-11-22 06:03
Wow, that's wild. Could this be a symptom of https://github.com/rust-lang/rust/issues/118124, where data gets corrupted on some intrinsic call? Then https://github.com/rust-lang/rust/pull/118127 would help.

**Comment by ehuss** [comment] 2023-11-22 18:55
I confirmed that https://github.com/rust-lang/rust/pull/118127 fixed rustfmt for me on aarch64. I haven't tested it heavily, though.

**Comment by ytmimi** [comment] 2023-11-22 20:08
@ehuss thanks for the confirmation. Would you mind quickly outlining what steps you took to verify that https://github.com/rust-lang/rust/pull/118127 fixed rustfmt for you

**Comment by ytmimi** [comment] 2023-11-22 20:22
What I did to verify that the changes in https://github.com/rust-lang/rust/pull/118127 resolved the issue is that I checked out Ralph's branch, built `rustfmt 1.7.0-dev (ebfb95a3571 2023-11-22)`, and then ran it against the snippets posted here and found that no diffs were produced.

**Comment by ehuss** [comment] 2023-11-22 21:10
Yea, that's what I did.  Essentially:
1. `./x.py build rusfmt`
2. Verified it formatted incorrectly.
3. `gh pr checkout 118127`
4. `./x.py build rustfmt`
5. Verified it formatted correctly.

**Comment by xfbs** [comment] 2023-11-25 09:47
Hey just to chip in here, I ran into the same issue. 

- CI runs nightly Rust 1.74 with `rustfmt 1.7.0-nightly (37b2813 2023-11-24)` on `x86_64-unknown-linux-gnu`
- Locally, I run nightly Rust 1.74 with `rustfmt 1.7.0-nightly (37b2813a 2023-11-24)` on `aarch64-unknown-linux-gnu`

I'm working on an M2 MacBook Air, but I'm coding inside a Debian VM (hence aarch64 but Linux).

Running `cargo +nightly fmt`, I get inconsistent output. It appears like `rustfmt` has a different idea of what the line width should be on my local machine. I thought I was going crazy, as I'm using the exact same build, until I realized that I am using it on a different platform, which lead to me finding this issue here.

**Comment by ytmimi** [comment] 2023-11-26 16:55
I just checked and I can't reproduced the issue when using the `nightly-2023-11-26-aarch64-apple-darwin` toolchain. @xfbs when you have a moment could you confirm whether you're still seeing issues with `nightly-2023-11-26`.

**Comment by xfbs** [comment] 2023-11-26 19:59
Can confirm this is resolved. I just updated with `rustup` to the latest nightly:

```
nightly-aarch64-unknown-linux-gnu updated - rustc 1.76.0-nightly (f5dc2653f 2023-11-25)
```

This is the rustfmt version I have now:

```
rustfmt 1.7.0-nightly (f5dc2653 2023-11-25)
```

And formatting my (correctly formatted) code from my repository no longer crates a diff.

**Comment by calebcartwright** [comment] 2023-11-29 21:07
Agreed this is sorted so going to close. Thanks for the reports, feedback, and assistance troubleshooting & resolving.

I am curious about the absence of preemptive test failures, but that's something for us to dig into separately moving forward

**Closed by calebcartwright** 2023-11-29 21:07 UTC
