### ISSUE TITLE
Stable rustfmt panics on nested tuple access

### ISSUE THREAD

**Issue by khoek** [rust-lang/rustfmt#4511] opened 2020-11-04 13:42 UTC
**Describe the bug**

The expression `a.0.1;` on a line in the body of a function panics rustfmt.

**To Reproduce**

Try to format:

````rust
fn main() {
    a.0.1;
}
````

**Expected behavior**

No crash, since this is well formed rust code (and would compile if we cluttered the reproducer with a definition of `a`).

**Meta**

- rustfmt version: `rustfmt 1.4.20-stable (48f6c32 2020-08-09)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment] 2020-11-04 15:29
Duplicate of #4355, resolved in the upcoming 1.4.23 release

**Closed by calebcartwright** 2020-11-04 15:29 UTC
Labels: bug, duplicate
