### ISSUE TITLE
brace_style doesn’t respect PreferSameLine

### ISSUE THREAD

**Issue by phaazon** [rust-lang/rustfmt#3299] opened 2019-01-27 23:57 UTC
I have the behavior of `SameLineWhere` while I have this in my `rustfmt.toml`:

```
brace_style = "PreferSameLine"
```

[File and project here](https://github.com/phaazon/luminance-rs/blob/e75637e34c4cfb1d1667a6e0884105d67c74b4ea/rustfmt.toml#L16)

**Comment by scampi** [comment] 2019-01-28 09:22
Can you point to a part of the code where you have the unexpected behaviour ?

**Comment by phaazon** [comment] 2019-01-28 10:46
Sure, [here, for instance](https://github.com/phaazon/luminance-rs/blob/e75637e34c4cfb1d1667a6e0884105d67c74b4ea/luminance/examples/04-shader-uniforms/src/main.rs#L81).

**Comment by calebcartwright** [comment] 2022-05-13 00:29
`brace_style` as currently intended is only applicable in item contexts. We'd started going down the path of extending it to apply in certain expression contexts, but after some reflection think we need to take a different path in the config option surface in order to provide sufficient control and flexibility.

Closing this accordingly, but feel free to subscribe to #3376 for updates on when/how we'll expose brace style control in some of these expression contexts

**Closed by calebcartwright** 2022-05-13 00:29 UTC
Labels: only-with-option
