### ISSUE TITLE
`error[internal]: left behind trailing whitespace`

### ISSUE THREAD

**Issue by dotjpg3141** [rust-lang/rustfmt#5055] opened 2021-10-30 09:06 UTC
I'm getting the error:

```
error[internal]: left behind trailing whitespace
 --> xy\src\main.rs:6:6:20
  |
6 |     let _x = Blob {
  |                    ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

with the following code:

```
struct Blob {
    data: u32
}



fn main()  {
    let _x = Blob { 
         data:   Some(1).expect("missing one of fields 'xxx', 'xxxxxx', 'xxxxxxxxx', 'xxxxxxxxxx', 'xxxxxxxx', 'xxxxxx'")
         };
}
```

Version: `rustfmt 1.4.38-nightly (c390d69a 2021-10-28)`

Removing the trailing whitespace after `let _x = Blob {` doesn't emit the error, but the code still isn't formated propertly. It seems the bug is sensitive to the length of the string.

**Comment by calebcartwright** [comment] 2021-10-30 14:47
Thanks for sharing, but going to close as a duplicate of #3863. The issue is indeed the length of your string, which is impossible to fit within the `max_width` constraints. To address, you'll want to either:

* define the string in a local, reference the local in the struct
* manually break the string into multiple lines so that it's possible to fit the entire string within the max_width limit
* enable the `format_strings` configuration option to give rustfmt permission to attempt to break the long string lit on your behalf

**Closed by calebcartwright** 2021-10-30 14:47 UTC

**Comment by dotjpg3141** [comment] 2021-10-30 15:10
Thanks
