### ISSUE TITLE
"error[internal]: left behind trailing whitespace" with match arm followed by comment

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustfmt#5077] opened 2021-11-13 04:44 UTC
### Code

```rust
fn foo() {
    match 123 {
        123 => 
            true
        ,
        // a comment
        _ => true,
    }
}
```

### Error

```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:3:3:15
  |
3 |         123 => 
  |               ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

### Version

```
rustfmt 1.4.38-nightly (2021-11-12 e90c5fb)
```

**Comment by calebcartwright** [comment] 2021-11-13 16:44
Closing as a duplicate of #4917 but lmk if you think there's something different going on

**Closed by calebcartwright** 2021-11-13 16:44 UTC
