### ISSUE TITLE
#[doc = concat!(...)] causes indentation every time rustfmt runs.

### ISSUE THREAD

**Issue by Qix-** [rust-lang/rustfmt#6126] opened 2024-03-26 20:17 UTC
I found some non-deterministic indentation in rustfmt today, whereby the following code snippet has the `concat!()` contents indented every single time it runs:

```rust
macro_rules! define_descriptor {
    ($doc:literal) => {
        pub struct Foo;
        impl Foo {
            #[doc = concat!(
                "Foo ", $doc, " bar."
            )]
            pub fn new() -> Self {
                Self
            }
        }
    };
}
```

Playground link here (reproducible): https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=40b0571d9b37dd9c4f250debff0a0d97

https://github.com/rust-lang/rustfmt/assets/885648/3456a86f-ddd1-4621-b760-759032eeb84c

---

Workaround is to move the `concat!` call into its own macro and then invoke the macro, like so:

```rust
macro_rules! doc_concat {
    ($doc:literal) => (concat!("Foo ", $doc, " bar."));
}

// later...

#[doc = doc_concat!($doc)]
```

**Comment by ytmimi** [comment] 2024-03-26 21:26
@Qix- Thank you for the report! The video was also very helpful. Right now I think this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5974

**Closed by ytmimi** 2024-03-26 21:26 UTC
