### ISSUE TITLE
Rustfmt removes comments in `use`s

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#3984] opened 2019-12-26 19:13 UTC
Rustfmt sometimes removes comments in uses with `{}`. For example (diffs from `cargo fmt -- --check`):
```diff
-use a::{item /* comment */};
+use a::item;
```
With `merge_imports = true`:
```diff
-use a::{
-    x,
-    // comment
-    item,
-};
+use a::{item, x};
```

**Comment by WaffleLapkin** [comment] 2019-12-26 19:19
Another interesting case:
```diff
-use b::{
-    x,
-    y,
-};
-use a::item; // comment
+use a::item;
+use b::{x, y}; // comment
```
`// comment` moved to other `use`

**Comment by WaffleLapkin** [comment] 2019-12-26 19:21
I've just found new variant:
```diff
-use b::{
-    x,
-    y,
-};
-use a::item /* comment */;
+use a::item;
+use b::{x, y};
```
Sounds like there are some problems with formatting comments in uses :D

**Comment by WaffleLapkin** [comment] 2019-12-26 19:37
Should I open a separate issue for this?

Wrong indent:
```diff
-use a::item; // really long comment (with `use` exactly 100 characters) ____________________________
+use a::item; /* really long comment (with `use` exactly 100 characters)
+               * ____________________________ */
 use b::{x, y};
```

**Comment by calebcartwright** [comment] 2019-12-26 22:50
@WaffleLapkin - what version of rustfmt are you using, and do you have a rustfmt config file/are you passing any config options via the cli?

**Comment by WaffleLapkin** [comment] 2019-12-26 23:43
@calebcartwright version:
```
% cargo +nightly fmt -- --version
rustfmt 1.4.11-nightly (1838235 2019-12-03)
```
I don't have rustfmt config nor I pass config options via the cli, exept second example where I have rustfmt.toml with following line:
```
merge_imports = true
```

**Comment by calebcartwright** [comment] 2019-12-26 23:44
Thanks! I can't reproduce your last example with the latest version of rustfmt on the master branch (which contains a lot of unreleased changes), but the others are still all reproducible

**Comment by MarcoIeni** [comment] 2020-02-22 15:46
I worked on this with [wise86-android](https://github.com/wise86-android).

We noticed that when the `use` is in the form `use a::{...}`, comments are handled correctly.
However, there are problems when there are not curly braces.
For example, `use a::item /* comment */;` is converted to `use a::item; // comment */;`, while what we would expect is something like: `use a::item; // comment`.

We see that the comment transformation is done here:
https://github.com/rust-lang/rustfmt/blob/9124dd88d6ef14d0ae77dc52ff5e9598f24a75a0/rustfmt-core/rustfmt-lib/src/comment.rs#L247-L254

If we give `/* comment1 */;` as `orig` param, then `// comment1 */;` is returned.

**Comment by sharnoff** [comment] 2020-09-11 17:36
@MarcoIeni @calebcartwright It seems like the case fixed by PR #3999 does not currently work. I was a little surprised by this - given that there's a test case [here](https://github.com/rust-lang/rustfmt/blob/master/tests/target/imports.rs#L33), but (I would assume) the playground does not lie. The following example ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=138fbe462fd3e64a73cf28de2533aa6f)) exhibits the old behavior:

```diff
-use std::foo::{/* it's a comment! */ bar /* and another */};
+use std::foo::bar;

// filler

-use std::foo::{/* it's a comment! */ bar};
+use std::foo::bar;

// filler

-use std::foo::{bar /* and another */};
+use std::foo::bar;
```

I noticed this occuring with rustfmt 1.4.18-stable, and (per the playground) it seems to still be there in 1.14.21-nightly (2020-09-04 01f2ead). As a side note, it still occurs with just `std::{ ... }` -- there's no need for two leading path segments for this to happen.

**Comment by calebcartwright** [comment] 2020-09-11 18:06
@sharnoff - note that the referenced PR was merged to the master branch, so it's included in the unreleased rustfmt v2.0, but not in the 1.x versions you referenced

**Comment by sharnoff** [comment] 2020-09-11 18:08
@calebcartwright Ah, that makes a bunch of sense! Thanks :)

**Comment by ytmimi** [comment] 2022-07-21 04:01
> Another interesting case:
> 
> ```diff
> -use b::{
> -    x,
> -    y,
> -};
> -use a::item; // comment
> +use a::item;
> +use b::{x, y}; // comment
> ```
> 
> `// comment` moved to other `use`

This issue is a duplicate of #3720

**Comment by ytmimi** [comment] 2023-08-31 04:33
Now that https://github.com/rust-lang/rustfmt/pull/5853 is merged comments within uses are preserved. As noted, this example https://github.com/rust-lang/rustfmt/issues/3984#issuecomment-1191011816 is a duplicate of another issue, so I'm going to close this now.

**Closed by ytmimi** 2023-08-31 04:33 UTC
Labels: bug, a-comments, a-imports
