### ISSUE TITLE
Strangle Result<> break on long phrases

### ISSUE THREAD

**Issue by sanboxrunner** [rust-lang/rustfmt#3797] opened 2019-09-14 19:29 UTC
Hiya:

We get a strangle line break on a long Result phrase:

```
    fn create_pipeline(
        device: &mut <I::Backend as Backend>::Device,
        extent: Extent2D,
        render_pass: &<I::Backend as Backend>::RenderPass,
    ) -> Result<
        (
            Vec<<I::Backend as Backend>::DescriptorSetLayout>,
            <I::Backend as Backend>::DescriptorPool,
            <I::Backend as Backend>::PipelineLayout,
            <I::Backend as Backend>::GraphicsPipeline,
        ),
        &'static str,
    > {
```
Not how the final line is `> {`. Seems like the `>` should be on the second to final line, and then we should just have the bare `{` on that line.

I can confirm this is how rustfmt ships by default (ie -- no options on, this still happens).

No big deal, just thought I'd mention it

**Comment by topecongiro** [comment] 2019-09-15 13:28
Thank you for filing an issue. This is actually expected and working as intended. rustfmt puts the opening `{` on the same line if the line only consists of the closing `>`.

**Closed by topecongiro** 2019-09-15 13:28 UTC
