### ISSUE TITLE
Comments in match arms with multiple patterns breaks formatting for whole match block

### ISSUE THREAD

**Issue by TomPridham** [rust-lang/rustfmt#5492] opened 2022-08-09 19:47 UTC
minimal repro: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c84aad243b9a68dd7b0eed3ee0c01dea

Adding a comment in between patterns in a match arm breaks formatting for the whole match block. I discovered this when i commented out some arms that clippy said were unused

**Comment by calebcartwright** [comment] 2022-08-09 20:10
Thanks for sharing but going to close as a duplicate of #4119

**Closed by calebcartwright** 2022-08-09 20:10 UTC
