### ISSUE TITLE
rustfmt failed: left behind trailing whitespace 

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#6321] opened 2024-09-10 08:03 UTC
Rustfmt fails to format this file:
```rust
use std::mem;

// We have three fields to avoid the ScalarPair optimization.
#[allow(unused)]
enum E {
    None,
    Some(&'static (), &'static (), usize),
}

fn main() { unsafe {
    let mut p: mem::MaybeUninit<E> = mem::MaybeUninit::zeroed();
    // The copy when `E` is returned from `transmute` should destroy padding
    // (even when we use `write_unaligned`, which under the hood uses an untyped copy).
    p.as_mut_ptr().write_unaligned(mem::transmute((0usize, 0usize, 0usize)));
    // This is a `None`, so everything but the discriminant is padding.
    assert!(matches!(*p.as_ptr(), E::None));

    // Turns out the discriminant is (currently) stored
    // in the 2nd pointer, so the first half is padding.
    let c = &p as *const _ as *const u8;
    let _val = *c.add(0); // Get a padding byte.
    //~^ERROR: uninitialized
} }
```
with these settings:
```
version = "Two"
```
The error is:
```
error[internal]: left behind trailing whitespace
  --> /home/r/src/rust/miri/tests/fail/uninit/padding-enum.rs:23:23:1
   |
23 |         
   | ^^^^^^^^
   |
```
If I comment out the "version" setting, formatting works fine.

I saw a bunch of other issues with similar errors but it is not clear to me which one of them this could be a duplicate of.

**Comment by RalfJung** [comment] 2024-09-10 08:05
Strangely, even the "properly formatted" version of this file causes the same error:
```
use std::mem;

// We have three fields to avoid the ScalarPair optimization.
#[allow(unused)]
enum E {
    None,
    Some(&'static (), &'static (), usize),
}

fn main() {
    unsafe {
        let mut p: mem::MaybeUninit<E> = mem::MaybeUninit::zeroed();
        // The copy when `E` is returned from `transmute` should destroy padding
        // (even when we use `write_unaligned`, which under the hood uses an untyped copy).
        p.as_mut_ptr().write_unaligned(mem::transmute((0usize, 0usize, 0usize)));
        // This is a `None`, so everything but the discriminant is padding.
        assert!(matches!(*p.as_ptr(), E::None));

        // Turns out the discriminant is (currently) stored
        // in the 2nd pointer, so the first half is padding.
        let c = &p as *const _ as *const u8;
        let _val = *c.add(0); // Get a padding byte.        
        //~^ERROR: uninitialized
    }
}
```
It always adds an empty line with 8 spaces before the `//~^ERROR: uninitialized` comment.

**Comment by matthiaskrgr** [comment] 2024-09-10 17:47
ah :laughing: I also just found this, looking at new rustfmt failures.

with 
```toml
version = "Two"
merge_derives = false
imports_granularity = "Module"

```


```rust
use std::mem;

#[allow(unused)]
#[repr(C)]
union U {
    field: (u8, u16),
}

fn main() {
    unsafe {
        let p: U = mem::transmute(0u32); // The copy when `U` is returned from `transmute` should destroy padding.
        let c = &p as *const _ as *const [u8; 4];
        let _val = *c; // Read the entire thing, definitely contains the padding byte.
        
        //~^ERROR: uninitialized
    }
}
```

fails to fmt

```
error[internal]: left behind trailing whitespace
  --> /tmp/im/padding-union.rs:14:14:1
   |
14 |
   | ^^^^^^^^
   |
```

**Comment by ytmimi** [comment] 2024-09-10 18:29
Duplicate of https://github.com/rust-lang/rustfmt/issues/6157 and https://github.com/rust-lang/rustfmt/issues/5391

**Closed by ytmimi** 2024-09-10 18:29 UTC
