### ISSUE TITLE
Bad formatting of let-else in macro

### ISSUE THREAD

**Issue by est31** [rust-lang/rustfmt#5213] opened 2022-02-02 15:34 UTC
The following macro makes rustfmt as of nightly do bad formatting:
```Rust
macro_rules! unwrap_some {
    ($name:ident) => {
        let Some($name) = $name else {
            panic!();
        };
    };
}
```
If you run it once, it moves the panic and the `};` one indentation level to the right:
```Rust
macro_rules! unwrap_some {
    ($id:ident) => {
        let Some($id) = $id else {
                    panic!();
                };
    };
}
```
This process is continued, until you reach this fixpoint:
```Rust
macro_rules! unwrap_some {
    ($id:ident) => {
        let Some($id) = $id else {
                                                                                    panic!();
                                                                                };
    };
}
```
I file this bug not because the output is *bad* style (it is, but that is the purpose of #4914 to figure out), but because the rustfmt output from running it once is not a fixpoint.

**Comment by ytmimi** [comment] 2022-02-02 16:54
Thanks for submitting this issue!

It's very likely that this is related to #5062 and #5044

**Comment by ytmimi** [comment] 2022-07-27 02:18
Going to close this as I believe this is a duplicate of the issues linked above

**Closed by ytmimi** 2022-07-27 02:18 UTC
Labels: bug, duplicate, a-macros
