### ISSUE TITLE
cargo-fmt cleans up /// cargo-doc-tables

### ISSUE THREAD

**Issue by meltyness** [rust-lang/rustfmt#4891] opened 2021-07-05 23:53 UTC
Describe the problem you are trying to solve
cargo-fmt leaves doc tables with whatever bizarre spacing was typed in.

Describe the solution you'd like
max and center contents within the typed table when cargo-fmt is run

Notes
cargo-doc supports tables: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#tables

**Comment by calebcartwright** [comment] 2021-07-06 02:28
Could you please clarify what you are reporting and/or requesting? Are you requesting new rustfmt behavior to have it reformat markdown-specific content like tables within code docs?

If so I have to say that feels quite outside the scope of rustfmt.

**Comment by meltyness** [comment] 2021-07-06 02:38
I believe you have understood my request.

**Comment by calebcartwright** [comment] 2021-07-06 02:40
> I believe you have understood my request.

To repeat the opening from my last comment: please clarify

**Comment by meltyness** [comment] 2021-07-06 02:48
> > I believe you have understood my request.
> 
> To repeat the opening from my last comment: please clarify

Rustdoc has a table markdown that I provided the link to the docs for. Rustdoc can parse it within some tolerance even if the spacing is off and turn it into and HTML table. It was unexpected to me that cargo fmt didn't fix the spacing of each column to the maximum width (+padding) of any inferior cells.

No comment here on whether or not the funny-looking stuff you can put into doc comments is a result of rustfmt functionality or the goofy syntax rustdoc used for this feature (I think it's inherited)

**Comment by calebcartwright** [comment] 2021-07-06 02:57
> It was unexpected to me that cargo fmt didn't fix the spacing of each column to the maximum width (+padding) of any inferior cells.

Again, as I asked previously, are you asking for an enhancement to rustfmt to have it apply formatting rules to markdown tables in doc comments? AFAICT you've stated that you're surprised rustfmt doesn't do this already, but you also implied that you weren't asking for us to extend rustfmt to support formatting markdown tables, hence the confusion.

rustfmt has some support for formatting snippets of rust code within doc comments, but rustfmt otherwise does not modify the contents within comments, markdown or otherwise. This is expected behavior. Formatting markdown-specific constructs like tables, lists, etc. is really outside the scope of rustfmt.

**Comment by meltyness** [comment] 2021-07-07 02:19
> Again, as I asked previously, are you asking for an enhancement to rustfmt to have it apply formatting rules to markdown tables in doc comments?
>  This is expected behavior. Formatting markdown-specific constructs like tables, lists, etc. is really outside the scope of rustfmt.

Yes effectively an enhancement, but I have no permissions to flag this issue as such.

**Comment by calebcartwright** [comment] 2021-07-18 04:36
> Yes effectively an enhancement, but I have no permissions to flag this issue as such.

Thank you for clarifying! I appreciate your desire for markdown formatting, but that's not something we're going to do in rustfmt so I'm going to close this issue.

It's still a bit unclear to me whether you actually encountered any issues with rustdoc being unable to handle your tables (due to spacing or some other issue). However, if you encountered some issue with rustdoc not being able to handle a valid markdown table in your project then I'd encourage you to reach out to the rustdoc team with a reproducible example so they can take a look.

**Closed by calebcartwright** 2021-07-18 04:36 UTC
