### ISSUE TITLE
Nesting beyond max width makes rustfmt do nothing

### ISSUE THREAD

**Issue by soerenmeier** [rust-lang/rustfmt#4878] opened 2021-06-22 16:11 UTC
When expanding `tokio::select` with `cargo expand`, rustfmt gives up formatting. The whole block stays on one line.
Full expanded code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d330c86ac24942de0c5e64efda0a262e).
After deleting some stuff i found out that it probably is caused by nesting going nearly beyond the max width.
The shortest example i came up with: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ed6ef08e81e6045243f2df25fe24a78b).

**Comment by soerenmeier** [comment] 2021-06-22 16:18
Removing the following code in the first playground
```rust
{ :: core :: panicking :: panic_fmt (:: core :: fmt :: Arguments :: new_v1 (& ["internal error: entered unreachable code: "] , & match (& "reaching this means there probably is an off by one bug" ,) { (arg0 ,) => [:: core :: fmt :: ArgumentV1 :: new (arg0 , :: core :: fmt :: Display :: fmt)] , })) }
```
allows formatting to happen.

**Comment by calebcartwright** [comment] 2021-06-23 01:05
Closing as duplicate of various other issues, all being tracked in #3863 now.

You're hypothesis is indeed generally correct. It was decided long ago to have rustfmt bail in cases where it's impossible to reformat the code to fit within the max_width. There's not really anything to be done about this in the interim since it's not handwritten code, but you increasing `max_width` to a sufficiently high point will provide something that's formatted, and you may occasionally get lucky by enabling `format_strings`

**Closed by calebcartwright** 2021-06-23 01:05 UTC

**Comment by soerenmeier** [comment] 2021-06-23 01:19
Thanks for the info, sorry for the duplicate.
Would it work to make two passes, first with a big max_width value and a second one with the default value?
So almost all lines would be formatted correctly.
