### ISSUE TITLE
Rustfmt breaks macros due to changes

### ISSUE THREAD

**Issue by alexkazik** [rust-lang/rustfmt#4631] opened 2021-01-07 21:34 UTC
**Describe the bug**

The contents of macros are changed.

Input:
```rust
test_macro!(pub fn test_fn(); "foobar");
```

Output:
```rust
test_macro!(fn test_fn();, "foobar");
```

**Expected behavior**

Unchanged, or "formatted" but not keywords/symbols removed/added.

**Meta**

- rustfmt version: rustfmt 1.4.30-nightly (acd94866 2020-12-20)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: cargo fmt --all

**Comment by Ekleog** [comment] 2021-01-08 17:50
I have just hit a similar issue with `rustfmt 1.4.29-nightly (70ce182 2020-12-04)` (installed from the nixpkgs-mozilla overlay, that grabs from the rustup repository):
```rust
fn main() {
    quote!(type Foo: Bar;);
}
```
becomes
```rust
fn main() {
    quote!(
        type Foo: Bar = impl Bar;
    );
}
```

(where the result is not even valid stable rust code)

**Comment by zyctree** [comment] 2021-01-15 04:37
the same,

could use `{}` like `test_macro! { pub fn test_fn(); "foobar" };` to avoid this change

**Comment by alexkazik** [comment] 2021-01-20 16:34
Thanks for the tip with `{}`.

**Comment by qiujiangkun** [comment] 2021-07-02 06:44
`debug!(meta ?= meta, "Ready to subscribe");` is being formatted as `debug!(meta? = meta, "Ready to subscribe");` and thus breaking `tracing-log`

**Comment by ytmimi** [comment] 2022-07-26 15:23
closing this as a duplicate of #4375

**Closed by ytmimi** 2022-07-26 15:23 UTC
Labels: bug, duplicate, a-macros
