### ISSUE TITLE
An extra `}` is added if there's a comment with an odd number of `"`

### ISSUE THREAD

**Issue by wtfsck** [rust-lang/rustfmt#4806] opened 2021-04-19 19:42 UTC
**Describe the bug**

An extra `}` is added when the following code is formatted

**To Reproduce**

Format this

```rust
enum X {
    A,
    /*"*/
}
```

This is the result:

```rust
enum X {
    A,
    /*"*/
    }
}
```

**Expected behavior**

Input does not change or at most the comment is moved but no extra `}` should be added

**Meta**

- rustfmt version: rustfmt 1.4.36-stable (7de6968e 2021-02-07)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`

**Comment by calebcartwright** [comment] 2021-04-21 02:52
Thank you for the report but going to close as a duplicate of a few previous issues (e.g. #4744)

**Closed by calebcartwright** 2021-04-21 02:52 UTC
Labels: bug
