### ISSUE TITLE
Incorrect indentation on multi-line single generic bound

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4689] opened 2021-02-07 23:45 UTC
We have a bug in the generic bounds formatting code that does not properly account for the case where there's a single bound that itself has to be formatted across multiple lines.

**Input**

```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
        'tcx,
        Error = fmt::Error,
        Path = Self,
        Region = Self,
        Type = Self,
        DynExistential = Self,
        Const = Self,
    >
    {
         //
    }
```

**Output**

```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
    'tcx,
    Error = fmt::Error,
    Path = Self,
    Region = Self,
    Type = Self,
    DynExistential = Self,
    Const = Self,
>
{
    //
}

```

**Expected output**
The same indentation as if there were 2+ bounds
```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
        'tcx,
        Error = fmt::Error,
        Path = Self,
        Region = Self,
        Type = Self,
        DynExistential = Self,
        Const = Self,
    >
{
    //
}

// what it would look like with an extra bound:
pub trait PrettyPrinter<'tcx>:
    Printer<
        'tcx,
        Error = fmt::Error,
        Path = Self,
        Region = Self,
        Type = Self,
        DynExistential = Self,
        Const = Self,
    > + fmt::Write
{
    //
}
```

**Meta**

- rustfmt version: all (latest 1.x version as of 1.4.36 and 2.0-rc on master branch
- From where did you install rustfmt?: any

The problematic code can be found here:

https://github.com/rust-lang/rustfmt/blob/d84a32caa2249f476d9af50cbe8cb586c415c6b1/src/formatting/types.rs#L1000-L1007

The issue is an incorrect assumption that if there's just one bound, or multiple bounds but which were able to be formatted on a single line without exceeding the max width limit, then we'll be formatting the bound(s) on a single line and there's no need to reformat the bounds with the proper indentation. However, as noted above this fails to catch the multi-lined single bound case so this check will need to be updated to also account for that case.

**Comment by davidBar-On** [comment] 2021-02-23 08:07
Based on the guidelines in the description I tried the "naive" change of just deleting the `&& items.len() > 1` condition from the [if statement](https://github.com/rust-lang/rustfmt/blob/d84a32caa2249f476d9af50cbe8cb586c415c6b1/src/formatting/types.rs#L1001), and running the tests with this change.  The tests failed on two types of errors, where at least one of them makes it unclear to me what should be changed.

**1st test error type: when the bound name is in the same line of the preceding code**.  E.g:
https://github.com/rust-lang/rustfmt/blob/257311c304fddf578d8d4041ddf129533390b8ef/tests/target/issue-3651.rs#L1-L7
However, when `fmt::Write` bound is added, indentation is changed to:
```rust
fn f() -> Box<
    dyn FnMut() -> Thing<
            WithType = LongItemName,
            Error = LONGLONGLONGLONGLONGONGEvenLongerErrorNameLongerLonger,
        > + fmt::Write,
> {
}
```
With the code change, **both** cases are indented the same.  **Should indentation be the same with or without the `fmt::Write`?**  Except for backward compatibility, it doesn't seem right that adding the second bound impacts indentation of the first bound.

**2nd test error type: function in `where` clause**.  E.g.:
https://github.com/rust-lang/rustfmt/blob/257311c304fddf578d8d4041ddf129533390b8ef/tests/target/issue-3508.rs#L1-L7
With the change, indentation is changed to:
```rust
fn foo<F>(foo2: F)
where
    F: Fn(
            // this comment is deleted
        )
{
}
```
I assume that in this case the **extra indentation is an error**, and that the code change should **not** change the current indentation.

Note that also in the case ` + fmt::Write` can be added after the `Fn` closing `)`, and also in this case the indentation is changed (with the original code).  I am not sure if there should have been a compilation error in this case, or the ability to add ` + fmt::Write` in this case is a rust feature that I don't understand.

**Comment by calebcartwright** [comment] 2021-02-24 02:50
So there's two things to this, the existing behavior with extra indentation that's added when adding a second bound (however odd that may be in those snippets :smile:) is a separate bug.

However, that doesn't change the fact that the naive change is not viable, as that introduces a new bug. A different approach will be needed to address the bug with the trait bounds described in the issue description, though if the additional bug you've discovered can be addressed at the same time that'd be great too!

**Comment by davidBar-On** [comment] 2022-06-22 06:58
@[jyn514](https://github.com/jyn514),
> I think this might the same issue, but happy to open a new issue if not - rustfmt removes all indentation from the where clause here, .....

I checked and this issue is **not** fixed by the PR.  I assume it is better to open a new issue then try to enhance the PR to also fix this problem.

**Comment by davidBar-On** [comment] 2022-06-23 19:24
> I think this might the same issue, but happy to open a new issue if not ...

@[jyn514](https://github.com/jyn514), the issue is not resolved by this PR.  I evaluated it to make sure it is not related and I have some observations.  If you will open a new issues I will discuss there what I found.

**Comment by ytmimi** [comment] 2022-08-09 13:55
closing since #5390 was merged

**Closed by ytmimi** 2022-08-09 13:55 UTC
Labels: good first issue, poor-formatting, help wanted, 1x-backport:pending
