### ISSUE TITLE
A long string inside a closure makes the entire closure unable to be formatted

### ISSUE THREAD

**Issue by maboroshinokiseki** [rust-lang/rustfmt#5606] opened 2022-11-17 08:33 UTC
A simple example here, code inside the closure can't be formatted.

    let num = Some(123);
    let num = num.unwrap_or_else(|| {
        let a="This is a loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong string";

        123
    });

**Comment by ytmimi** [comment] 2022-11-17 14:16
Thanks for reaching out! Because of the call to `.unwrap_or_else` this is a chain, and therefore a duplicate of #3863

**Closed by ytmimi** 2022-11-17 14:16 UTC
Labels: duplicate
