### ISSUE TITLE
Rustfmt discards newlines between `#[doc]` attributes and other attributes

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustfmt#4604] opened 2020-12-19 17:51 UTC
**Input**

```rust
//! Some docs here
#![cfg_attr(bootstrap, doc = "xxx")]

#![cfg_attr(debug_assertions, stable(feature = "rust1", since = "1.0.0"))]
```

**Output**

```rust
//! Some docs here
#![cfg_attr(bootstrap, doc = "xxx")]
#![cfg_attr(debug_assertions, stable(feature = "rust1", since = "1.0.0"))]
```

**Expected output**

```rust
//! Some docs here
#![cfg_attr(bootstrap, doc = "xxx")]

#![cfg_attr(debug_assertions, stable(feature = "rust1", since = "1.0.0"))]
```

I see here *why* rustfmt did this - it thinks that all cfg_attr attributes should be grouped together. But this doesn't make sense in the semantic context of the program: `cfg_attr(doc)` is a doc-comment and should be grouped with other doc-comments. See https://github.com/rust-lang/rust/pull/80181#issuecomment-748487592 for a more realistic example.

Is there a way to disable this behavior?

**Meta**

- rustfmt version: rustfmt 1.4.24-stable (eb894d5 2020-11-05)
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment] 2020-12-19 21:39
Going to close as a duplicate of #4082. The context here around doc comments is helpful as additional reference cases/motivation, but fundamentally relates to the same lack of support (default or opt-in) for newlines between attrs

> Is there a way to disable this behavior?

Not categorically, but `#[rustfmt::skip]` and/or `#[rustfmt::skip::attributes(cfg_attr)]` _could_ potentially be of use

**Closed by calebcartwright** 2020-12-19 21:39 UTC
Labels: duplicate, poor-formatting
