### ISSUE TITLE
Rustfmt adds new indentation every time it formats `let else` in macro declaration

### ISSUE THREAD

**Issue by PoignardAzur** [rust-lang/rustfmt#5503] opened 2022-08-15 15:38 UTC
Example code:

```rust
// The indentation stays the same, as expected
fn foobar() {
    let x = y else {
        panic!();
    };
}

// The indentation is increased every time you run `cargo fmt`
macro_rules! foobar {
    () => {
        let pat = expr else {
                    panic!();
                };
    };
}
```

**Comment by ytmimi** [comment] 2022-08-15 16:35
Thanks for reaching out. I think the underlying issue is that rustfmt doesn't currently format let else expressions because the rules for formatting them have not yet been finalized via an RFC in [fmt-rfcs repo](https://github.com/rust-dev-tools/fmt-rfcs).

Related issues are #5489, #5044, and #4609 which also deal with cases where extra indentation is added in macro definitions when rustfmt fails to format the macro body.

**Comment by est31** [comment] 2022-09-23 02:35
This is a precise dupe of #5213 , which got closed as dupe of the issues linked above.

**Comment by est31** [comment] 2022-09-23 02:46
It's quite interesting that this is the second time that this specific let else case was hit. Maybe many people wrote macros in that fashion and now want to replace them with `let else`?

**Comment by PoignardAzur** [comment] 2022-09-23 08:38
I don't know about the other bug, but I was writing [`assert_let`](https://crates.io/crates/assert_let_bind)

**Comment by ytmimi** [comment] 2022-09-26 15:25
Going to close this as a duplicate of https://github.com/rust-lang/rustfmt/issues/5213

As mentioned above, the underlying issue here is that rustfmt doesn't currently format `let else`. Rules need to be added to the Rust Style Guide before an implementation can be added to rustfmt. If you want to stay informed about the style discussion you can subscribe to https://github.com/rust-dev-tools/fmt-rfcs/pull/165, and to keep up with implementation progress you can subscribe to #4914.

If the macro indentation behavior continues after `let else` formatting is implemented, then we can reopen this issue and investigate further.

**Closed by ytmimi** 2022-09-26 15:25 UTC
Labels: bug, a-macros
