### ISSUE TITLE
[Feature Request] For Procedual Macros

### ISSUE THREAD

**Issue by BlackAsLight** [rust-lang/rustfmt#5777] opened 2023-06-05 01:41 UTC
Hello, at the moment these types of macros `view! { cx, <Body /> }` don't have any formatting by rustfmt, which leads other people to make their own fmt cli-tools for their specific macros. This in my opinion can be quite annoying, because not only does every library that makes use of these macros not come with their own fmt cli-tool, the ones that do can be buggy or lack the features to match the complexity that rustfmt offers. 

I understand why rustfmt doesn't format the contents of these types of macros, as the content could take many forms, so 
what I'd like to suggest is that rustfmt provide a way for the libraries to describe how their macros should be formatted by rustfmt. I don't know what type of technical details one would need to do to accomplish this, but I'd love to hear back your thoughts.

**Comment by calebcartwright** [comment] 2023-06-05 01:56
Thank you but I'm going to close as a duplicate of #8. There's loads of discussion in there, including your high level proposal and the technical blockers that prevent that from being a viable option.

**Closed by calebcartwright** 2023-06-05 01:56 UTC
