### ISSUE TITLE
"left behind trailing whitespace" when line appears before long, unbreakable line

### ISSUE THREAD

**Issue by talbenari1** [rust-lang/rustfmt#5175] opened 2022-01-19 05:15 UTC
This bug seems to be weirdly sensitive to the way the code is structured, but I've managed to whittle down an example to the following (note the trailing whitespace in the empty `if` block):

```rust
fn foo() {
    f.x({
        if foo {
 
        } else {
            my_macro!(ReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongStructName)
        }
    })
}
```

When running on the Rust Playground ([here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=eb9f94c540d29b32399f105ea391ec4c)), the error looks like this:

```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:4:4:1
  |
4 |  
  | ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by calebcartwright** [comment] 2022-01-19 16:20
Thanks for reaching out but this is a duplicate of #3863

**Closed by calebcartwright** 2022-01-19 16:20 UTC
Labels: duplicate
