### ISSUE TITLE
There is (no) lint for keeping spaces between functions

### ISSUE THREAD

**Issue by sagudev** [rust-lang/rustfmt#4866] opened 2021-06-12 06:20 UTC
Look at the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2ba1e36c23a274040afaa0e7f7342b55) and try `rustfmt`. I expect one blank lines between functions as that's how [most](https://github.com/rust-lang/futures-rs/blob/master/futures-channel/src/lock.rs) [code](https://github.com/servo/servo/blob/master/components/script/script_runtime.rs) [is](https://github.com/rust-lang/rust/blob/master/library/std/src/io/stdio.rs#L157) formatted in rust as far as I know. I didn't find it as existing lint but it would be very similar to `blank_lines_lower_bound` but only for outside blocks.

What I would expect from lint to do:
Before:
```rust
mod my_mod {
    fn private_function() {
        println!("called `my_mod::private_function()`");
    }
    pub fn function() {
        println!("called `my_mod::function()`");
    }
}
mod my_mod2 {
    fn private_function() {
        println!("called `my_mod::private_function()`");
    }
    pub fn function() {
        println!("called `my_mod::function()`");
    }
}
fn function() {
    println!("called `function()` 1");
    println!("called `function()` 2");
    println!("called `function()` 3");
}
fn function2() {
    println!("called `function2()` 1");
    println!("called `function2()` 2");
    println!("called `function2()` 3");
}
```
After:
```rust
mod my_mod {
    fn private_function() {
        println!("called `my_mod::private_function()`");
    }

    pub fn function() {
        println!("called `my_mod::function()`");
    }
}

mod my_mod2 {
    fn private_function() {
        println!("called `my_mod::private_function()`");
    }

    pub fn function() {
        println!("called `my_mod::function()`");
    }
}

fn function() {
    println!("called `function()` 1");
    println!("called `function()` 2");
    println!("called `function()` 3");
}

fn function2() {
    println!("called `function2()` 1");
    println!("called `function2()` 2");
    println!("called `function2()` 3");
}
```

**Comment by calebcartwright** [comment] 2021-06-21 03:23
Thanks for reaching out, but this is actually a duplicate of bugs (e.g. #2954) with `blank_lines_lower_bound` where newlines were inserted just about everywhere instead of between Items as it should. That has been fixed in source but on a different experimental branch for a potential v2 of rustfmt, and the fix hasn't been backported into the rustfmt mainline and release train (#2954 is labeled accordingly).

Getting that fix backported is definitely on the radar, so I'm going to go ahead and close this. You may want to subscribe to that issue for any updates, as well as potentially the stabilization tracking issue (#3382) where other bugs and discussion may take place, as `blank_lines_lower_bound` is still an unstable/in-process option.

**Closed** 2021-06-21 03:23 UTC
Labels: duplicate

**Comment by sagudev** [comment] 2021-06-21 03:37
Thank you.
