### ISSUE TITLE
Idempotency issue with comments after tuple entry

### ISSUE THREAD

**Issue by Pascal-So** [rust-lang/rustfmt#5241] opened 2022-02-25 22:46 UTC
This was tested on the current stable (1.4.38-stable) as well as with directly cloning from GitHub at 89ca3f3a.

Given this input

```rust
fn hi() {
    (
        asdf.method_a()
            // .method_b()
            // .method_c()
        , 2
    );
}
```

the first invocation results in

```rust
fn hi() {
    (
        asdf.method_a(), // .method_b()
                         // .method_c()
        2,
    );
}
```

and a second invocation yields

```rust
fn hi() {
    (
        asdf.method_a(), // .method_b()
        // .method_c()
        2,
    );
}
```

A third invocation doesn't change anything.

I'm not using a `rustfmt.toml` file, this is using the default config.

Interestingly, the following input is stable:

```rust
fn hi() {
    (
        2,
        asdf.method_a(), // .method_b()
                         // .method_c()
    );
}
```

**Comment by ytmimi** [comment] 2022-02-25 23:20
Thanks for the report!

I think this is related to #4848 (possibly a duplicate), but more specifically I think it has to do with whether or not there is a comma or not in the original source text. I explain my initial investigation in a little more detail [here](https://github.com/rust-lang/rustfmt/issues/4848#issuecomment-939387474)

**Comment by ytmimi** [comment] 2022-07-26 16:15
Although this is related to #4848 this is actually a duplicate of #3847, and I'm going to close this accordingly.

**Closed by ytmimi** 2022-07-26 16:15 UTC
Labels: bug, duplicate, a-comments
