### ISSUE TITLE
Function arguments don't appear to be getting formatted

### ISSUE THREAD

**Issue by TheButlah** [rust-lang/rustfmt#5476] opened 2022-07-29 08:03 UTC
<details><summary>code here</summary>

```rust

#[cfg(test)]
mod tests {
    use super::*;
    use lazy_static::lazy_static;

    fn make_example_struct() -> Components {
        let mut components = HashMap::new();
        components.insert(
            ComponentName::Server,
           ComponentInfo    {
                download_url: Url::parse("https://github.com/SlimeVR/SlimeVR-Server/releases/download/v0.2.0/slimevr.jar").unwrap().into(),
                        install_dir: InstallPath::RelativeToSlime(PathBuf::from("")).into(),
            }
        );

        Components(components)
    }

    lazy_static! {
        static ref EXAMPLE_STRUCT: Components = make_example_struct();
    }

}
```

</details>

My code doesn't seem to be autoformatting when inside function arguments. Other code seems to format fine. The code compiles successfully.

Tested on both latest nightly, and on stable, and on windows and mac.

I could have sworn this worked fine - what am I doing wrong?

Here's the non-simplified example: https://github.com/SlimeVR/SlimeVR-Rust/blob/257db8ed4192eccd46422ae8660a23bd3542ede9/autoupdater/src/parsing.rs#L101

**Comment by TheButlah** [comment] 2022-07-29 08:12
Looks like it may have something to do with the very long string literal. I moved that to a separate const and now that the line doesn't overflow, the subsequent line formats as expected.

Is this the intended behavior? I don't see why subequent and prior lines should not be formatted just because one line exceeds the limit.

**Comment by ytmimi** [comment] 2022-07-29 13:53
Thanks for reaching out. This is a duplicate of #3863 so I'm gong to close this accordingly.

> Is this the intended behavior? 

It's the current behavior, and long ago the decision was made to not allow rustfmt to format code if it can't do so while maintaining the `max_width` constraint. increasing the `max_width`, setting `format_strings=True`, or refactoring the code are your best options here.

> I don't see why subequent and prior lines should not be formatted just because one line exceeds the limit.

rutfmt doesn't operate on the input lines directly. rustfmt operates on the AST of your program. The call to `components.insert()` is a chained method call. Because the AST node containing `ComponentInfo` can't be formatted that bubbles up and prevents rustfmt from making any changes to the root node in the chain. Hope that helps you understand what's going on a little better.

**Closed by ytmimi** 2022-07-29 13:53 UTC
Labels: duplicate, a-chains, a-strings
