### ISSUE TITLE
rewriting chains fails if one line fails to wrap

### ISSUE THREAD

**Issue by JakeHillion** [rust-lang/rustfmt#5334] opened 2022-05-06 09:02 UTC
Consider the following example (using clap, as it's one of the easiest builders to demonstrate with):

```rust
use clap::{Arg, Command};

fn main() {
    let matches = Command::new("app")
        .arg(Arg::new("debug").long("debug").short('d').help("Enable additional debugging.").takes_value(false))
        .about("This string is really super long and rustfmt refuses to wrap it, so long that it isn't even suitable on a line of its own.")
        .arg(Arg::new("debug").long("debug").short('d').help("Enable additional debugging.").takes_value(false))
        .get_matches();
}
```

rustfmt does nothing (tested on current playground, 1.4.38-nightly (2022-05-05 30f3860)).

Whereas the following example, without the exceedingly long string:

```rust
use clap::{Arg, Command};

fn main() {
    let matches = Command::new("app")
        .arg(Arg::new("debug").long("debug").short('d').help("Enable additional debugging.").takes_value(false))
        .about("This is a short string.")
        .arg(Arg::new("debug").long("debug").short('d').help("Enable additional debugging.").takes_value(false))
        .get_matches();
}
```

Formats to the following (what I would expect):

```rust
use clap::{Arg, Command};

fn main() {
    let matches = Command::new("app")
        .arg(
            Arg::new("debug")
                .long("debug")
                .short('d')
                .help("Enable additional debugging.")
                .takes_value(false),
        )
        .about("This is a short string.")
        .arg(
            Arg::new("debug")
                .long("debug")
                .short('d')
                .help("Enable additional debugging.")
                .takes_value(false),
        )
        .get_matches();
}
```

It seems like rustfmt gives up on the entire statement if any part won't satisfy the width heuristic in the output, rather than still doing its best. The ideal formatting for the long string version would be the final output of the short string version, with the short string substituted. With extremely long builder chains this leads to horrible formatting, as it must all be done manually.

**Comment by ytmimi** [comment] 2022-05-06 11:15
Thanks for the report!

This is a known issue and is a duplicate of #3416, and #3863

**Closed by ytmimi** 2022-05-06 11:15 UTC
Labels: duplicate, a-chains, a-strings
