### ISSUE TITLE
Panic on double tuple indexing

### ISSUE THREAD

**Issue by 1c7718e7** [rust-lang/rustfmt#4494] opened 2020-10-26 11:00 UTC
**Describe the bug**

Rustfmt panics when formatting perfectly valid, stable Rust code.
 
**To Reproduce**

Run rustfmt on:
```
const y: () = x.0.1; // whether x is defined does not matter.
```
Bug is triggered inside any expressions, not just const declarations.

**Expected behavior**

Rustfmt does not panic.

**Meta**

- rustfmt version: rustfmt 1.4.22-nightly (97d0301 2020-10-04)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: cargo-fmt, but bug is also reproducible by running rustfmt directly

**Comment by calebcartwright** [comment] 2020-10-26 15:15
Duplicate of #4355, resolved in the upcoming 1.4.23 release

**Closed by calebcartwright** 2020-10-26 15:15 UTC
Labels: bug, duplicate
