### ISSUE TITLE
Inconsistant formatting, reformatting changes format multiple times

### ISSUE THREAD

**Issue by MingweiSamuel** [rust-lang/rustfmt#5586] opened 2022-11-03 20:08 UTC
`1.5.1-nightly (2022-11-02 edf0182)`

Input
```rust
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident =
                            if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
                                self.node_id_as_ident(node_id, false)
                            } else {
                                // Entire subgraph is pull (except for a single send/push handoff output).
                                assert_eq!(
                                    1,
                                    send_ports.len(),
                                    "If entire subgraph is pull, should have only one handoff output."
                                );
                                send_ports[0].clone()
                            };
                    }
                }
            }
        }
    }
}
```

Format once (looks good)
```rust
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident = if let Some(&node_id) =
                            subgraph_nodes.get(pull_to_push_idx)
                        {
                            self.node_id_as_ident(node_id, false)
                        } else {
                            // Entire subgraph is pull (except for a single send/push handoff output).
                            assert_eq!(
                                1,
                                send_ports.len(),
                                "If entire subgraph is pull, should have only one handoff output."
                            );
                            send_ports[0].clone()
                        };
                    }
                }
            }
        }
    }
}
```

Format a second time (bad)
```rust
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident =
                            if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
                                self.node_id_as_ident(node_id, false)
                            } else {
                                // Entire subgraph is pull (except for a single send/push handoff output).
                                assert_eq!(
                                1,
                                send_ports.len(),
                                "If entire subgraph is pull, should have only one handoff output."
                            );
                                send_ports[0].clone()
                            };
                    }
                }
            }
        }
    }
}
```
---

Alternative, start with this input (same tokens)
```rust
fn main() {
    {{{{{
        let push_ident =
            if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
                self.node_id_as_ident(node_id, false)
            } else {
                // Entire subgraph is pull (except for a single send/push handoff output).
                assert_eq!(
                    1,
                    send_ports.len(),
                    "If entire subgraph is pull, should have only one handoff output."
                );
                send_ports[0].clone()
            };
    }}}}}
}
```

Format it and you get this, the worst of them all:
```rust
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident =
                            if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
                                self.node_id_as_ident(node_id, false)
                            } else {
                                // Entire subgraph is pull (except for a single send/push handoff output).
                                assert_eq!(
                    1,
                    send_ports.len(),
                    "If entire subgraph is pull, should have only one handoff output."
                );
                                send_ports[0].clone()
                            };
                    }
                }
            }
        }
    }
}
```

**Comment by MingweiSamuel** [comment] 2022-11-03 20:12
I guess its just giving up at a certain width
```rust
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident =
                            if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
                                self.node_id_as_ident(node_id, false)
                            } else {
                                // Entire subgraph is pull (except for a single send/push handoff output).
                                assert_eq!(
    1,
    send_ports.len(),
    "If entire subgraph is pull, should have only one handoff output."
);
                                send_ports[0].clone()
                            };
                    }
                }
            }
        }
    }
}
```
but it is interesting that it can cycle through multiple formats, first time I have seen that

**Comment by ytmimi** [comment] 2022-11-03 21:28
@MingweiSamuel are you using any non default settings?

**Comment by ytmimi** [comment] 2022-11-03 21:35
I believe these idempotency issues are only present when using `version=One`. These seem to be fixed when setting `version=Two`. @MingweiSamuel let me know if you can confirm that setting `version=Two` helps resolve the issue.

**Comment by amab8901** [comment] 2022-11-28 07:31
> ```rust
> assert_eq!(
> ```

I think this example is a great case study for implementing a rule that says something like this:

```
right parenthesis of a macro must be on the same column as the macro's first letter 
``` 

and another rule that says something like this:
```
if there is at least one line between the parentheses of a macro, then those lines must be indented at least once relative to the leftmost parenthesis of the macro
```

**Comment by ytmimi** [comment] 2022-11-28 14:44
@amab8901 I appreciate you reaching out. I understand that the formatting isn't ideal, but because of our backwards comparability guarantee we can't always fix bugs in a way that resolves the issue on version `One`. I can't say for certain what the original issue is, but from my testing I've found this not to be an issue with `version=Two`. If you have the time to confirm my findings that would be very helpful😁

**Comment by ytmimi** [comment] 2022-11-28 15:07
When running rustfmt from the command line you can pass the `--config` option e.g `rustfmt --config=Version=Two` You can also add `version = "Two"` to a rustfmt.toml file. **Note** `version=Two` requires a nightly version of rustfmt.

The [Configuring Rustfmt](https://github.com/rust-lang/rustfmt#configuring-rustfmt) section of the README might be useful. Also check out this [Github page](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=) to see all available configurations.

**Comment by amab8901** [comment] 2022-11-28 16:22
I figured out how to do it, and it works for me.

Steps to reproduce:
1. insert the below code in your `main.rs`
> ```rust
> fn main() {
>     {
>         {
>             {
>                 {
>                     {
>                         let push_ident =
>                             if let Some(&node_id) = subgraph_nodes.get(pull_to_push_idx) {
>                                 self.node_id_as_ident(node_id, false)
>                             } else {
>                                 // Entire subgraph is pull (except for a single send/push handoff output).
>                                 assert_eq!(
>     1,
>     send_ports.len(),
>     "If entire subgraph is pull, should have only one handoff output."
> );
>                                 send_ports[0].clone()
>                             };
>                     }
>                 }
>             }
>         }
>     }
> }
> ```

2. create a new file called `rustfmt.toml` in your project's root folder. Insert the following content therein:
```
version="Two"
```
3. in your terminal (in project's root folder), run the following:
```
rustup override set nightly
cargo fmt
```
4. the output from `cargo fmt` will say something like this:
```
error: 'cargo-fmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu`
```
Yours may be called something else other than `nightly-x86_64-unknown-linux-gnu`. As the output instructs you to do, run the following in your terminal (but with `nightly-x86_64-unknown-linux-gnu` replaced with your equivalent name):
```
rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
```
5. in terminal (in project's root folder), run `cargo fmt`
6. voila! The code in step 1 becomes:
```
fn main() {
    {
        {
            {
                {
                    {
                        let push_ident = if let Some(&node_id) =
                            subgraph_nodes.get(pull_to_push_idx)
                        {
                            self.node_id_as_ident(node_id, false)
                        } else {
                            // Entire subgraph is pull (except for a single send/push handoff output).
                            assert_eq!(
                                1,
                                send_ports.len(),
                                "If entire subgraph is pull, should have only one handoff output."
                            );
                            send_ports[0].clone()
                        };
                    }
                }
            }
        }
    }
}
```
7. and now that you have configured it, anytime you want to change from code in step #1 to code in step #2, you only need to write `cargo fmt` in terminal.

**Comment by ytmimi** [comment] 2022-11-28 16:34
@amab8901 just to be clear are you confirming that `version=Two` resolves the issue?

**Comment by amab8901** [comment] 2022-11-28 16:36
> @amab8901 just to be clear are you confirming that `version=Two` resolves the issue?

yes, and I'm also simultaneously providing @MingweiSamuel  the steps needed to accomplish this outcome, just in case.

**Comment by ytmimi** [comment] 2022-11-28 16:40
Great, thank you! I'm happy to close this as resolved, but if you want to add a test case to the test suite you can follow the [Create test case](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#create-test-cases) docs.

**Closed** 2023-01-28 21:18 UTC
