### ISSUE TITLE
Indentation increases after every format

### ISSUE THREAD

**Issue by tritoke** [rust-lang/rustfmt#6259] opened 2024-07-30 13:40 UTC
```rs
macro_rules! impl_sponge_constructor {
    ($func_name:ident, $xof:ident, $sponge:ident, $example_hash:literal) => {
        #[doc=concat!(
            "Construct a ", stringify!($sponge), " directly from `data`\n",
            "\n",
            "Example:\n",
            "\n",
            ".. code-block:: python\n",
            "\n",
            "   >>> from xoflib import shake128\n",
            "   >>> xof = shake128(b\"bytes to absorb\")\n",
            "   >>> xof.read(16).hex()\n",
            "   '250ef380a0f0c92e9506af9893f640fa'\n",
        )]
        #[pyfunction]
        fn $func_name(data: &Bound<'_, PyAny>) -> PyResult<$sponge> {
            Ok($xof::new(Some(data))?.finalize())
        }
    };
}
```

Whenever I try to format this code rustfmt indents the strings further and further, after three formats it becomes:
```rs
macro_rules! impl_sponge_constructor {
    ($func_name:ident, $xof:ident, $sponge:ident, $example_hash:literal) => {
        #[doc=concat!(
                                    "Construct a ", stringify!($sponge), " directly from `data`\n",
                                    "\n",
                                    "Example:\n",
                                    "\n",
                                    ".. code-block:: python\n",
                                    "\n",
                                    "   >>> from xoflib import shake128\n",
                                    "   >>> xof = shake128(b\"bytes to absorb\")\n",
                                    "   >>> xof.read(16).hex()\n",
                                    "   '250ef380a0f0c92e9506af9893f640fa'\n",
                                )]
        #[pyfunction]
        fn $func_name(data: &Bound<'_, PyAny>) -> PyResult<$sponge> {
            Ok($xof::new(Some(data))?.finalize())
        }
    };
}
```

Rustfmt version: 
rustfmt 1.7.0-stable (0514789 2024-07-21)
installed via rustup
OS: Arch Linux

**Comment by tritoke** [comment] 2024-07-30 13:42
@kinnison has confirmed that he can reproduce it

**Comment by kinnison** [comment] 2024-07-30 13:44
> @kinnison has confirmed that he can reproduce it

For reference, I had `rustfmt 1.7.0-stable (9b00956 2024-04-29)` on the system I tried on.

**Comment by tritoke** [comment] 2024-07-30 13:45
Also of note `cargo fmt --check` claims the code is formatted, but `cargo fmt` still reformats the code.

**Comment by RobinJadoul** [comment] 2024-07-30 14:19
Can also reproduce on the [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=efcacf16bd4f57415927d967b20cfeee) (tools -> rustfmt, both stable and nightly)

**Comment by calebcartwright** [comment] 2024-07-30 14:27
believe it's a duplicate of #5974

**Comment by tritoke** [comment] 2024-07-31 12:36
Yeah that looks identical, I'll close this.

**Closed** 2024-07-31 12:37 UTC
Labels: bug
