### ISSUE TITLE
thread 'main' panicked at lib.rs:376:47 because of empty code block in doc comment

### ISSUE THREAD

**Issue by oovm** [rust-lang/rustfmt#4793] opened 2021-04-10 05:12 UTC
**Describe the bug**

```yaml
$ RUST_BACKTRACE=full cargo fmt
thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}`', src\\lib.rs:376:47
stack backtrace:
   0:     0x7ff700d0665e - <unknown>
   1:     0x7ff700d1e72b - <unknown>
   2:     0x7ff700d02d98 - <unknown>
   3:     0x7ff700d092bd - <unknown>
   4:     0x7ff700d08d89 - <unknown>
   5:     0x7ff700d09b70 - <unknown>
   6:     0x7ff700d096a1 - <unknown>
   7:     0x7ff700d06fef - <unknown>
   8:     0x7ff700d095f9 - <unknown>
   9:     0x7ff700d1bcc0 - <unknown>
  10:     0x7ff700d218d6 - <unknown>
  11:     0x7ff70086b81d - <unknown>
  12:     0x7ff700844519 - <unknown>
  13:     0x7ff700846a9f - <unknown>
  14:     0x7ff70083f7a2 - <unknown>
  15:     0x7ff70094f5f0 - <unknown>
  16:     0x7ff70085dd83 - <unknown>
  17:     0x7ff700935e77 - <unknown>
  18:     0x7ff70092bc06 - <unknown>
  19:     0x7ff7009231a4 - <unknown>
  20:     0x7ff700936705 - <unknown>
  21:     0x7ff7009374f8 - <unknown>
  22:     0x7ff70080607d - <unknown>
  23:     0x7ff700838ea7 - <unknown>
  24:     0x7ff70080b9ca - <unknown>
  25:     0x7ff700815b07 - <unknown>
  26:     0x7ff70080b246 - <unknown>
  27:     0x7ff700812071 - <unknown>
  28:     0x7ff70080f162 - <unknown>
  29:     0x7ff70080d2b6 - <unknown>
  30:     0x7ff70080d5cc - <unknown>
  31:     0x7ff700d09e47 - <unknown>
  32:     0x7ff700816aa7 - <unknown>
  33:     0x7ff700d27714 - <unknown>
  34:     0x7fff6fcc7034 - BaseThreadInitThunk
  35:     0x7fff70782651 - RtlUserThreadStart
```

It's very strange.

There is no `fn main() {}` in my project, nor 376 lines in `lib.rs`

**To Reproduce**

The project can be found here: [sdl-rs/sdl-ast@fe2daf4](https://github.com/sdl-lang/sdl-rs/blob/da720afb35db7160d1034612bd0def436fe2daf4/projects/sdl-ast)

**Expected behavior**

**Meta**

- rustfmt version: `v1.4.36`
- From where did you install rustfmt?: `rustfmt_windows-x86_64-msvc_v1.4.36`
- How do you run rustfmt: 

Run `RUST_BACKTRACE=full cargo fmt` in MINGW64

![image](https://user-images.githubusercontent.com/17541209/114259029-96295980-99fd-11eb-88f5-58204f4e3df6.png)

**Comment by calebcartwright** [comment] 2021-04-10 05:22
Important to note that rustup is the recommended and preferred way of getting the right components onto your system, but if you're going to download the pre-built binaries then I'd think for mingw you'd want to use rustfmt_windows-x86_64-gnu_v1.4.36.zip and not the msvc one, no?

**Comment by oovm** [comment] 2021-04-10 05:30
I just replaced with `rustfmt_windows-x86_64-gnu_v1.4.36.zip`, the problem still exists, only the address of the stack backtrace has changed.

```yaml
$ rustfmt -V
rustfmt 1.4.36-nightly (7de6968 2021-02-07)

$ RUST_BACKTRACE=full cargo fmt
thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}`', src\\lib.rs:376:47
stack backtrace:
   0:     0x7ff7be54665e - <unknown>
   1:     0x7ff7be55e72b - <unknown>
   2:     0x7ff7be542d98 - <unknown>
   3:     0x7ff7be5492bd - <unknown>
   4:     0x7ff7be548d89 - <unknown>
   5:     0x7ff7be549b70 - <unknown>
   6:     0x7ff7be5496a1 - <unknown>
   7:     0x7ff7be546fef - <unknown>
   8:     0x7ff7be5495f9 - <unknown>
   9:     0x7ff7be55bcc0 - <unknown>
  10:     0x7ff7be5618d6 - <unknown>
  11:     0x7ff7be0ab81d - <unknown>
  12:     0x7ff7be084519 - <unknown>
  13:     0x7ff7be086a9f - <unknown>
  14:     0x7ff7be07f7a2 - <unknown>
  15:     0x7ff7be18f5f0 - <unknown>
  16:     0x7ff7be09dd83 - <unknown>
  17:     0x7ff7be175e77 - <unknown>
  18:     0x7ff7be16bc06 - <unknown>
  19:     0x7ff7be1631a4 - <unknown>
  20:     0x7ff7be176705 - <unknown>
  21:     0x7ff7be1774f8 - <unknown>
  22:     0x7ff7be04607d - <unknown>
  23:     0x7ff7be078ea7 - <unknown>
  24:     0x7ff7be04b9ca - <unknown>
  25:     0x7ff7be055b07 - <unknown>
  26:     0x7ff7be04b246 - <unknown>
  27:     0x7ff7be052071 - <unknown>
  28:     0x7ff7be04f162 - <unknown>
  29:     0x7ff7be04d2b6 - <unknown>
  30:     0x7ff7be04d5cc - <unknown>
  31:     0x7ff7be549e47 - <unknown>
  32:     0x7ff7be056aa7 - <unknown>
  33:     0x7ff7be567714 - <unknown>
  34:     0x7fff6fcc7034 - BaseThreadInitThunk
  35:     0x7fff70782651 - RtlUserThreadStart
```

**Comment by calebcartwright** [comment] 2021-04-10 05:41
Thanks. The panic and line info is a reference to rustfmt, not your source input, and is related to some extra processing required in cases like formatting code blocks in comments.

Could you please try to distill your input down into a smaller reproducible example? Even getting down to a single file would be a helpful starting point as opposed to an entire project. You may want to try running with `--verbose` to get a better idea of which file contains the problematic area.

**Comment by oovm** [comment] 2021-04-10 05:58
Everything is fine after removing: [sdl-ast/src/ast/loops/mod.rs](https://github.com/sdl-lang/sdl-rs/blob/da720afb35db7160d1034612bd0def436fe2daf4/projects/sdl-ast/src/ast/loops/mod.rs#L38-L40)

So I think

````
/// ```
/// 
/// ```
````

gives this panic

**Comment by calebcartwright** [comment] 2021-04-16 03:02
That's super helpful, thanks so much for reducing that to a minimal example!

**Comment by jplatte** [comment] 2021-09-10 13:56
I get the same panic with some `macro_rules!` code, not sure whether it's the same root cause: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a244d68ae7968bc2727e8ea52d240dd4)

**Comment by ytmimi** [comment] 2022-07-27 02:26
going to close this in favor of #5234, as the issue is clearer in that issue

**Closed by ytmimi** 2022-07-27 02:26 UTC
Labels: bug, p-medium, help wanted
