### ISSUE TITLE
`rustfmt` wrongly deletes labels

### ISSUE THREAD

**Issue by cychen2021** [rust-lang/rustfmt#5926] opened 2023-09-27 05:46 UTC
```rust
match x {
    0 => 'label: {
        if some_flag {
            break 'label;
        }
        println!("hello");
    }
    _ => { println!("no hello"); }
}
```

becomes

```rust
match x {
    0 => {
        if some_flag {
            break 'label;
        }
        println!("hello");
    }
    _ => { println!("no hello"); }
}
```

after formatting.

**Comment by ytmimi** [comment] 2023-09-27 18:55
Thanks for the report! This is a duplicate of https://github.com/rust-lang/rustfmt/issues/5676

#5677 is already merged and fixes this issue. All that's left to do now is wait for the next release.

**Closed by ytmimi** 2023-09-27 18:55 UTC
