### ISSUE TITLE
rustfmt sometimes generates code which triggers clippy::unused_unit

### ISSUE THREAD

**Issue by ratmice** [rust-lang/rustfmt#5442] opened 2022-07-13 13:24 UTC
The code at the bottom triggers rustfmt to expand `if some_macro!(*x > 5) == true => (),` into 

```
if some_macro!(*x > 5) == true => {
    ()
}
```

which subsequently triggers the clippy lint `clippy::unused_unit`
As a workaround and suggested fix, switching it to `=> {}` does not and `=> {},` just removes the comma,
`(),` should probably produce `{}` alone in this case.

```
enum SomethingLongish {
    Pickles(usize),
}
struct SomethingAlsoLongish(SomethingLongish);

macro_rules! some_macro {
    ($e:expr) => {{
        $e
    }};
}
fn main() {
    let a: Result<(), Vec<SomethingAlsoLongish>> =
        Err(vec![SomethingAlsoLongish(SomethingLongish::Pickles(6))]);
    match a.as_ref().map_err(Vec::as_slice) {
        Ok(_) => panic!("ok"),
        Err([SomethingAlsoLongish(SomethingLongish::Pickles(x))])
            if some_macro!(*x > 5) == true => (),
        Err(_) => panic!("not ok"),
    }
}
```

**Comment by ytmimi** [comment] 2022-07-13 21:36
Thanks for reaching out, but going to close this as a duplicate of #5134. This is intended behavior. See https://github.com/rust-lang/rustfmt/issues/5134#issuecomment-995299405.

**Closed by ytmimi** 2022-07-13 21:36 UTC
Labels: duplicate
