### ISSUE TITLE
adds extra comma in tuple formatting

### ISSUE THREAD

**Issue by f01dab1e** [rust-lang/rustfmt#5942] opened 2023-10-18 10:03 UTC
pre:
```rust
fn main() {
( 
    /*a*/
    1
    /*b*/,
/*c*/
2/*d*/, 

);
}
```
post:
```rust
fn main() {
    (
        /*a*/
        1, /*b*/,
           /*c*/
        2, /*d*/
    );
}
```

error:
```
error: expected expression, found `,`
 --> /workspace/rustfmt/a:4:17
  |
4 |         1, /*b*/,
  |                 ^ expected expression

**Comment by ytmimi** [comment] 2023-10-18 13:26
Thanks for the report. Going to close this as a duplicate of https://github.com/rust-lang/rustfmt/issues/5425.

**Closed by ytmimi** 2023-10-18 13:26 UTC
