### ISSUE TITLE
Formatting of Comment Inside Const

### ISSUE THREAD

**Issue by davidBar-On** [rust-lang/rustfmt#4508] opened 2020-11-03 21:11 UTC
**Input** / **Output**
Test [comment-inside-const.rs](https://github.com/rust-lang/rustfmt/blob/4abdda1d0ac448a4a1f7a8b0bf7855af342799dc/tests/target/comment-inside-const.rs#L1:L9) is now:
```rust
fn issue982() {
    const SOME_CONSTANT: u32 =
        // Explanation why SOME_CONSTANT needs FLAG_A to be set.
        FLAG_A |
        // Explanation why SOME_CONSTANT needs FLAG_B to be set.
        FLAG_B |
        // Explanation why SOME_CONSTANT needs FLAG_C to be set.
        FLAG_C;
}
```

**Expected output**
Should the desired output (and input) be:
```rust
fn issue982() {
    const SOME_CONSTANT: u32 =
        // Explanation why SOME_CONSTANT needs FLAG_A to be set.
        FLAG_A
            // Explanation why SOME_CONSTANT needs FLAG_B to be set.
            | FLAG_B
            // Explanation why SOME_CONSTANT needs FLAG_C to be set.
            | FLAG_C;
}
```
That is, the **`|` is put at the beginning of the line** as `binop_separator = "Front"` is used, and the **lines past `FLAG_A` are indented to the right**, based on the current formatting of the following example:
```rust
fn main() {
    const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: u32 =
        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
            | zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
            | uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu;
}
```

The current test should probably be formatted as something like (with `binop_separator = "Front"`):
```rust
fn issue982() {
    const SOME_CONSTANT: u32 =
        // Explanation why SOME_CONSTANT needs FLAG_A to be set.
        FLAG_A
            |
            // Explanation why SOME_CONSTANT needs FLAG_B to be set.
            FLAG_B
            |
            // Explanation why SOME_CONSTANT needs FLAG_C to be set.
            FLAG_C;
}
````

**Comment by ytmimi** [comment] 2022-07-26 14:27
Going to close as this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3167. The reason we don't format here is that we don't yet handle comments between binary operators

**Closed by ytmimi** 2022-07-26 14:27 UTC
Labels: duplicate, a-comments, a-binop
