### ISSUE TITLE
Rustfmt loses visibility on some trait items and impl items

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#4960] opened 2021-08-20 21:03 UTC
As of current master, rustfmt applies the following incorrect diff to this valid Rust code.

```diff
 #[cfg(any())]
 trait Visible {
-    pub const C: i32;
+    const C: i32;
     pub type T;
-    pub fn f();
+    fn f();
-    pub fn g() {}
+    fn g() {}
 }

 #[cfg(any())]
 impl Visible for Bar {
     pub const C: i32;
     pub type T;
-    pub fn f();
+    fn f();
     pub fn g() {}
 }
```

To reproduce: `cargo run --bin rustfmt repro.rs`

**Comment by dtolnay** [comment] 2021-08-20 21:20
Use case: I hit this in https://github.com/dtolnay/inherent.

**Comment by upsuper** [comment] 2021-08-21 13:58
I believe this is a duplicate of #4631.

**Comment by calebcartwright** [comment] 2021-08-21 15:43
> I believe this is a duplicate of #4631.

No, it isn't.

There is indeed some symptom similarity, but there are also fundamental differences. Crucially, this issue reporting the impact on associated items as valid Rust code vs. #4631 being about call args to macros where folks opt to use the delimiters that instruct rustfmt to format the args as their valid Rust code counterparts if they can be parsed as such.

**Closed** 2021-08-22 17:06 UTC
Labels: bug
