### ISSUE TITLE
Spooky action-at-a-distance causing missed linewraps

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rustfmt#3654] opened 2019-06-25 18:37 UTC
rustfmt output:
```rust
fn get_in_params() {
    m.in_params
        .iter()
        .map(|| {
            let direction = arg_types.get_arg(name); // removing this line causes formatting ?!?!?!
            match ty {
                Some(_) => {
                    if some_bool {
                    }
                    match size {
                        _ => {
                            if some_bool { // removing any of these lines causes formatting
                            } else { // the following line must be long or else formatting will happen
                                panic!("missing 'arg_type' attribute: string direction must be specified")
                            }
                        }
                    }
                }
                None => {
                    if some_bool {
                        let resolved_type = format!("ptr[{}, array[{}]]", to_c_name(&direction), ty_to_syzkaller_str(ast, ty).unwrap());
                    }
                }
            }
        })
        .collect() // removing this line causes formatting ?!?!?!
}
```

Removing or significantly editing basically any line causes the `let resolved_type = ...` line (which is too long and *should* be wrapped) to be reformatted.

**Comment by cramertj** [comment] 2019-06-25 18:38
Possibly related to https://github.com/rust-lang/rustfmt/issues/3638

**Comment by cramertj** [comment] 2019-06-25 18:49
note when reproducing: you'll have to remove the comments

**Comment by cramertj** [comment] 2019-06-25 18:51
version without comments:
```rust
fn get_in_params() {
    m.in_params
        .iter()
        .map(|| {
            let direction = arg_types.get_arg(name);
            match ty {
                Some(_) => {
                    if some_bool {
                    }
                    match size {
                        _ => {
                            if some_bool {
                            } else {
                                panic!("missing 'arg_type' attribute: string direction must be specified")
                            }
                        }
                    }
                }
                None => {
                    if some_bool {
                        let resolved_type = format!("ptr[{}, array[{}]]", to_c_name(&direction), ty_to_syzkaller_str(ast, ty).unwrap());
                    }
                }
            }
        })
        .collect()
}
```

**Comment by cramertj** [comment] 2019-06-25 18:51
reformatted after removing the `let` binding:

```rust
fn get_in_params() {
    m.in_params
        .iter()
        .map(|| match ty {
            Some(_) => {
                if some_bool {}
                match size {
                    _ => {
                        if some_bool {
                        } else {
                            panic!(
                                "missing 'arg_type' attribute: string direction must be specified"
                            )
                        }
                    }
                }
            }
            None => {
                if some_bool {
                    let resolved_type = format!(
                        "ptr[{}, array[{}]]",
                        to_c_name(&direction),
                        ty_to_syzkaller_str(ast, ty).unwrap()
                    );
                }
            }
        })
        .collect()
}
```

**Comment by scampi** [comment] 2019-09-28 07:56
I think snippet at https://github.com/rust-lang/rustfmt/issues/3654#issuecomment-505574877 can be reformatted because the match is not wrapped in a block and therefore it is not indented.
This gives enough space for the `panic!` to be rewritten, allowing the `match` to be reformatted.

**Comment by scampi** [comment] 2019-09-28 07:58
Maybe the match rewrite could allow for some branch to be unformatted, this would allow the `Some` to be left as is, but reformat the `None` branch.

**Comment by ytmimi** [comment] 2022-07-20 18:50
I believe this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863

**Closed by ytmimi** 2022-07-20 18:50 UTC
Labels: poor-formatting
