### ISSUE TITLE
Don't indiscrimanently group module attributes

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rustfmt#4932] opened 2021-07-30 00:30 UTC
I'd deliberately added the empty line here between those lines adjusting lint handling from those controlling enabling of features to draw attention to the fact that something different is going on with the latter. I don't think rustfmt should be indiscriminately grouping such things.

```diff
 #![warn(missing_docs)]
 #![deny(bare_trait_objects)]
-
 #![cfg_attr(docsrs, feature(doc_cfg))]
```

Version string: **rustfmt 1.4.37-stable (a178d03 2021-07-26)**
Project: https://github.com/jnqnfe/pulse-binding-rust
Specific file: https://github.com/jnqnfe/pulse-binding-rust/blob/master/pulse-binding/src/lib.rs
Ran against the master branch.

**Comment by calebcartwright** [comment] 2021-09-03 04:31
Closing as duplicate of #4082

**Closed by calebcartwright** 2021-09-03 04:31 UTC
Labels: duplicate
