### ISSUE TITLE
Overly long expressions prevent surround code from being formatted

### ISSUE THREAD

**Issue by matklad** [rust-lang/rustfmt#5576] opened 2022-10-26 17:36 UTC
Consider this snippet:  

```rust
fn main() {
    this.wrap(1+1,|| match msg {
	() => {
		"comment me out xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
		let x =1+1;
	}
})
}
```

Here, the literal is very long, and theer's little rustfmt can do with it, which is expected. *However*, it seems that it also prevetns *surrounding* code from being reformatted (eg, spaces around `+`), and that seems like a bug. 

In the real-world use-case, the long experssion is a `tracing::info!` call, which is a part of a hundred-lines long `match`, and rustfmt effectively doesn't work for the whole match expressions.

**Comment by ytmimi** [comment] 2022-10-26 17:40
Thanks for reaching out. I believe this a duplicate of #3863 because of the chained `.wrap` call.

**Comment by ytmimi** [comment] 2022-10-26 17:43
Would it be possible to post the real-world snippet?

**Comment by matklad** [comment] 2022-10-26 17:45
https://github.com/near/nearcore/blob/c1b6250ad10b9161689b02654743e74cc86fb2c7/chain/client/src/client_actor.rs#L296

And yeah, seems like a dupe

**Comment by ytmimi** [comment] 2022-10-26 18:13
Thanks for the link. I'm going to close this as a duplicate, but For what it's worth, I took a look at the snippet and these are the lines that are too long:

|Length with indentation| Line|
|------|------|
|129|                     info!(target: "adversary", "Producing {} block out of {}, height = {}", blocks_produced, num_blocks, height);|
|102|                 // timeout is set to 1.5 seconds to give some room as we wait in Nightly for 2 seconds|
|115|                 info!(target: "adversary", "Check Storage Consistency, timeout set to {:?} milliseconds", timeout);|
|104|                     error!(target: "client", "Storage Validation failed, {:?}", store_validator.errors);|

chances are if we special cased formatting for tracing macros (related to #5516), we should be able to format the snippet since each macro call would likely be split over multiple lines.

**Closed by ytmimi** 2022-10-26 18:13 UTC
Labels: duplicate, a-chains
