### ISSUE TITLE
Ugly line break when initializing fields in struct from returns value of function

### ISSUE THREAD

**Issue by maltekliemann** [rust-lang/rustfmt#5898] opened 2023-08-29 12:38 UTC
rustfmt 1.5.2-stable (84c898d6 2023-04-16)

```rust
// Before
fn main() -> Result<(), Box<dyn std::error::Error>> {

    let x = A {
        bbbbbbbbbbbbb: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc(),
    };   
    //                                                                                             ^
    //                                                                                    column 100

    Ok(())
}

// After
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let x = A {
        bbbbbbbbbbbbb: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc(
        ),
    };
    Ok(())
}

// Would have expected/preferred
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let x = A {
        bbbbbbbbbbbbb:
            cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc(),
    };
    Ok(())
}
```

Note that the placement of the open parens in column 100 (or 99) is very important. If it's in column 101, the formatting is OK.

**Comment by ytmimi** [comment] 2023-08-29 12:56
Thanks for the report. Going to close this as a duplicate of https://github.com/rust-lang/rustfmt/issues/5356

**Closed as not planned by ytmimi** 2023-08-29 12:56 UTC
Labels: S-duplicate, I-poor-formatting
