### ISSUE TITLE
rustfmt locks up

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rustfmt#4718] opened 2021-02-24 11:34 UTC
When I run rustfmt on my projects it locks up, freezes, or just takes seemingly forever.

**To Reproduce**

`cargo new --lib super_tree`
`cd super_tree`
`time rustfmt -v`
Wait forever or kill the process after some time.

No output with `RUST_LOG="debug,rustfmt=debug" rustfmt` either

**Expected behavior**

`rustfmt` returns in a near instant time as there isn't much work for it to do.

**Meta**

- rustfmt version: rustfmt 1.4.30-stable (8c6769d 2021-01-18) (same effect with multiple versions including rustfmt 1.4.36-nightly (7de6968 2021-02-07))
- From where did you install rustfmt?: rustup
- How do you run rustfmt: rustfmt

Ubuntu 20.04LTS vanilla.
```bash
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ uname -a
Linux ubuntu-amocsy 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.50.0 (cb75ad5db 2021-02-10)`
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ rustfmt --version
rustfmt 1.4.30-stable (8c6769d 2021-01-18)
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ 
amocsy@ubuntu-amocsy:/mnt/linux_storage/dev/games/super_tree$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/amocsy/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-05-07-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
master
1.30.0-x86_64-unknown-linux-gnu
1.35.0-x86_64-unknown-linux-gnu
1.40.0-x86_64-unknown-linux-gnu
1.43.1-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

```

**Comment by calebcartwright** [comment] 2021-02-24 22:47
Thanks for reaching out, but going to close this. As with rustc, and many of the other rust tools, `-v` is a shorthand for `--verbose`, and `-V` is the shorthand printing a version.

rustfmt supports formatting both files and strings of rust code provided via stdin, documented [here](https://github.com/rust-lang/rustfmt#running-rustfmt-directly).

When you execute `rustfmt -v` without specifying a file name, rustfmt is actually waiting on _you_ to provide the input and flush the stdin buffer, which it would then format with verbose mode enabled. This is very much by design, to support interactivity.

**Closed by calebcartwright** 2021-02-24 22:47 UTC
