### ISSUE TITLE
Formatter does not fold a long line

### ISSUE THREAD

**Issue by megahomyak** [rust-lang/rustfmt#5412] opened 2022-06-28 10:12 UTC
```
if is_action {
    if let Some(action) = all_actions.borrow_mut().iter_mut().find(|action| action.shortcut == shortcut) {
        stack.push((action.callback)().into());
    } else {
        ui.invoke_show_message(
            format!("Command with shortcut \"{shortcut}\" (found at line {line_number}) not found!").into(),
        );
    }
}
```
^ two lines here are longer than 100 characters (even not considering the additional indentation in my code), but none of those are folded

**rustfmt version**: rustfmt 1.4.38-stable (fe5b13d6 2022-05-18)

**Comment by ytmimi** [comment] 2022-06-28 13:44
Thanks for reaching out.

I'm unable to reproduce this. I'm using `rustfmt 1.4.38-stable (fe5b13d6 2022-05-18)` with no configuration options. The issue may be that you need to wrap you snippet in a function for it to parse properly. Here's how I've modified your snippet (just wrapping it in a main function):

```rust
fn main() {
    if is_action {
        if let Some(action) = all_actions.borrow_mut().iter_mut().find(|action| action.shortcut == shortcut) {
            stack.push((action.callback)().into());
        } else {
            ui.invoke_show_message(
                format!("Command with shortcut \"{shortcut}\" (found at line {line_number}) not found!").into(),
            );
        }
    }
}
```

After running rustfmt I get:

```rust
fn main() {
    if is_action {
        if let Some(action) = all_actions
            .borrow_mut()
            .iter_mut()
            .find(|action| action.shortcut == shortcut)
        {
            stack.push((action.callback)().into());
        } else {
            ui.invoke_show_message(
                format!(
                    "Command with shortcut \"{shortcut}\" (found at line {line_number}) not found!"
                )
                .into(),
            );
        }
    }
}
```

When you get a chance can you confirm that the issue was the snippet or perhaps provide a different snippet that illustrates the problem that you're having.

**Comment by megahomyak** [comment] 2022-06-28 15:04
Oh, it really works fine without the context. Here's the full snippet: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9a0eaa300539229fd54f8d84da914295
Line 158 is the line of interest

**Comment by ytmimi** [comment] 2022-06-28 16:00
Thanks for including the full snippet. The extra context really helps! I see now that we're dealing with a deeply nested structure. Almost certain this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3416, and https://github.com/rust-lang/rustfmt/issues/3863 so going to close accordingly.

If you're using a nightly rustfmt, you can try setting `version=Two` and `format_strings=true` to allow rustfmt to wrap the long string literal, which should solve the issue.

You can run rustfmt manually on your file with the following:
```
rustfmt --config=version=Two,format_strings=true <filename>
```

If you're using a stable rustfmt you can try bumping up the `max_width` to some value that's sufficiently large. I tested it out with `120`, but you might find that a smaller value also works.

```
rustfmt --config=max_width <filename>
```
Passing config values via the command line is tedious so you might consider [adding a `rustfmt.toml` file](https://github.com/rust-lang/rustfmt#configuring-rustfmt) to the root of your project with your desired configuration.

Also, tagging me is just fine 👍🏼

**Closed** 2022-06-28 16:01 UTC
Labels: duplicate, a-chains, a-strings
