### ISSUE TITLE
Error finding a config file shows error message with insufficient context

### ISSUE THREAD

**Issue by tmfink** [rust-lang/rustfmt#5188] opened 2022-01-24 02:55 UTC
There are cases where `rustfmt`'s call to `fs::metadata()` will fail
(due to permissions) and panic. For example, an ancestor directory or the home directory may exist but
the user may not have permissions to list the contents of the directory.

(Issue originally noted in PR #5178)

## Setup Reproduction
This is an example on a Linux system where the user cannot read the home directory.

As root user, create `/opt/root-only` with permissions so that only root can read:
```
# mkdir -p /opt/root-only
# chmod 700 /opt/root-only
# ls -ld /opt/root-only
drwx------ - root 2022-01-19 15:26 /opt/root-only/
```

## Current Behavior

Run `rustfmt` as a non-root user with their home directory set to the directory created above (user should not have permissions to read directory):
```
$ HOME=/opt/root-only rustfmt --check /dev/null
Permission denied (os error 13)
```

## Expected Behavior

Ideally, the error above should show more context about what file could not be opened, why the file was opened (to find config), etc.

```
$ HOME=/opt/root-only rustfmt --check /dev/null
Could not read home directory "/opt/root-only": Permission denied (os error 13)
```

**Comment by calebcartwright** [comment] 2022-01-26 23:19
Thank you for opening this. I have two questions/asks:

- You've mentioned panics in a couple places, but from the output you've shared, I'm only seeing errors; not panics. Is there some scenario where you're actually seeing a true panic, and if so, could you please open a separate issue with a minimal repro? If not, let's update the description as exiting with an error (regardless of how good/bad the message is) is quite different than panicking
- Could you please make the scope more specific and concrete? As originally reported, the issue is rather vague and high level. Yes, it includes on example, but implies others, and that ambiguity makes tracking the issue more challenging than it needs to be (i.e. how does one know when it is resolved?)

**Comment by tmfink** [comment] 2022-01-28 08:24
@calebcartwright I reworded the title/description of the issue. Hopefully it's more clear. There was never a panic--only an exit on error.

At least in the error path described, the error message is just confusing--it does not indicate what attempted action lead to "permission denied".

**Comment by ytmimi** [comment] 2022-05-10 19:04
Going to close this as #5207 addressed this issue

**Closed by ytmimi** 2022-05-10 19:04 UTC
