### ISSUE TITLE
Poor formatting of if-else-if chain with the default case comment and #[cfg(...)] for conditional compilation.

### ISSUE THREAD

**Issue by JohnScience** [rust-lang/rustfmt#4780] opened 2021-04-02 08:44 UTC
**Input**

```rust
#![feature(vec_into_raw_parts)]

use std::io;

#[cfg(all(not(target_family="unix"), not(target_family="windows")))]
    compile_error!("Unknown EOL (End-of-line) for the target OS family.");
const EOL_LENGTH :usize =
    if cfg!(target_family="unix") { "\n".len() }
    else /* if cfg!(target_family="windows") */ { "\r\n".len() };

fn main() -> io::Result<()> {
    println!("Привет, как тебя зовут?");
    println!(
        "Очень приятно познакомиться, {name}. А меня зовут Феррис. Я талисман Раст. *клац-клац*",
        name = {
            let mut name_buffer = String::new();
            // Переменная name_buffer будет содержать перенос строки после чтения строки в неё.
            io::stdin().read_line(&mut name_buffer).unwrap();
            // String::truncate() совершает ненужную проверку на границы UTF-8 символов.
            {
                let (ptr, len, cap) = name_buffer.into_raw_parts();
                unsafe { String::from_raw_parts(ptr, len - EOL_LENGTH, cap) }
            }
        }
    );
    // Переменная name_buffer здесь не определена, так как находится вне её области видимости.
    Ok(())
}
```

**Output**

```rust
#![feature(vec_into_raw_parts)]

use std::io;

#[cfg(all(not(target_family = "unix"), not(target_family = "windows")))]
compile_error!("Unknown EOL (End-of-line) for the target OS family.");
const EOL_LENGTH: usize = if cfg!(target_family = "unix") {
    "\n".len()
} else
/* if cfg!(target_family="windows") */
{
    "\r\n".len()
};

fn main() -> io::Result<()> {
    println!("Привет, как тебя зовут?");
    println!(
        "Очень приятно познакомиться, {name}. А меня зовут Феррис. Я талисман Раст. *клац-клац*",
        name = {
            let mut name_buffer = String::new();
            // Переменная name_buffer будет содержать перенос строки после чтения строки в неё.
            io::stdin().read_line(&mut name_buffer).unwrap();
            // String::truncate() совершает ненужную проверку на границы UTF-8 символов.
            {
                let (ptr, len, cap) = name_buffer.into_raw_parts();
                unsafe { String::from_raw_parts(ptr, len - EOL_LENGTH, cap) }
            }
        }
    );
    // Переменная name_buffer здесь не определена, так как находится вне её области видимости.
    Ok(())
}
```

**Expected output (unchanged)**

**or**

```rust
#![feature(vec_into_raw_parts)]

use std::io;

#[cfg(all(not(target_family="unix"), not(target_family="windows")))]
    compile_error!("Unknown EOL (End-of-line) for the target OS family.");
const EOL_LENGTH :usize =
    if cfg!(target_family="unix")               { "\n".len()    }
    else /* if cfg!(target_family="windows") */ { "\r\n".len()  };

fn main() -> io::Result<()> {
    println!("Привет, как тебя зовут?");
    println!(
        "Очень приятно познакомиться, {name}. А меня зовут Феррис. Я талисман Раст. *клац-клац*",
        name = {
            let mut name_buffer = String::new();
            // Переменная name_buffer будет содержать перенос строки после чтения строки в неё.
            io::stdin().read_line(&mut name_buffer).unwrap();
            // String::truncate() совершает ненужную проверку на границы UTF-8 символов.
            {
                let (ptr, len, cap) = name_buffer.into_raw_parts();
                unsafe { String::from_raw_parts(ptr, len - EOL_LENGTH, cap) }
            }
        }
    );
    // Переменная name_buffer здесь не определена, так как находится вне её области видимости.
    Ok(())
}
```

**Meta**

- rustfmt version: rustfmt 1.4.36-nightly (7de6968e 2021-02-07)
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment] 2021-04-04 22:06
hi thanks for reaching out, but I'm going to close this.

rustfmt is an AST-driven pretty printer style of formatter which reformats the input code to align to the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs), and by design it does not take the original/input styling into account.

Your original input code is quite divergent from the Rust Style Guide, while the output is aligned, so this is expected formatting behavior.

**Closed by calebcartwright** 2021-04-04 22:06 UTC
