### ISSUE TITLE
`rusfmt` misses some nested modules

### ISSUE THREAD

**Issue by pchampin** [rust-lang/rustfmt#4894] opened 2021-07-09 14:33 UTC
Consider a project with the following structure
```
src
|- lib.rs
|- m1
|  |- mod.rs
|  `- m11.rs
`- m2
  `- m21.rs
```
`lib.rs` contains
```
pub mod m1;
pub mod m2 {
    pub mod m21;
}
```
and  `m1/mod.rs` contains
```
pub mod m11;
```

`rustfmt src/lib.rs` visits all files **except** `m11.rs`. It seems that it does not expect embedded module (in that case `m1`) to contain "external" modules themselves...

I am using `rustfmt 1.4.37-stable (2a3635d 2021-05-04)`

**Comment by calebcartwright** [comment] 2021-07-18 03:27
Closing as duplicate of #4874. Understand it's a slightly different use case but it's the same underlying issue that was fixed on nightly a while back. Fix was backported to beta but don't think the release team was planning on a backport to stable.

**Closed by calebcartwright** 2021-07-18 03:27 UTC
Labels: duplicate
