### ISSUE TITLE
Rustfmt seems not working on this indention-messed file

### ISSUE THREAD

**Issue by Officeyutong** [rust-lang/rustfmt#5199] opened 2022-01-28 06:07 UTC
```rust
use rusqlite::{params, Connection, OptionalExtension};
#[derive(Default)]
struct TestModel {
    pub group_id: i64,
    pub user_id: i64,
    pub time: i64,
}

struct MyStruct {
    conn: Option<Connection>,
}
impl MyStruct {
    pub fn test(&self, group_id: i64, user_id: i64) -> rusqlite::Result<TestModel> {
        let db = self.conn.as_ref().unwrap();
        let query_result = db.
        query_row("SELECT * FROM SIGNINS WHERE GROUP_ID = ? AND USER_ID = ? ORDER BY TIME DESC LIMIT 1", params![group_id, user_id], 
        |r|Ok(TestModel{
            group_id:r.get(0)?,

    user_id:r.get(1)?,            time:r.get(2)?,
        })).optional();
        return Ok(query_result?.unwrap_or(TestModel::default()));
    }
}
fn main() {}

```
The closure in the call to `query_row` has a messed indention, but running `rustfmt ./src/main.rs` makes no change to this file.

I'm using `rustfmt 1.4.38-stable (db9d1b20 2022-01-20)`, the only dependency of this program is `rusqlite = { version = "0.26.3", features = ["bundled"] }`

**Comment by calebcartwright** [comment] 2022-01-29 05:15
Closing as a duplicate of #3863

**Closed by calebcartwright** 2022-01-29 05:15 UTC
Labels: duplicate
