### ISSUE TITLE
spooky extra space added when accessing fields in nested tuple structs

### ISSUE THREAD

**Issue by EllenNyan** [rust-lang/rustfmt#4622] opened 2021-01-03 20:29 UTC
**Input**

```rust
struct Bar(());
struct Foo(Bar);

fn main() {
    let foo = Foo(Bar(()));

    foo.0.0;
}
```

**Output**

```rust
struct Bar(());
struct Foo(Bar);

fn main() {
    let foo = Foo(Bar(()));

    foo.0 .0;
}
```

**Expected output**

```rust
struct Bar(());
struct Foo(Bar);

fn main() {
    let foo = Foo(Bar(()));

    foo.0.0;
}
```

**Meta**

- rustfmt version: 1.4.30-nightly (acd9486 2020-12-0)
- From where did you install rustfmt?: rustup (happens on playground too)

**Comment by calebcartwright** [comment] 2021-01-03 20:31
Duplicate of various issues (e.g. #4543), explained in https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276

**Closed by calebcartwright** 2021-01-03 20:31 UTC
Labels: poor-formatting
