### ISSUE TITLE
Comments between match guard and `=>` token confuse rustfmt

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/rustfmt#4484] opened 2020-10-21 04:49 UTC
**Describe the bug**

rustfmt silently no-ops on this file:

```
fn f() {
    match foo {
        Bar /* asdf */ => todo!(),
        Quux => { if let Some(xyz)=g(){}else{}}}
}
```

**Meta**

- rustfmt version: `rustfmt 1.4.22-nightly (97d0301 2020-10-04)`
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment] 2020-10-21 17:03
Thank you for the report, but this is a duplicate of #4119

**Closed by calebcartwright** 2020-10-21 17:03 UTC
Labels: bug
