### ISSUE TITLE
Not fixing indentation in long statement with multiple indentation levels and long string literals

### ISSUE THREAD

**Issue by faern** [rust-lang/rustfmt#4316] opened 2020-07-10 13:50 UTC
**Input**

```rust
fn create_app() -> App {
    let mut app = App::new("A program name")
                .about("A program that does stuff to computers")
        .arg(
            Arg::with_name("disable_foo_bar")
            .long("disable-foo-bar")
            .help("Disable all the foos in the bar. Prevents things from going all baz on you for example")
            );
    app
}
```

**Output**

Nothing changes

**Expected output**

I expect the indentation of the `.about(...)`, `.long(...)` and `.help(...)` as well as the final `);` to be fixed. But they are not.

It all works as expected if the string passed to `.help(....)` is shorter.

```rust
fn create_app() -> App {
    let mut app = App::new("A program name")
        .about("A program that does stuff to computers")
        .arg(
            Arg::with_name("disable_foo_bar")
                .long("disable-foo-bar")
                .help("Disable all the foos in the bar. Prevents things from going all baz on you for example")
        );
    app
}

```

**Meta**

- rustfmt version: Tested on both `rustfmt 1.4.16-stable (939e164 2020-06-11)` and `rustfmt 2.0.0-rc.2-nightly (2c39e809 2020-07-10)`
- From where did you install rustfmt?: 1.4.16 via the default component via rustup. 2.0.0.-rc.2 from the git master branch today.

**Comment by ayazhafiz** [comment] 2020-07-10 15:07
Maybe a dupe of #4183?

**Comment by calebcartwright** [comment] 2020-07-10 15:14
Yeah this is a duplicate of several issues, all driven by rustfmt's current behavior wherein if any single chain item exceeds max_width then the entire chain is left unformatted.

The general consensus/desire seems to be to have rustfmt format the chain anyway (and just let the problematic item(s) exceed the width). I spent some time a while ago fighting this and had a semi-working fix though I was somewhat unhappy with my implementation attempt and dropped it :smile: 

Part of the challenge with carrying on with formatting the entire chain is dealing with certain combinations of indent_style and where the long item is within the chain. For example when `indent_style` is `Visual` and the long chain item is the parent or first item, you can end up with a formatted result that's far worse than the original. 

Anyway, thanks for reporting this @faern but I'm going to close this given the dupe nature. Feel free to track #4183!

**Closed by calebcartwright** 2020-07-10 15:14 UTC
Labels: duplicate, poor-formatting
