### ISSUE TITLE
When "use" lines are re-arranged, inline comments are placed on the wrong line

### ISSUE THREAD

**Issue by Teknomancer** [rust-lang/rustfmt#4739] opened 2021-03-06 07:19 UTC
**Describe the bug**

When `use` lines are re-arranged by the formatter, comments are moved to the wrong line.

**To Reproduce**

1. `cargo new hello_world --bin`
2. `cd hello_world`
3. Edit `src/main.rs` to have these exact lines (order of lines is important)
```
use std::convert::TryFrom;
use std::fmt;
use std::collections::{Vec, VecDeque};  // testing

fn main() {
    println!("Hello, world!");
}
```
4. `cargo fmt`
5. Check `src/main.rs`, the `//testing` comment has been moved from `std::collections` line to `std::fmt` line as shown below:
```
use std::collections::{Vec, VecDeque};
use std::convert::TryFrom;
use std::fmt; // testing

fn main() {
    println!("Hello, world!");
}
```

**Expected behavior**

The comments in `use` lines should stay with the same line when lines are re-arranged (I'm assuming it's done in alphabetical order). In the above example it would be:
```
use std::collections::{Vec, VecDeque};  // testing
use std::convert::TryFrom;
use std::fmt;
```

**Meta**

- rustfmt version: `rustfmt 1.4.25-stable (0f29ff6d 2020-11-11)`
- From where did you install rustfmt?: `rustup component add rustfmt`
- How do you run rustfmt: `cargo-fmt`

I'm running this on Windows 10 (64-bit) host.

**Comment by calebcartwright** [comment] 2021-03-06 19:52
Closing as duplicate of #4027/#3720

**Closed by calebcartwright** 2021-03-06 19:52 UTC
Labels: duplicate
