### ISSUE TITLE
Needlessly large expansion when using '@' sign to bind names to certain patterns

### ISSUE THREAD

**Issue by kaikalii** [rust-lang/rustfmt#4133] opened 2020-04-21 00:25 UTC
I have a struct like this:
```rust
struct Foo {
    val: u32,
    kinda_long_field_name: bool,
}
```
I want to do a match on a value of type `Result<Foo, _>`, which I think should probably be formatted like this: 
```rust
#[rustfmt::skip]
match foo {
    Ok(f @ Foo {
        kinda_long_field_name: false,
        ..
    }) => {},
    Ok(Foo {
        val,
        kinda_long_field_name,
    }) => {},
    Err(()) => {},
}
```
However, it gets weirdly formatted to this: 
```rust
match foo {
    Ok(
        f
        @ Foo {
            kinda_long_field_name: false,
            ..
        },
    ) => {}
    Ok(Foo {
        val,
        kinda_long_field_name,
    }) => {}
    Err(()) => {}
}
```

...which I think is kind of odd behavior.

I know that '@' and this kind of name-to-pattern binding is pretty niche and uncommon, but I think it should probably still format in a nice way.

**Comment by calebcartwright** [comment] 2020-04-21 00:58
Thanks for reaching out @kaikalii!

This is a duplicate of #4031 and has already been fixed. It should be included in the next release of rustfmt, but if you need the fix more urgently you could consider building rustfmt from source in the interim.

**Closed by calebcartwright** 2020-04-21 00:58 UTC
Labels: duplicate
