### ISSUE TITLE
Rustfmt chokes on heavily nested code inside closures

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/rustfmt#4738] opened 2021-03-05 02:57 UTC
**Describe the bug**

In deeply nested code, rustfmt is sometimes not able to get the code within the default `max_width`, so it just bails on formatting the entire statement.

The behavior seems to depend on the specific AST nodes being formatted. For example, it seems to happen in blocks inside of closures, but not in simple function blocks.

I don't want to simply bump up `max_width`, as that will change all the heuristics and join various things to a single line throughout my project.

**To Reproduce**

~Attempt to format this file and note that nothing happens: https://gist.github.com/umanwizard/36aae1346df5b567cf93f6e5d908f47b~

Edit: Actually, look at my comment below.

**Expected behavior**

~The `println` statement should have been de-indented, as it is at the wrong indentation.~

Edit: See my comment below.

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-nightly (87e96027 2021-03-01)
- From where did you install rustfmt?: built from source
- How do you run rustfmt: `rustfmt path/to/file`

**Comment by umanwizard** [comment] 2021-03-05 03:01
Actually, I'm not sure if the linked repro file is demonstrating the particular bug I'm concerned about. (Rustfmt seems unable to format that even if I get rid of a bunch of the indentation... maybe that's a separate bug.)

A real-world example is here: https://github.com/MaterializeInc/materialize/blob/dba61fea9d6f0886ebff554b0353204ab47e1e25/src/dataflow/src/decode/csv.rs#L59

Try changing the indentation of that line 59 and note that Rustfmt can't fix it. It seems to be giving up on formatting anything in the `let stream = stream.unary(...` call.

**Comment by calebcartwright** [comment] 2021-03-05 04:19
Thanks for reaching out, but going to close this as a duplicate of several previous issues (e.g. #3863).

Your [referenced snippet](https://github.com/MaterializeInc/materialize/blob/dba61fea9d6f0886ebff554b0353204ab47e1e25/src/dataflow/src/decode/csv.rs#L59) is actually a chain that [starts up on line 49](https://github.com/MaterializeInc/materialize/blob/dba61fea9d6f0886ebff554b0353204ab47e1e25/src/dataflow/src/decode/csv.rs#L49) via the `read.unary(` call 

And you then have multiple lines of code in the deeply nested closures (which again are themselves part of a massive chain) which are simply not possible to reformat and fit within the max_width limit. One example is the [string on line 134](https://github.com/MaterializeInc/materialize/blob/dba61fea9d6f0886ebff554b0353204ab47e1e25/src/dataflow/src/decode/csv.rs#L134), and there are various cases of comments blowing way past the 100 column limit.

You can either modify your rustfmt config to give it permission to attempt to wrap your strings and comments to make things fit, or you can wrap them yourself and/or refactor things to reduce the requisite indentation levels.

e.g. 
```bash
rustfmt src/dataflow/src/decode/csv.rs --check --config error_on_line_overflow=true,error_on_unformatted=true,format_strings=true,wrap_comments=true,comment_width=75
```

(note cli config overrides used for visibility, config file specification is fine too)

**Closed by calebcartwright** 2021-03-05 04:19 UTC
Labels: duplicate

**Comment by umanwizard** [comment] 2021-03-05 04:23
@calebcartwright is it not considered a bug for `rustfmt` to be unable to format code?

Perhaps the documentation should be changed, then. It [suggests that this is a bug](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#error_on_line_overflow): "If this happens, then it is a bug in Rustfmt."

Anyway, what seems ideal here is a setting that allows `rustfmt` to make lines as long as it needs to if there is no other way to format them, but otherwise respect `max_width` and the other heuristics.

**Comment by umanwizard** [comment] 2021-03-05 04:25
The comments and strings do not seem to be the issue, since [`filter_normal_code`](https://github.com/rust-lang/rustfmt/blob/79c36960af85fa52ae4dc60ec1f83ec7f9b2733f/src/formatting/comment.rs#L1613-L1629) is run before the width is checked.

**Comment by calebcartwright** [comment] 2021-03-05 04:31
> is it not considered a bug for rustfmt to be unable to format code?

Not really sure what this question is in reference to, but the answer is no. If it's my removal of the GitHub label, that's because we use that label for specific purposes (the description of that label is `Panic, non-idempotency, invalid code, etc. `)

If it's in general, then still no. There's plenty of macro calls that rustfmt is unable to format either. In these cases it's really a matter of deferring to the developer to format things that cannot be formatted within the provided constraints.

> The comments and strings do not seem to be the issue, since filter_normal_code is run before the width is checked.

Please read the details in the previously linked issue and review the specific problem lines I pointed you to, as well as the command I've provided that you can run directly to view this in action for yourself. You have a string literal that ends at column 106, all within a chain, hence the duplicate of #3863. Not really keen on debating nor repeating any of those items.
