### ISSUE TITLE
rustfmt should remove `::{self}` in use statements

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rustfmt#6278] opened 2024-08-12 19:56 UTC
In my opinion, rustfmt should rewrite `use std::io::{self};` to `use std::io;`. `use std::io::{self};` can sometimes be left over after removing other imports. If you for example (automatically) import `std::io` and `std::io::Read` (with rust-analyzer) and then remove the `Read` import, `use std::io::{self};` is left behind.

**Comment by ytmimi** [comment] 2024-08-13 14:12
duplicate of https://github.com/rust-lang/rustfmt/issues/6129 and other similar issues. rustfmt doesn't perform the conversion because `use std::io::{self};` and `use std::io;` are semantically different.

**Closed by ytmimi** 2024-08-13 14:12 UTC
Labels: duplicate, a-imports

**Comment by antonilol** [comment] 2024-08-13 15:13
Would it be possible to have rustfmt figure out if they both refer to the same thing and only then rewrite it?

**Comment by calebcartwright** [comment] 2024-08-15 21:58
> Would it be possible to have rustfmt figure out if they both refer to the same thing and only then rewrite it?

Nope. Well more precisely, there's technically a universe in which it could be done but it's note remotely feasible and it's behavior that the tools avoid for good reason (rustfix won't apply this transformation either for the same underlying reasons)
