### ISSUE TITLE
Freeze and severe memory leak trying to format very short file

### ISSUE THREAD

**Issue by shellixyz** [rust-lang/rustfmt#6215] opened 2024-06-24 18:30 UTC
rustfmt 1.7.0-stable (129f3b9 2024-06-10)

To reproduce try to format this text:
```rust
cfg_if!(
    if #[cfg(feature = "xxxx")] {
        if #[cfg(feature = "yyyy")] {
            pub const C1: u8 = 1;
        } else {
            pub const C2: u8 = 2;
        }
    }
);
```

**Comment by ytmimi** [comment] 2024-06-24 19:16
Duplicate of https://github.com/rust-lang/rustfmt/issues/4442

**Closed by ytmimi** 2024-06-24 19:16 UTC
