### ISSUE TITLE
Double quotes in specific positions cause string formatting errors

### ISSUE THREAD

**Issue by waruto210** [rust-lang/rustfmt#6315] opened 2024-09-07 16:40 UTC
If we set `max_width = 100`, and a double quote in the string appears at Col 100 during the formatting process, this double quote will be moved to the next line, causing a syntax error.

```rust
fn main() {
    let value = 1;

    let ret = format!("a.string.have.double.quote.paddinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\"{}\"", value);
}
```

After formatting, the code becomes:

```rust
fn main() {
    let value = 1;

    let ret = format!(
        "a.string.have.double.quote.\
         paddinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\\
         "{}\"",
        value
    );
}
```

**Comment by waruto210** [comment] 2024-09-09 02:23
@ytmimi PTAL

**Comment by ytmimi** [comment] 2024-09-09 15:24
PTAL?

**Comment by waruto210** [comment] 2024-09-09 15:25
> PTAL?

I mean that can you please take a look？

**Comment by ytmimi** [comment] 2024-09-09 15:33
@waruto210 what version of rustfmt are you using, also, what configuration options are you setting?

**Comment by waruto210** [comment] 2024-09-09 15:41
> @waruto210 what version of rustfmt are you using, and what configuration options are you setting?

To reproduce:
`rust-toolchain.toml`
```tmol
channel = "nightly-2024-08-25"
```

`rust-fmttoml`
```toml
max_width = 100
format_strings = true
```
I have also changed the toolchain to some earlier versions，such as `nightly-2024-06-25`, but got the same error.

**Comment by ytmimi** [comment] 2024-09-09 15:49
You shouldn't need to update the toolchain version. rustfmt is pinned to specific nightly toolchain. The issue is most likely a bug with `format_strings` There's been a similar issue about not properly handling escapes posted before.

**Comment by ytmimi** [comment] 2024-09-12 05:24
Did some digging. This is a duplicate of https://github.com/rust-lang/rustfmt/issues/5138

**Closed by ytmimi** 2024-09-12 05:24 UTC
Labels: bug, only-with-option, a-strings
