### ISSUE TITLE
rustfmt fails to ignore/format long match statements

### ISSUE THREAD

**Issue by elenakrittik** [rust-lang/rustfmt#6146] opened 2024-04-11 18:26 UTC
Reproducible on [rust-playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=00eb8d7fe46c6341a0f009be9c2ecd63). May be related to #6141 

Note that it is important to have some spaces on the line between the match arms, otherwise rustfmt works fine. fn item being inside an impl looks to be a requirement as well (at least i couldn't reproduce it on bare fns).

**Comment by ytmimi** [comment] 2024-04-11 18:53
This is a duplicate of #4706 and #5521

The issue is that the input snippet contains trailing whitespace, but you've explicitly told rustfmt not to edit the code using `#[rustfmt::skip]`.

```rust
impl MyStruct {
    #[rustfmt::skip]
    fn query(self, input: MyEnum) -> MyEnum {
        match input {
            MyEnum::AnInsanelyLongEnumVariantIdentifier1 => MyEnum::AnInsanelyLongEnumVariantIdentifier1,
            
// ^^^^^^^^^
// trailing whitespace here
            MyEnum::AnInsanelyLongEnumVariantIdentifier2 => MyEnum::AnInsanelyLongEnumVariantIdentifier2,
        }
    }
}
```

**Closed by ytmimi** 2024-04-11 18:53 UTC
Labels: duplicate, a-rustfmt::skip, e-trailing whitespace
