### ISSUE TITLE
rustfmt inserts a space between consecutive tuple indexes

### ISSUE THREAD

**Issue by brianfeaster** [rust-lang/rustfmt#6008] opened 2024-01-06 05:38 UTC
```
fn main() {
    let t = (((1,),),);
    println!("{:?}", t.0.0.0);
    println!("{:?}", t.0 .0 .0); // rustfmt adds spaces
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4411dc7f98bd6944e937bb662ccebf29)

**Comment by ytmimi** [comment] 2024-01-06 20:56
This is a duplicate of #5745 and other linked issues. This is resolved when using `version=Two`

**Closed by ytmimi** 2024-01-06 20:56 UTC
