### ISSUE TITLE
Internal error: entered unreachable code while formatting

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rustfmt#3702] opened 2019-07-24 17:15 UTC
Happens when formatting https://github.com/paritytech/ink/commit/7bfc9a0b61a4a5af1d66ec0c4ddac29964888785 (and also some earlier commits).

Also look here for CI: https://travis-ci.org/paritytech/ink/builds/563037289#L932

Backtrace:

```
thread 'main' panicked at 'internal error: entered unreachable code', src/tools/rustfmt/src/formatting.rs:322:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
   8: <rustfmt_nightly::format_report_formatter::FormatReportFormatter as core::fmt::Display>::fmt
   9: core::fmt::write
             at src/libcore/fmt/mod.rs:1016
  10: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1288
  11: <std::io::stdio::Stderr as std::io::Write>::write_fmt
             at src/libstd/io/stdio.rs:692
  12: std::io::stdio::print_to::{{closure}}
             at src/libstd/io/stdio.rs:786
  13: std::thread::local::LocalKey<T>::try_with
             at src/libstd/thread/local.rs:257
  14: std::io::stdio::print_to
             at src/libstd/io/stdio.rs:780
  15: std::io::stdio::_eprint
             at src/libstd/io/stdio.rs:811
  16: rustfmt::format_and_emit_report
  17: rustfmt_nightly::Session<T>::override_config
  18: rustfmt::execute
  19: rustfmt::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  24: std::panicking::try
             at src/libstd/panicking.rs:275
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: main
  28: __libc_start_main
  29: <unknown>
```

**Comment by topecongiro** [comment] 2019-07-28 21:11
Thank you for reporting an issue. AFAICT this seems to be a dup of https://github.com/rust-lang/rustfmt/pull/3655. The issue is fixed on 1.3.1 or later.

**Closed by topecongiro** 2019-07-28 21:11 UTC
Labels: duplicate
