### ISSUE TITLE
Large expression ignored

### ISSUE THREAD

**Issue by osa1** [rust-lang/rustfmt#4704] opened 2021-02-18 08:53 UTC
**Describe the bug**

`rustfmt`, when invoked directly or via `cargo fmt`, ignores a large expression, while formatting rest of the file and other files in the same project.

**To Reproduce**

The large expression is: https://github.com/osa1/sg/blob/1465f2491fd4f3fd9b821a5c1c8294cae63ac0f1/src/cli.rs#L56-L136

- Clone the repo: `git clone https://github.com/osa1/sg`
- Checkout the commit: `git checkout 1465f2491fd4f3fd9b821a5c1c8294cae63ac0f1`
- Edit the file `src/cli.rs` to break indentation, or join lines etc. in lines 56-136.
- Run `cargo fmt`, or `rustfmt` directly.

You'll see that the expression won't be formatted. If you break indentation etc. in the rest of the file those will be formatted as expected.

**Expected behavior**

I'd expect the code to be formatted.

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-nightly (257311c3 2021-02-15)
- From where did you install rustfmt?: git repo
- How do you run rustfmt: `cargo-fmt`, or from editor, using [rust-vim](https://github.com/rust-lang/rust.vim)

**Comment by calebcartwright** [comment] 2021-02-19 02:40
Thanks for the report, but going to close this as a duplicate of many previous similar issues and advise subscribing to #3863 

You've got a string lit for one of the help texts that's too long which prevents rustfmt from being able to format the chain to fit within your max_width constraints (default is `100`). 

It's this line in particular (note indentation hits on width not maintained in GitHub copy/paste, but in your code it's well over 100)
```rust
.help("Group matches by file name, print file name once before matches (enabled by default)")
```

Recommendation in these cases is to refactor your code a bit so that it's possible to fit everything within the width limits, either by defining a local with the lit value outside the chain, or by splitting the string into multiple lines yourself, or by enabling `format_strings` to give rustfmt permission to multiline long strings on your behalf.

**Closed by calebcartwright** 2021-02-19 02:41 UTC
Labels: bug
