### ISSUE TITLE
Incorrectly removing `async` from extern "C" blocks

### ISSUE THREAD

**Issue by pauldorehill** [rust-lang/rustfmt#4360] opened 2020-07-31 07:39 UTC
**Describe the bug**

When running rustfmt `async` is removed from my functions:

**To Reproduce**
Add any extern block with `async`, run `cargo fmt` and the `async` will be removed:

```rust
#[wasm_bindgen(module = "clock")]
extern "C" {
    #[wasm_bindgen]
    async fn strike_thirteen();
}
```
becomes
```rust
#[wasm_bindgen(module = "clock")]
extern "C" {
    #[wasm_bindgen]
    fn strike_thirteen();
}
```
**Expected behavior**
My async stays

**Meta**

- rustfmt version: `1.4.15-stable`
- From where did you install rustfmt: `rustup`
- How do you run rustfmt: `cargo fmt` (also VSCode + rust-analyzer)

**Comment by calebcartwright** [comment] 2020-08-01 01:06
Thank you for the report @pauldorehill. This is a duplicate of #4288 that's already been addressed in source but just hasn't been released yet. Closing accordingly

**Closed by calebcartwright** 2020-08-01 01:06 UTC
Labels: bug, duplicate, fixed

**Comment by pauldorehill** [comment] 2020-08-01 03:36
Ah apologies... I only searched open

**Comment by calebcartwright** [comment] 2020-08-02 18:54
No worries! We've got quite a lot of unreleased changes on the master branch, and myriad associated issues that have been closed, so it can be trickier than usual to tell sometimes. Thanks again for reaching out!
