### ISSUE TITLE
Rustfmt sometimes fails to format lambdas with eprintln!

### ISSUE THREAD

**Issue by arxanas** [rust-lang/rustfmt#4624] opened 2021-01-05 01:14 UTC
The following is not formatted correctly (e.g. line with incorrect spacing is untouched). This is the smallest example I could make:

```
fn get_cursor_head_oid(&self) -> Option<git2::Oid> {
    self.events[0..1].iter().find_map(|event| -> Option<git2::Oid> {
        // Obviously bad formatting, should be fixed.
        match       &event        {
            Event::RefUpdateEvent { .. } => {
                match git2::Oid::from_str(&new_ref) {
                    Ok(oid) => Some(oid),
                    Err(_) => {
                        // Try commenting out the below line. Commenting out certain other lines also works.
                        eprintln!("Expected HEAD new_ref to point to an OID; instead pointed to: {:?}", new_ref);
                        None
                    }
                }
            }
        }
    })
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c6da46ef9789be267a350081e0c32c89)

Removing the `eprintln!` line, or removing various other syntax elements (such as`-> Option<git2::Oid>`) causes the lambda contents to be formatted.

Expected formatting should fix the spacing on the first `match` line.

Playground `rustfmt` version: `1.4.30-nightly (2020-12-20 acd9486)`

**Comment by calebcartwright** [comment] 2021-01-05 03:02
Thanks for reaching out. There's two issues with your original snippet (the comment and the string arg) that would result in the formatting blowing past the width limit (default is `100`) which rustfmt does not do. If you were to run rustfmt against the above input with `error_on_unformatted=true` that will permit rustfmt to emit error details, e.g. 

```bash
error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 108)
 --> stdin:9:9:100
  |
9 |                         // Try commenting out the below line. Commenting out certain other lines also works.
  |                                                                                                     ^^^^^^^^
  |
  = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals
```

In cases like these where rustfmt cannot format without violating some other constraint, it simply leaves the existing formatting in place. Here, the failure to be able to format the body of  `Err` arm results in a failure to format that inner match, which then cascades up to top level match, thus the original formatting being left in place.

I know the comment was added for reference and presumably not a part of your original code, but the same width issues come into play for that first lit arg in the eprintln mac call where it _just_ exceeds the limit.
```rust
                        eprintln!(
                            "Expected HEAD new_ref to point to an OID; instead pointed to: {:?}",
                            new_ref
                        );
```
You can address this either by setting the config option: `format_strings=true` to give rustfmt permission to split string lits like these to stay within the `max_width` bounds, and/or you could break the string up into a multiline string yourself at your desired split points.

> such as-> Option<git2::Oid>)

If anything, this would be a potential bug. There's slightly different code paths for closures depending on whether it's a default or explicit ret type, and in the case of the former there's apparently a missing check on the width limit

**Comment by arxanas** [comment] 2021-01-05 05:29
@calebcartwright thanks for the explanation. Is there a way to configure Rustfmt to behave the way it does when I remove the return type, in which it formats everything it can and leaves the too-long string otherwise in place? This would be my preferred behavior.

This would be the preferred formatting:

```
fn get_cursor_head_oid(&self) -> Option<git2::Oid> {
    self.events[0..1].iter().find_map(|event| {
        // Obviously bad formatting, should be fixed.
        match &event {
            Event::RefUpdateEvent { .. } => {
                match git2::Oid::from_str(&new_ref) {
                    Ok(oid) => Some(oid),
                    Err(_) => {
                        // Try commenting out the below line. Commenting out certain other lines also works.
                        eprintln!(
                            "Expected HEAD new_ref to point to an OID; instead pointed to: {:?}",
                            new_ref
                        );
                        None
                    }
                }
            }
        }
    })
}
```

**Comment by calebcartwright** [comment] 2021-01-06 02:10
> Is there a way to configure Rustfmt to behave the way it does when I remove the return type, in which it formats everything it can and leaves the too-long string otherwise in place? This would be my preferred behavior.

Nope. What you're telling rustfmt to do right now is:

* reformat my code so that everything fits within 100 columns
* but don't split any of my string lits
* apply all other indentation rules from the style guide

and you've got your code structured in a way that it's impossible to comply. in these cases rustfmt intentionally defers to the programmer, so that you can either refactor your code or change your configuration (i.e. increased max allowed width).

Your request would require adding the ability for rustfmt to contradict itself/violate the formatting rules it's governed by. The fact that it currently does this silently on a closure with a default return type is a bug, not a feature.

My advice for you is still to either increase your width limit, or split the lit:
```rust
                        eprintln!(
                            "Expected HEAD new_ref to point to an OID; \
                             instead pointed to: {:?}",
                            new_ref
                        );
```

**Comment by ytmimi** [comment] 2022-07-26 15:21
Closing this as a duplicate of #3863

**Closed by ytmimi** 2022-07-26 15:21 UTC
Labels: duplicate, a-comments, a-chains
