### ISSUE TITLE
`where` clauses in GAT impls aren't formatted

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rustfmt#5580] opened 2022-10-31 01:45 UTC
Playground example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1ef166f9e2b31f3f4093728719de4efc

```rust
pub trait Test {
    type Ref<'a> where Test: 'a;
}

impl<T, U> Test for (T,) {
    type Ref<'a> = (&'a T,) where T: 'a;
}

impl<T, U> Test for (T, U) {
    type Ref<'a> = (&'a T, &'a U) where T: 'a, U: 'a;
}
```

The above autoformats to:

```rust
pub trait Test {
    type Ref<'a>
    where
        Test: 'a;
}

impl<T, U> Test for (T,) {
    type Ref<'a> = (&'a T,) where T: 'a;
}

impl<T, U> Test for (T, U) {
    type Ref<'a> = (&'a T, &'a U) where T: 'a, U: 'a;
}
```

You'll notice that the `where` clauses for the impls aren't formatted at all, whereas I would expect:

```rust
pub trait Test {
    type Ref<'a>
    where
        Test: 'a;
}

impl<T, U> Test for (T,) {
    type Ref<'a> = (&'a T,)
    where
        T: 'a;
}

impl<T, U> Test for (T, U) {
    type Ref<'a> = (&'a T, &'a U)
    where
        T: 'a,
        U: 'a;
}
```

**Comment by ytmimi** [comment] 2022-10-31 15:55
Thanks for reaching out!

I haven't had a chance to look into this yet, but I'll try to dig into this when I've got a little more time

**Comment by derekdreery** [comment] 2022-11-04 12:21
I hit an issue where a longer GAT where clause had a linebreak inserted. This then caused an internal error on `rustfmt --check`. I suspect this issue will go away as and when formatting for GATs is implemented, but wanted to record it.

**Comment by ytmimi** [comment] 2022-11-04 13:49
@derekdreery would it be possible for you to post a code snippet? It would help in the investigation!

**Comment by derekdreery** [comment] 2022-11-04 13:55
Hi @ytmimi. It seems like I can't reproduce the problem - good news! It might have been something to do with the upgrade that is now resolved. Will report back here if I manage to reproduce it again.

**Comment by ytmimi** [comment] 2022-11-04 15:05
That is good news! I appreciate you taking the time to look into it

**Comment by derekdreery** [comment] 2022-11-04 15:06
@ytmimi no worries thanks for an awesome tool!

**Comment by CJKay** [comment] 2023-04-21 01:50
Still seems to be occurring - the associated type declaration in the trait formats fine, but the impl remains untouched.

**Comment by tamird** [comment] 2023-09-07 17:13
Note that this doesn't require GATs; it happens on any associated type in an impl that has a where clause. From #5751: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=448e25cc22bb316f236e5ee6aeb455de.

**Comment by clarfonthey** [comment] 2023-09-07 22:34
Aren't those still considered GATs? I was under the impression that any conditions on associated types were forbidden before GATs were stabilised, and the code is shared for all of them.

**Comment by ia0** [comment] 2024-10-29 10:27
I suspect this is now fixed, although in a weird way. Notice how the actual output differs from the expected output in the original issue comment. You can use the playground link provided there to reproduce.

```rust
pub trait Test {
    type Ref<'a>
    where
        Test: 'a;
}

impl<T, U> Test for (T,) {
    type Ref<'a>
        = (&'a T,)
    where
        T: 'a;
}

impl<T, U> Test for (T, U) {
    type Ref<'a>
        = (&'a T, &'a U)
    where
        T: 'a,
        U: 'a;
}
```

**Comment by ytmimi** [comment] 2024-10-29 13:52
@ia0 Thanks for pointing out that this one is now resolved. The current formatting is expected. As of rustfmt [1.8.0](https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#180-2024-09-20) trailing where clauses in type aliases started to get formatted, and formatting is following the rules outlined [by the style guide](https://doc.rust-lang.org/nightly/style-guide/items.html#type-aliases).

If you'd like to propose a different default style you can open an issue on [the style-team's repo](https://github.com/rust-lang/style-team), or if you'd like to propose a new formatting option in rustfmt you can open a new issue to outline the idea.

**Comment by ytmimi** [comment] 2024-10-29 13:52
closed by https://github.com/rust-lang/rustfmt/pull/5887

**Closed by ytmimi** 2024-10-29 13:52 UTC
Labels: poor-formatting, p-low

**Comment by ia0** [comment] 2024-10-29 14:00
Sounds good, thanks for the link!
