### ISSUE TITLE
assignment is not formatted properly

### ISSUE THREAD

**Issue by BenjaminBrienen** [rust-lang/rustfmt#6394] opened 2024-11-17 00:35 UTC
"formatted" code:
```rs
    pub(crate) fn register_info<T: Bundle>(
        &mut self,
        components: &mut Components,
        storages: &mut Storages,
    ) -> BundleId {
        let bundle_infos = &mut self.bundle_infos;
        let id = *self.bundle_ids.entry(TypeId::of::<T>()).or_insert_with(|| {
            let mut component_ids= Vec::new();
            T::component_ids(components, storages, &mut |id| component_ids.push(id));
            let id = BundleId(bundle_infos.len());
            let bundle_info =
                // SAFETY: T::component_id ensures:
                // - its info was created
                // - appropriate storage for it has been initialized.
                // - it was created in the same order as the components in T
                unsafe { BundleInfo::new(core::any::type_name::<T>(), components, component_ids, id) };
            bundle_infos.push(bundle_info);
            id
        });
        id
    }
```

The focus:
```rs
let mut component_ids= Vec::new();
```

Expected:
```rs
let mut component_ids = Vec::new();
```

**Comment by ytmimi** [comment] 2024-11-18 16:38
This line `                unsafe { BundleInfo::new(core::any::type_name::<T>(), components, component_ids, id) };` is 103 characters long, which exceeds the default `max_width` of `100`. Because this is inside the `.or_insert_with()` call this is a duplicate of #3863. You can bump the `max_width` and rustfmt will be able to format this chained method call.

**Closed by ytmimi** 2024-11-18 16:38 UTC
Labels: duplicate
