### ISSUE TITLE
Configuration option request: don't reindent comments

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rustfmt#4030] opened 2020-01-24 17:08 UTC
There are cases where personal comment placement style might differ from the rustfmt style, and it'd be nice to be able to choose, but I don't see an option about aligning/reindenting/moving comments around or not. 

I don't know that my issues here are bugs necessarily, because I could see what rustfmt is doing being the right thing in other situations. 🤷‍♀ 

This might be a duplicate of https://github.com/rust-lang/rustfmt/issues/763 but [this comment](https://github.com/rust-lang/rustfmt/issues/763#issuecomment-272964557) says comments are skipped by default, but that's not what I'm seeing...? Perhaps that issue means something different than I do by "formatting comments".

Examples:

rustfmt 1.4.11-nightly (2019-12-03 1838235)

```
fn main() {
    {              // I would like to talk about this scope
        let x = 3; // and continue the comment here
    }              // and even down here
    // but here is a different topic that I don't want aligned
}
```

rustfmt changes this into:

```
fn main() {
    {
        // I would like to talk about this scope
        let x = 3; // and continue the comment here
    } // and even down here
      // but here is a different topic that I don't want aligned
}
```

Possibly related issues that might not be bugs that could instead be dealt with by turning off comment moving/formatting:

- https://github.com/rust-lang/rustfmt/issues/3255
- https://github.com/rust-lang/rustfmt/issues/4014
- https://github.com/rust-lang/rustfmt/issues/3979

**Comment by phi-gamma** [comment] 2020-07-17 08:04
Seconding the issue. With Rust 1.45 and ``cargo +stable fmt``
rustfmt produces nonsensical indentation like this:

    +            }
    
    -//          eprintln!("ClientOpts: invoking client using opts=[{:?}] ⇒ argv=[{:?}]",
    -//                    self, argv);
    +            //          eprintln!("ClientOpts: invoking client using opts=[{:?}] ⇒ argv=[{:?}]",
    +            //                    self, argv);
    
                 Client::run_with_argv(&argv, &prefix)

and damages comments like this:

     /** A status code used with all API functions. Further results
    -    have to be transported as out parameters. */
    +have to be transported as out parameters. */
     #[repr(C)]
     #[allow(non_camel_case_types)]
     #[derive(PartialEq, Debug, Clone, Copy)]
     pub enum APX_status {

Adorning all comments with skip attributes isn’t a workable solution.

It would be great if there was at least a way to indicate to rustfmt that it
should leave comments alone. Even better if it were possible to teach it the
commenting style of a given project.

**Comment by georgefst** [comment] 2020-10-15 12:27
#4108 is similar, and points out that this is inconsistent with `rustfmt`'s apparent decision to stick to block based indentation.

This is annoying for me mostly because of the interaction with version control. For example, adding one value to an enum can cause the entire declaration to become part of a diff.

**Comment by ytmimi** [comment] 2022-07-26 02:06
Closing this as a duplicate of #1264

**Closed by ytmimi** 2022-07-26 02:06 UTC
Labels: duplicate, a-comments, feature-request
