### ISSUE TITLE
rustfmt incorrectly removing blank lines between non-doc comments and doc comments in struct definition

### ISSUE THREAD

**Issue by woody77** [rust-lang/rustfmt#5916] opened 2023-09-18 18:55 UTC
Using `rustfmt 1.5.3-nightly (75726cae373 2023-06-28)`

The following source:
```
/// Writes lines to the file
struct Foo {
  // Set during initialization, and not changed later:

  /// destination file path
  file_path: PathBuf
```
is formatted as:
```
/// Writes lines to the file
struct Foo {
  // Set during initialization, and not changed later:
  /// destination file path
  file_path: PathBuf
```

However, if an additional blank line is added, and another (empty) non-doc comment is used rustfmt doesn't change it:
```
/// Writes lines to the file
struct Foo {
  // Set during initialization, and not changed later:

  //
  /// destination file path
  file_path: PathBuf
```

If the non-doc comment is changed to a doc-comment, rustfmt also doesn't change it:
```
/// Writes lines to the file
struct Foo {
  /// Set during initialization, and not changed later:

  /// destination file path
  file_path: PathBuf
```
But then the comment is included in the documentation for the `file_path` field, which is not desired.

**Comment by woody77** [comment] 2023-09-18 18:58
This appears to be similar to #4930 and #3716.  I suspect that all three are caused by not treating the doc comment that follows a comment as another comment, and so it's being removed to keep comments with the statements that they are meant to be about.

**Comment by ytmimi** [comment] 2023-09-19 18:10
Thanks for reaching out. I believe this is a duplicate of the issues you've linked to above so I'll go ahead and close this one.

**Closed by ytmimi** 2023-09-19 18:10 UTC
