### ISSUE TITLE
rustfmt should have options to format in tabular style

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rustfmt#1385] opened 2017-03-16 20:23 UTC
I always try to make my code as readable as possible.
Sometimes this can be achieved best with a tabular layout.  

A good example use case for this is a match expression with many one-line match arms as can be seen in this [GitHub-GIST](https://gist.github.com/Robbepop/6a629dfe67f8f1cf04fff6a4c7d47cf9):

Unfortunately I wasn't able to find a configuration under which rustfmt did not completely destroy this format.
But maybe in future we could go further and implement functionality for rustfmt to create such tabular layouts in situations where it is appropriate.

**Other use cases are:**
 - members of struct definitions type alignment
 - function parameters type alignment
 - let bindings alignments (especially in combination with mut keyword)

**Comment by karyon** [comment] 2018-04-18 18:53
match statements have another issue with some discussion here: #894

**Comment by calebcartwright** [comment] 2022-01-29 05:25
Going to close as the thrust of this is a duplicate of #894. Some of the other items are ostensibly already covered via config options (e.g. https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=threshold#struct_field_align_threshold), and those that are not likely already have a respective report that's more singularly focused (though folks should feel free to report more specific/targeted issues if there's not an existing one already)

**Closed by calebcartwright** 2022-01-29 05:25 UTC
Labels: fun!
