### ISSUE TITLE
Internal error when arm of match block is followed by a blank line in `#[rustfmt::skip]` `fn`. 

### ISSUE THREAD

**Issue by Alfriadox** [rust-lang/rustfmt#6045] opened 2024-01-27 08:23 UTC
Source file: 
```rust
//! First pass lexer that gets run on the source code and returns a series of tokens with their associated [Fragment]s.
//!
//! Note that this will strip out comments and whitespace, returning only fragments that match one of the paterns
//! defined for tokens.

use super::fragment::Fragment;

/// The lexical analyser for wright. This produces a series of tokens that make up the larger elements of the language.
#[derive(Debug)]
pub struct Lexer<'src> {
    /// The remaining source code that has not been processed and returned as a token from the iterator yet.
    pub remaining: Fragment<'src>,
}

/// A token in wright source code.
#[derive(Debug)]
pub struct Token<'src> {
    /// What type of token this is.
    pub variant: TokenTy,
    /// The matching fragment of source code -- this contains the location and length data for the token.
    pub fragment: Fragment<'src>,
}

/// The different types of tokens in wright source.
#[rustfmt::skip] // Turn off auto reformat. 
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenTy {
    LeftCurly, RightCurly,
    LeftBracket, RightBracket,
    LeftParen, RightParen,

    Plus, PlusEq,
    Minus, MinusEq,
    Star, StarEq,
    Div, DivEq,
    Xor, XorEq,
    Mod, ModEq,
    Bang, BangEq,
    Eq, EqEq,

    Lt, LtEq, LtLt,
    Gt, GtEq, GtGt,
    And, AndEq, AndAnd,
    Or, OrEq, OrOr,
    
    Colon, ColonColon,

    At,
    Tilde,
    Underscore,
    Semi,
    Dot,
    Comma,
    Hash,

    Identifier,

    OuterDocComment, OuterBlockDocComment,
    InnerDocComment, InnerBlockDocComment,

    KwRecord,
    KwType,
    KwEnum,
    KwUnion,
    KwFunc,
    KwRepr,
    KwImpl,
    KwConstraint,
    KwTrait,
    KwUse,
    KwAs,
    KwConst,
    KwMod,
    KwIf,
    KwElse,
    KwFor,
    KwIn,
    KwWhile,
    KwTrue,
    KwFalse,
    KwLoop,
    KwWhere,

    /// Unknown character in lexer fragment. 
    Unknown
}

impl<'src> Lexer<'src> {
    /// Get the number of bytes remaining that we need to transform into tokens.
    pub const fn bytes_remaining(&self) -> usize {
        self.remaining.len()
    }

    /// Construct a new lexer over a given reference to a source string.
    pub const fn new(source: &'src str) -> Self {
        Lexer {
            remaining: Fragment { inner: source },
        }
    }

    /// Try to match a single character to a single character token if possible.
    #[rustfmt::skip]
    const fn single_char_tokens(c: char) -> Option<TokenTy> {
        use TokenTy::*;

        match c {
            '{' => Some(LeftCurly),
            '}' => Some(RightCurly),
            '[' => Some(LeftBracket),
            ']' => Some(RightBracket),
            '(' => Some(LeftParen),
            ')' => Some(RightParen),
            
            '@' => Some(At),
            '~' => Some(Tilde),
            '_' => Some(Underscore),
            '.' => Some(Dot),
            ',' => Some(Comma),
            ';' => Some(Semi),
            '#' => Some(Hash),

            _ => None,
        }
    }

    /// Try to match a fragment recognized to be an identifier or keyword to
    /// a keyword or return [TokenTy::Identifier].
    fn identifier_or_keyword(fragment: Fragment<'src>) -> TokenTy {
        use TokenTy::*;

        match fragment.inner {
            "record" => KwRecord,
            "type" => KwType,
            "enum" => KwEnum,
            "union" => KwUnion,
            "func" => KwFunc,
            "repr" => KwRepr,
            "impl" => KwImpl,
            "constraint" => KwConstraint,
            "trait" => KwTrait,
            "const" => KwConst,
            "where" => KwWhere,

            "use" => KwUse,
            "as" => KwAs,
            "mod" => KwMod,

            "if" => KwIf,
            "else" => KwElse,

            "for" => KwFor,
            "in" => KwIn,
            "while" => KwWhile,
            "loop" => KwLoop,

            "true" => KwTrue,
            "false" => KwFalse,

            _ => Identifier,
        }
    }
}
```

Error: 
```
> cargo fmt  
error[internal]: left behind trailing whitespace
   --> \\?\C:\Users\alfri\Documents\Projects\wright\wright-lang\wright\src\parser\lexer.rs:113:113:1
    |
113 |
    | ^^^^^^^^^^^^
    |

warning: rustfmt has failed to format. See previous 1 errors.

> cargo fmt --version
rustfmt 1.7.0-stable (82e1608d 2023-12-21)
> 
```

**Comment by ytmimi** [comment] 2024-01-27 14:24
Thanks for reaching out. Unfortunately when using `#[rustfmt::skip]` removing whitespace is on the developer.

Closing as a duplicate of https://github.com/rust-lang/rustfmt/issues/4706

**Closed by ytmimi** 2024-01-27 14:24 UTC

**Comment by Alfriadox** [comment] 2024-01-27 14:56
I'm fine with that, I don't want it to remove white space in that circumstance, I just want to suppress the error, since I don't think anything labeled with `#[rustfmt::skip]` should be able to produce an error

**Comment by ytmimi** [comment] 2024-01-27 17:52
There's been some previous discussion on error reporting in rustfmt. I can't find any links at the moment, but I know we've mentioned moving to more of an `ignore`/`warn`/`error` model. Right now I think we'll always issue a warning on trailing whitespace so your best option right now is to remove the whitespace.
