### ISSUE TITLE
rustfmt prints "rewriting static" in its output

### ISSUE THREAD

**Issue by asomers** [rust-lang/rustfmt#6210] opened 2024-06-24 02:11 UTC
Commit 30cdc2b3e98e30b4dafdb99d2a14809fe9c79074 from #6204  included what looks like a debugging println! that causes rustfmt to generate invalid rust code.  I don't have a minimal test case, but it's causing failures in combination with bindgen in at least 3 other crates.
Downstream bug: https://github.com/rust-lang/rust/issues/126887

**Comment by compiler-errors** [comment] 2024-06-24 02:31
I've put up a fix in-tree in rust-lang/rust https://github.com/rust-lang/rust/pull/126888 which can later get subtree-sync'd here. @calebcartwright @ytmimi i'm happy to perform the rust->rustfmt subtree sync to pull this in if you'd like.

**Comment by calebcartwright** [comment] 2024-06-24 03:02
Definitely agreed with getting the fix in directly. If you're up for doing a subtree push to bring that over here then that's helpful as well (though not urgent nor impactful on this side)

**Comment by compiler-errors** [comment] 2024-06-24 03:06
Cool, I can do a push tomorrow when this lands.

**Comment by rami3l** [comment] 2024-06-24 11:25
@calebcartwright Maybe adding some `disallowed` rules (https://rust-lang.github.io/rust-clippy/master/#/disallowed) will prevent this from happening again?

**Comment by calebcartwright** [comment] 2024-06-24 15:01
https://github.com/rust-lang/rust/pull/126888 landed but I guess github won't close cross-repo issues still

this issue is resolved (and should only exist in a single nightly release), and there's no additional action to take here so i'm going to close

**Closed by calebcartwright** 2024-06-24 15:01 UTC

**Comment by calebcartwright** [comment] 2024-06-24 15:04
> @calebcartwright Maybe adding some `disallowed` rules (https://rust-lang.github.io/rust-clippy/master/#/disallowed) will prevent this from happening again?

certainly an option, although we don't regularly run clippy on this repo and don't gate CI on a passing clippy check

i'm also surprised that this didn't cause any test failures. if the issue was only reproducible when running rustfmt with stdin/stdout (which is how RA internally uses rustfmt) then that would explain the lack of test failures, but if it was reproducible via standard rustfmt execution against a file then i'm really puzzled how there wasn't mass failure of tests

**Comment by RalfJung** [comment] 2024-06-24 21:36
> i'm also surprised that this didn't cause any test failures. if the issue was only reproducible when running rustfmt with stdin/stdout (which is how RA internally uses rustfmt) then that would explain the lack of test failures, but if it was reproducible via standard rustfmt execution against a file then i'm really puzzled how there wasn't mass failure of tests

In standard rustfmt execution, the message appears in the terminal but not in the file. So it doesn't break anything.

**Comment by calebcartwright** [comment] 2024-06-26 19:58
> I don't see stdin documented by `rustfmt --help`. Is this not something that is meant to be public?

You're right that's not explicitly clear in the help text, but it's also not something that's intended to be a secret: https://github.com/rust-lang/rustfmt?tab=readme-ov-file#running-rustfmt-directly
