### ISSUE TITLE
BUG: nightly removing doc comments

### ISSUE THREAD

**Issue by joshka** [rust-lang/rustfmt#5965] opened 2023-11-25 02:23 UTC
In Ratatui, we format using nightly to take advantage of a few nightly only configuration settings.

Today, in addition to a bunch of changes that seem to make the code easier to read, I noticed that rustfmt started removing doc comments from the source code, which is really odd.

A PR that shows the problematic changes:
https://github.com/ratatui-org/ratatui/pull/645/files#diff-628d0c731b37af0b4b3e76450a4b5fa9efc05880d9038403ee7663f171f07f2a

Specifically the first change is in src/backend/crossterm.rs, but there are a few similar changes.

I've run rustup update which got:
   nightly-aarch64-apple-darwin updated - rustc 1.76.0-nightly (37b2813a7 2023-11-24) (from rustc 1.76.0-nightly (1e9dda77b 2023-11-22))

Repro steps in case that's not enough:
- gh repo clone ratatui-org/ratatui
- cargo +nightly fmt
and 
rustfmt 1.7.0-nightly (37b2813a 2023-11-24)

Diff:
````diff
impl<W> CrosstermBackend<W>
where
    W: Write,
{
    /// Creates a new `CrosstermBackend` with the given writer.
-    ///
-    /// # Example
-    ///
-    /// ```rust,no_run
-    /// # use std::io::stdout;
-    /// # use ratatui::prelude::*;
-    /// let backend = CrosstermBackend::new(stdout());
-    /// ```
    pub fn new(writer: W) -> CrosstermBackend<W> {
        CrosstermBackend { writer }
    }
}
````

**Comment by xfbs** [comment] 2023-11-25 14:41
Duplicate of https://github.com/rust-lang/rustfmt/issues/5964, I think.

**Comment by ytmimi** [comment] 2023-11-25 15:51
@xfbs yes, I think you're right. I'm pretty sure this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5964. From my understanding this issue was caused by ABI changes in the rust-lang/rust repo and isn't related to code changes in rustfmt itself. https://github.com/rust-lang/rust/pull/118127 should resolve the issues on nightly.

**Closed by ytmimi** 2023-11-25 15:51 UTC

**Comment by joshka** [comment] 2023-11-25 22:45
Thanks :)
