### ISSUE TITLE
Array items aren't formatted correctly when long lines are used

### ISSUE THREAD

**Issue by winterqt** [rust-lang/rustfmt#5558] opened 2022-10-03 02:11 UTC
**rustfmt version**: `1.5.1-nightly (57f097ea 2022-10-01)`
**Options**: default
**Code**:
```rust
fn main() {
    let a = [
(
    foo("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    )
    ];
}

```

Ideally, rustfmt would collapse the array, or indent the parens if multiple items are present, to be in line with how it would format the array if the `aaa` line was shorter.

This may be related to one of the already open long line issues, but just in case, I figured I'd open this separately.

**Comment by ytmimi** [comment] 2022-10-04 00:26
Thanks for reaching out, but going to close this as a duplicate of #4403

**Closed by ytmimi** 2022-10-04 00:26 UTC

**Comment by winterqt** [comment] 2022-10-04 03:04
Ah, somehow missed that. Apologies, and thanks for pointing me in the right direction.
