### ISSUE TITLE
Rustfmt command returns an error despite problematic file being ignored and hide_parse_errors is true

### ISSUE THREAD

**Issue by maplant** [rust-lang/rustfmt#3916] opened 2019-11-09 00:20 UTC
I have a problematic file that is not able to be parsed. The reason for that is I'm autogenerating symbol names with macros, in a manner that looks like this:
```rust
#[no_mangle]
extern "system" fn jni_symbol!( funcName ) ( ... ) -> {} 
```
Rustfmt is failing to parse this at the token `!`, but the larger issue is that I'm failing rusty-hooks despite this file being put into ignore, hide_parse_errors being set to true and no error being emitted and rustfmt seemingly handling every other file just fine. I know that this file is the one that is causing issues because commenting it out results in rustfmt returning 0 as it should

**Comment by calebcartwright** [comment] 2019-11-09 01:31
hey @maplant - what happens if you change `hide_parse_errors` to `false` in your config and keep that file listed under `ignore`? I added a change a while back to handle recoverable parser errors in ignored files, but I think I have a theory why this is happening and believe it's related to `hide_parse_errors` being set to true

**Comment by maplant** [comment] 2019-11-09 03:32
@calebcartwright the same effect is observed for me

**Comment by calebcartwright** [comment] 2019-11-09 05:49
The underlying problem is that the parser is hitting a fatal error on your snippet, and is unable to create the ast. As such rustfmt is unable to start formatting and exits with an error as well.

In instances where the parser encounters errors, but was still able to recover and construct the ast, rustfmt is able to start formatting and will not exit with an error if all the parser errors (or formatting errors of course) originated in an `ignore`d file.

In your case, rustfmt returning an error code in the presence of that unparseable snippet is expected because rustfmt needs the ast to be able to format the code. How are you running rustfmt in your project, are you using `cargo fmt` or running `rustfmt` directly against specified files? 

Related aside, there's a couple minor improvements we should make on the rustfmt side anyway (@topecongiro I'll start working on these shortly)

* should still emit the error when the associated DB level is Fatal, regardless of whether the source file is `ignore`d since the parser won't be able to give rustfmt the ast anyway
* even when `hide_parse_errors` is true, the associated emitter should include the same logic checks to see if DB source file origin was in an `ignore`d file so that the same error reset logic can be used to ignore the recoverable parser errors

**Comment by maplant** [comment] 2019-11-09 06:25
I am using cargo fmt to run rustfmt.
I understand that this is producing an error, if I remove the file from ignored it prints the error. 

I would claim that it is unexpected behavior to create an error condition for being unable to build the AST for an ignored file. If the file is ignored, why is it being parsed at all?

**Comment by calebcartwright** [comment] 2019-11-09 06:26
That's the rustc parser doing the parsing, and it doesn't take rustfmt's config file into consideration

**Comment by maplant** [comment] 2019-11-09 06:42
Ah I'm sorry I had some build issues that were obscuring the parse error in my build; I genuinely thought the snippet I sent was valid. Oops!

**Comment by calebcartwright** [comment] 2019-11-09 06:44
> Ah I'm sorry I had some build issues that were obscuring the parse error in my build; I genuinely thought the snippet I sent was valid. Oops!

No worries! I found a couple things while looking through this that we should improve anyway, so it was a helpful question regardless!

**Comment by topecongiro** [comment] 2019-11-14 00:40
Closing as if I understand correctly the rustfmt error was due to the source code unparsable, which is an expected behavior. Please feel free to reopen if there are any issues.

**Closed by topecongiro** 2019-11-14 00:40 UTC
