### ISSUE TITLE
Consider array accesses part of a chain?

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rustfmt#2139] opened 2017-11-11 08:00 UTC
Consider the following function:

```rust
fn read_format(name: &str) -> u8 {
    ok!(name.split("format").collect::<Vec<_>>()[1].split(".").collect::<Vec<_>>()[0].parse())
}
```

After running rustfmt-nightly, one obtains the following:

```rust
fn read_format(name: &str) -> u8 {
    ok!(
        name.split("format").collect::<Vec<_>>()[1]
            .split(".")
            .collect::<Vec<_>>()[0]
            .parse()
    )
}
```

I’m wondering if it’s the expected behavior. Shouldn’t it be as shown below?

```rust
fn read_format(name: &str) -> u8 {
    ok!(
        name.split("format")
            .collect::<Vec<_>>()[1]
            .split(".")
            .collect::<Vec<_>>()[0]
            .parse()
    )
}
```

**Comment by topecongiro** [comment] 2017-11-11 08:24
I think this is due to how rustc parses the given expression. Since rustfmt formats the code based on AST, it considers that there are three separate chains in the above code.

**Comment by nrc** [comment] 2017-11-12 23:51
I guess we could manipulate the AST to consider array access as part of a chain like `?`. I'm not sure if we should do that though.

**Comment by ytmimi** [comment] 2022-07-20 03:49
Using `rustfmt 1.5.1-nightly (0f93f53e 2022-07-19)` I get the following formatting:

**Input**
```rust
fn read_format(name: &str) -> u8 {
    ok!(name.split("format").collect::<Vec<_>>()[1].split(".").collect::<Vec<_>>()[0].parse())
}
```

**output**
```rust
fn read_format(name: &str) -> u8 {
    ok!(name.split("format").collect::<Vec<_>>()[1]
        .split(".")
        .collect::<Vec<_>>()[0]
        .parse())
}
```

@calebcartwright it feels like this is the intended behavior, so I'm wondering if we can close this issue?

**Closed** 2022-12-24 21:12 UTC
Labels: poor-formatting, p-low, a-chains
