### ISSUE TITLE
Formatting stops working if a string is too long with deep nesting levels

### ISSUE THREAD

**Issue by localcc** [rust-lang/rustfmt#5704] opened 2023-03-01 17:55 UTC
When a string is too long the formatter stops working in certain conditions. 
Code to reproduce:

```rust
use egui::RichText;

#[derive(Default)]
struct Data {
    untrusted_mods: Vec<u64>,
}

fn main() {
    let data = Data::default();
    let ctx = egui::Context::default();
    egui::Window::new("Untrusted Mods")
        .resizable(false)
        .collapsible(false)
        .anchor(egui::Align2::CENTER_TOP, (0.0, 50.0))
        .fixed_size((600.0, 400.0))
        .show(&ctx, |ui| {
            egui::ScrollArea::vertical().show(ui, |ui| {
                {
                    ui.label(
                        RichText::new(
                            "1234567891234567891234567891234567891234567891234567891234567891234567",
                        )
                        .heading(),
                    );
                }

                println!("{:?}", 
                data.untrusted_mods);
            });
        });
}
```

Expected result is that the println should get formatted to one line.

Occurs on:

```
stable-x86_64-pc-windows-msvc (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```
```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.69.0-nightly (31f858d9a 2023-02-28)
```

**Comment by ytmimi** [comment] 2023-03-01 18:00
Thanks for reaching out, but going to close this as a duplicate of #3863

**Closed by ytmimi** 2023-03-01 18:00 UTC
