### ISSUE TITLE
Format derive attributes alphabetically

### ISSUE THREAD

**Issue by maksym-arutyunyan** [rust-lang/rustfmt#6298] opened 2024-08-29 12:05 UTC
[Feature Request] 

Please add a feature to automatically format `#[derive(...)]` attributes in alphabetical order by default.

```rs
// Current (not sorted):
#[derive(Ord, PartialEq, Eq, Hash, Debug, Clone)]

// Desired (sorted):
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq)]
```

Thank you!

**Comment by ytmimi** [comment] 2024-08-29 16:09
Closing this as a duplicate of https://github.com/rust-lang/rustfmt/issues/4112.

**Closed by ytmimi** 2024-08-29 16:09 UTC
