### ISSUE TITLE
Formatting attribute item with leading comma removes entire item

### ISSUE THREAD

**Issue by ayazhafiz** [rust-lang/rustfmt#4162] opened 2020-05-09 15:18 UTC
Running rustfmt (at least since a5cb5d26833cfda6fa2ed35735448953f728bd5e) on a code like

```rust
#[derive(, Eq)]
struct A {}
```

results in

```rust
#[derive()]
struct A {}
```

Is this intentional?

**Comment by calebcartwright** [comment] 2020-05-09 16:20
Thanks for the report @ayazhafiz, but this is a duplicate of #4029/#3898. The issue has been fixed but not yet released (it will be in the next version of rustfmt)

**Closed by calebcartwright** 2020-05-09 16:20 UTC
Labels: duplicate
