### ISSUE TITLE
nested tuple field access formats as tuple field access and float

### ISSUE THREAD

**Issue by phrohdoh** [rust-lang/rustfmt#4683] opened 2021-01-31 23:56 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1d48baa8ed38a4c4e3e5bade31c0a4f9

**Input**

```rust
struct A(String);
struct B(A);

fn do_thing(b: B) -> String {
    b.0.0
}
```

**Output**

```rust
struct A(String);
struct B(A);

fn do_thing(b: B) -> String {
    b.0 .0
}
```

**Expected output**

unchanged from input

**Meta**

- rustfmt version:  `1.4.25-stable (0f29ff6d 2020-11-11)`
- From where did you install rustfmt?:  `rustup`

**Comment by calebcartwright** [comment] 2021-02-01 01:20
Thanks for the report but closing as a duplicate of various issues (e.g. #4543), explained in #4355 (comment)

**Closed by calebcartwright** 2021-02-01 01:20 UTC
Labels: poor-formatting
