### ISSUE TITLE
Rust/WinRT related exit code 101 caused by usage of unstable features.

### ISSUE THREAD

**Issue by NickelCoating** [rust-lang/rustfmt#4333] opened 2020-07-18 09:29 UTC
**Describe the bug**

In the Minesweeper example for Rust/WinRT, there lays a project named bindings. I can't pin point what's so special about it, but it causes an exit code 101 and therefore a failed build with these commands:

```
fn_params_layout = "Compressed"
where_single_line = true
width_heuristics = "Max"
struct = "Visual"
max_width = 200
```

The output:
```
error: failed to run custom build command for `bindings v0.1.0 (D:\minesweeper-rs\bindings)`

Caused by:
  process didn't exit successfully: `D:\minesweeper-rs\target\debug\build\bindings-0937e96e73cb3233\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=D:\minesweeper-rs\target\debug\build\bindings-1aa6501d8efe7a61\out\winrt.rs

--- stderr
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
thread 'main' panicked at 'Could not successfully build', bindings\build.rs:1:1
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic<str*>
             at C:\Users\imort\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:410
  11: build_script_build::build
             at .\build.rs:1
  12: build_script_build::main
             at .\build.rs:26
  13: std::rt::lang_start::{{closure}}<()>
             at C:\Users\imort\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:52
  15: std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:297
  16: std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:274
  17: std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panic.rs:394
  18: std::rt::lang_start_internal
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:51
  19: std::rt::lang_start<()>
             at C:\Users\imort\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  20: main
  21: invoke_main
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  22: __scrt_common_main_seh
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


Process finished with exit code 101
```

**To Reproduce**

Use a rustfmt.toml within the bindings project of [Minesweeper example](https://github.com/robmikh/minesweeper-rs). With these commands:

```
unstable_features = true
fn_params_layout = "Compressed"
where_single_line = true
width_heuristics = "Max"
struct = "Visual"
max_width = 200
```

Or have a look at [my fork](https://github.com/NickelCoating/minesweeper-rs/tree/master/bindings).

**Expected behavior**

I understand that I use unstable features, but the thing is that I got my own project with the whole Rust jazz on it using those commands. It's a workspace project and plus a couple of crates like gl/glutin/ash that also use custom build scripts and all. But I don't get the error code 101 or any warning with them. At least for as long as I don't reference bindings project with it. 

**Meta**

- rustfmt version: That which comes with Rust version 1.45.0 (But initial tests failed with 1.44.1, too)
- From where did you install rustfmt?: CLion terminal `rustup update`.
- How do you run rustfmt: Via CLion's terminal `cargo run --release`, and project's run/build button. (But initial tests failed with VS Code, too)

**Comment by calebcartwright** [comment] 2020-07-18 18:28
hi @NickelCoating, would you please provide some additional detail, specifically?

1) your version of rustfmt (note that rustfmt is versioned separately from rustc, so please run `rustfmt --version` and provide the output)
2) is the output you shared in the edit to the issue description from running `cargo build --release` or something else?

**Comment by NickelCoating** [comment] 2020-07-18 19:11
1. `rustfmt 1.4.15-stable (530eadf4 2020-06-02)`
2. Yes, it's for `cargo build --release`.

Side note, for getting the rustfmt version the command `rustfmt -V` doesn't work as it is mentioned in the bug issue template for **Meta**. That's why I couldn't provide a proper version. When using command `rustfmt -V` or `rustfmt --v`, it just freezes. No output, and no way to write new commands. Caret just blinks and that's all in PowerShell.

**Comment by calebcartwright** [comment] 2020-07-18 19:28
> When using command rustfmt -V or rustfmt --v, it just freezes. No output, and no way to write new commands. Caret just blinks and that's all in PowerShell

`rustfmt -V` should work, and does for me though admittedly on linux. Would you mind opening a separate issue for that?

**Comment by calebcartwright** [comment] 2020-07-18 19:32
> Yes, it's for cargo build --release.

I'm a little confused by this but haven't really had a chance to look over the details of your repo. Are you trying to run rustfmt as part of your build script (and if so, why?) 

Secondly, you are using rustfmt v.1.4.15 but you are trying to use configuration options/values from a different version of rustfmt (the latest rustfmt from source v2.0). Stable vs. unstable options isn't really a factor. 

If you go to the documentation page for configuration options (https://rust-lang.github.io/rustfmt/) you can update the version in the dropdown to your version of rustfmt, and then browse the corresponding supported config options for your version.

**Comment by calebcartwright** [comment] 2020-07-18 19:55
I've removed the bug label, as the issue is due to the combination of the build script in your running rustfmt and panicking if it doesn't succeed, and your project having an invalid rustfmt configuration file for the version of rustfmt you are using.

I'm still not sure I understand why rustfmt's been introduced within the build process, but the build failure is bubbling up from the winrt build (note the assertion on the last line) that you are using in your project which requires the rustfmt command to exit successfully. However, in your case rustfmt correctly exits with a non-zero error code because your configuration is invalid. 
https://github.com/microsoft/winrt-rs/blob/33fd93beaaa6d140a459ac76a25af797364f3ffa/crates/macros/src/lib.rs#L122-L155

You can resolve this by correcting your rustfmt configuration file, though longer term I'd probably advise against incorporating a successful rustfmt as a required step in your build script. There's other ways formatting can be enforced in a project, for example with CI checks, local git hooks, etc. 

As this is not a bug in rustfmt I am going to close this issue, but if you have any additional question about your configuration options don't hesitate to ask here and/or in Discord

Thanks!

**Closed by calebcartwright** 2020-07-18 19:55 UTC

**Comment by NickelCoating** [comment] 2020-07-18 20:20
> I'm a little confused by this but haven't really had a chance to look over the details of your repo. Are you trying to run rustfmt as part of your build script (and if so, why?)

Yes, it should format all code. That's how I expect it to run. Are you saying that a build script normally wouldn't get a formatting? For the record though, I'm not the author of the bindings project for the Minesweeper example. So I didn't write that build script either. All I originally did was to use that bindings project from Minesweeper in my own project as a starting point. And I happened to use all those unstable features inside my own rustfmt.toml already, but the bindings project added to my own just didn't like it and caused exit code 101.

The author @robmikh of the issue I filed in his repo mentioned:
>Part of it may be that winrt-rs calls rustfmt directly from within the generated build function. Not that it's problematic itself, but it may explain a difference in behavior from other crates that generate bindings.
>
> If you end up filing an issue with them, I'd be interested to know what the root cause is. Closing this issue for now.

Seems that my rustfmt.toml overwrites his hard coded configs(if there is such a thing)? Because I couldn't find any toml file there.

If it is not a bug then it's a design flaw. If I use a feature that isn't even available in an unstable form so isn't even usable via `unstable_features = true`, that the rustfmt won't tell me that there is no such a thing as, for instance, `fn_params_layout`. It never told me bfore that it's not even an unstable feature in 1.4.15. Well, that explains why it never worked... -.-

If this ain't a bug, than it's a design flaw not informing the user that a config doesn't exist. Not user friendly at all. If it is hidden beyond the activation via  `unstable_features = true`, then it should be hidden better.

Anyways, since I got a means now to check for the version, I can make sure myself in the first place. :)

**Comment by calebcartwright** [comment] 2020-07-18 23:28
@NickelCoating - I'll follow up with direct responses to items in your last comment, but since you mentioned Rust being relatively new for you in the other issue I have also included some info and links below that should provide context and be helpful for you (some/most of which you may already know). 

<hr />

## Background

rustfmt is the code formatting tool for Rust code, and is based on the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs).

The vast majority of the time users will use the `cargo fmt` subcommand to run the rustfmt tooling against their project. `rustfmt` can be invoked directly itself, but it's almost always easiest to use cargo for the same types of reasons folks typically run `cargo build` instead of invoking the rust compiler directly with all the requisite flags and args. Most editors/IDEs also support running rustfmt as part of their format-on-save features. 

Though rustfmt's default mode will emit Rust code formatted according to the Style Guide, it also supports config options to let users customize the formatting in cases where they prefer a style that differs from the Style Guide (for example tabs instead of spaces or next line bracket placement). 

As rustfmt evolves with new features, bug fixes, etc., we release new versions. Sometimes those updates to rustfmt include things like net-new configuration options or new supported values for existing configuration options, and in the case of a major version bump of rustfmt, this could potentially include breaking changes (removal of config options, renaming, etc.).

This means that if we implement and release a new configuration option `foo` in version 1.8.0 of rustfmt, then `foo` is of course available in version 1.8.0. However, an older version of rustfmt like 1.2.0 doesn't have a clue what `foo` is and v1.2.0 doesn't have the requisite implementation to support formatting code based on config option `foo`. 

As such, the supported/available rustfmt configuration options are tightly associated with a version of rustfmt, and there are multiple versions of rustfmt in use by our users; some are using the latest beta v2.0.0-rc while others are using much older versions like v1.4.9. The configuration options available (and supported values) for users with v2.0.0 of rustfmt are very different than what's available for users working with v1.4.9 of rustfmt, so the [Configuration options documentation](https://rust-lang.github.io/rustfmt/) is structured so that users can view exactly what options are available with the specific version of rustfmt they are using.

<hr />

## Channels and Stable vs. Unstable
First up, note that you are using the stable Rust channel, but there's also Beta and Nightly distributions
https://github.com/rust-lang/rustup#keeping-rust-up-to-date
https://github.com/rust-lang/rustup#toolchain-specification
https://github.com/rust-lang/rustup#working-with-nightly-rust

It's common, especially with official Rust tooling, for new features to be considered "unstable" and typically are only available on Nightly or in some rarer cases Beta. Sometimes that's because they explicitly rely on a feature in the compiler that's itself unstable/nightly-only, or in others just because the new feature hasn't not been fully tested/could break things.

This is also true with new features, including configuration options, in rustfmt. When we add a net-new config option it is unstable, and historically rustfmt hasn't allowed the usage of unstable features/options on stable Rust. If you take a look at the [configuring rustfmt section](https://github.com/rust-lang/rustfmt#configuring-rustfmt) of our readme you'll see this called out explicitly.

> Configuration options are either stable or unstable. Stable options can always be used on any channel. Unstable options are always available on nightly, but can only be used on stable and beta with an explicit opt-in (starting in Rustfmt v2.0).

> **Unstable options are not available on stable/beta with Rustfmt v1.x.**

We decided that with the next major release of rustfmt (v2.0) that we'll allow folks to opt-in to unstable features on stable if they really want to (at their own risk), but unstable features won't be available to you today with a 1.x version of rustfmt.

<hr />

## Your Project

I think it's easier to look at this starting with rustfmt and your project itself independent of WinRT, and you may want to run `cargo fmt` directly against your project to get the subset of the output from rustfmt without the stacktrace noise from WinRT (though you can also view this within the full output shared in the issue description. 

When you run rustfmt with bad configuration the output from rustfmt will let you know what the problem is, whether that's for example unknown/unsupported options, invalid values for known options, or trying to use an unstable option on stable. The problem you have is that you structured your config file based on supported configuration options for rustfmt 2.0 but you're using v1.4.15 of rustfmt. It doesn't really have anything to do with stable vs. unstable or really even WinRT. 

Here's the output from rustfmt telling you that your config file is bad:
```
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
```
Since you're using v1.4.15 of rustfmt you'll want to look at the 1.4.15 version of the config docs https://rust-lang.github.io/rustfmt/?version=v1.4.15 to get this corrected

Specifically to correct your configuration issues:
* I'm not sure which option you were targeting with `struct`, as that's not a valid config option in any version. 
* Use `fn_args_layout` (https://rust-lang.github.io/rustfmt/?version=v1.4.15&search=#fn_args_layout) instead (fn_args_layout is getting renamed as part of the major v2.0 release). 
* Use `use_small_heuristics` (https://rust-lang.github.io/rustfmt/?version=v1.4.15&search=#use_small_heuristics) instead of `width_heuristics`. 

The exit code is happening with `width_heuristics` because, again that's only a publicly supported config option with rustfmt 2.0, not the v1.4.15 version you are using where it is a private/internal option and it can't be parsed because your value is invalid. 

The same thing happens if you provide an invalid value for any config type for example:

```
# rustfmt.toml
unstable_features = "adfasdf"
```
Will result in the below when running rustfmt

```bash
Error: Decoding config file failed:
invalid type: string "adfasdf", expected a boolean for key `unstable_features`
Please check your config file.
```

Lastly, when you do attempt to use an unstable config options on stable, you'll get a similar warning and the config option won't be utilized:
```
# rustfmt.toml
binop_separator = "Front"
```

Results in:
```bash
Warning: can't set `binop_separator = Front`, unstable features are only available in nightly channel.
```

**Comment by calebcartwright** [comment] 2020-07-18 23:43
@NickelCoating  - regarding your previous comment

> Yes, it should format all code. That's how I expect it to run. Are you saying that a build script normally wouldn't get a formatting?

No, that's not correct. The WinRT build script does not run rustfmt against your entire project, AFAICT it seems like it's just trying to ensure the generated `winrt.rs` file in the outdirectory is formatted. The `build.rs` file itself will be formatted when you run rustfmt normally in your project (`cargo fmt` or `rustfmt ..your-files...   ...other-flags...`)

> bindings project added to my own just didn't like it and caused exit code 101.

The driver of the problem is your invalid rustfmt config file that results in rustfmt exiting with an error when you run it. However, IMHO the WinRT build script shouldn't attempt to run and require a successful rustfmt run against the generated file. There's a portion of Rust users that don't use `rustfmt`, and since `rustfmt` doesn't ship with the default rustup profile they're inevitably going to end up with people getting build errors that complain about `rustfmt` not existing on the users system. 

I image that the WinRT folks did this so that when users subsequently ran `cargo fmt` in their project it wouldn't fail with complaints about the generated file. However, in my experience this is typically handled by leveraging rustfmt's ability to ignore files (typically by adding `#![rustfmt:skip]` to the top of the generated file(s))

> If it is not a bug then it's a design flaw.

Sorry, but I have to strongly disagree with you here. Individual versions of rustfmt don't (and shouldn't) have detailed knowledge of what features are supported in all past/future versions of itself. When rustfmt sees a config file that's invalid it'll let you know the problem, but erroring with an invalid/unparseable config file is the desired behavior.

rustfmt's output is very explicitly telling you what's wrong with your config file, that's just getting lost in the noise of the stacktrace from the WinRT build script. 

```bash
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
```

> If this ain't a bug, than it's a design flaw not informing the user that a config doesn't exist. Not user friendly at all.

I feel like these comments were based off your original diagnosis, and I hope that the details I provided here and in my last response help give you a better idea of what the actual issue with your project is.

If you have suggestions about the rustfmt-specific portions of the output we'd be happy to hear them! However, we don't have any control over what the WinRT build script chooses to do nor how the rustfmt output falls within the broader stack trace.

**Comment by NickelCoating** [comment] 2020-07-19 10:03
>> If it is not a bug then it's a design flaw.

> Sorry, but I have to strongly disagree with you here. Individual versions of rustfmt don't (and shouldn't) have detailed knowledge of what features are supported in all past/future versions of itself. 

I do agree with you. But that's not what I said earlier. 

Yes, such a feature would require some kind of register/manifest of a file that keeps track of all features and their build versions. That said though, indeed I don't need rustfmt to tell me things like "This feature is not supported in this version. Please try that version instead."

I need "This feature is not supported in this version.", as in what you said below:

> When rustfmt sees a config file that's invalid it'll let you know the problem, but erroring with an invalid/unparseable config file is the desired behavior.

So, why is it that I don't see error/warnings with, for instance, `pn_params_layout`? When I create a new CLion project and add my rustfmt.toml with its unstable/unsupported features for the stable version of 1.4.15, there are no errors or warnings, which can't be right, right!? Docs don't even list `pn_params_layout` for 1.4.15. It doesn't exist. It's altogether not supported.

I hope that this explanation is clearer than my last.

I think this lack of information from rustfmt.exe is the real problem I tried to zeroing-in on over the course of two issues opened on github. Target acquired, firing at your command. Which makes this issue also outdated and should stay indeed closed for clarity. In case I'm right, I open a new issue when you suggest so.

Could you reproduce this issue with that simple new project? Building, running, and hitting the "format cargo project with Rustfmt" button in CLion(Or VSCode equivalent) doesn't print any errors/warnings for any unstable/unsupported features that I use in my toml.

For what it's worth, I can avoid this error after all, and stick to the docs info instead rustfmt errors/warnings. It will fix itself once unstable/unsupported features are stable. Then I can use my old toml again. :)

**Comment by calebcartwright** [comment] 2020-07-19 15:22
@NickelCoating have you tried running `cargo fmt` from your terminal/command line as I previously suggested? 

> I think this lack of information from rustfmt.exe

So far you've only mentioned running rustfmt in your project from a custom build script that panics and from your IDE, and as I noted previously the rustfmt output is in the original output you shared. You keep talking about missing information from rustfmt but the information from rustfmt can be seen above in your original issue description and is easily seen when running rustfmt directly. It's not clear to me that you've actually tried run rustfmt itself yet. 

> When I create a new CLion project and add my rustfmt.toml with its unstable/unsupported features for the stable version of 1.4.15, there are no errors or warnings, which can't be right, right!?

I'm not sure what exactly you are describing here. We don't maintain the CLion IDE and I'm not a CLion user, so again, please try running `cargo fmt` directly.

> Could you reproduce this issue with that simple new project? Building, running, and hitting the "format cargo project with Rustfmt" button in CLion(Or VSCode equivalent) doesn't print any errors/warnings for any unstable/unsupported features that I use in my toml.

Again I want to stress that we have no control over what other tools/IDEs/editors do with rustfmt, only rustfmt itself. If your IDE is not displaying data from stdout/stderr for tools that it runs, then you need to take that up with the owners of your IDE. Here's what you see if you run rustfmt directly, with the output from our tool clearly calling out your problematic `pn_params_layout` config option

```bash
$ cargo new nickelcoating
     Created binary (application) `nickelcoating` package
$ cd nickelcoating/
$ echo "pn_params_layout = true" >> .rustfmt.toml
$ cat .rustfmt.toml
pn_params_layout = true
$ cargo fmt
Warning: Unknown configuration option `pn_params_layout`
$ cargo fmt --version
rustfmt 1.4.15-stable (530eadf 2020-06-02)
```

**Comment by calebcartwright** [comment] 2020-07-19 15:24
> It will fix itself once unstable/unsupported features are stable. Then I can use my old toml again. :)

This is categorically false. I've already explained in detail what's wrong your original config, and specific steps (with links) to what you'd need to do to correct it. Your issue doesn't have anything to do with stable or unstable, and I'm not sure why you continue to think that is the case.

**Comment by NickelCoating** [comment] 2020-07-19 17:26
> @NickelCoating have you tried running cargo fmt from your terminal/command line as I previously suggested?

No I didn't, my bad. That request of yours went down with both of our text walls.

>> When I create a new CLion project and add my rustfmt.toml with its unstable/unsupported features for the stable version of 1.4.15, there are no errors or warnings, which can't be right, right!?

> I'm not sure what exactly you are describing here.
We don't maintain the CLion IDE and I'm not a CLion user, so again, please try running cargo fmt directly.

I tried to make a simple example to avoid anything else getting in the way like the build script. However, It's CLion's that omits that info, not rustfmt as I thought. Via terminal directly, as you suggested, works fine. It prints all the errors/warnings.

Wow, it's really pathetic that CLion can't even hook into the output. It could have avoided so many mistakes.

Anyways, thanks for your patience with this! I'm not having it with the Rust plugin anymore. 👍

**Comment by calebcartwright** [comment] 2020-07-19 17:37
No worries! It's great when editors/other tools try to make things easier for you but sometimes in doing so they may obfuscate info from the tools they are helping you with. 

The JetBrains IDE's are used pretty extensively within the Rust community so hopefully it's just a setting or something on their end to display the tool output (I use VS Code personally so can't help much there unfortunately). 

Separately, I will follow up with the WinRT folks to suggest they consider alternatives in their build script as I could see it being a recurring source of confusion, and also if you're still getting a hung terminal from running `rustfmt -V` please feel free to open a separate issue as that's definitely something we'd want to dig into.

**Comment by rylev** [comment] 2020-07-20 12:27
@calebcartwright maintainer of WinRT-rs here. Happy to have any suggests on how to improve the flow. I think the easiest way to start fixing this on our side is to actually display stderr when the command does not succeed.

**Comment by calebcartwright** [comment] 2020-07-20 18:00
Thanks @rylev! Let me know if there's a thread over in the WinRT-rs space to discuss in more detail, but TL;DR I'd advise against requiring a successful rustfmt run within the build script there.

The rationale for my suggestion there copied below:

> There's a portion of Rust users that don't use rustfmt, and they may also want to take into account that rustfmt doesn't ship with the default rustup profile so they're inevitably going to end up with people getting build errors that complain about rustfmt not existing on the users system (local dev environments as well as CI).

> I image that the WinRT folks did this so that when users subsequently ran cargo fmt in their project it wouldn't fail with complaints about the generated file. However, in my experience this is typically handled by leveraging rustfmt's ability to ignore files (typically by adding #![rustfmt:skip] to the top of the generated file(s))
