### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by Quandrax** [rust-lang/rustfmt#6393] opened 2024-11-16 19:39 UTC
```
    #[rustfmt::skip]
    fn recreate_swapchain(&mut self)-> VkResult<()> {
        unsafe {
            self.device.device_wait_idle()?;

            self.device.destroy_command_pool(self.command_pool, None);
            self.device.destroy_pipeline(self.pipeline, None);
            self.device.destroy_pipeline_layout(self.pipeline_layout, None);
            self.image_views.iter().for_each(|image_view|{
                self.device.destroy_image_view(*image_view, None);
            });
            self.swapchain_loader.destroy_swapchain(self.swapchain, None);

            (self.swapchain, self.swapchain_loader, self.format, self.extent) = 
                Renderer::create_swapchain(&self.surface_loader, self.physical_device, self.surface, &self.instance, &self.device, self.queue_family_index)?;
            (self.images, self.image_views) = 
                Renderer::acquire_swapchain_images_and_image_views(&self.swapchain_loader, self.swapchain, self.format, &self.device)?;
            (self.command_pool, self.command_buffers) = Renderer::create_command_buffers(self.queue_family_index, &self.device)?;
            (self.pipeline_layout, self.pipeline) = Renderer::create_pipeline(&self.device, self.extent, self.format)?;
        }

        self.swapchain_dirty = false;

        Ok(())
    }
```

```
error[internal]: left behind trailing whitespace

   --> /playground/src/main.rs:772:772:80
    |
772 |             (self.swapchain, self.swapchain_loader, self.format, self.extent) = 
    |                                                                                ^
    |

error[internal]: left behind trailing whitespace
   --> /playground/src/main.rs:774:774:46
    |
774 |             (self.images, self.image_views) = 
    |                                              ^
    |

warning: rustfmt has failed to format. See previous 2 errors.
```

**Comment by ytmimi** [comment] 2024-11-18 16:43
The ` #[rustfmt::skip]` annotation is telling rustfmt not to format the function, and the function contains trailing whitespace. This is effectively a duplicate of #4706

**Closed by ytmimi** 2024-11-18 16:43 UTC
Labels: duplicate, a-rustfmt::skip, e-trailing whitespace
