### ISSUE TITLE
Trailing commas in multi-line `feature`/lint group attributes are not preserved

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rustfmt#4972] opened 2021-08-30 14:31 UTC
I tried formatting the following code:
```rust
#![feature(
    allocator_api,
    array_methods,
    bool_to_option,
    control_flow_enum,
    decl_macro,
    destructuring_assignment,
    drain_filter,
    duration_consts_2,
    exact_size_is_empty,
    float_interpolation,
    hash_drain_filter,
    iter_intersperse,
    label_break_value,
    maybe_uninit_array_assume_init,
    maybe_uninit_extra,
    maybe_uninit_uninit_array,
    once_cell,
)]
```

I expected the trailing comma to be preserved, similar to multi-line structs or function calls. Instead, the comma was removed:
```diff
     maybe_uninit_uninit_array,
-    once_cell,
+    once_cell
 )]
```

rustfmt version: `rustfmt 1.4.37-nightly (0035d9d 2021-08-16)`

**Comment by calebcartwright** [comment] 2021-09-08 02:06
Thanks for reaching out but closing as a duplicate of #3277

**Closed by calebcartwright** 2021-09-08 02:06 UTC
