### ISSUE TITLE
Option to skip uneccessary match arm brackets

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/rustfmt#5351] opened 2022-05-24 23:02 UTC
If rustfmt decides to indent after the `=>` in a match (because the line ran too long) it also adds a `{}` and an extra line (for the `}`) even if the contents of the match arm fit onto a single line.

In the example at https://github.com/rust-bitcoin/rust-bitcoin/pull/959#discussion_r869753811 rustfmt generated

```
Error::SerializationError => {
    "can not serialize the spending transaction in Transaction::verify()"
},
```

when it arguably could have (optionally) just stuck with

```
Error::SerializationError =>
    "can not serialize the spending transaction in Transaction::verify()",
```

unlike ifs (and the C world) you can't get screwed by the lack of `{}` here - if you end up with two statements back-to-back its a compile error rather than incorrect logic.

Thanks!

**Comment by calebcartwright** [comment] 2022-05-24 23:26
Thanks for sharing, but going to close as a duplicate of #4896

You may want to also subscribe to #4924. It may have stalled out a bit but made good progress and is the most likely candidate for implementation

**Closed by calebcartwright** 2022-05-24 23:26 UTC
