### ISSUE TITLE
Weird spacing with nested tuples

### ISSUE THREAD

**Issue by pommicket** [rust-lang/rustfmt#5745] opened 2023-04-09 19:00 UTC
This code:
```rust
fn main() {
    let x = ((0, 1), 2);
    println!("{}", x.0.0);
}
```
Gets formatted to:
```rust
fn main() {
    let x = ((0, 1), 2);
    println!("{}", x.0 .0);
}
```
This was intentional since apparently `x.0.0` used to get parsed as `x.(0.0)` (see #1063). But the version without the space compiles now, so maybe rustfmt shouldn't add the space anymore?

**Comment by ytmimi** [comment] 2023-04-09 19:05
Thanks for reaching out. This is a duplicate of #5532

This is fixed when setting `version=Two`. See https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276 for more details.

**Closed** 2023-04-09 19:05 UTC
Labels: duplicate, fixed-with-v2

**Comment by ytmimi** [comment] 2023-04-09 19:06
I'll also note that because of our stance on breaking formatting changes we haven't fixed this on `version=One`, and you'll need to use `version=Two` to get the formatting that you want, but you'll need a nightly version of rustfmt.
