### ISSUE TITLE
Fails in some deeply nested method chains sprinkled with indexing

### ISSUE THREAD

**Issue by berrymot** [rust-lang/rustfmt#6151] opened 2024-04-23 05:29 UTC
Found in an attempt to format [this](https://github.com/berrymot/notoize/blob/e1d273c411af9b36a01acd9591b408b785320e77/src/lib.rs). Haven't found a minimal reproduction yet, sorry

![image](https://github.com/rust-lang/rustfmt/assets/50974538/df7d23ba-ebda-4a76-b1fb-3e34d434d9cd)

`rustfmt.toml`:

```toml
error_on_line_overflow = true
max_width = 100
imports_granularity = "Crate"
```

Version: `rustfmt 1.7.0-nightly (7f2fc33d 2024-04-22)`

**Comment by ytmimi** [comment] 2024-04-23 13:23
[It's the long string literal on line 86 thats preventing formatting](https://github.com/berrymot/notoize/blob/e1d273c411af9b36a01acd9591b408b785320e77/src/lib.rs#L86C1-L86C104). rustfmt can't fit that string literal within the `max_width` so it fails to reformat the entire method call chain.

This is another duplicate of https://github.com/rust-lang/rustfmt/issues/3863

**Closed by ytmimi** 2024-04-23 13:23 UTC
