### ISSUE TITLE
Closure having long string in method argument is not formatted

### ISSUE THREAD

**Issue by codingskynet** [rust-lang/rustfmt#5823] opened 2023-07-11 03:11 UTC
Case:
```rust
struct A;

impl A {
    fn b(&self, f: impl FnOnce()) {
        f()
    }
}

fn test() {
    let a = A;

    a.b(
      || {

   println!("sdflkdslkdkfmdslfdslkmdsflkmfdslkmfdsmlkfdsmlkfdslkfdsklfdslkmdsflfvdvjnlnlkccvjnxnlcvxjnlxcvjncvxjnkcvxjnxkcvz");
        }
    );
}
```

But this is not formatted.

Checked version of rustfmt: rustfmt 1.6.0-nightly (8ca44ef9 2023-07-10)

**Comment by ytmimi** [comment] 2023-07-11 13:35
Thanks for reaching out, but this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863

**Closed by ytmimi** 2023-07-11 13:35 UTC
Labels: duplicate
