### ISSUE TITLE
formatting takes too long

### ISSUE THREAD

**Issue by ohad-starkware** [rust-lang/rustfmt#6397] opened 2024-11-17 17:01 UTC
I have an auto-gen artifact such as this:

```rust
let op1_as_rel_imm_cond_col225 = ((pc_update_jnz_col15) + (((((((((((((((((((((((((((((((((((((((((((((((((((((((((const_0))
) + (v))) + (c))) + 
(e))) + (f))) + 
(g))) + (h))) + (a))) + (a))) + (a))) + (a))) + (a))) + (a))) +
 (a))) + (ab))) + (dst_limb_15_col37))) + (a))) + (a))) + (a))) + (aa))))) +
  (a))) + (a))) + (dst_limb_23_ol45))) + (a))) + (a))) + (a))) + (a))));
    });
``` 

fmt runs forever! 
but if you reduce some characters from some variable names, it runs instantly.

**Comment by ytmimi** [comment] 2024-11-18 15:56
Thanks for the report. I'm fairly certain that this is a duplicate of #6357.

If you're using a nightly rustfmt and you don't mind your autogenerated files not being formatted you can add a `//@generated` comment to the top of the file and set [`format_generated_files=false`](https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#format_generated_files). rustfmt will ignore these files and the process won't take forever to run.

**Closed by ytmimi** 2024-11-18 15:56 UTC
