### ISSUE TITLE
Left behind trailing whitespace after writeln macro

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rustfmt#5222] opened 2022-02-07 09:34 UTC
Reproduce it with:
```
echo 'Zm4gbWFpbigpIHsKICAgIHdyaXRlbG4hKHJlc3VsdCwgIjwhLS0ge306IEN1cnZlOjpmcm9tX3BvaW50cyhDb29yZDIoeHgsIHh4KSwgKENvb3JkMih4eCwgeHgpLCBDb29yZDIoeHgsIHh4KSksIENvb3JkMigpKSAtLT4iLAogICAgaW5kZXgsIAogICAgKTsKfQo=' | base64 -d | rustfmt
```

```
error[internal]: left behind trailing whitespace
 --> stdin:3:3:11
  |
3 |     index,
  |           ^
  |
```

rustfmt 1.4.38-nightly (f624427 2022-02-06)

**Comment by ytmimi** [comment] 2022-02-07 14:46
Thanks for submitting the issue!

I find that it's a little easier to include the snippet of code directly so anyone wanting to work on the issue can easily copy and paste it.

```rust
fn main() {
    writeln!(result, "<!-- {}: Curve::from_points(Coord2(xx, xx), (Coord2(xx, xx), Coord2(xx, xx)), Coord2()) -->",
    index, 
    );
}
```

Does the issue only happen when the input is read from stdin? I'm not able to reproduce this when formatting the input from a file.

**Comment by hellow554** [comment] 2022-02-07 14:55
```
cd $(mktemp -d)
cargo init . --name abc
echo 'Zm4gbWFpbigpIHsKICAgIHdyaXRlbG4hKHJlc3VsdCwgIjwhLS0ge306IEN1cnZlOjpmcm9tX3Bv
aW50cyhDb29yZDIoeHgsIHh4KSwgKENvb3JkMih4eCwgeHgpLCBDb29yZDIoeHgsIHh4KSksIENv
b3JkMigpKSAtLT4iLAogICAgaW5kZXgsIAogICAgKTsKfQo=' | base64 -d > src/main.rs
cargo fmt
```

errors as intended ;)

That's why I provided the base64 input. Your editor may remove the trailing whitespace on its own.

**Comment by calebcartwright** [comment] 2022-02-11 02:12
Thank you for sharing.

The root cause of the problem is that it's impossible to apply the formatting rules to your input in any way that's compliant with all rules and your config settings (yes I realize those are at the default values). In these cases rustfmt simply leaves the code as you wrote it instead of trying to pick which rule(s)/config(s) to violate. Your original input had a trailing space, and rustfmt is simply flagging that as part of an indicator to let you know.

That's intentional behavior for the default, though I also realize some folks would prefer rustfmt forget about `max_width` in these cases. There's some instances where we have enhanced rustfmt to be able to do this, but it's feature gated so as to not introduce breaking changes.

The default behavior isn't going to change any time soon, so I'm going to close this. Here's some options available today for you to consider:

- Set `version=Two` in your config file. Note that this will likely introduce other formatting changes, generally improvements, but it also is the flag that gives rustfmt the :+1: to not worry about the long string lit
  - You may also want to consider pairing this with `error_on_unformatted=true` to get a more explicit error about such long lines
- Set `format_strings=true` in your config file to give rustfmt permission to wrap the long string lit in order to keep it within the `max_width` limit
- Manually split\wrap the long string in the manner of your choosing such that it can fit within the `max_width` limit

**Closed by calebcartwright** 2022-02-11 02:12 UTC
