### ISSUE TITLE
Internal error: left behind trailing whitespace

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rustfmt#4248] opened 2020-06-09 09:06 UTC
```
error[internal]: left behind trailing whitespace
   --> /home/mkpankov/work/integrated-manager-for-lustre/iml-services/iml-device/src/virtual_device/mod.rs:133:133:61
    |
133 |                                 guid2.map(|g| if g == guid1 { 
    |                                                              ^
    |

warning: rustfmt has failed to format. See previous 1 errors.
```

Happens around this code:
```rust
    if is_virtual(d) {
        if !commands.is_empty() {
            tracing::info!("Looking through commands");
            for c in commands {
                match c {
                    Command::PoolCommand(pc) => {
                        tracing::info!("Got PoolCommand");
                        match pc {
                            PoolCommand::UpdatePool(p) => {
                                tracing::info!("Got UpdatePool");

                                let guid1 = p.guid;
                                let guid2 = match d {
                                    Device::Zpool(dd) => Some(dd.guid),
                                    _ => None,
                                };
                                guid2.map(|g| if g == guid1 { 
                                results.push(parent.expect("Tried to push to parents the parent of the Root, which doesn't exist"))
                            });
                            }
                            _ => {}
                        }
                    }
                    _ => {}
                }
            }
            results
        } else {
            tracing::debug!(
                "Collecting parent {} of {}",
                parent.map(|x| to_display(x)).unwrap_or("None".into()),
                to_display(d)
            );
            vec![parent
                .expect("Tried to push to parents the parent of the Root, which doesn't exist")]
        }
    } else {
```

Full repository:
https://github.com/whamcloud/integrated-manager-for-lustre/tree/formatting

`cd iml-services/iml-device && cargo fmt`

**Comment by calebcartwright** [comment] 2020-06-10 23:40
what version of rustfmt are you using @mkpankov (`rustfmt --version`)?

**Comment by mkpankov** [comment] 2020-06-11 09:09
```
$ rustfmt --version
rustfmt 1.4.12-stable (a828ffe 2020-03-11)
```

**Comment by calebcartwright** [comment] 2020-06-11 13:27
could you try updating to a newer version? this appears to be fixed starting in 1.4.14/15

**Comment by rchaser53** [comment] 2020-06-11 14:00
I created the small reproduction on the rust playground. Please use it.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a4b9436f2415711f30e8d678c0393178

**Comment by calebcartwright** [comment] 2020-06-11 14:31
thanks @mkpankov and @rchaser53, this is still reproducible even on master/rustfmt v2.0 (i didn't notice the need to use the **formatting** branch before)

**Comment by oilaba** [comment] 2021-01-24 14:47
I am getting this error on `rustfmt 1.4.25`.

**Comment by ytmimi** [comment] 2022-07-26 03:08
I believe this is a duplicate of #3863 that just so happens to lead to a trailing whitespace issue. Going to close accordingly.

**Closed by ytmimi** 2022-07-26 03:08 UTC
Labels: duplicate, poor-formatting, a-chains, a-strings, e-trailing whitespace
