### ISSUE TITLE
Rustfmt fails to resolve mod

### ISSUE THREAD

**Issue by Skgland** [rust-lang/rustfmt#5198] opened 2022-01-27 22:44 UTC
Reproduction

```sh
git clone https://github.com/Skgland/scryer-prolog.git
pushd scryer-prolog
git checkout --track origin/rustfmt/issue1
cargo check # succeeds
cargo fmt --all # Error writing files: failed to resolve mod `macros`: /home/bennet/Git/tmp/scryer-prolog/src does not exist
```

#5167 has a similar error message but this one should not be ambiguous.

**Comment by ytmimi** [comment] 2022-01-28 13:38
Thanks for the report!

At a quick glance over the repo (https://github.com/Skgland/scryer-prolog.git) it does seem like this should be different than 5167. I'll try to dig into this over the next few days to see if I can better understand what's going on.

**Comment by ytmimi** [comment] 2022-01-30 17:12
After diving into the rustfmt module resolution code and revisiting your repo I've identified that the issue is that you define both a  ``src\lib`` directory (that doesn't contain any rust code) and a ``src\lib.rs`` file.

module resolution is trying to look for modules in the ``src\lib`` directory and because we can't find:
``src\\lib\\macros.rs`` or ``src\\lib\\macros\\mod.rs`` We run into a  ``rustc_expand::module::ModError::FileNotFound`` error when we call ``ParseSess::default_submod_path``.

https://github.com/rust-lang/rustfmt/blob/8b0b213cddb23a9bbe421b717d1a0e5fb3982712/src/modules.rs#L372-L374

Just as a note, our implementation of ``ParseSess::default_submod_path`` just forwards values to ``rustc_expand::module::default_submod_path``, so if this is a recent issue then maybe things changed in the compiler (but I can't be sure of that).

That being said, I think I have a fix for this.

**Comment by Skgland** [comment] 2022-01-30 18:16
No, this does not appear to be a recent issue, I tried most rust stables back to `1.46.0 (2020-08-27)` and could reproduce this with all tried versions and `src/lib.rs` was only introduced on `2021-02-28` when splitting of the lib in <https://github.com/mthom/scryer-prolog/commit/2f428b72618aeb421485950ffb91ff9dba2f0b0c>.

**Comment by ytmimi** [comment] 2022-01-30 18:32
Thanks for the additional info. I'm pretty confident that it was the introduction of the ``src/lib.rs`` file that caused this module resolution issue. I should have a PR to fix this soon!

**Closed** 2022-03-01 05:13 UTC
Labels: a-mods
