### ISSUE TITLE
Code with usual string not formatted

### ISSUE THREAD

**Issue by fanatid** [rust-lang/rustfmt#4331] opened 2020-07-16 09:25 UTC
Code from https://github.com/timberio/vector/blob/ff1884062e09956a7696a644f80c401e593d3e6f/src/sinks/statsd.rs but with small changes.

Code on playground not formatted: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f18a74b89c3b1d2a1c894c0f056bc03e

But if comment line 178, code will be formatted.

Line 178:
```rust
Bytes::from("vector.counter:1.5|c|#empty_tag:,normal_tag:value,true_tag\nvector.histogram:2|h|@0.01")
```

I tried cargo-fmt and rustfmt directly.

**Comment by ayazhafiz** [comment] 2020-07-16 14:54
Simpler repro:

```rust
fn test_send_to_statsd() {
    rt.block_on_std(async move {
let sink = StatsdSvc::new(config, Acker::Null).unwrap();
        let messages = collect_n(rx, 1).compat().await.ok().unwrap();
        assert_eq(
            messages[0],
            Bytes::from("vector.counter:1.5|c|#empty_tag:,normal_tag:value,true_tag\nvector.histogram:2|h|@0.01")
        );
    });
}
```

**Comment by hbina** [comment] 2020-08-04 02:01
I am not sure if this is related but it seems that `rustfmt` fails to format code that have long string literals.
The code below will not be formatted.
If one removes the dummy long string below it will format just fine.

```rust
extern crate clap;
use clap::{App, Arg, SubCommand};

fn main() {
    let matches = App::new("wrwerwerw")
        .version("1.0")
        .author("Testsetsts")
        .about("wtwetwetwe")
        // Required arguments.
        .arg(
            Arg::with_name("language")
                .help("Desired language")
                .takes_value(true)
                .index(1)
                .required(true),
        )
        .arg(
            Arg::with_name("input")
                .help("Input file")
                .takes_value(true)
                .index(2)
                .required(true),
        )
        .arg(
            Arg::with_name("output")
                .help("Output file")
                .takes_value(true)
                .index(3)
                // TODO: Let the user decide if they simply wants to print to stdout or to a file.
                .required(true),
        )
        // Optional arguments
        .arg(Arg::with_name("no-const").help("Generated variables are mutable."))
        // NOTE: I don't quite get what this means...
        .arg(Arg::with_name("always-escape")
        .
        help("some long string some long string some long string some long string some long string some long string some long string some long string some long string some long string "))
        .
        arg(Arg::with_name("line-length")
        . short("l")
        .
        help("test"))
        .get_matches();
}
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=58c97546a834227e6dcf6fc03bd62e03

**Comment by calebcartwright** [comment] 2020-08-04 02:19
@hbina - Thanks for sharing, but that is a separate, known issue. You can track that item at #3863, but I'm going to minimize these comments to keep this thread focused on the OP topic.

**Comment by calebcartwright** [comment] 2022-07-20 18:15
Correct, it's another duplicate of #3863

**Closed by calebcartwright** 2022-07-20 18:15 UTC
Labels: duplicate, poor-formatting, p-low, a-strings
