### ISSUE TITLE
Whitespace alignment between match arms

### ISSUE THREAD

**Issue by tusharmath** [rust-lang/rustfmt#6002] opened 2023-12-31 06:04 UTC
It would be great to see some whitespace alignment between various match arms.

**before**
```rust
pub fn digits(data: i32) {
  match data {
    1000 => 3,
    100 => 2,
    1 => 1,
  }
}
```

**after**
```rust
pub fn digits(data: i32) {
  match data {
    1000 => 3,
    100  => 2,
    1    => 1,
  }
}
```

The readability improves quite significantly with complex pattern matches. Here is another example — 
**before**
```rust
enum Action {
    Login(String),
    Logout,
    Read(String, usize),
    Write(String, String),
}

fn perform_action(action: Action) -> String {
    match action {
        Action::Login(username) => format!("User {} logged in", username),
        Action::Logout => "User logged out".to_string(),
        Action::Read(file, position) => format!("Reading from file {} at position {}", file, position),
        Action::Write(file, content) => format!("Writing to file {}: {}", file, content),
    }
}
```

**after**
```rust
enum Action {
    Login(String),
    Logout,
    Read(String, usize),
    Write(String, String),
}

fn perform_action(action: Action) -> String {
    match action {
        Action::Login(username)           => format!("User {} logged in", username),
        Action::Logout                    => "User logged out".to_string(),
        Action::Read(file, position)      => format!("Reading from file {} at position {}", file, position),
        Action::Write(file, content)      => format!("Writing to file {}: {}", file, content),
    }
}
```

**Comment by tusharmath** [comment] 2023-12-31 06:08
I would also propose having this feature for variable assignments -

**before:**
```rust
fn main() {
    let total_orders = get_total_orders();
    let average_price = calculate_average_price();
    let is_stock_available = check_stock_availability();
    let customer_feedback = get_customer_feedback();
    let last_order_date = get_last_order_date();
    let next_shipment_eta = calculate_next_shipment_eta();
}

**after:**
```rust
fn main() {
    let total_orders        = get_total_orders();
    let average_price       = calculate_average_price();
    let is_stock_available  = check_stock_availability();
    let customer_feedback   = get_customer_feedback();
    let last_order_date     = get_last_order_date();
    let next_shipment_eta   = calculate_next_shipment_eta();
}
```

Can open a separate issue if you think that's a better way to track.

**Comment by tusharmath** [comment] 2023-12-31 06:10
The inspiration for this setting comes from scaslafmt

https://scalameta.org/scalafmt/docs/configuration.html#alignpreset

**Comment by ytmimi** [comment] 2023-12-31 06:31
Thanks for reaching out. Going to close this since this is a duplicate of both https://github.com/rust-lang/rustfmt/issues/894, https://github.com/rust-lang/rustfmt/issues/3821

**Closed by ytmimi** 2023-12-31 06:31 UTC
