### ISSUE TITLE
rustfmt puts comment on a different line

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#5828] opened 2023-07-12 12:20 UTC
This diff says it all:
```rust
diff --git a/src/lib.rs b/src/lib.rs
index 4a093d7b..39a249cd 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -48,14 +48,14 @@ extern crate rustc_ast;
 extern crate rustc_errors;
 #[macro_use]
 extern crate rustc_middle;
+extern crate either;
 extern crate rustc_const_eval;
 extern crate rustc_data_structures;
 extern crate rustc_hir;
 extern crate rustc_index;
 extern crate rustc_session;
 extern crate rustc_span;
-extern crate rustc_target;
-extern crate either; // the one from rustc
+extern crate rustc_target; // the one from rustc
 
 // Necessary to pull in object code as the rest of the rustc crates are shipped only as rmeta
 // files.
```
Notice how the comment "the one from rustc" got moved from the line with `either` to the line with `rustc_target`, completely destroying its meaning. This is the kind of semantics-altering transformations that a formatter should never perform.

**Comment by ytmimi** [comment] 2023-07-12 12:26
Thanks for reaching out! I'm going to close this as a duplicate of #3720

**Closed by ytmimi** 2023-07-12 12:26 UTC

**Comment by RalfJung** [comment] 2023-07-12 15:42
Ah, I thought I had seen this before but couldn't find the issue... thanks.
