### ISSUE TITLE
rustfmt gives up on entire closure if it contains a long string

### ISSUE THREAD

**Issue by acshi** [rust-lang/rustfmt#5528] opened 2022-09-02 18:03 UTC
I'm sure this is a variation on many previous issues, but it is also a little different and worse (in my humble opinion).

If we have a long string in a structure, that structure is not formatted: https://github.com/rust-lang/rustfmt/issues/4800

If we have a long string in a chain of function calls, that chain is not formatted: https://github.com/rust-lang/rustfmt/issues/3863

However, if we have a long string somewhere in a closure, the _entire closure_ is not formatted! This is a much worse user experience, and does not give any errors by default to even guide why rustfmt fails.

I took the example from https://github.com/rust-lang/rustfmt/issues/4800 and wrapped it in a closure. rustfmt does nothing and doesn't complain either:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1193f5482e94bfbdfbdb6a5a0c93866b

**Comment by ytmimi** [comment] 2022-09-02 18:26
Setting `error_on_unformatted=true` and `error_on_line_overflow=true` will give you feedback on the error:

```
error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 121)
 --> <stdin>:9:101
  |
9 |               foo: "long_long_long_long_long_long_long_lo_long_long_long_long_long_long__long_long_long_long_long_long_",
  |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals

error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 133)
  --> <stdin>:10:101
   |
10 | bar: "long_long_long_long_long_long_long_long_long_long_lo_long_long_lolong_long_long_lo_long_long_lolong_long_long_lo_long_long_lo",
   |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals

warning: rustfmt has failed to format. See previous 2 errors.
```

**Comment by calebcartwright** [comment] 2022-09-03 18:22
I'm closing as a duplicate of #3863. The closure is a red herring; it's the `.map` call on the opening line, for which the closure is an argument, which makes the entire element a chain.

**Closed by calebcartwright** 2022-09-03 18:22 UTC
Labels: poor-formatting, a-closures

**Comment by calebcartwright** [comment] 2022-09-03 18:23
> This is a much worse user experience, and does not give any errors by default to even guide why rustfmt fails.

From https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-700441739:

> try running with --config error_on_line_overflow=true which exists for precisely this purpose (make sure you're on nightly), it's just disabled by default. If you'd like to make a case for that being enabled by default then https://github.com/rust-lang/rustfmt/issues/3391 would be the place to do so
