### ISSUE TITLE
`cargo fmt` silently fails to format certain code in at least one file.

### ISSUE THREAD

**Issue by finnbear** [rust-lang/rustfmt#5153] opened 2021-12-25 19:13 UTC
I tried running `cargo fmt` in the directory with this code: https://github.com/SoftbearStudios/mk48/blob/main/server/src/world_physics_radius.rs

I expected to see my code be brought to spec with the format (e.g. fix operator spacing on line 270, all the extremely long lines get shuffled to multiple lines), or an error to be printed (although the code does compile).

Instead, only incorrect format near the top of the file gets fixed (e.g. if an extra space is introduced between the end of a `use` statement and the line-ending `;`), and no error is printed.

### Context

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (475b00aa4 2021-12-24)
binary: rustc
commit-hash: 475b00aa4037461b506539a06d15ca6091b461a7
commit-date: 2021-12-24
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0

```
`rustfmt --version`
```
rustfmt 1.4.38-nightly (475b00a 2021-12-24)
```

**Comment by calebcartwright** [comment] 2021-12-26 22:26
Thanks for reaching out, but closing as a duplicate of #3863 

The line you referenced (270) is part of a rather large closure used as an arg to a chain item which begins all the way back on line 88. The significant block indentation and content within your closure is so large and deep that there's absolutely no way rustfmt can format it such that it also complies with the `max_width` configuration (assuming the default of `100`)

https://github.com/SoftbearStudios/mk48/blob/7e2b51b089eaa23122554f1bfdce83196ae36896/server/src/world_physics_radius.rs#L88-L90

Your options are essentially the same as those outlined in the link issue. If you really want to maintain the deep and wide nature of that closure, you'll need to crank up `max_width` (I'd guess probably to 250-300+ based on a quick glance of the code), or refactor your code to reduce the rightward drift/horizontal scrolling. Fwiw the latter is what I'd advise

**Closed by calebcartwright** 2021-12-26 22:26 UTC
Labels: duplicate
