### ISSUE TITLE
`rustfmt` doesn't always remove unecessary `where` clause

### ISSUE THREAD

**Issue by kennykerr** [rust-lang/rustfmt#6385] opened 2024-11-04 17:45 UTC
Given:

```rust
fn test() where {}
```

`rustfmt` will correctly produce:

```rust
fn test() {}
```

But given:

```rust
fn test() -> () where {}
```

`rustfmt` will fail to remove the unecessary `where` clause.

**Comment by ytmimi** [comment] 2024-11-04 17:56
Duplicate of https://github.com/rust-lang/rustfmt/issues/4649.

**Closed by ytmimi** 2024-11-04 17:56 UTC
Labels: duplicate

**Comment by riverar** [comment] 2024-11-04 18:17
@ytmimi Not sure that's an appropriate issue to dupe on. That issue is concerned with incorrect _removal_ of the where clause. This issue is concerned with incorrect _preservation_ of the where clause.
