### ISSUE TITLE
Nightly formatter removes multi line comments in extern blocks

### ISSUE THREAD

**Issue by faern** [rust-lang/rustfmt#4532] opened 2020-11-17 12:23 UTC
**Describe the bug**

If I have A multi line comment in an extern block preceding a function declaration, it is removed. But not a single line comment.

**To Reproduce**

If I have this code:
```rust
extern "C" {
    // A comment that is
    // spread out over
    // multiple lines
    fn a();

    // A single line comment
    fn b();
}
```
And format it with the nightly formatter. I end up with:
```rust
extern "C" {
    fn a();

    // A single line comment
    fn b();
}
```

**Expected behavior**

I expect both comments to be retained. As far as I know it's not invalid or unidiomatic to write a comment multi line comment on an extern declaration.

**Meta**

- rustfmt version: `rustfmt 1.4.26-nightly (293d7d0 2020-11-14)`
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo +nighty fmt`

**Comment by calebcartwright** [comment] 2020-11-17 14:37
Duplicate of #4528

**Closed by calebcartwright** 2020-11-17 14:37 UTC
Labels: bug, duplicate

**Comment by faern** [comment] 2020-11-17 14:59
Sorry, did not find that one when trying to look for a duplicate. Great it's being worked on already :+1:

**Comment by calebcartwright** [comment] 2020-11-17 15:00
No worries!
