### ISSUE TITLE
Extra brace is inserted after `#[cfg(...)]` on a block

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rustfmt#4475] opened 2020-10-17 05:02 UTC
**Describe the bug**

When formatting a single-line block expression with a `#[cfg(...)]` attribute before it, an extra open brace is produced.

**To Reproduce**

`main.rs`:
```rust
fn main() {
    #[cfg(debug_assertions)]
    { println!("DEBUG"); }
}
```

Run `rustfmt main.rs`

`main.rs` now contains:
```rust
fn main() {
    #[cfg(debug_assertions)]
    {
{        println!("DEBUG");
    }
}
```

**Expected behavior**

The braces are put onto different lines correctly

**Meta**

- rustfmt version: `rustfmt 1.4.22-nightly (97d03010 2020-10-04)`
- From where did you install rustfmt?: I think cargo
- How do you run rustfmt:

  I tried with both `cargo fmt` and `rustfmt`. Both do the same

**Comment by calebcartwright** [comment] 2020-10-17 05:25
Thank you for the report, though closing as a duplicate of #4467 and https://github.com/rust-lang/rustfmt/issues/4452#issuecomment-705886282. Will be addressed in the next rustc-ap bump

**Closed by calebcartwright** 2020-10-17 05:25 UTC
Labels: bug, duplicate
