### ISSUE TITLE
`x fmt` doesn't format some code

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#5145] opened 2021-12-21 17:20 UTC
While working on `rustc` I've noticed that `x fmt` doesn't format some obviously misformatted code.

Here is the code: https://github.com/rust-lang/rust/pull/92164#discussion_r773245118

**Comment by calebcartwright** [comment] 2021-12-21 17:24
Duplicate of #3863, closing accordingly.

Try splitting the `"the `#[rustc_must_implement_one_of]` attribute must be used with at least 2 method names",` string manually

**Closed by calebcartwright** 2021-12-21 17:24 UTC
