### ISSUE TITLE
rust-fmt stops working if the size of a string exceeds a certain length (in the same line)

### ISSUE THREAD

**Issue by rxdiscovery** [rust-lang/rustfmt#6162] opened 2024-05-11 07:15 UTC
Hello,

I've noticed that rust-fmt stops working if the size of a string exceeds a certain length (in the same line).

here's a video demo and the code (playground)
_________

**rustc version**:  
rustc 1.78.0 (9b00956e5 2024-04-29)

## video

[Screencast from 2024-05-11 08-07-00.webm](https://github.com/rust-lang/rustfmt/assets/131091294/f6ec8f5f-9aef-4296-9613-d8f9916b1123)

## code snippet to reproduce : 

[Code playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=77ac0de38f4c12681a920af0786fe224)

Thank you for your help..

**Comment by ytmimi** [comment] 2024-05-11 15:41
This is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863. The `max_width` is a hard constraint for rustfmt. I see two options to try to work around this:

1. Increase the `max_width` to some sufficiently high value.
2. Refactor the code to avoid long string literals:
   ```rust
   pub async fn get_all_permissions_for_role(
       conn: &mut DBConnection,
       role_id: i64,
   ) -> Result<Vec<PermissionEntity>, RepositoryError> {
       let query = r#"SELECT p.*
   FROM ta_per_rol_aspr a, te_permission_per p
   WHERE a.aspr_rol_id = $1 AND a.aspr_per_id = p.per_id"#;
       match diesel::sql_query(query)
       .bind::<diesel::sql_types::BigInt, _>(role_id)
       .get_results(conn)
               .await
       {
                       Ok(r) => Ok(r),
           Err(e) => match e {
               Error::NotFound => Err(RepositoryError::NotFoundError {
                   detail: "No permissions affected".to_string(),
               }),
               _ => Err(RepositoryError::FatalError {
                   detail: "Database error".to_string(),
               }),
           },
       }
   }
   ```

**Closed by ytmimi** 2024-05-11 15:41 UTC

**Comment by ytmimi** [comment] 2024-05-11 21:05
> Why not make rustfmt more flexible on this point, for example if the line exceeds the max_width, and it can't be split in two (the case of a string), it will make an exception for this line only and keep it whole, and continue its formatting strategy on the following lines.

rustfmt doesn't really operate on lines of code. it reformats the AST of your program, and many nodes span multiple lines. When rustfmt fails to format part of an AST node it fails to format the entire node. In this case rustfmt fails to format the string literal, which cascades and leads to a failure to format the match expression.

> (and a small formatting error message would be welcome, to help developers identify the cause of the formatting bug.)

If you set `error_on_unformatted=true` you should be alerted to the max width issue that caused formatting to fail.

**Comment by BlackAsLight** [comment] 2024-05-12 01:35
>rustfmt doesn't really operate on lines of code. it reformats the AST of your program, and many nodes span multiple lines. When rustfmt fails to format part of an AST node it fails to format the entire node. In this case rustfmt fails to format the string literal, which cascades and leads to a failure to format the match expression.

Is rustfmt unable to make a new rule where the max_width is infinite for this section when it exceeds this limit causing it to error?

**Comment by rxdiscovery** [comment] 2024-05-12 19:43
> > Why not make rustfmt more flexible on this point, for example if the line exceeds the max_width, and it can't be split in two (the case of a string), it will make an exception for this line only and keep it whole, and continue its formatting strategy on the following lines.
> 
> rustfmt doesn't really operate on lines of code. it reformats the AST of your program, and many nodes span multiple lines. When rustfmt fails to format part of an AST node it fails to format the entire node. In this case rustfmt fails to format the string literal, which cascades and leads to a failure to format the match expression.
> 
> > (and a small formatting error message would be welcome, to help developers identify the cause of the formatting bug.)
> 
> If you set `error_on_unformatted=true` you should be alerted to the max width issue that caused formatting to fail.

@ytmimi  thank you for this tip (`error_on_unformatted=true`) , it will help me a lot. :+1:
