### ISSUE TITLE
ICE: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by MaxOhn** [rust-lang/rustfmt#6318] opened 2024-09-09 11:07 UTC
## `lib.rs`
```rs
fn my_fn() {
    enum MyEnum
    where
    SomeTypeA___: SomeTrait__<
            _A,
            Archived = <SomeTypeB____ as SomeTrait__<
                Option<[u8; 4]>,
            >>::Archived,
        >,
    {
    }
}
```
## `rustfmt.toml`
```toml
max_width = 80
```
## Output
```
thread 'main' panicked at src\tools\rustfmt\src\items.rs:547:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fff8edf408d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7fff8edf408d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7fff8edf408d - std::sys::backtrace::_print_fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:65
   3:     0x7fff8edf408d - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:40
   4:     0x7fff8ee24bb9 - core::fmt::rt::Argument::fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\fmt\rt.rs:173
   5:     0x7fff8ee24bb9 - core::fmt::write
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\fmt\mod.rs:1182
   6:     0x7fff8edeab71 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\io\mod.rs:1827
   7:     0x7fff8edf7127 - std::panicking::default_hook::closure$1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:269
   8:     0x7fff8edf6d19 - std::panicking::default_hook
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:296
   9:     0x7fff82822ed5 - memchr
  10:     0x7fff8edf796b - alloc::boxed::impl$50::call
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\alloc\src\boxed.rs:2084
  11:     0x7fff8edf796b - std::panicking::rust_panic_with_hook
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:808
  12:     0x7fff8edf773f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:667
  13:     0x7fff8edf49ff - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:168
  14:     0x7fff8edf7356 - std::panicking::begin_panic_handler
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
  15:     0x7fff8ee4dc34 - core::panicking::panic_fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
  16:     0x7fff8ee4dcdd - core::panicking::panic
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:148
  17:     0x7fff8ee4db9e - core::option::unwrap_failed
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\option.rs:2020
  18:     0x7ff793575c3c - <unknown>
  19:     0x7ff7935e5e66 - <unknown>
  20:     0x7ff7935ea75a - <unknown>
  21:     0x7ff7935e2126 - <unknown>
  22:     0x7ff7935e47f4 - <unknown>
  23:     0x7ff7935e5dd2 - <unknown>
  24:     0x7ff7935c551d - <unknown>
  25:     0x7ff7935eb657 - <unknown>
  26:     0x7ff79342bba9 - <unknown>
  27:     0x7ff793443acd - <unknown>
  28:     0x7ff793440037 - <unknown>
  29:     0x7ff79343bfa6 - <unknown>
  30:     0x7ff793427156 - <unknown>
  31:     0x7ff79342780c - <unknown>
  32:     0x7fff8eddba49 - std::rt::lang_start_internal::closure$2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  33:     0x7fff8eddba49 - std::panicking::try::do_call
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:557
  34:     0x7fff8eddba49 - std::panicking::try
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:521
  35:     0x7fff8eddba49 - std::panic::catch_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panic.rs:350
  36:     0x7fff8eddba49 - std::rt::lang_start_internal
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  37:     0x7ff79344505c - <unknown>
  38:     0x7ff79377ea30 - <unknown>
  39:     0x7ffffe777374 - BaseThreadInitThunk
  40:     0x7ffffeb7cc91 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rustfmt/issues/new?labels=bug

note: rustc 1.81.0 (eeb90cda1 2024-09-04) running on x86_64-pc-windows-msvc

query stack during panic:
end of query stack
```

**Comment by ytmimi** [comment] 2024-09-09 14:55
Thanks for the report. It's Likely that this is a duplicate of https://github.com/rust-lang/rustfmt/issues/5738

**Closed by ytmimi** 2024-09-09 14:55 UTC
