### ISSUE TITLE
Put attributes below docs

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rustfmt#6003] opened 2024-01-01 04:22 UTC
```rust
#[important_attr]
/// Very long docs
/// ...
fn foo() {}
```

If the docs are very long (as in take up the whole screen), then it is easy to miss attributes that have been placed before the docs. Thus, for improved readability (and consistency) it is important to always have attributes placed below function docs.

**Comment by ytmimi** [comment] 2024-01-01 15:15
Thanks for reaching out. Going to close this as a duplicate of https://github.com/rust-lang/rustfmt/issues/3744

**Closed by ytmimi** 2024-01-01 15:15 UTC
