### ISSUE TITLE
Spaces before colons in macro_rules?

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustfmt#2534] opened 2018-03-16 00:25 UTC
Before formatting:

```rust
macro_rules! foo {
    ($a:ident : $b:ty) => {};
    ($a:ident $b:ident $c:ident) => {};
}
```

After formatting:

```rust
macro_rules! foo {
    ($a: ident: $b: ty) => {};
    ($a: ident $b: ident $c: ident) => {};
}
```

This formatting makes the macro patterns difficult to read.

I understand why rustfmt adds a space after every `:`, and it makes a lot of sense when arguments are separated by commas or semicolons. But if arguments are separated by spaces or other kinds of delimiters, the end result is not great. :(

cc @RReverser

**Comment by RReverser** [comment] 2018-03-16 00:33
I also agree it's not perfect when it's not a list of comma-separated arguments but that's how it was implemented before me in initial version https://github.com/rust-lang-nursery/rustfmt/commit/f86f6dcd9c33fa7b2b1bcda29edbed4d4fd9cba2 by @nrc , so I decided not to change that bit when extending support for macros 1.1/1.0.

**Comment by topecongiro** [comment] 2018-03-17 06:26
As much as I prefer to keep formatting consistent between function definitions and `macro_rules`, IMHO we should not add a space after `:` by default, because it makes parsing arguments by human eyes harder. Unlike function definitions where arguments are separated by commas, arguments for macros can be separated by anything, or even there could be no separators.
Also I rarely find a code where a space is added after comma in the wild.

**Comment by stjepang** [comment] 2018-03-19 10:48
This was fixed by adding a space before the colon. But I wonder: should we add spaces before some other characters, too?

Here it sort of looks like `ident` is a function name because paratheses are sticked to it:
```
($name: ident($($dol: tt $var: ident)*) $($body: tt)*) => {};
```

But if we add a space, it's clearer that `ident` is actually the type of `$name`:

```
($name: ident ($($dol: tt $var: ident)*) $($body: tt)*) => {};
```

I'd probably prefer to always add a space after the token type, unless it is followed by one of `,;)]}`.

**Comment by dtolnay** [comment] 2018-03-24 19:00
Reopening because the commit that closed this did not address where the discussion seemed to be heading -- that as much as it may be motivated by the formatting of function definitions, macro syntax has different requirements and we should not be inserting whitespace after the metavariable colon. I agree with @topecongiro's and @RReverser reasoning.

```rust
macro_rules! foo {
    ($a:ident : $b:ty) => {};
    ($a:ident $b:ident $c:ident) => {};
}
```

**Comment by petrochenkov** [comment] 2018-03-24 19:50
I always reformat macros as functions when I touch them in code (and use appropriate lower/upper-case for macro parameters), it makes them looking much more like normal code and therefore more readable for a non-macro-expert.

I agree with @stjepang though that colons used as separators and not as a part of `$param: type` should have an extra space, i.e.
```rust
macro_rules! foo {
    ($a: ident : $T: ty) => {};
    ($a: ident $b: ident $c: ident) => {};
}
```

>including the formatting in the Rust Book that probably inspired everyone else

We should fix the book, IMO.

**Comment by topecongiro** [comment] 2018-03-25 05:19
@dtolnay The first PR adds a space before non-metavariable colon which comes after metavariable. The following PR (#2549) removes a space after metavariable colon. So the issue is fixed on the master.

We have not settled on how we should format macro arguments. I think that we have three options to choose from:

1. Never put a space after metavariable colon (`$a:ident`).
2. Always put a space after metavariable colon (`$a: ident`).
3. Heuristically choose whether to put a space after metavariable colon (e.g. put a space if metavariables are separated by commas).

Currently rustfmt follows 1.

**Comment by dtolnay** [comment] 2018-03-25 09:31
Thank you! That PR had not been linked to this issue before. Looking forward to a release.

**Comment by aturon** [comment] 2018-07-10 22:37
Related to https://github.com/rust-lang-nursery/rustfmt/issues/2753, in that we may want to punt on this formatting via a flag for now.

**Comment by RReverser** [comment] 2018-07-18 07:31
> we no longer format macro matchers by default

@nrc Why not? The attached commit just mentions #2543 but that seems unrelated to macro matchers.

**Comment by nrc** [comment] 2018-07-18 09:00
So we can decide on the formatting later - there is no clear answer here and we're approaching the cut-off for 1.0, so I think we need to punt.

**Comment by RReverser** [comment] 2018-07-18 09:41
I see. Too bad, I really wanted macros to be autoformatted (which is why I PRd it in the first place) but understandable that exact rules need more care and time. I will still be able to opt-in to their formatting with `rustfmt.toml` in the meanwhile, right?

**Comment by RReverser** [comment] 2018-07-18 09:42
Oh wait, if I'm reading the diff correctly, this also affects just the matching definitions, but bodies will be still formatted?

**Comment by RReverser** [comment] 2018-07-18 11:59
Sounds perfect and reasonable, thanks.

**Closed** 2022-07-19 22:07 UTC
Labels: poor-formatting, a-macros
