### ISSUE TITLE
Does not format attributes containing arrays

### ISSUE THREAD

**Issue by cyqsimon** [rust-lang/rustfmt#5195] opened 2022-01-26 13:51 UTC
rustfmt seems to fail when an attribute contains an array. This is problematic when using clap with derive feature, for example.

## Steps to reproduce
Try formatting the code below using rustfmt.
```rust
use clap::Parser;

#[derive(Debug, Parser)]
struct CliArgs {
    #[clap(
        long = "very-long-arg-name-to-stretch-out-line-length",
        value_name = "stretch_out_the_line_some_more", possible_values = ["lorem", "ipsum"]
    )]
    my_arg: String,
}
```

## Expected behaviour
`possible_values` should appear on a new line.

## Actual behaviour
rustfmt gives up on formatting this attribute. Does nothing.

**Comment by calebcartwright** [comment] 2022-01-27 00:57
Thanks for sharing. I believe the root cause of this is that the corresponding AST node for the attribute (as produced by rustc's parser) doesn't actually have an associated MetaItem which leaves rustfmt nothing that can be formatted. Any resolution to this is going to have to be made upstream so I'm going to close.

When/if it's addressed in the parser then rustfmt will automatically pick that up

**Closed by calebcartwright** 2022-01-27 00:57 UTC
