### ISSUE TITLE
Rustfmt puts single-line comment after wrong import when reordering imports

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#4027] opened 2020-01-24 03:04 UTC
before rustfmt:
```rust
pub use views::*;
pub use foo::bar; // re-export for frontend
```
after (with import reordering enabled):
```rust
pub use foo::bar;
pub use views::*; // re-export for frontend
```
The comment is at the wrong import now. It should not just reorder the imports but also their comments with them!

**Comment by mbarbar** [comment] 2020-09-10 12:40
Looks like #3720.

**Comment by whizsid** [comment] 2020-10-20 22:22
I am working on this issue.

**Comment by mbarbar** [comment] 2020-10-21 03:58
This comment may make getting started a little easier, though it may be outdated.
https://github.com/rust-lang/rustfmt/issues/3720#issuecomment-564570935

**Comment by ytmimi** [comment] 2022-07-26 02:03
closing this as a duplicate of #3720

**Closed by ytmimi** 2022-07-26 02:03 UTC
Labels: duplicate, a-comments, a-imports
