### ISSUE TITLE
Formatting fails with println! invocation with many arguments

### ISSUE THREAD

**Issue by tyilo** [rust-lang/rustfmt#6245] opened 2024-07-18 16:23 UTC
The following code fails to be formatted:

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8d04e740011dfe6de7d78ff692519bdf)

```rust
fn foo() {
    std::thread::scope(|scope| {
        scope.spawn(move || {
            for i in 0..100 {
                if i % 10 == 0 {
                    println!(
                        "{a}, {b}, {percentage}, foo_barbazqux = {foo_barbazqux} {v_percentage:.4}%",
                        a = 1,
                        b = 2,
                        percentage = 3,
                        foo_barbazqux = 4,
                        v_percentage = 5
                    );
                }
            }
            
            // Not formatted:
            _ = 1+1;
        });
    });
}
```

I have reduced this from some real code, but I can't seem to reduce it further.

**Comment by ytmimi** [comment] 2024-07-18 17:21
This is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863. The long string literal prevents the call to `scope.spawn()` from being formatted. You can work around this by bumping the max width.

Here's the output when I build and run rustfmt locally:

```
$: cargo run --bin rustfmt -- --check --config=max_width=105
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/rustfmt --check --config=max_width=105`
fn foo() {
    std::thread::scope(|scope| {
        scope.spawn(move || {
            for i in 0..100 {
                if i % 10 == 0 {
                    println!(
                        "{a}, {b}, {percentage}, foo_barbazqux = {foo_barbazqux} {v_percentage:.4}%",
                        a = 1,
                        b = 2,
                        percentage = 3,
                        foo_barbazqux = 4,
                        v_percentage = 5
                    );
                }
            }
            
            // Not formatted:
            _ = 1+1;
        });
    });
}
Diff in <stdin>:13:
                     );
                 }
             }
-            
+
             // Not formatted:
-            _ = 1+1;
+            _ = 1 + 1;
         });
     });
 }
```

**Closed by ytmimi** 2024-07-18 17:21 UTC
