### ISSUE TITLE
Rustfmt removes `impl` keyword bug

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rustfmt#3859] opened 2019-10-13 02:12 UTC
Consider the following code:

```rust
type BufferOnChange<OnDirty> = impl Fn(usize);
```

Rustfmt will change it to:

```rust
type BufferOnChange<OnDirty>  Fn(usize);
```

which changes the semantics (!).

**Comment by rchaser53** [comment] 2019-10-14 06:48
what version of rustfmt are you using? I cannot reproduce it using the rustfmt 1.4.9-nightly.

rust playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4fbde16ddd588841b1cb87c286aa0e91

**Comment by topecongiro** [comment] 2019-10-19 03:12
This seems to be fixed on the latest stable & nightly. As such, I will close this issue. If you find any problem, feel free to reopen this.

**Closed by topecongiro** 2019-10-19 03:12 UTC
