### ISSUE TITLE
Cargo fmt strips if let pattern field attributes.

### ISSUE THREAD

**Issue by rustonaut** [rust-lang/rustfmt#3790] opened 2019-09-10 21:43 UTC
Cargo fmt strips if let patterns annotations/meta (in this case a feature gate).

So this code:

```
    pub fn endpoint<F>(self, func: F) -> Response<hyper::Body>
    where
         /*stripped*/
    {
        let Endpoint {
            global,
            request,
            type_hint: _,
            #[cfg(feature="test-functionality")]
            mock_workspace,
        } = self;
       
        /**stripped*/
    }
```

Becomes 

```
    pub fn endpoint<F>(self, func: F) -> Response<hyper::Body>
    where
        /*stripped*/
    {
        let Endpoint {
            global,
            request,
            type_hint: _,
            mock_workspace,
        } = self;
       
        /**stripped*/
    }
```

Which then fails to compile if you do so without the `test-functionality` feature...

**Comment by topecongiro** [comment] 2019-09-11 00:52
This is a duplicate of #3759. The issue has been fixed on the latest nightly.

**Closed by topecongiro** 2019-09-11 00:52 UTC
Labels: duplicate
