### ISSUE TITLE
Raw identifier ordering is different in mod and use

### ISSUE THREAD

**Issue by kazatsuyu** [rust-lang/rustfmt#4254] opened 2020-06-13 14:33 UTC
I made the following file:

```rust
// example.rs
mod d;
mod f;
mod s;
mod r#if;
mod r#else;

use d::*;
use f::*;
use s::*;
use r#if::*;
use r#else::*;
```

And I ran the following command:

```sh
rustfmt --unstable-features --skip-children --emit stdout example.rs
```

I got the following output.

```rust
// example.rs
mod d;
mod r#else;
mod f;
mod r#if;
mod s;

use d::*;
use f::*;
use r#else::*;
use r#if::*;
use s::*;
```

rustfmt version: 1.4.15-nightly (aedff61f 2020-05-19)

**Comment by ayazhafiz** [comment] 2020-06-13 21:10
`skip-children` and `unstable-features` were removed in #4006, looks like this is fixed on master. I'll add a test case for regression

**Closed** 2020-06-14 00:26 UTC
