### ISSUE TITLE
`rustfmt` ignores chains when it contains long argument

### ISSUE THREAD

**Issue by TimeEngineer** [rust-lang/rustfmt#5851] opened 2023-07-20 15:37 UTC
```rust
fn main() {
    Foo::foo("")
    .foo(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
    .foo("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    .foo("")
}
```

remains unchanged but should be atleast indented as:

```rust
fn main() {
    Foo::foo("")
        .foo(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
        .foo("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
        .foo("")
}
```

**Comment by calebcartwright** [comment] 2023-07-20 15:47
Duplicate of #3863

**Closed by calebcartwright** 2023-07-20 15:47 UTC
Labels: duplicate
