### ISSUE TITLE
[unstable option] `imports_granularity`

### ISSUE THREAD

**Issue by karyon** [rust-lang/rustfmt#5082] opened 2021-11-14 09:03 UTC
Tracking issue for unstable option: imports_granularity.

See [Processes.md, "Stabilising an Option"](https://github.com/rust-lang/rustfmt/blob/master/Processes.md#stabilising-an-option):

* [ ] Is the default value correct?
* [ ] The design and implementation of the option are sound and clean.
* [ ] The option is well tested, both in unit tests and, optimally, in real usage.
* [ ] There is no open bug about the option that prevents its use.

**Comment by calebcartwright** [comment] 2021-11-14 19:50
Thanks but closing as a duplicate of #4991

**Closed by calebcartwright** 2021-11-14 19:50 UTC
Labels: unstable option
