### ISSUE TITLE
A comment in a oneliner closure breaks rustfmt

### ISSUE THREAD

**Issue by khoda81** [rust-lang/rustfmt#5925] opened 2023-09-24 19:12 UTC
To reproduce:
```rust
fn main() {
    let res = None.map(|_| 
        // hello
        0);
}
```
The whole file is left unchanged and this is rustfmt output:
```
Formatting ...\src\main.rs
Spent 0.006 secs in the parsing phase, and 0.001 secs in the formatting phase
error[internal]: left behind trailing whitespace
 --> ...\src\main.rs:2:2:27
  |
2 |     let res = None.map(|_|
  |                           ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```
tested versions: 
```
rustfmt: rustfmt 1.6.0-stable (d5c2e9c3 2023-09-13)
         rustfmt 1.6.0-nightly (bdb0fa3e 2023-09-19)
         rustfmt 1.6.0-nightly (13e6f24b 2023-09-23) <- latest at the time
OS: Windows 11
```

**Comment by calebcartwright** [comment] 2023-09-25 10:15
Thanks for sharing but going to close as I believe this is a duplicate of #4855

**Closed by calebcartwright** 2023-09-25 10:15 UTC

**Comment by calebcartwright** [comment] 2023-09-25 10:18
> The whole file is left unchanged and this is rustfmt output:

Will also note that this is not correct. The chain containing the closure arg is left as-is (and the existence of the trailing space in the input is what's triggering the whitespace error), but the rest of the function is formatted as would be anything in the file. You can see this in action with a slightly modified example of the input on the [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0080cef2a45a62180a9b0ec6cc806dea), and in your original input you can remove the trailing space manually to prevent the error.
