### ISSUE TITLE
rustfmt attempting to format invalid code

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rustfmt#4276] opened 2020-06-24 15:33 UTC
My version of rustfmt (rustfmt 1.4.14-stable (e417356 2020-04-21)) rewrites the following to something with different semantic meaning. The code is invalid so rustfmt should probably reject it (notice the double if `if if`).

```rust
#[inline]
pub fn r_q_p01_boundaries(p: f64, left: f64, right: f64, lower_tail: bool, log_p: bool) -> Option<f64> {
     if log_p {
 if p > 0.0 {
     Some(f64::NAN)
         } else if p == 0.0 {/* upper bound*/
     Some(if lower_tail {
         right
             } else {
                 left
             })
         } else if if p == f64::NEG_INFINITY {
     Some(if lower_tail {
         left
             } else {
                 right
             })
         } else {
             None
         }
     } else { /* !log_p */
 if p < 0.0 || p > 1.0 {
     Some(f64::NAN)
         } else if p == 0.0 {
     Some(if lower_tail {
         left
             } else {
                 right
             })
         } else if p == 1.0 {
     Some(if lower_tail {
         right
             } else {
                 left
             })
         } else {
             None
         }
     }
 }
```

**Comment by calebcartwright** [comment] 2020-06-24 15:39
Thanks @derekdreery. This has already been fixed in source and is a duplicate of a few other issues (#4126 and #4249), so I am going to go ahead and close.

**Closed by calebcartwright** 2020-06-24 15:39 UTC
Labels: duplicate, fixed

**Comment by derekdreery** [comment] 2020-06-24 15:51
Yep I just tried on nightly and didn't have the problem. Sorry.

**Comment by calebcartwright** [comment] 2020-06-24 15:56
no worries!
